package org.churchpresenter.helper.intent.glossary

internal val ARABIC = Glossary(
    "ar",
    listOf(
        // Asking where, or how.
        "أين" to "where",
        "اين" to "where",
        "وين" to "where",
        "فين" to "where",
        "إلى أين" to "where",
        "الى اين" to "where",
        "كيف يمكنني" to "how can i",
        "كيف أستطيع" to "how can i",
        "كيف استطيع" to "how can i",
        "كيف أقدر" to "how can i",
        "كيف اقدر" to "how can i",
        "كيف أقوم" to "how do i",
        "كيف اقوم" to "how do i",
        "كيف" to "how do i",
        "ازاي" to "how do i",
        "لا أجد" to "can't find",
        "لا اجد" to "can't find",
        "لا أستطيع أن أجد" to "can't find",
        "لا استطيع ان اجد" to "can't find",
        "لا أستطيع إيجاد" to "can't find",
        "لا استطيع ايجاد" to "can't find",
        "لم أجد" to "can't find",
        "لم اجد" to "can't find",
        "مش لاقي" to "can't find",
        "أرني" to "show me",
        "ارني" to "show me",
        "أريني" to "show me",
        "اريني" to "show me",
        "وريني" to "show me",
        "اعرض لي" to "show me",

        // Doing.
        "اعرض" to "show",
        "أعرض" to "show",
        "عرض" to "show",
        "أظهر" to "show",
        "اظهر" to "show",
        "إظهار" to "show",
        "اظهار" to "show",
        "ضع على الشاشة" to "show",
        "ضع على الشاشه" to "show",
        "افتح" to "open",
        "فتح" to "open",
        "اذهب إلى" to "go to",
        "اذهب الى" to "go to",
        "انتقل إلى" to "go to",
        "انتقل الى" to "go to",
        "روح على" to "go to",
        "الانتقال إلى" to "go to",
        "الانتقال الى" to "go to",
        "بدّل إلى" to "switch to",
        "بدّل الى" to "switch to",
        "بدل إلى" to "switch to",
        "بدل الى" to "switch to",
        "ابحث عن" to "find",
        "ابحث" to "find",
        "البحث عن" to "find",
        "اقرأ" to "read",
        "اقرا" to "read",
        "اجعل" to "make",
        "خلّي" to "make",
        "خلي" to "make",
        "أنشئ" to "create",
        "انشئ" to "create",
        "إنشاء" to "create",
        "انشاء" to "create",
        "اصنع" to "create",
        "أضف" to "add",
        "اضف" to "add",
        "إضافة" to "add",
        "اضافة" to "add",
        "إضافه" to "add",
        "اضافه" to "add",
        "ضيف" to "add",
        "حمّل" to "load",
        "تحميل" to "download",
        "نزّل" to "download",
        "تنزيل" to "download",
        "استورد" to "import",
        "استيراد" to "import",
        "ثبّت" to "install",
        "تثبيت" to "install",
        "اختر" to "choose",
        "اختيار" to "choose",
        "أعدّ" to "set up",
        "اعدّ" to "set up",
        "إعداد" to "set up",
        "اعداد" to "set up",
        "اضبط" to "set up",
        "ضبط" to "set up",
        "اتصل ب" to "connect",
        "وصّل" to "connect",
        "توصيل" to "connect",
        "ربط" to "connect",
        "اربط" to "connect",
        "عيّن" to "assign",
        "تعيين" to "assign",
        "أخف" to "hide",
        "اخف" to "hide",
        "أخفِ" to "hide",
        "اخفِ" to "hide",
        "إخفاء" to "hide",
        "اخفاء" to "hide",
        "اخفي" to "hide",
        "شيل" to "hide",
        "أوقف" to "stop",
        "اوقف" to "stop",
        "إيقاف" to "stop",
        "ايقاف" to "stop",
        "وقّف" to "stop",
        "احذف" to "delete",
        "حذف" to "delete",
        "امسح" to "clear",
        "مسح" to "clear",
        "نظّف" to "clear",
        "أطفئ الشاشة" to "black out",
        "اطفئ الشاشة" to "black out",
        "أطفئ الشاشه" to "black out",
        "اطفئ الشاشه" to "black out",
        "شاشة سوداء" to "black out",
        "شاشة فارغة" to "blank",
        "شاشة فارغه" to "blank",
        "تراجع" to "undo",
        "ارجع كما كان" to "undo",
        "ألغ" to "undo",
        "الغ" to "undo",
        "على الهواء" to "go live",
        "بث مباشر" to "go live",
        "شغّل" to "turn on",
        "شغل" to "turn on",
        "تشغيل" to "turn on",
        "فعّل" to "turn on",
        "تفعيل" to "turn on",
        "أطفئ" to "turn off",
        "اطفئ" to "turn off",
        "إطفاء" to "turn off",
        "اطفاء" to "turn off",
        "عطّل" to "turn off",
        "تعطيل" to "turn off",
        "بدّل" to "toggle",
        "التالي" to "next",
        "التالية" to "next",
        "التاليه" to "next",
        "القادم" to "next",
        "للأمام" to "forward",
        "للامام" to "forward",
        "السابق" to "previous",
        "السابقة" to "previous",
        "السابقه" to "previous",
        "للخلف" to "back",
        "ارجع" to "back",
        "رجوع" to "back",
        "كبّر" to "increase",
        "كبر" to "increase",
        "تكبير" to "increase",
        "زد" to "increase",
        "زيادة" to "increase",
        "زياده" to "increase",
        "أكبر" to "bigger",
        "اكبر" to "bigger",
        "صغّر" to "decrease",
        "صغر" to "decrease",
        "تصغير" to "decrease",
        "قلل" to "decrease",
        "تقليل" to "decrease",
        "أصغر" to "smaller",
        "اصغر" to "smaller",
        "حوّل" to "convert",
        "تحويل" to "convert",
        "محوّل" to "converter",
        "محول" to "converter",
        "انقل" to "transfer",
        "نقل" to "transfer",
        "عدّل" to "edit",
        "عدل" to "edit",
        "تعديل" to "edit",
        "حرّر" to "edit",
        "تحرير" to "edit",
        "غيّر" to "change",
        "تغيير" to "change",
        "أعد تسمية" to "rename",
        "اعد تسمية" to "rename",
        "أعد تسميه" to "rename",
        "اعد تسميه" to "rename",
        "إعادة تسمية" to "rename",
        "اعادة تسمية" to "rename",
        "إعادة تسميه" to "rename",
        "اعادة تسميه" to "rename",
        "صحّح" to "fix",
        "أصلح" to "fix",
        "اصلح" to "fix",
        "إصلاح" to "fix",
        "اصلاح" to "fix",
        "رتّب" to "organize",
        "ترتيب" to "organize",
        "نظّم" to "organize",
        "تنظيم" to "organize",
        "قارن" to "compare",
        "مقارنة" to "compare",
        "مقارنه" to "compare",
        "ترجم" to "translate",
        "خطط" to "plan",
        "خطّط" to "plan",
        "تخطيط" to "plan",
        "أتمتة" to "automate",
        "اتمتة" to "automate",
        "أتمته" to "automate",
        "اتمته" to "automate",
        "تلقائيا" to "automatically",
        "تلقائياً" to "automatically",
        "حدّد" to "identify",
        "رقّم الشاشات" to "number the",
        "ترقيم" to "number the",

        // Too small, too big, not working.
        "صغير جدا" to "too small",
        "صغير جداً" to "too small",
        "صغيرة جدا" to "too small",
        "صغيرة جداً" to "too small",
        "صعب القراءة" to "hard to read",
        "صعب القراءه" to "hard to read",
        "صعبة القراءة" to "hard to read",
        "صعبة القراءه" to "hard to read",
        "لا يمكن قراءته" to "hard to read",
        "غير واضح" to "hard to read",
        "مش واضح" to "hard to read",
        "كبير جدا" to "too big",
        "كبير جداً" to "too big",
        "كبيرة جدا" to "too big",
        "كبيرة جداً" to "too big",
        "لا يتسع" to "doesn't fit",
        "لا يناسب الشاشة" to "doesn't fit",
        "لا يناسب الشاشه" to "doesn't fit",
        "لا يعمل" to "not working",
        "لا تعمل" to "not working",
        "مش شغال" to "not working",
        "لا يظهر" to "not showing",
        "لا تظهر" to "not showing",
        "لا يظهر شيء" to "nothing shows",
        "لا شيء" to "nothing shows",
        "الشاشة سوداء" to "screen is black",
        "لا توجد إشارة" to "no signal",
        "لا توجد اشارة" to "no signal",
        "لا توجد إشاره" to "no signal",
        "لا توجد اشاره" to "no signal",
        "لا إشارة" to "no signal",
        "لا اشارة" to "no signal",
        "لا إشاره" to "no signal",
        "لا اشاره" to "no signal",
        "لا توجد صورة" to "no picture",
        "لا توجد صوره" to "no picture",
        "لا صورة" to "no picture",
        "لا صوره" to "no picture",
        "أي شاشة" to "which screen",
        "اي شاشة" to "which screen",
        "أي شاشه" to "which screen",
        "اي شاشه" to "which screen",
        "أي جهاز عرض" to "which projector",
        "اي جهاز عرض" to "which projector",
        "أي شاشات" to "which screen",
        "اي شاشات" to "which screen",

        // What is on screen.
        "خلفي*" to "background",
        "الخلفي*" to "background",
        "كلمات الترنيمة" to "lyrics",
        "كلمات الترنيمه" to "lyrics",
        "كلمات الأغنية" to "lyrics",
        "كلمات الاغنية" to "lyrics",
        "كلمات الأغنيه" to "lyrics",
        "كلمات الاغنيه" to "lyrics",
        "ترانيم" to "songs",
        "الترانيم" to "songs",
        "ترنيم*" to "song",
        "الترنيم*" to "song",
        "أغاني" to "songs",
        "اغاني" to "songs",
        "الأغاني" to "songs",
        "الاغاني" to "songs",
        "أغني*" to "song",
        "اغني*" to "song",
        "الأغني*" to "song",
        "الاغني*" to "song",
        "تسبيح*" to "worship",
        "التسبيح*" to "worship",
        "عباد*" to "worship",
        "العباد*" to "worship",
        "تراتيل" to "hymn",
        "التراتيل" to "hymn",
        "ترتيل*" to "hymn",
        "الترتيل*" to "hymn",
        "الكتاب المقدس" to "bible",
        "كتاب المقدس" to "bible",
        "إنجيل" to "bible",
        "انجيل" to "bible",
        "الإنجيل" to "bible",
        "الانجيل" to "bible",
        "أسفار" to "scripture",
        "اسفار" to "scripture",
        "الأسفار" to "scripture",
        "الاسفار" to "scripture",
        "آية" to "verse",
        "اية" to "verse",
        "آيه" to "verse",
        "ايه" to "verse",
        "الآية" to "verse",
        "الاية" to "verse",
        "الآيه" to "verse",
        "الايه" to "verse",
        "آيات" to "verse",
        "ايات" to "verse",
        "الآيات" to "verse",
        "الايات" to "verse",
        "إصحاح" to "chapter",
        "اصحاح" to "chapter",
        "الإصحاح" to "chapter",
        "الاصحاح" to "chapter",
        "أصحاح" to "chapter",
        "الأصحاح" to "chapter",
        "فصل" to "chapter",
        "الفصل" to "chapter",
        "خط" to "font",
        "الخط" to "font",
        "خطوط" to "font",
        "الخطوط" to "font",
        "حجم" to "size",
        "الحجم" to "size",
        "نص" to "text",
        "النص" to "text",
        "نصوص" to "text",
        "النصوص" to "text",
        "كلمات" to "words",
        "الكلمات" to "words",
        "حروف" to "letters",
        "الحروف" to "letters",
        "أحرف" to "letters",
        "احرف" to "letters",
        "الأحرف" to "letters",
        "الاحرف" to "letters",
        "عرض الشرائح" to "slideshow",
        "شريح*" to "slide",
        "الشريح*" to "slide",
        "شرائح" to "slide",
        "الشرائح" to "slide",
        "صور" to "photo",
        "الصور" to "photo",
        "صورة" to "picture",
        "صوره" to "picture",
        "الصورة" to "picture",
        "الصوره" to "picture",
        "ألبوم*" to "album",
        "البوم*" to "album",
        "الألبوم*" to "album",
        "الالبوم*" to "album",
        "عرض تقديمي" to "presentation",
        "العرض التقديمي" to "presentation",
        "فيديو*" to "video",
        "الفيديو*" to "video",
        "فيلم" to "movie",
        "الفيلم" to "movie",
        "أفلام" to "movie",
        "افلام" to "movie",
        "الأفلام" to "movie",
        "الافلام" to "movie",
        "مقطع*" to "clip",
        "المقطع*" to "clip",
        "كليب" to "clip",
        "الكليب" to "clip",
        "وسائط" to "media",
        "الوسائط" to "media",
        "صوت" to "audio",
        "الصوت" to "audio",
        "الثلث السفلي" to "lower third",
        "ثلث سفلي" to "lower third",
        "شريط الاسم" to "name strap",
        "الاسم واللقب" to "name and title",
        "إعلان*" to "announcement",
        "اعلان*" to "announcement",
        "الإعلان*" to "announcement",
        "الاعلان*" to "announcement",
        "شريط إخباري" to "ticker",
        "شريط اخباري" to "ticker",
        "الشريط إخباري" to "ticker",
        "الشريط اخباري" to "ticker",
        "نص متحرك" to "ticker",
        "غرفة الأطفال" to "kids room",
        "غرفة الاطفال" to "kids room",
        "حضانة الأطفال" to "kids room",
        "حضانة الاطفال" to "kids room",
        "عد تنازلي" to "countdown",
        "العد التنازلي" to "countdown",
        "مؤقت" to "timer",
        "المؤقت" to "timer",
        "ساعة إيقاف" to "stopwatch",
        "ساعة ايقاف" to "stopwatch",
        "ساعة" to "clock",
        "ساعه" to "clock",
        "الساعة" to "clock",
        "الساعه" to "clock",
        "الوقت الحالي" to "current time",
        "وقت" to "time",
        "الوقت" to "time",
        "ملاحظات" to "notes",
        "الملاحظات" to "notes",
        "كورد*" to "chord",
        "الكورد*" to "chord",
        "أكورد*" to "chord",
        "اكورد*" to "chord",
        "الأكورد*" to "chord",
        "الاكورد*" to "chord",
        "ترجم*" to "translation",
        "الترجم*" to "translation",
        "لغة" to "language",
        "لغه" to "language",
        "اللغة" to "language",
        "اللغه" to "language",
        "لغات" to "language",
        "اللغات" to "language",
        "بلغتين" to "bilingual",
        "ثنائي اللغة" to "bilingual",
        "ثنائي اللغه" to "bilingual",
        "لغة أخرى" to "another language",
        "لغة اخرى" to "another language",
        "بلغة أخرى" to "another language",
        "بلغة اخرى" to "another language",
        "لغة ثانية" to "second language",
        "لغة ثانيه" to "second language",
        "بلغتين اثنتين" to "two languages",

        // Screens and outputs.
        "الشاشة الرئيسية" to "main screen",
        "الشاشة الرئيسيه" to "main screen",
        "شاشة رئيسية" to "main screen",
        "شاشة رئيسيه" to "main screen",
        "ملء الشاشة" to "full screen",
        "ملء الشاشه" to "full screen",
        "شاشة كاملة" to "full screen",
        "شاشة كامله" to "full screen",
        "كامل الشاشة" to "full screen",
        "كامل الشاشه" to "full screen",
        "الشاشة الثانية" to "second screen",
        "الشاشة الثانيه" to "second screen",
        "شاشة ثانية" to "second screen",
        "شاشة ثانيه" to "second screen",
        "شاش*" to "screen",
        "الشاش*" to "screen",
        "جهاز العرض" to "projector",
        "بروجكتور" to "projector",
        "البروجكتور" to "projector",
        "بروجيكتور" to "projector",
        "البروجيكتور" to "projector",
        "شاشة المسرح" to "stage monitor",
        "شاشة المنصة" to "stage monitor",
        "شاشة المنصه" to "stage monitor",
        "شاشة المنبر" to "stage monitor",
        "شاشة الواعظ" to "stage monitor",
        "مونيتور" to "monitor",
        "المونيتور" to "monitor",
        "شاشات" to "display",
        "الشاشات" to "display",
        "مخرج*" to "output",
        "المخرج*" to "output",
        "نافذة الإخراج" to "output window",
        "نافذة الاخراج" to "output window",
        "إخراج" to "output",
        "اخراج" to "output",
        "الإخراج" to "output",
        "الاخراج" to "output",
        "منص*" to "stage",
        "المنص*" to "stage",
        "مسرح" to "stage",
        "المسرح" to "stage",
        "منطقة" to "zone",
        "منطقه" to "zone",
        "المنطقة" to "zone",
        "المنطقه" to "zone",
        "مناطق" to "zone",
        "المناطق" to "zone",
        "تصميم" to "design",
        "التصميم" to "design",
        "رسال*" to "message",
        "الرسال*" to "message",
        "أرسل" to "send",
        "ارسل" to "send",
        "إرسال" to "send",
        "ارسال" to "send",
        "معاين*" to "preview",
        "المعاين*" to "preview",
        "ما على الشاشة" to "what is on screen",
        "ما على الشاشه" to "what is on screen",
        "ملف تعريف" to "profile",
        "الملف تعريف" to "profile",
        "ملفات تعريف" to "profile",
        "الملفات تعريف" to "profile",
        "بث" to "stream",
        "البث" to "stream",
        "تلفزيون" to "tv",
        "التلفزيون" to "tv",
        "تلفاز" to "tv",
        "التلفاز" to "tv",

        // Pages, tabs and tools.
        "إعدادات" to "settings",
        "اعدادات" to "settings",
        "الإعدادات" to "settings",
        "الاعدادات" to "settings",
        "خيارات" to "options",
        "الخيارات" to "options",
        "معالج الإعداد" to "setup wizard",
        "معالج الاعداد" to "setup wizard",
        "البدء من جديد" to "start over",
        "ابدأ من جديد" to "start over",
        "ابدا من جديد" to "start over",
        "اختصار*" to "shortcut",
        "الاختصار*" to "shortcut",
        "مفاتيح الاختصار" to "hotkeys",
        "لوحة المفاتيح" to "keyboard",
        "اللوحة المفاتيح" to "keyboard",
        "تبويب*" to "tab",
        "التبويب*" to "tab",
        "مكتبة الترانيم" to "song library",
        "مكتبة الأغاني" to "song library",
        "مكتبة الاغاني" to "song library",
        "مكتب*" to "library",
        "المكتب*" to "library",
        "ويب" to "web",
        "الويب" to "web",
        "موقع" to "website",
        "الموقع" to "website",
        "متصفح" to "browser",
        "المتصفح" to "browser",
        "قاموس" to "dictionary",
        "القاموس" to "dictionary",
        "سترونغ" to "strong",
        "كاميرا*" to "camera",
        "الكاميرا*" to "camera",
        "لوحة" to "canvas",
        "لوحه" to "canvas",
        "اللوحة" to "canvas",
        "اللوحه" to "canvas",
        "خادم" to "server",
        "الخادم" to "server",
        "سيرفر" to "server",
        "السيرفر" to "server",
        "عن بعد" to "remote",
        "جهاز التحكم" to "remote",
        "الجهاز التحكم" to "remote",
        "هاتف" to "phone",
        "الهاتف" to "phone",
        "جوال" to "phone",
        "الجوال" to "phone",
        "موبايل" to "phone",
        "الموبايل" to "phone",
        "جهاز لوحي" to "tablet",
        "الجهاز لوحي" to "tablet",
        "تابلت" to "tablet",
        "التابلت" to "tablet",
        "تكامل*" to "integrations",
        "التكامل*" to "integrations",

        // Services and planning.
        "ترتيب الخدمة" to "order of service",
        "ترتيب الخدمه" to "order of service",
        "برنامج الخدمة" to "order of service",
        "برنامج الخدمه" to "order of service",
        "برنامج العبادة" to "order of service",
        "برنامج العباده" to "order of service",
        "خدم*" to "service",
        "الخدم*" to "service",
        "اجتماع*" to "meeting",
        "الاجتماع*" to "meeting",
        "يوم الأحد" to "sunday",
        "يوم الاحد" to "sunday",
        "الأحد" to "sunday",
        "الاحد" to "sunday",
        "تقويم" to "calendar",
        "التقويم" to "calendar",
        "رزنامة" to "calendar",
        "رزنامه" to "calendar",
        "الرزنامة" to "calendar",
        "الرزنامه" to "calendar",
        "برنامج" to "schedule",
        "البرنامج" to "schedule",
        "جدول" to "schedule",
        "الجدول" to "schedule",
        "قائمة تشغيل" to "playlist",
        "القائمة تشغيل" to "playlist",
        "كل أحد" to "every sunday",
        "كل احد" to "every sunday",
        "كل يوم أحد" to "every sunday",
        "كل يوم احد" to "every sunday",
        "كل أسبوع" to "every week",
        "كل اسبوع" to "every week",
        "أسبوعي*" to "weekly",
        "اسبوعي*" to "weekly",
        "شهري*" to "monthly",
        "كرر" to "repeat",
        "تكرار" to "repeat",
        "قالب" to "template",
        "القالب" to "template",
        "قوالب" to "template",
        "القوالب" to "template",

        // Many, all, both.
        "كل" to "all",
        "الكل" to "all",
        "جميع" to "all",
        "كلها" to "all",
        "كله" to "all",
        "كلاهما" to "both",
        "الاثنين" to "both",
        "عدة" to "several",
        "عده" to "several",
        "بعض" to "several",
        "كثير" to "many",
        "كثيرة" to "many",
        "كثيره" to "many",
        "دفعة واحدة" to "at once",
        "دفعة واحده" to "at once",
        "مرة واحدة" to "at once",
        "مرة واحده" to "at once",
        "لهذه الخدمة" to "this service",
        "لهذه الخدمه" to "this service",
        "لهذا الاجتماع" to "this service",
        "لليوم" to "for today",
        "لهذا اليوم" to "for today",
        "مؤقتا" to "temporarily",
        "مؤقتاً" to "temporarily",

        // Languages, by name.
        "عربي*" to "arabic",
        "العربي*" to "arabic",
        "إنجليزي*" to "english",
        "انجليزي*" to "english",
        "الإنجليزي*" to "english",
        "الانجليزي*" to "english",
        "إنكليزي*" to "english",
        "انكليزي*" to "english",
        "الإنكليزي*" to "english",
        "الانكليزي*" to "english",
        "إسباني*" to "spanish",
        "اسباني*" to "spanish",
        "الإسباني*" to "spanish",
        "الاسباني*" to "spanish",
        "روسي*" to "russian",
        "الروسي*" to "russian",
        "أوكراني*" to "ukrainian",
        "اوكراني*" to "ukrainian",
        "الأوكراني*" to "ukrainian",
        "الاوكراني*" to "ukrainian",
        "بيلاروسي*" to "belarusian",
        "البيلاروسي*" to "belarusian",
        "بولندي*" to "polish",
        "البولندي*" to "polish",
        "ألماني*" to "german",
        "الماني*" to "german",
        "الألماني*" to "german",
        "الالماني*" to "german",
        "فرنسي*" to "french",
        "الفرنسي*" to "french",
        "برتغالي*" to "portuguese",
        "البرتغالي*" to "portuguese",
        "إيطالي*" to "italian",
        "ايطالي*" to "italian",
        "الإيطالي*" to "italian",
        "الايطالي*" to "italian",
        "هولندي*" to "dutch",
        "الهولندي*" to "dutch",
        "روماني*" to "romanian",
        "الروماني*" to "romanian",
        "تركي*" to "turkish",
        "التركي*" to "turkish",
        "فارسي*" to "persian",
        "الفارسي*" to "persian",
        "عبري*" to "hebrew",
        "العبري*" to "hebrew",
        "يوناني*" to "greek",
        "اليوناني*" to "greek",
        "هندي*" to "hindi",
        "الهندي*" to "hindi",
        "نيبالي*" to "nepali",
        "النيبالي*" to "nepali",
        "تاميل*" to "tamil",
        "التاميل*" to "tamil",
        "صيني*" to "chinese",
        "الصيني*" to "chinese",
        "ياباني*" to "japanese",
        "الياباني*" to "japanese",
        "كوري*" to "korean",
        "الكوري*" to "korean",
        "أرمني*" to "armenian",
        "ارمني*" to "armenian",
        "الأرمني*" to "armenian",
        "الارمني*" to "armenian",
        "أمهري*" to "amharic",
        "امهري*" to "amharic",
        "الأمهري*" to "amharic",
        "الامهري*" to "amharic",
        "سواحيلي*" to "swahili",
        "السواحيلي*" to "swahili",
        "لاتيني*" to "latin",
        "اللاتيني*" to "latin",

        // Colors.
        "أزرق غامق" to "dark blue",
        "ازرق غامق" to "dark blue",
        "أزرق داكن" to "dark blue",
        "ازرق داكن" to "dark blue",
        "أزرق فاتح" to "light blue",
        "ازرق فاتح" to "light blue",
        "أخضر غامق" to "dark green",
        "اخضر غامق" to "dark green",
        "أخضر فاتح" to "light green",
        "اخضر فاتح" to "light green",
        "أحمر غامق" to "dark red",
        "احمر غامق" to "dark red",
        "رمادي غامق" to "dark grey",
        "رمادي فاتح" to "light grey",
        "كحلي*" to "navy",
        "الكحلي*" to "navy",
        "سماوي*" to "light blue",
        "السماوي*" to "light blue",
        "أزرق" to "blue",
        "ازرق" to "blue",
        "الأزرق" to "blue",
        "الازرق" to "blue",
        "زرقاء" to "blue",
        "الزرقاء" to "blue",
        "أسود" to "black",
        "اسود" to "black",
        "الأسود" to "black",
        "الاسود" to "black",
        "سوداء" to "black",
        "السوداء" to "black",
        "أبيض" to "white",
        "ابيض" to "white",
        "الأبيض" to "white",
        "الابيض" to "white",
        "بيضاء" to "white",
        "البيضاء" to "white",
        "رمادي*" to "grey",
        "الرمادي*" to "grey",
        "فضي*" to "silver",
        "الفضي*" to "silver",
        "أحمر" to "red",
        "احمر" to "red",
        "الأحمر" to "red",
        "الاحمر" to "red",
        "حمراء" to "red",
        "الحمراء" to "red",
        "عنابي*" to "maroon",
        "العنابي*" to "maroon",
        "نبيتي*" to "maroon",
        "النبيتي*" to "maroon",
        "برتقالي*" to "orange",
        "البرتقالي*" to "orange",
        "أصفر" to "yellow",
        "اصفر" to "yellow",
        "الأصفر" to "yellow",
        "الاصفر" to "yellow",
        "صفراء" to "yellow",
        "الصفراء" to "yellow",
        "ذهبي*" to "gold",
        "الذهبي*" to "gold",
        "أخضر" to "green",
        "اخضر" to "green",
        "الأخضر" to "green",
        "الاخضر" to "green",
        "خضراء" to "green",
        "الخضراء" to "green",
        "ليموني*" to "lime",
        "الليموني*" to "lime",
        "فيروزي*" to "turquoise",
        "الفيروزي*" to "turquoise",
        "بنفسجي*" to "purple",
        "البنفسجي*" to "purple",
        "أرجواني*" to "violet",
        "ارجواني*" to "violet",
        "الأرجواني*" to "violet",
        "الارجواني*" to "violet",
        "وردي*" to "pink",
        "الوردي*" to "pink",
        "زهري*" to "pink",
        "الزهري*" to "pink",
        "بني" to "brown",
        "البني" to "brown",
        "بنية" to "brown",
        "بنيه" to "brown",
        "البنية" to "brown",
        "البنيه" to "brown",
        "بيج" to "beige",
        "البيج" to "beige",
        "كريمي*" to "cream",
        "الكريمي*" to "cream",
        "غامق*" to "dark",
        "داكن*" to "dark",
        "فاتح*" to "light",

        // Talking to the helper.
        "مرحبا" to "hello",
        "مرحباً" to "hello",
        "أهلا" to "hello",
        "اهلا" to "hello",
        "أهلاً" to "hello",
        "اهلاً" to "hello",
        "السلام عليكم" to "hello",
        "سلام" to "hello",
        "صباح الخير" to "hello",
        "مساء الخير" to "hello",
        "ساعدني" to "help",
        "مساعدة" to "help",
        "مساعده" to "help",
        "المساعدة" to "help",
        "المساعده" to "help",
        "ماذا تستطيع أن تفعل" to "what can you do",
        "ماذا تستطيع ان تفعل" to "what can you do",
        "ماذا يمكنك أن تفعل" to "what can you do",
        "ماذا يمكنك ان تفعل" to "what can you do",
        "ماذا تستطيع" to "what can you do",
        "ماذا تفعل" to "what do you do",
        "ايش تقدر تسوي" to "what can you do",
        "من أنت" to "who are you",
        "من انت" to "who are you",
        "مين انت" to "who are you",
        "شكرا" to "thanks",
        "شكراً" to "thanks",
        "شكرا لك" to "thank you",
        "شكراً لك" to "thank you",
        "أشكرك" to "thank you",
        "اشكرك" to "thank you",
        "من فضلك" to "please",
        "لو سمحت" to "please",
        "رجاء" to "please",
        "ويك" to "wick",
    ),
)
