package org.churchpresenter.helper.intent.glossary

internal val BELARUSIAN = Glossary(
    "be",
    listOf(
        // Asking where, or how.
        "дзе" to "where",
        "куды" to "where",
        "як мне" to "how do i",
        "як я магу" to "how can i",
        "як можна" to "how can i",
        "як" to "how do i",
        "не магу знайсці" to "can't find",
        "не знаходжу" to "can't find",
        "пакажы мне" to "show me",
        "падкажы*" to "how do i",

        // Doing.
        "пакажы" to "show",
        "паказаць" to "show",
        "пакажыце" to "show",
        "паказваць" to "show",
        "вывядзі на экран" to "show",
        "вывядзі" to "show",
        "вывесці" to "show",
        "адлюструй*" to "display",
        "адкрый*" to "open",
        "адкрыць" to "open",
        "перайдзі на" to "go to",
        "перайдзі да" to "go to",
        "перайдзі ў" to "go to",
        "перайдзі у" to "go to",
        "перайдзі" to "go to",
        "перайсці" to "go to",
        "пераключы на" to "switch to",
        "пераключыся на" to "switch to",
        "знайдзі" to "find",
        "знайдзіце" to "find",
        "знайсці" to "find",
        "прачытай*" to "read",
        "зрабі" to "make",
        "зрабіце" to "make",
        "зрабіць" to "make",
        "ствары*" to "create",
        "стварыць" to "create",
        "дадай*" to "add",
        "дадаць" to "add",
        "дадава*" to "add",
        "загрузі*" to "load",
        "загрузіць" to "load",
        "імпарт*" to "import",
        "спампу*" to "download",
        "спампава*" to "download",
        "скачай*" to "download",
        "скачаць" to "download",
        "усталю*" to "install",
        "устанаві*" to "install",
        "выберы*" to "choose",
        "выбраць" to "choose",
        "абяры*" to "choose",
        "абраць" to "choose",
        "наладзь*" to "set up",
        "наладзі*" to "set up",
        "наладжва*" to "set up",
        "падключ*" to "connect",
        "прызнач*" to "assign",
        "прыбяры*" to "hide",
        "прыбраць" to "hide",
        "схавай*" to "hide",
        "схаваць" to "hide",
        "спыні*" to "stop",
        "спыніць" to "stop",
        "выдалі*" to "delete",
        "ачысці*" to "clear",
        "ачысціць" to "clear",
        "зацямні*" to "black out",
        "пагасі экран" to "black out",
        "пусты экран" to "blank",
        "адмяні*" to "undo",
        "вярні як было" to "undo",
        "вярні назад" to "undo",
        "у эфір" to "go live",
        "ў эфір" to "go live",
        "вывесці ў эфір" to "go live",
        "вывядзі ў эфір" to "go live",
        "уключы*" to "turn on",
        "ўключы*" to "turn on",
        "выключы*" to "turn off",
        "пераключы*" to "toggle",
        "наступн*" to "next",
        "далей" to "next",
        "наперад" to "forward",
        "папярэдн*" to "previous",
        "назад" to "back",
        "павялічы*" to "increase",
        "больш" to "bigger",
        "большы" to "bigger",
        "большым" to "bigger",
        "буйней" to "bigger",
        "паменшы*" to "decrease",
        "менш" to "smaller",
        "меншы" to "smaller",
        "меншым" to "smaller",
        "драбней" to "smaller",
        "канверту*" to "convert",
        "канвертар*" to "converter",
        "перанясі*" to "transfer",
        "перанос*" to "transfer",
        "рэдагу*" to "edit",
        "адрэдагу*" to "edit",
        "змяні*" to "change",
        "змяніць" to "change",
        "памяняй*" to "change",
        "перайменуй*" to "rename",
        "перайменаваць" to "rename",
        "выправі*" to "fix",
        "упарадкуй*" to "organize",
        "упарадкава*" to "organize",
        "арганізу*" to "organize",
        "навесці парадак" to "clean up",
        "параўна*" to "compare",
        "перакладзі" to "translate",
        "перакласці" to "translate",
        "сплануй*" to "plan",
        "спланава*" to "plan",
        "плану*" to "plan",
        "заплану*" to "plan",
        "аўтаматызу*" to "automate",
        "аўтаматычн*" to "automatically",
        "вызнач*" to "identify",
        "пранумаруй*" to "number the",

        // Too small, too big, not working.
        "занадта дробн*" to "too small",
        "занадта маленьк*" to "too small",
        "занадта мал*" to "too small",
        "надта дробн*" to "too small",
        "дрэнна відаць" to "hard to read",
        "не відаць" to "hard to read",
        "не чытаецца" to "hard to read",
        "цяжка чытаць" to "hard to read",
        "занадта вялік*" to "too big",
        "занадта буйн*" to "too big",
        "надта вялік*" to "too big",
        "не змяшчаецца" to "doesn't fit",
        "не ўлазіць" to "doesn't fit",
        "не ўмяшчаецца" to "doesn't fit",
        "не працуе" to "not working",
        "не паказвае" to "not showing",
        "нічога не паказвае" to "nothing shows",
        "нічога няма" to "nothing shows",
        "чорны экран" to "screen is black",
        "няма сігналу" to "no signal",
        "няма карцінкі" to "no picture",
        "няма выявы" to "no picture",
        "які экран" to "which screen",
        "які манітор" to "which monitor",
        "які праектар" to "which projector",

        // What is on screen.
        "фон*" to "background",
        "задні план" to "backdrop",
        "тэкст песні" to "lyrics",
        "словы песні" to "lyrics",
        "песень" to "songs",
        "песн*" to "song",
        "гімн*" to "hymn",
        "праслаўлен*" to "worship",
        "біблі*" to "bible",
        "пісанн*" to "scripture",
        "верш*" to "verse",
        "раздзел*" to "chapter",
        "глава" to "chapter",
        "главу" to "chapter",
        "главы" to "chapter",
        "шрыфт*" to "font",
        "памер*" to "size",
        "тэкст*" to "text",
        "словы" to "words",
        "літар*" to "letters",
        "слайд-шоу" to "slideshow",
        "слайдшоу" to "slideshow",
        "слайд*" to "slide",
        "фатаграф*" to "photo",
        "фота*" to "photo",
        "карцін*" to "picture",
        "выяв*" to "picture",
        "малюн*" to "image",
        "альбом*" to "album",
        "прэзентацы*" to "presentation",
        "відэа" to "video",
        "фільм*" to "movie",
        "ролік*" to "clip",
        "кліп*" to "clip",
        "медыя" to "media",
        "аўдыя" to "audio",
        "ніжн* трац*" to "lower third",
        "цітр*" to "lower third",
        "плашк*" to "name strap",
        "імя і пасада" to "name and title",
        "аб'яв*" to "announcement",
        "абвестк*" to "announcement",
        "анонс*" to "announcement",
        "бягуч* радок" to "ticker",
        "бягучага радка" to "ticker",
        "дзіцяч* пакой*" to "kids room",
        "дзіцяч* пакоі" to "kids room",
        "зваротн* адлік*" to "countdown",
        "адлік*" to "countdown",
        "таймер*" to "timer",
        "секундамер*" to "stopwatch",
        "гадзіннік*" to "clock",
        "бягучы час" to "current time",
        "час" to "time",
        "нататк*" to "notes",
        "акорд*" to "chord",
        "пераклад*" to "translation",
        "мов*" to "language",
        "двухмоўн*" to "bilingual",
        "на іншай мове" to "another language",
        "іншая мова" to "another language",
        "іншую мову" to "another language",
        "другая мова" to "second language",
        "другую мову" to "second language",
        "на дзвюх мовах" to "two languages",

        // Screens and outputs.
        "галоўн* экран*" to "main screen",
        "поўны экран" to "full screen",
        "на ўвесь экран" to "full screen",
        "на увесь экран" to "full screen",
        "увесь экран" to "full screen",
        "ўвесь экран" to "full screen",
        "поўнаэкранн*" to "fullscreen",
        "другі экран" to "second screen",
        "экран*" to "screen",
        "праектар*" to "projector",
        "манітор* сцэны" to "stage monitor",
        "манітор* на сцэне" to "stage monitor",
        "манітор* для сцэны" to "stage monitor",
        "сцэнічн* манітор*" to "stage monitor",
        "суфлёр*" to "confidence monitor",
        "манітор*" to "monitor",
        "дысплэ*" to "display",
        "вывад*" to "output",
        "акно вываду" to "output window",
        "сцэн*" to "stage",
        "зон*" to "zone",
        "раскладк*" to "layout",
        "макет*" to "layout",
        "размяшчэнн*" to "arrangement",
        "паведамлен*" to "message",
        "адпраў*" to "send",
        "дашлі*" to "send",
        "папярэдні прагляд" to "preview",
        "прагляд*" to "preview",
        "прэв'ю" to "preview",
        "што на экране" to "what is on screen",
        "профіл*" to "profile",
        "трансляцы*" to "stream",
        "стрым*" to "stream",
        "тэлевізар*" to "tv",

        // Pages, tabs and tools.
        "налад*" to "settings",
        "параметр*" to "options",
        "майстар налад*" to "setup wizard",
        "пачаць спачатку" to "start over",
        "пачаць зноў" to "start over",
        "спалучэнн* клавіш" to "shortcut",
        "гарач* клавіш*" to "hotkeys",
        "клавіятур*" to "keyboard",
        "укладк*" to "tab",
        "ўкладк*" to "tab",
        "бібліятэк* песень" to "song library",
        "бібліятэк*" to "library",
        "вэб" to "web",
        "веб" to "web",
        "сайт*" to "website",
        "браўзер*" to "browser",
        "слоўнік*" to "dictionary",
        "стронг*" to "strong",
        "камер*" to "camera",
        "палатн*" to "canvas",
        "сервер*" to "server",
        "аддален*" to "remote",
        "пульт*" to "remote",
        "тэлефон*" to "phone",
        "смартфон*" to "phone",
        "планшэт*" to "tablet",
        "кампаньён*" to "companion",
        "інтэграцы*" to "integrations",

        // Services and planning.
        "парадак служэння" to "order of service",
        "парадку служэння" to "order of service",
        "праграма служэння" to "order of service",
        "богаслужэнн*" to "service",
        "служэнн*" to "service",
        "сход*" to "meeting",
        "нядзел*" to "sunday",
        "каляндар*" to "calendar",
        "календар*" to "calendar",
        "праграм*" to "schedule",
        "плэйліст*" to "playlist",
        "плейліст*" to "playlist",
        "кожную нядзелю" to "every sunday",
        "кожны тыдзень" to "every week",
        "штотыднёв*" to "weekly",
        "штомесячн*" to "monthly",
        "паўтара*" to "repeat",
        "паўтор*" to "repeat",
        "шаблон*" to "template",

        // Many, all, both.
        "усе" to "all",
        "ўсе" to "all",
        "усё" to "all",
        "ўсё" to "all",
        "усюды" to "everything",
        "паўсюль" to "everything",
        "абодва" to "both",
        "абедзве" to "both",
        "абодвух" to "both",
        "некалькі" to "several",
        "шмат" to "many",
        "многа" to "many",
        "адразу" to "at once",
        "для гэтага служэння" to "this service",
        "на сёння" to "for today",
        "часова" to "temporarily",

        // Languages, by name.
        "руск*" to "russian",
        "украінск*" to "ukrainian",
        "беларуск*" to "belarusian",
        "англійск*" to "english",
        "іспанск*" to "spanish",
        "нямецк*" to "german",
        "французск*" to "french",
        "польск*" to "polish",
        "казахск*" to "kazakh",
        "узбекск*" to "uzbek",
        "румынск*" to "romanian",
        "малдаўск*" to "moldovan",
        "партугальск*" to "portuguese",
        "італьянск*" to "italian",
        "чэшск*" to "czech",
        "літоўск*" to "lithuanian",
        "латышск*" to "latvian",
        "латын*" to "latin",

        // Colors.
        "цёмна-сін*" to "navy",
        "светла-сін*" to "light blue",
        "блакітн*" to "light blue",
        "сіні" to "blue",
        "сінім" to "blue",
        "сіняга" to "blue",
        "сіняя" to "blue",
        "сінюю" to "blue",
        "сіняе" to "blue",
        "сіняй" to "blue",
        "чорн*" to "black",
        "белы" to "white",
        "белым" to "white",
        "белага" to "white",
        "белая" to "white",
        "белую" to "white",
        "белае" to "white",
        "белай" to "white",
        "шэры" to "grey",
        "шэрым" to "grey",
        "шэрага" to "grey",
        "шэрая" to "grey",
        "шэрую" to "grey",
        "шэрае" to "grey",
        "срэбн*" to "silver",
        "чырвон*" to "red",
        "бардов*" to "maroon",
        "аранжав*" to "orange",
        "памяранцав*" to "orange",
        "жоўт*" to "yellow",
        "залат*" to "gold",
        "зялён*" to "green",
        "салатав*" to "lime",
        "бірузов*" to "turquoise",
        "фіялетав*" to "purple",
        "бэзав*" to "violet",
        "ружов*" to "pink",
        "карычнев*" to "brown",
        "бэжав*" to "beige",
        "крэмав*" to "cream",
        "цёмн*" to "dark",
        "светл*" to "light",

        // Talking to the helper.
        "прывітанне" to "hello",
        "прывітанні" to "hello",
        "вітаю" to "hello",
        "добры дзень" to "hello",
        "дапамажы*" to "help",
        "дапамога" to "help",
        "дапамогу" to "help",
        "што ты ўмееш" to "what can you do",
        "што ты умееш" to "what can you do",
        "што ты можаш" to "what can you do",
        "хто ты" to "who are you",
        "дзякуй" to "thanks",
        "дзякую" to "thank you",
        "калі ласка" to "please",
        "вік" to "wick",
        "уік" to "wick",
    ),
)
