package org.churchpresenter.helper.intent.glossary

internal val CHINESE = Glossary(
    "zh",
    listOf(
        // Asking where, or how.
        "在哪里" to "where",
        "在哪儿" to "where",
        "在哪裡" to "where",
        "在哪" to "where",
        "哪里" to "where",
        "哪儿" to "where",
        "哪裡" to "where",
        "我该怎么" to "how do i",
        "我怎么" to "how do i",
        "我如何" to "how do i",
        "怎样才能" to "how can i",
        "如何才能" to "how can i",
        "怎么才能" to "how can i",
        "怎么" to "how do i",
        "怎麼" to "how do i",
        "怎样" to "how do i",
        "如何" to "how do i",
        "教我" to "how do i",
        "找不到" to "can't find",
        "找不着" to "can't find",
        "给我看" to "show me",
        "給我看" to "show me",

        // Doing.
        "显示" to "show",
        "顯示" to "show",
        "展示" to "show",
        "打开" to "open",
        "打開" to "open",
        "跳转到" to "go to",
        "转到" to "go to",
        "轉到" to "go to",
        "前往" to "go to",
        "切换到" to "switch to",
        "切換到" to "switch to",
        "查找" to "find",
        "搜索" to "find",
        "搜尋" to "find",
        "寻找" to "find",
        "朗读" to "read",
        "改成" to "make",
        "变成" to "make",
        "设为" to "make",
        "设成" to "make",
        "弄成" to "make",
        "创建" to "create",
        "新建" to "create",
        "建立" to "create",
        "添加" to "add",
        "增加" to "add",
        "加入" to "add",
        "导入" to "import",
        "匯入" to "import",
        "加载" to "load",
        "载入" to "load",
        "載入" to "load",
        "上传" to "upload",
        "下载" to "download",
        "下載" to "download",
        "安装" to "install",
        "安裝" to "install",
        "选择" to "choose",
        "選擇" to "choose",
        "配置" to "set up",
        "连接" to "connect",
        "連接" to "connect",
        "分配" to "assign",
        "指定" to "assign",
        "隐藏" to "hide",
        "隱藏" to "hide",
        "停止" to "stop",
        "暂停" to "pause",
        "删除" to "delete",
        "刪除" to "delete",
        "移除" to "remove",
        "清除" to "clear",
        "清空" to "clear",
        "清屏" to "clear",
        "黑屏" to "black out",
        "空白" to "blank",
        "撤销" to "undo",
        "撤消" to "undo",
        "復原" to "undo",
        "还原" to "undo",
        "上屏" to "go live",
        "投屏" to "go live",
        "开启" to "turn on",
        "打开输出" to "turn on output",
        "关闭" to "turn off",
        "關閉" to "turn off",
        "关掉" to "turn off",
        "下一" to "next",
        "前进" to "forward",
        "上一" to "previous",
        "后退" to "back",
        "返回" to "back",
        "放大" to "bigger",
        "变大" to "bigger",
        "調大" to "bigger",
        "调大" to "bigger",
        "加大" to "bigger",
        "大一点" to "bigger",
        "大一些" to "bigger",
        "更大" to "bigger",
        "增大" to "increase",
        "缩小" to "smaller",
        "縮小" to "smaller",
        "变小" to "smaller",
        "调小" to "smaller",
        "小一点" to "smaller",
        "小一些" to "smaller",
        "更小" to "smaller",
        "减小" to "decrease",
        "转换器" to "converter",
        "转换" to "convert",
        "轉換" to "convert",
        "迁移" to "migrate",
        "转移" to "transfer",
        "编辑" to "edit",
        "編輯" to "edit",
        "修改" to "change",
        "更改" to "change",
        "改变" to "change",
        "更换" to "change",
        "重命名" to "rename",
        "改名" to "rename",
        "修复" to "fix",
        "整理" to "organize",
        "比较" to "compare",
        "对比" to "compare",
        "翻译" to "translate",
        "翻譯" to "translate",
        "规划" to "plan",
        "计划" to "plan",
        "安排" to "plan",
        "自动化" to "automate",
        "自动" to "automatically",
        "自動" to "automatically",
        "识别" to "identify",
        "编号" to "number the",

        // Too small, too big, not working.
        "太小" to "too small",
        "看不清楚" to "hard to read",
        "看不清" to "hard to read",
        "难以阅读" to "hard to read",
        "看不到" to "hard to read",
        "太大" to "too big",
        "放不下" to "doesn't fit",
        "装不下" to "doesn't fit",
        "显示不全" to "doesn't fit",
        "不工作" to "not working",
        "没反应" to "not working",
        "不能用" to "not working",
        "用不了" to "not working",
        "坏了" to "not working",
        "不显示" to "not showing",
        "没显示" to "not showing",
        "沒顯示" to "not showing",
        "什么都不显示" to "nothing shows",
        "什么都没有" to "nothing shows",
        "屏幕是黑的" to "screen is black",
        "屏幕全黑" to "screen is black",
        "没有信号" to "no signal",
        "无信号" to "no signal",
        "没有画面" to "no picture",
        "没画面" to "no picture",
        "哪个屏幕" to "which screen",
        "哪块屏幕" to "which screen",
        "哪个显示器" to "which monitor",
        "哪个投影仪" to "which projector",

        // What is on screen.
        "背景" to "background",
        "底色" to "background",
        "歌词" to "lyrics",
        "歌詞" to "lyrics",
        "歌曲" to "song",
        "诗歌" to "song",
        "詩歌" to "song",
        "首歌" to "song",
        "赞美诗" to "hymn",
        "讚美詩" to "hymn",
        "圣诗" to "hymn",
        "聖詩" to "hymn",
        "敬拜" to "worship",
        "赞美" to "worship",
        "圣经" to "bible",
        "聖經" to "bible",
        "经文" to "scripture",
        "經文" to "scripture",
        "经节" to "verse",
        "經節" to "verse",
        "字体" to "font",
        "字體" to "font",
        "字号" to "size",
        "字號" to "size",
        "大小" to "size",
        "尺寸" to "size",
        "文字" to "text",
        "文本" to "text",
        "幻灯片放映" to "slideshow",
        "轮播" to "slideshow",
        "幻灯片" to "slide",
        "幻燈片" to "slide",
        "照片" to "photo",
        "相片" to "photo",
        "图片" to "picture",
        "圖片" to "picture",
        "图像" to "image",
        "相册" to "album",
        "相簿" to "album",
        "演示文稿" to "presentation",
        "简报" to "presentation",
        "简报文件" to "presentation",
        "视频" to "video",
        "視頻" to "video",
        "影片" to "video",
        "电影" to "movie",
        "電影" to "movie",
        "短片" to "clip",
        "片段" to "clip",
        "媒体" to "media",
        "媒體" to "media",
        "音频" to "audio",
        "字幕条" to "lower third",
        "下三分之一" to "lower third",
        "人名条" to "name strap",
        "姓名和职位" to "name and title",
        "通告" to "announcement",
        "公告" to "announcement",
        "通知" to "notice",
        "滚动字幕" to "ticker",
        "跑马灯" to "ticker",
        "儿童室" to "kids room",
        "儿童房" to "kids room",
        "育婴室" to "nursery",
        "倒计时" to "countdown",
        "倒數" to "countdown",
        "计时器" to "timer",
        "定时器" to "timer",
        "秒表" to "stopwatch",
        "正计时" to "count up",
        "时钟" to "clock",
        "時鐘" to "clock",
        "当前时间" to "current time",
        "时间" to "time",
        "時間" to "time",
        "讲道笔记" to "sermon notes",
        "笔记" to "notes",
        "备注" to "notes",
        "和弦" to "chord",
        "译本" to "translation",
        "译文" to "translation",
        "语言" to "language",
        "語言" to "language",
        "双语" to "bilingual",
        "雙語" to "bilingual",
        "其他语言" to "another language",
        "另一种语言" to "another language",
        "别的语言" to "another language",
        "第二语言" to "second language",
        "两种语言" to "two languages",

        // Screens and outputs.
        "主屏幕" to "main screen",
        "主屏" to "main screen",
        "全屏" to "full screen",
        "全螢幕" to "full screen",
        "第二个屏幕" to "second screen",
        "第二屏幕" to "second screen",
        "副屏" to "second screen",
        "屏幕" to "screen",
        "螢幕" to "screen",
        "投影仪" to "projector",
        "投影機" to "projector",
        "投影" to "projection",
        "舞台监视器" to "stage monitor",
        "舞台显示器" to "stage monitor",
        "舞台屏幕" to "stage monitor",
        "提词器" to "confidence monitor",
        "监视器" to "monitor",
        "显示器" to "monitor",
        "輸出" to "output",
        "输出窗口" to "output window",
        "输出" to "output",
        "舞台" to "stage",
        "区域" to "zone",
        "分区" to "zone",
        "布局" to "layout",
        "版面" to "layout",
        "排列" to "arrangement",
        "消息" to "message",
        "信息" to "message",
        "留言" to "message",
        "发送" to "send",
        "发给" to "send",
        "预览" to "preview",
        "預覽" to "preview",
        "屏幕上是什么" to "what is on screen",
        "配置文件" to "profile",
        "直播" to "stream",
        "推流" to "stream",
        "电视" to "tv",

        // Pages, tabs and tools.
        "设置向导" to "setup wizard",
        "快速上手" to "setup wizard",
        "设置" to "settings",
        "設置" to "settings",
        "設定" to "settings",
        "选项卡" to "tab",
        "选项" to "options",
        "偏好" to "preferences",
        "重新开始" to "start over",
        "快捷键" to "shortcut",
        "快捷鍵" to "shortcut",
        "热键" to "hotkeys",
        "键盘" to "keyboard",
        "鍵盤" to "keyboard",
        "标签页" to "tab",
        "歌曲库" to "song library",
        "曲库" to "song library",
        "网页" to "web",
        "网站" to "website",
        "浏览器" to "browser",
        "原文词典" to "dictionary",
        "词典" to "dictionary",
        "字典" to "dictionary",
        "斯特朗" to "strong",
        "摄像头" to "camera",
        "摄像机" to "camera",
        "相机" to "camera",
        "画布" to "canvas",
        "服务器" to "server",
        "伺服器" to "server",
        "远程" to "remote",
        "遥控" to "remote",
        "手机" to "phone",
        "手機" to "phone",
        "平板" to "tablet",
        "集成" to "integrations",

        // Services and planning.
        "礼拜程序" to "order of service",
        "崇拜程序" to "order of service",
        "聚会流程" to "order of service",
        "程序单" to "schedule",
        "礼拜" to "service",
        "禮拜" to "service",
        "崇拜" to "service",
        "聚会" to "meeting",
        "聚會" to "meeting",
        "每个主日" to "every sunday",
        "每周日" to "every sunday",
        "主日" to "sunday",
        "星期天" to "sunday",
        "星期日" to "sunday",
        "周日" to "sunday",
        "日历" to "calendar",
        "日曆" to "calendar",
        "播放列表" to "playlist",
        "每周" to "every week",
        "每星期" to "every week",
        "每个月" to "monthly",
        "每月" to "monthly",
        "重复" to "repeat",
        "模板" to "template",
        "範本" to "template",

        // Many, all, both.
        "所有" to "all",
        "全部" to "all",
        "一切" to "everything",
        "两个都" to "both",
        "两者" to "both",
        "多个" to "multiple",
        "几个" to "several",
        "很多" to "many",
        "批量" to "batch",
        "一起" to "together",
        "同时" to "at once",
        "这次礼拜" to "this service",
        "今天" to "for today",
        "暂时" to "temporarily",
        "临时" to "temporarily",

        // Languages, by name.
        "英语" to "english",
        "英文" to "english",
        "西班牙语" to "spanish",
        "俄语" to "russian",
        "俄文" to "russian",
        "乌克兰语" to "ukrainian",
        "白俄罗斯语" to "belarusian",
        "波兰语" to "polish",
        "德语" to "german",
        "德文" to "german",
        "法语" to "french",
        "法文" to "french",
        "葡萄牙语" to "portuguese",
        "意大利语" to "italian",
        "荷兰语" to "dutch",
        "罗马尼亚语" to "romanian",
        "捷克语" to "czech",
        "斯洛伐克语" to "slovak",
        "克罗地亚语" to "croatian",
        "塞尔维亚语" to "serbian",
        "保加利亚语" to "bulgarian",
        "匈牙利语" to "hungarian",
        "希腊语" to "greek",
        "土耳其语" to "turkish",
        "阿拉伯语" to "arabic",
        "波斯语" to "persian",
        "希伯来语" to "hebrew",
        "印地语" to "hindi",
        "尼泊尔语" to "nepali",
        "泰米尔语" to "tamil",
        "泰语" to "thai",
        "泰文" to "thai",
        "老挝语" to "lao",
        "中文" to "chinese",
        "汉语" to "chinese",
        "华语" to "chinese",
        "普通话" to "mandarin",
        "國語" to "mandarin",
        "粤语" to "cantonese",
        "广东话" to "cantonese",
        "日语" to "japanese",
        "日文" to "japanese",
        "韩语" to "korean",
        "韩文" to "korean",
        "朝鲜语" to "korean",
        "越南语" to "vietnamese",
        "印度尼西亚语" to "indonesian",
        "印尼语" to "indonesian",
        "马来语" to "malay",
        "他加禄语" to "tagalog",
        "菲律宾语" to "filipino",
        "斯瓦希里语" to "swahili",
        "阿姆哈拉语" to "amharic",
        "哈萨克语" to "kazakh",
        "乌兹别克语" to "uzbek",
        "爱沙尼亚语" to "estonian",
        "拉脱维亚语" to "latvian",
        "立陶宛语" to "lithuanian",
        "芬兰语" to "finnish",
        "瑞典语" to "swedish",
        "挪威语" to "norwegian",
        "丹麦语" to "danish",
        "亚美尼亚语" to "armenian",
        "格鲁吉亚语" to "georgian",
        "摩尔多瓦语" to "moldovan",
        "拉丁语" to "latin",
        "拉丁文" to "latin",

        // Colors.
        "深蓝" to "navy",
        "藏青" to "navy",
        "海军蓝" to "navy",
        "浅蓝" to "light blue",
        "淡蓝" to "light blue",
        "天蓝" to "sky",
        "蓝绿色" to "teal",
        "蓝色" to "blue",
        "藍色" to "blue",
        "蓝" to "blue",
        "藍" to "blue",
        "黑色" to "black",
        "黑底" to "black",
        "白色" to "white",
        "白底" to "white",
        "灰色" to "grey",
        "银色" to "silver",
        "酒红" to "maroon",
        "枣红" to "maroon",
        "红色" to "red",
        "紅色" to "red",
        "红" to "red",
        "紅" to "red",
        "橙色" to "orange",
        "橘色" to "orange",
        "黄色" to "yellow",
        "黃色" to "yellow",
        "金色" to "gold",
        "黄绿" to "lime",
        "橄榄绿" to "olive",
        "深绿" to "dark green",
        "浅绿" to "light green",
        "绿色" to "green",
        "綠色" to "green",
        "绿" to "green",
        "青色" to "cyan",
        "绿松石" to "turquoise",
        "紫罗兰" to "violet",
        "淡紫" to "lavender",
        "紫色" to "purple",
        "紫" to "purple",
        "粉红" to "pink",
        "粉色" to "pink",
        "洋红" to "magenta",
        "棕色" to "brown",
        "咖啡色" to "brown",
        "褐色" to "brown",
        "米色" to "beige",
        "奶油色" to "cream",
        "深色" to "dark",
        "浅色" to "light",
        "深" to "dark",
        "浅" to "light",

        // Talking to the helper.
        "你好" to "hello",
        "您好" to "hello",
        "哈喽" to "hello",
        "嗨" to "hi",
        "帮帮我" to "help",
        "帮助" to "help",
        "幫助" to "help",
        "帮我" to "help",
        "你能做什么" to "what can you do",
        "你会做什么" to "what can you do",
        "你能干什么" to "what can you do",
        "你会什么" to "what can you do",
        "你是谁" to "who are you",
        "你是誰" to "who are you",
        "谢谢" to "thanks",
        "謝謝" to "thanks",
        "多谢" to "thanks",
        "谢了" to "thanks",
        "感谢" to "thank you",
        "麻烦你" to "please",
        "请" to "please",
        "請" to "please",
        "维克" to "wick",
        "威克" to "wick",
    ),
    spaced = false,
)
