package org.churchpresenter.helper.intent.glossary

internal val CROATIAN = Glossary(
    "hr",
    listOf(
        // Asking where, or how.
        "gdje" to "where",
        "kamo" to "where",
        "kuda" to "where",
        "kako mogu" to "how can i",
        "kako se može" to "how can i",
        "kako se moze" to "how can i",
        "kako" to "how do i",
        "ne mogu naći" to "can't find",
        "ne mogu naci" to "can't find",
        "ne mogu pronaći" to "can't find",
        "ne mogu pronaci" to "can't find",
        "ne nalazim" to "can't find",
        "pokaži mi" to "show me",
        "pokazi mi" to "show me",

        // Doing.
        "pokaži" to "show",
        "pokazi" to "show",
        "pokazati" to "show",
        "pokažite" to "show",
        "pokazite" to "show",
        "prikaži uživo" to "go live",
        "prikazi uzivo" to "go live",
        "prikaži" to "display",
        "prikazi" to "display",
        "prikazati" to "display",
        "otvori" to "open",
        "otvoriti" to "open",
        "otvorite" to "open",
        "idi na" to "go to",
        "idi u" to "go to",
        "idi do" to "go to",
        "prijeđi na" to "go to",
        "prijedi na" to "go to",
        "prijeđi u" to "go to",
        "prijedi u" to "go to",
        "prebaci na" to "switch to",
        "prebaci se na" to "switch to",
        "nađi" to "find",
        "nadji" to "find",
        "nadi" to "find",
        "pronađi" to "find",
        "pronadji" to "find",
        "pronadi" to "find",
        "naći" to "find",
        "naci" to "find",
        "pronaći" to "find",
        "pronaci" to "find",
        "potraži" to "find",
        "potrazi" to "find",
        "pročitaj" to "read",
        "procitaj" to "read",
        "napravi" to "make",
        "napraviti" to "make",
        "učini" to "make",
        "ucini" to "make",
        "stvori" to "create",
        "stvoriti" to "create",
        "kreiraj*" to "create",
        "dodaj*" to "add",
        "dodati" to "add",
        "učitaj*" to "load",
        "ucitaj*" to "load",
        "uvezi" to "import",
        "uvesti" to "import",
        "uvoz*" to "import",
        "importiraj*" to "import",
        "preuzmi" to "download",
        "preuzeti" to "download",
        "skini" to "download",
        "skinuti" to "download",
        "instaliraj*" to "install",
        "odaberi*" to "choose",
        "izaberi*" to "choose",
        "odabrati" to "choose",
        "izabrati" to "choose",
        "postavi*" to "set up",
        "konfiguriraj*" to "set up",
        "poveži" to "connect",
        "povezi" to "connect",
        "povezati" to "connect",
        "spoji" to "connect",
        "spojiti" to "connect",
        "dodijeli*" to "assign",
        "sakrij*" to "hide",
        "zaustavi*" to "stop",
        "obriši" to "delete",
        "obrisi" to "delete",
        "obrisati" to "delete",
        "izbriši" to "delete",
        "izbrisi" to "delete",
        "izbrisati" to "delete",
        "ukloni" to "delete",
        "ukloniti" to "delete",
        "očisti" to "clear",
        "ocisti" to "clear",
        "očistiti" to "clear",
        "ocistiti" to "clear",
        "zatamni*" to "black out",
        "prazan zaslon" to "blank",
        "prazan ekran" to "blank",
        "poništi*" to "undo",
        "ponisti*" to "undo",
        "vrati kako je bilo" to "undo",
        "vrati natrag" to "undo",
        "uživo" to "go live",
        "uzivo" to "go live",
        "pusti uživo" to "go live",
        "pusti uzivo" to "go live",
        "uključi*" to "turn on",
        "ukljuci*" to "turn on",
        "isključi*" to "turn off",
        "iskljuci*" to "turn off",
        "prebaci*" to "toggle",
        "sljedeć*" to "next",
        "sljedec*" to "next",
        "slijedeć*" to "next",
        "slijedec*" to "next",
        "dalje" to "next",
        "naprijed" to "forward",
        "prethodn*" to "previous",
        "natrag" to "back",
        "nazad" to "back",
        "povećaj*" to "increase",
        "povecaj*" to "increase",
        "veći" to "bigger",
        "veci" to "bigger",
        "veće" to "bigger",
        "vece" to "bigger",
        "veća" to "bigger",
        "veca" to "bigger",
        "smanji*" to "decrease",
        "manji" to "smaller",
        "manje" to "smaller",
        "manja" to "smaller",
        "pretvori*" to "convert",
        "konvertiraj*" to "convert",
        "pretvarač*" to "converter",
        "pretvarac*" to "converter",
        "konverter*" to "converter",
        "prenesi" to "transfer",
        "prenijeti" to "transfer",
        "prijenos pjesama" to "transfer songs",
        "uredi" to "edit",
        "urediti" to "edit",
        "uređivanje" to "edit",
        "uredjivanje" to "edit",
        "promijeni*" to "change",
        "izmijeni*" to "change",
        "preimenuj*" to "rename",
        "popravi*" to "fix",
        "ispravi*" to "fix",
        "organiziraj*" to "organize",
        "posloži" to "organize",
        "poslozi" to "organize",
        "pospremi" to "clean up",
        "usporedi*" to "compare",
        "prevedi" to "translate",
        "prevesti" to "translate",
        "isplaniraj*" to "plan",
        "planiraj*" to "plan",
        "automatiziraj*" to "automate",
        "automatsk*" to "automatically",
        "identificiraj*" to "identify",
        "numeriraj*" to "number the",
        "označi brojevima" to "number the",
        "oznaci brojevima" to "number the",

        // Too small, too big, not working.
        "premal*" to "too small",
        "presitn*" to "too small",
        "slabo se vidi" to "hard to read",
        "ne vidi se" to "hard to read",
        "teško se čita" to "hard to read",
        "tesko se cita" to "hard to read",
        "nečitk*" to "hard to read",
        "necitk*" to "hard to read",
        "prevelik*" to "too big",
        "ne stane" to "doesn't fit",
        "ne stane se" to "doesn't fit",
        "ne radi" to "not working",
        "ne prikazuje" to "not showing",
        "ništa se ne prikazuje" to "nothing shows",
        "nista se ne prikazuje" to "nothing shows",
        "ništa ne prikazuje" to "nothing shows",
        "nista ne prikazuje" to "nothing shows",
        "nema ništa" to "nothing shows",
        "nema nista" to "nothing shows",
        "crni zaslon" to "screen is black",
        "crni ekran" to "screen is black",
        "nema signala" to "no signal",
        "nema slike" to "no picture",
        "koji zaslon" to "which screen",
        "koji ekran" to "which screen",
        "koji monitor" to "which monitor",
        "koji projektor" to "which projector",

        // What is on screen.
        "pozadin*" to "background",
        "tekst pjesme" to "lyrics",
        "riječi pjesme" to "lyrics",
        "rijeci pjesme" to "lyrics",
        "pjesma nad pjesmama" to "pjesma nad pjesmama",
        "pjesama" to "songs",
        "pjesm*" to "song",
        "hvaljenj*" to "worship",
        "slavljenj*" to "worship",
        "biblij*" to "bible",
        "sveto pismo" to "scripture",
        "svetog pisma" to "scripture",
        "svetom pismu" to "scripture",
        "stih*" to "verse",
        "redak" to "verse",
        "retka" to "verse",
        "retke" to "verse",
        "retku" to "verse",
        "retci" to "verse",
        "redaka" to "verse",
        "poglavlj*" to "chapter",
        "veličin*" to "size",
        "velicin*" to "size",
        "tekst*" to "text",
        "riječi" to "words",
        "rijeci" to "words",
        "slova" to "letters",
        "dijaprojekcij*" to "slideshow",
        "slajd*" to "slide",
        "fotografij*" to "photo",
        "fotk*" to "photo",
        "slik*" to "picture",
        "prezentacij*" to "presentation",
        "videozapis*" to "video",
        "film*" to "movie",
        "isječ*" to "clip",
        "isjec*" to "clip",
        "klip*" to "clip",
        "medij*" to "media",
        "zvuk*" to "audio",
        "donja traka" to "lower third",
        "donju traku" to "lower third",
        "donje trake" to "lower third",
        "donjoj traci" to "lower third",
        "donja trećina" to "lower third",
        "donja trecina" to "lower third",
        "traka s imenom" to "name strap",
        "natpis s imenom" to "name strap",
        "ime i funkcija" to "name and title",
        "ime i titula" to "name and title",
        "objav*" to "announcement",
        "obavijest*" to "announcement",
        "pokretni tekst" to "ticker",
        "tekuća traka" to "ticker",
        "tekuca traka" to "ticker",
        "dječja soba" to "kids room",
        "djecja soba" to "kids room",
        "dječju sobu" to "kids room",
        "djecju sobu" to "kids room",
        "odbrojavanj*" to "countdown",
        "odbrojava*" to "countdown",
        "mjerač vremena" to "timer",
        "mjerac vremena" to "timer",
        "tajmer*" to "timer",
        "štoperic*" to "stopwatch",
        "stoperic*" to "stopwatch",
        "pokaži sat" to "show clock",
        "pokazi sat" to "show clock",
        "prikaži sat" to "show clock",
        "prikazi sat" to "show clock",
        "trenutno vrijeme" to "current time",
        "trenutačno vrijeme" to "current time",
        "trenutacno vrijeme" to "current time",
        "vrijeme" to "time",
        "bilješk*" to "notes",
        "biljesk*" to "notes",
        "akord*" to "chord",
        "prijevod*" to "translation",
        "jezik*" to "language",
        "jezic*" to "language",
        "dvojezičn*" to "bilingual",
        "dvojezicn*" to "bilingual",
        "na drugom jeziku" to "another language",
        "drugi jezik" to "second language",
        "na dva jezika" to "two languages",

        // Screens and outputs.
        "glavni zaslon" to "main screen",
        "glavni ekran" to "main screen",
        "glavnom zaslonu" to "main screen",
        "glavnom ekranu" to "main screen",
        "cijeli zaslon" to "full screen",
        "cijeli ekran" to "full screen",
        "cijelom zaslonu" to "full screen",
        "cijelom ekranu" to "full screen",
        "preko cijelog zaslona" to "full screen",
        "preko cijelog ekrana" to "full screen",
        "puni zaslon" to "full screen",
        "drugi zaslon" to "second screen",
        "drugi ekran" to "second screen",
        "drugom zaslonu" to "second screen",
        "drugom ekranu" to "second screen",
        "zaslon*" to "screen",
        "ekran*" to "screen",
        "projektor*" to "projector",
        "scenski monitor" to "stage monitor",
        "scenskom monitoru" to "stage monitor",
        "scenski monitori" to "stage monitor",
        "monitor na pozornici" to "stage monitor",
        "monitor za pozornicu" to "stage monitor",
        "šaptač*" to "confidence monitor",
        "saptac*" to "confidence monitor",
        "monitor*" to "monitor",
        "izlazni zaslon" to "output window",
        "izlazni prozor" to "output window",
        "izlaz" to "output",
        "izlaza" to "output",
        "izlazu" to "output",
        "izlazi" to "output",
        "izlazni" to "output",
        "izlazne" to "output",
        "izlaznom" to "output",
        "projekcij*" to "projection",
        "pozornic*" to "stage",
        "scena" to "stage",
        "sceni" to "stage",
        "scenu" to "stage",
        "zona" to "zone",
        "zonu" to "zone",
        "zoni" to "zone",
        "izgled zaslona" to "layout",
        "izgled ekrana" to "layout",
        "razmještaj*" to "arrangement",
        "razmjestaj*" to "arrangement",
        "poruk*" to "message",
        "pošalji" to "send",
        "posalji" to "send",
        "poslati" to "send",
        "pretpregled*" to "preview",
        "pregled*" to "preview",
        "što je na zaslonu" to "what is on screen",
        "sto je na zaslonu" to "what is on screen",
        "što je na ekranu" to "what is on screen",
        "sto je na ekranu" to "what is on screen",
        "profil*" to "profile",
        "prijenos*" to "stream",
        "televizor*" to "tv",
        "televizij*" to "tv",

        // Pages, tabs and tools.
        "postavk*" to "settings",
        "opcij*" to "options",
        "čarobnjak za postavljanje" to "setup wizard",
        "carobnjak za postavljanje" to "setup wizard",
        "prvi koraci" to "setup wizard",
        "kreni ispočetka" to "start over",
        "kreni ispocetka" to "start over",
        "ispočetka" to "start over",
        "ispocetka" to "start over",
        "tipkovni prečac" to "shortcut",
        "tipkovni precac" to "shortcut",
        "prečac*" to "shortcut",
        "precac*" to "shortcut",
        "prečic*" to "shortcut",
        "precic*" to "shortcut",
        "tipkovnic*" to "keyboard",
        "kartic*" to "tab",
        "knjižnica pjesama" to "song library",
        "knjiznica pjesama" to "song library",
        "knjižnicu pjesama" to "song library",
        "knjiznicu pjesama" to "song library",
        "biblioteka pjesama" to "song library",
        "biblioteku pjesama" to "song library",
        "knjižnic*" to "library",
        "knjiznic*" to "library",
        "bibliotek*" to "library",
        "web stranica" to "website",
        "web stranicu" to "website",
        "mrežna stranica" to "website",
        "mrezna stranica" to "website",
        "mrežnu stranicu" to "website",
        "mreznu stranicu" to "website",
        "preglednik*" to "browser",
        "rječnik*" to "dictionary",
        "rjecnik*" to "dictionary",
        "kamer*" to "camera",
        "platn*" to "canvas",
        "poslužitelj*" to "server",
        "posluzitelj*" to "server",
        "daljinsk*" to "remote",
        "telefon*" to "phone",
        "mobitel*" to "phone",
        "integracij*" to "integrations",

        // Services and planning.
        "tijek bogoslužja" to "order of service",
        "tijek bogosluzja" to "order of service",
        "red bogoslužja" to "order of service",
        "red bogosluzja" to "order of service",
        "program bogoslužja" to "order of service",
        "program bogosluzja" to "order of service",
        "bogoslužj*" to "service",
        "bogosluzj*" to "service",
        "služb*" to "service",
        "sluzb*" to "service",
        "sastan*" to "meeting",
        "okupljanj*" to "meeting",
        "nedjelj*" to "sunday",
        "kalendar*" to "calendar",
        "raspored*" to "schedule",
        "popis za reprodukciju" to "playlist",
        "svake nedjelje" to "every sunday",
        "svaki tjedan" to "every week",
        "svakog tjedna" to "every week",
        "tjedn*" to "weekly",
        "mjesečn*" to "monthly",
        "mjesecn*" to "monthly",
        "ponavlja*" to "repeat",
        "ponovi*" to "repeat",
        "predložak" to "template",
        "predlozak" to "template",
        "predlošk*" to "template",
        "predlosk*" to "template",

        // Many, all, both.
        "sve" to "all",
        "svi" to "all",
        "sva" to "all",
        "svih" to "all",
        "svim" to "all",
        "svugdje" to "everything",
        "posvuda" to "everything",
        "oba" to "both",
        "obje" to "both",
        "oboje" to "both",
        "nekoliko" to "several",
        "mnogo" to "many",
        "puno" to "many",
        "odjednom" to "at once",
        "istovremeno" to "at once",
        "za ovo bogoslužje" to "this service",
        "za ovo bogosluzje" to "this service",
        "za danas" to "for today",
        "privremeno" to "temporarily",

        // Languages, by name.
        "rusk*" to "russian",
        "ukrajinsk*" to "ukrainian",
        "bjelorusk*" to "belarusian",
        "englesk*" to "english",
        "španjolsk*" to "spanish",
        "spanjolsk*" to "spanish",
        "njemačk*" to "german",
        "njemack*" to "german",
        "francusk*" to "french",
        "poljsk*" to "polish",
        "češk*" to "czech",
        "cesk*" to "czech",
        "slovačk*" to "slovak",
        "slovack*" to "slovak",
        "hrvatsk*" to "croatian",
        "srpsk*" to "serbian",
        "bugarsk*" to "bulgarian",
        "mađarsk*" to "hungarian",
        "madarsk*" to "hungarian",
        "grčk*" to "greek",
        "grck*" to "greek",
        "portugalsk*" to "portuguese",
        "talijansk*" to "italian",
        "kazašk*" to "kazakh",
        "kazask*" to "kazakh",
        "rumunjsk*" to "romanian",
        "moldavsk*" to "moldovan",
        "latinsk*" to "latin",

        // Colors.
        "tamnoplav*" to "navy",
        "mornarsko plav*" to "navy",
        "svijetloplav*" to "light blue",
        "nebeskoplav*" to "light blue",
        "plav*" to "blue",
        "crna" to "black",
        "crno" to "black",
        "crni" to "black",
        "crnu" to "black",
        "crne" to "black",
        "crnom" to "black",
        "bijel*" to "white",
        "siva" to "grey",
        "sivo" to "grey",
        "sivi" to "grey",
        "sivu" to "grey",
        "sive" to "grey",
        "sivom" to "grey",
        "srebrn*" to "silver",
        "crven*" to "red",
        "bordo" to "maroon",
        "narančast*" to "orange",
        "narancast*" to "orange",
        "žut*" to "yellow",
        "zuta" to "yellow",
        "zuto" to "yellow",
        "zuti" to "yellow",
        "zutu" to "yellow",
        "zute" to "yellow",
        "zlatn*" to "gold",
        "zelen*" to "green",
        "limet*" to "lime",
        "tirkizn*" to "turquoise",
        "ljubičast*" to "purple",
        "ljubicast*" to "purple",
        "lila" to "violet",
        "ružičast*" to "pink",
        "ruzicast*" to "pink",
        "roza" to "pink",
        "smeđ*" to "brown",
        "smed*" to "brown",
        "bež" to "beige",
        "krem" to "cream",
        "tamn*" to "dark",
        "svijetl*" to "light",

        // Talking to the helper.
        "bok" to "hello",
        "zdravo" to "hello",
        "pozdrav" to "hello",
        "dobar dan" to "hello",
        "dobro jutro" to "hello",
        "pomozi*" to "help",
        "pomoć" to "help",
        "pomoc" to "help",
        "što znaš raditi" to "what can you do",
        "sto znas raditi" to "what can you do",
        "što znaš" to "what can you do",
        "sto znas" to "what can you do",
        "što možeš" to "what can you do",
        "sto mozes" to "what can you do",
        "tko si" to "who are you",
        "hvala lijepa" to "thank you",
        "hvala ti" to "thank you",
        "hvala" to "thanks",
        "molim te" to "please",
        "molim" to "please",
        "viku" to "wick",
        "vik" to "wick",
    ),
)
