package org.churchpresenter.helper.intent.glossary

internal val CZECH = Glossary(
    "cs",
    listOf(
        // Asking where, or how.
        "kde" to "where",
        "kam" to "where",
        "jak můžu" to "how can i",
        "jak muzu" to "how can i",
        "jak mohu" to "how can i",
        "jak se dá" to "how can i",
        "jak se da" to "how can i",
        "jak" to "how do i",
        "nemůžu najít" to "can't find",
        "nemuzu najit" to "can't find",
        "nemohu najít" to "can't find",
        "nemohu najit" to "can't find",
        "nenacházím" to "can't find",
        "nenachazim" to "can't find",
        "ukaž mi" to "show me",
        "ukaz mi" to "show me",
        "poraď" to "how do i",
        "poraďte" to "how do i",
        "poradte" to "how do i",

        // Doing.
        "ukaž" to "show",
        "ukaz" to "show",
        "ukázat" to "show",
        "ukazat" to "show",
        "ukažte" to "show",
        "ukazte" to "show",
        "zobraz*" to "display",
        "otevři" to "open",
        "otevri" to "open",
        "otevřít" to "open",
        "otevrit" to "open",
        "otevřete" to "open",
        "otevrete" to "open",
        "přejdi na" to "go to",
        "prejdi na" to "go to",
        "přejdi do" to "go to",
        "prejdi do" to "go to",
        "přejít na" to "go to",
        "prejit na" to "go to",
        "jdi na" to "go to",
        "jdi do" to "go to",
        "přepni na" to "switch to",
        "prepni na" to "switch to",
        "přepnout na" to "switch to",
        "prepnout na" to "switch to",
        "najdi" to "find",
        "najít" to "find",
        "najit" to "find",
        "vyhledej" to "find",
        "přečti" to "read",
        "precti" to "read",
        "udělej" to "make",
        "udelej" to "make",
        "udělat" to "make",
        "udelat" to "make",
        "vytvoř" to "create",
        "vytvor" to "create",
        "vytvořit" to "create",
        "vytvorit" to "create",
        "přidej*" to "add",
        "pridej*" to "add",
        "přidat" to "add",
        "pridat" to "add",
        "načti" to "load",
        "nacti" to "load",
        "načíst" to "load",
        "nacist" to "load",
        "nahraj*" to "load",
        "importuj*" to "import",
        "stáhni" to "download",
        "stahni" to "download",
        "stáhnout" to "download",
        "stahnout" to "download",
        "nainstaluj*" to "install",
        "vyber*" to "choose",
        "vybrat" to "choose",
        "nastav*" to "set up",
        "nakonfiguruj*" to "set up",
        "připoj*" to "connect",
        "pripoj*" to "connect",
        "přiřaď" to "assign",
        "prirad" to "assign",
        "přiřadit" to "assign",
        "priradit" to "assign",
        "skryj*" to "hide",
        "schovej*" to "hide",
        "zastav*" to "stop",
        "smaž" to "delete",
        "smaz" to "delete",
        "smazat" to "delete",
        "odstraň" to "delete",
        "odstran" to "delete",
        "odstranit" to "delete",
        "vymaž" to "clear",
        "vymaz" to "clear",
        "vymazat" to "clear",
        "vyčisti" to "clear",
        "vycisti" to "clear",
        "zatemni*" to "black out",
        "prázdná obrazovka" to "blank",
        "prazdna obrazovka" to "blank",
        "vrať zpět" to "undo",
        "vrat zpet" to "undo",
        "vrátit zpět" to "undo",
        "vratit zpet" to "undo",
        "zruš*" to "undo",
        "zrus*" to "undo",
        "naživo" to "go live",
        "nazivo" to "go live",
        "na živo" to "go live",
        "na zivo" to "go live",
        "pusť naživo" to "go live",
        "pust nazivo" to "go live",
        "zapni*" to "turn on",
        "vypni*" to "turn off",
        "přepni*" to "toggle",
        "prepni*" to "toggle",
        "další" to "next",
        "dalsi" to "next",
        "vpřed" to "forward",
        "vpred" to "forward",
        "předchozí" to "previous",
        "predchozi" to "previous",
        "zpět" to "back",
        "zpet" to "back",
        "zvětš*" to "increase",
        "zvets*" to "increase",
        "zvyš*" to "increase",
        "zvys*" to "increase",
        "větší" to "bigger",
        "vetsi" to "bigger",
        "zmenš*" to "decrease",
        "zmens*" to "decrease",
        "menší" to "smaller",
        "mensi" to "smaller",
        "konvertuj*" to "convert",
        "zkonvertuj*" to "convert",
        "převeď" to "convert",
        "preved" to "convert",
        "převést" to "convert",
        "prevest" to "convert",
        "převodník*" to "converter",
        "prevodnik*" to "converter",
        "konvertor*" to "converter",
        "přenes*" to "transfer",
        "prenes*" to "transfer",
        "uprav*" to "edit",
        "úprav*" to "edit",
        "edituj*" to "edit",
        "změň" to "change",
        "zmen" to "change",
        "změnit" to "change",
        "zmenit" to "change",
        "přejmenuj*" to "rename",
        "prejmenuj*" to "rename",
        "oprav*" to "fix",
        "uspořádej*" to "organize",
        "usporadej*" to "organize",
        "uspořádat" to "organize",
        "usporadat" to "organize",
        "ukliď" to "clean up",
        "uklid" to "clean up",
        "uklidit" to "clean up",
        "porovnej*" to "compare",
        "porovnat" to "compare",
        "přelož" to "translate",
        "preloz" to "translate",
        "přeložit" to "translate",
        "prelozit" to "translate",
        "naplánuj*" to "plan",
        "naplanuj*" to "plan",
        "plánuj*" to "plan",
        "planuj*" to "plan",
        "zautomatizuj*" to "automate",
        "automatizuj*" to "automate",
        "automatick*" to "automatically",
        "identifikuj*" to "identify",
        "očísluj*" to "number the",
        "ocisluj*" to "number the",

        // Too small, too big, not working.
        "příliš mal*" to "too small",
        "prilis mal*" to "too small",
        "moc mal*" to "too small",
        "špatně vidět" to "hard to read",
        "spatne videt" to "hard to read",
        "není vidět" to "hard to read",
        "neni videt" to "hard to read",
        "špatně čitelné" to "hard to read",
        "spatne citelne" to "hard to read",
        "nečiteln*" to "hard to read",
        "neciteln*" to "hard to read",
        "příliš velk*" to "too big",
        "prilis velk*" to "too big",
        "moc velk*" to "too big",
        "nevejde se" to "doesn't fit",
        "nevleze se" to "doesn't fit",
        "nefunguje" to "not working",
        "nezobrazuje" to "not showing",
        "nic se nezobrazuje" to "nothing shows",
        "nic nezobrazuje" to "nothing shows",
        "nic tam není" to "nothing shows",
        "nic tam neni" to "nothing shows",
        "černá obrazovka" to "screen is black",
        "cerna obrazovka" to "screen is black",
        "žádný signál" to "no signal",
        "zadny signal" to "no signal",
        "bez signálu" to "no signal",
        "bez signalu" to "no signal",
        "žádný obraz" to "no picture",
        "zadny obraz" to "no picture",
        "která obrazovka" to "which screen",
        "ktera obrazovka" to "which screen",
        "který monitor" to "which monitor",
        "ktery monitor" to "which monitor",
        "který projektor" to "which projector",
        "ktery projektor" to "which projector",

        // What is on screen.
        "pozadí" to "background",
        "pozadi" to "background",
        "text písně" to "lyrics",
        "text pisne" to "lyrics",
        "slova písně" to "lyrics",
        "slova pisne" to "lyrics",
        "píseň písní" to "píseň písní",
        "pisen pisni" to "pisen pisni",
        "písní" to "songs",
        "pisni" to "songs",
        "píseň" to "song",
        "pisen" to "song",
        "písn*" to "song",
        "pisn*" to "song",
        "písničk*" to "song",
        "pisnick*" to "song",
        "chvál*" to "worship",
        "chval*" to "worship",
        "bibli" to "bible",
        "biblí" to "bible",
        "biblick*" to "bible",
        "písmo svaté" to "scripture",
        "pismo svate" to "scripture",
        "písma svatého" to "scripture",
        "pisma svateho" to "scripture",
        "písmo" to "font",
        "pismo" to "font",
        "písma" to "font",
        "pisma" to "font",
        "verš*" to "verse",
        "vers" to "verse",
        "versi" to "verse",
        "versu" to "verse",
        "versem" to "verse",
        "versy" to "verse",
        "kapitol*" to "chapter",
        "velikost*" to "size",
        "slova" to "words",
        "písmen*" to "letters",
        "pismen*" to "letters",
        "snímk*" to "slide",
        "snimk*" to "slide",
        "slajd*" to "slide",
        "fotk*" to "photo",
        "fotografi*" to "photo",
        "obrazovk*" to "screen",
        "obrazovce" to "screen",
        "obrazovek" to "screen",
        "obráz*" to "picture",
        "obraz*" to "picture",
        "prezentac*" to "presentation",
        "videa" to "video",
        "videem" to "video",
        "film*" to "movie",
        "klip*" to "clip",
        "média" to "media",
        "médií" to "media",
        "zvuk*" to "audio",
        "spodní třetin*" to "lower third",
        "spodni tretin*" to "lower third",
        "jmenovk*" to "name strap",
        "jméno a funkce" to "name and title",
        "jmeno a funkce" to "name and title",
        "oznámen*" to "announcement",
        "oznamen*" to "announcement",
        "ohlášk*" to "announcement",
        "ohlask*" to "announcement",
        "běžící text" to "ticker",
        "bezici text" to "ticker",
        "dětský koutek" to "kids room",
        "detsky koutek" to "kids room",
        "dětská místnost" to "kids room",
        "detska mistnost" to "kids room",
        "odpočet*" to "countdown",
        "odpocet*" to "countdown",
        "odpočítávání" to "countdown",
        "odpocitavani" to "countdown",
        "časovač*" to "timer",
        "casovac*" to "timer",
        "stopk*" to "stopwatch",
        "hodiny" to "clock",
        "hodin" to "clock",
        "aktuální čas" to "current time",
        "aktualni cas" to "current time",
        "čas" to "time",
        "cas" to "time",
        "poznámk*" to "notes",
        "poznamk*" to "notes",
        "akord*" to "chord",
        "překlad*" to "translation",
        "preklad*" to "translation",
        "jazyk*" to "language",
        "dvojjazyčn*" to "bilingual",
        "dvojjazycn*" to "bilingual",
        "v jiném jazyce" to "another language",
        "v jinem jazyce" to "another language",
        "jiný jazyk" to "another language",
        "jiny jazyk" to "another language",
        "druhý jazyk" to "second language",
        "druhy jazyk" to "second language",
        "ve dvou jazycích" to "two languages",
        "ve dvou jazycich" to "two languages",

        // Screens and outputs.
        "hlavní obrazovka" to "main screen",
        "hlavni obrazovka" to "main screen",
        "hlavní obrazovce" to "main screen",
        "hlavni obrazovce" to "main screen",
        "celá obrazovka" to "full screen",
        "cela obrazovka" to "full screen",
        "na celou obrazovku" to "full screen",
        "celou obrazovku" to "full screen",
        "celé obrazovce" to "full screen",
        "cele obrazovce" to "full screen",
        "celoobrazovk*" to "fullscreen",
        "druhá obrazovka" to "second screen",
        "druha obrazovka" to "second screen",
        "druhé obrazovce" to "second screen",
        "druhe obrazovce" to "second screen",
        "druhou obrazovku" to "second screen",
        "projektor*" to "projector",
        "dataprojektor*" to "projector",
        "monitor scény" to "stage monitor",
        "monitor sceny" to "stage monitor",
        "monitoru scény" to "stage monitor",
        "monitoru sceny" to "stage monitor",
        "monitor na pódiu" to "stage monitor",
        "monitor na podiu" to "stage monitor",
        "pódiový monitor" to "stage monitor",
        "podiovy monitor" to "stage monitor",
        "odposlech*" to "stage monitor",
        "suflér*" to "confidence monitor",
        "sufler*" to "confidence monitor",
        "monitor*" to "monitor",
        "displej*" to "display",
        "výstupní okno" to "output window",
        "vystupni okno" to "output window",
        "výstup*" to "output",
        "vystup*" to "output",
        "projekc*" to "projection",
        "scén*" to "stage",
        "scena" to "stage",
        "sceny" to "stage",
        "scenu" to "stage",
        "scenou" to "stage",
        "pódium" to "stage",
        "podium" to "stage",
        "pódiu" to "stage",
        "podiu" to "stage",
        "zóna" to "zone",
        "zona" to "zone",
        "zóny" to "zone",
        "zony" to "zone",
        "zónu" to "zone",
        "zonu" to "zone",
        "rozložení" to "layout",
        "rozlozeni" to "layout",
        "uspořádání" to "arrangement",
        "usporadani" to "arrangement",
        "zpráv*" to "message",
        "zprav*" to "message",
        "pošli" to "send",
        "posli" to "send",
        "poslat" to "send",
        "odešli" to "send",
        "odesli" to "send",
        "odeslat" to "send",
        "náhled*" to "preview",
        "nahled*" to "preview",
        "co je na obrazovce" to "what is on screen",
        "profil*" to "profile",
        "přenos*" to "stream",
        "prenos*" to "stream",
        "vysílání" to "stream",
        "vysilani" to "stream",
        "televiz*" to "tv",

        // Pages, tabs and tools.
        "nastaven*" to "settings",
        "možnost*" to "options",
        "moznost*" to "options",
        "průvodce nastavením" to "setup wizard",
        "pruvodce nastavenim" to "setup wizard",
        "začínáme" to "setup wizard",
        "zaciname" to "setup wizard",
        "začít znovu" to "start over",
        "zacit znovu" to "start over",
        "od začátku" to "start over",
        "od zacatku" to "start over",
        "klávesová zkratka" to "shortcut",
        "klavesova zkratka" to "shortcut",
        "klávesové zkratky" to "shortcut",
        "klavesove zkratky" to "shortcut",
        "zkratk*" to "shortcut",
        "klávesnic*" to "keyboard",
        "klavesnic*" to "keyboard",
        "záložk*" to "tab",
        "zalozk*" to "tab",
        "kart*" to "tab",
        "knihovna písní" to "song library",
        "knihovna pisni" to "song library",
        "knihovnu písní" to "song library",
        "knihovnu pisni" to "song library",
        "knihovně písní" to "song library",
        "knihovne pisni" to "song library",
        "knihovn*" to "library",
        "webová stránka" to "website",
        "webova stranka" to "website",
        "webovou stránku" to "website",
        "webovou stranku" to "website",
        "prohlížeč*" to "browser",
        "prohlizec*" to "browser",
        "slovník*" to "dictionary",
        "slovnik*" to "dictionary",
        "kamer*" to "camera",
        "plátno" to "canvas",
        "platno" to "canvas",
        "plátna" to "canvas",
        "plátně" to "canvas",
        "serveru" to "server",
        "vzdálen*" to "remote",
        "vzdalen*" to "remote",
        "ovladač*" to "remote",
        "ovladac*" to "remote",
        "telefon*" to "phone",
        "mobil*" to "phone",
        "integrac*" to "integrations",

        // Services and planning.
        "pořad bohoslužby" to "order of service",
        "porad bohosluzby" to "order of service",
        "průběh bohoslužby" to "order of service",
        "prubeh bohosluzby" to "order of service",
        "program bohoslužby" to "order of service",
        "program bohosluzby" to "order of service",
        "bohoslužb*" to "service",
        "bohosluzb*" to "service",
        "shromážděn*" to "meeting",
        "shromazden*" to "meeting",
        "neděle" to "sunday",
        "nedele" to "sunday",
        "neděli" to "sunday",
        "nedeli" to "sunday",
        "kalendář*" to "calendar",
        "kalendar*" to "calendar",
        "rozvrh*" to "schedule",
        "harmonogram*" to "schedule",
        "každou neděli" to "every sunday",
        "kazdou nedeli" to "every sunday",
        "každý týden" to "every week",
        "kazdy tyden" to "every week",
        "týdně" to "weekly",
        "tydne" to "weekly",
        "týdenní" to "weekly",
        "tydenni" to "weekly",
        "měsíčně" to "monthly",
        "mesicne" to "monthly",
        "měsíční" to "monthly",
        "mesicni" to "monthly",
        "opakuj*" to "repeat",
        "opakov*" to "repeat",
        "šablon*" to "template",
        "sablon*" to "template",

        // Many, all, both.
        "všechn*" to "all",
        "vsechn*" to "all",
        "vše" to "all",
        "vse" to "all",
        "všude" to "everything",
        "vsude" to "everything",
        "oba" to "both",
        "obě" to "both",
        "obe" to "both",
        "obou" to "both",
        "několik" to "several",
        "nekolik" to "several",
        "mnoho" to "many",
        "hodně" to "many",
        "hodne" to "many",
        "najednou" to "at once",
        "naráz" to "at once",
        "naraz" to "at once",
        "pro tuto bohoslužbu" to "this service",
        "pro tuto bohosluzbu" to "this service",
        "pro dnešek" to "for today",
        "pro dnesek" to "for today",
        "na dnes" to "for today",
        "dočasně" to "temporarily",
        "docasne" to "temporarily",

        // Languages, by name.
        "rusk*" to "russian",
        "ruštin*" to "russian",
        "rustin*" to "russian",
        "ukrajinsk*" to "ukrainian",
        "ukrajinštin*" to "ukrainian",
        "ukrajinstin*" to "ukrainian",
        "běloru*" to "belarusian",
        "beloru*" to "belarusian",
        "anglick*" to "english",
        "angličtin*" to "english",
        "anglictin*" to "english",
        "španěl*" to "spanish",
        "spanel*" to "spanish",
        "německ*" to "german",
        "nemeck*" to "german",
        "němčin*" to "german",
        "nemcin*" to "german",
        "francouz*" to "french",
        "polsk*" to "polish",
        "polštin*" to "polish",
        "polstin*" to "polish",
        "česk*" to "czech",
        "cesk*" to "czech",
        "češtin*" to "czech",
        "cestin*" to "czech",
        "slovensk*" to "slovak",
        "slovenštin*" to "slovak",
        "slovenstin*" to "slovak",
        "chorvatsk*" to "croatian",
        "chorvatštin*" to "croatian",
        "chorvatstin*" to "croatian",
        "srbsk*" to "serbian",
        "portugalsk*" to "portuguese",
        "italsk*" to "italian",
        "italštin*" to "italian",
        "italstin*" to "italian",
        "kazašsk*" to "kazakh",
        "kazassk*" to "kazakh",
        "rumunsk*" to "romanian",
        "rumunštin*" to "romanian",
        "rumunstin*" to "romanian",
        "moldavsk*" to "moldovan",
        "latinsk*" to "latin",
        "latin*" to "latin",

        // Colors.
        "tmavomodr*" to "navy",
        "námořnick*" to "navy",
        "namornick*" to "navy",
        "světle modr*" to "light blue",
        "svetle modr*" to "light blue",
        "světlemodr*" to "light blue",
        "svetlemodr*" to "light blue",
        "blankytn*" to "light blue",
        "modr*" to "blue",
        "čern*" to "black",
        "cern*" to "black",
        "bílá" to "white",
        "bila" to "white",
        "bílý" to "white",
        "bily" to "white",
        "bílé" to "white",
        "bile" to "white",
        "bílou" to "white",
        "bilou" to "white",
        "bílým" to "white",
        "bilym" to "white",
        "bíle" to "white",
        "šedá" to "grey",
        "seda" to "grey",
        "šedý" to "grey",
        "sedy" to "grey",
        "šedé" to "grey",
        "sede" to "grey",
        "šedou" to "grey",
        "sedou" to "grey",
        "šediv*" to "grey",
        "sediv*" to "grey",
        "stříbrn*" to "silver",
        "stribrn*" to "silver",
        "červená" to "red",
        "cervena" to "red",
        "červený" to "red",
        "cerveny" to "red",
        "červené" to "red",
        "cervene" to "red",
        "červenou" to "red",
        "cervenou" to "red",
        "červeně" to "red",
        "vínov*" to "maroon",
        "vinov*" to "maroon",
        "oranžov*" to "orange",
        "oranzov*" to "orange",
        "žlut*" to "yellow",
        "zlut*" to "yellow",
        "zlat*" to "gold",
        "zelen*" to "green",
        "limetk*" to "lime",
        "tyrkysov*" to "turquoise",
        "fialov*" to "purple",
        "levandulov*" to "lavender",
        "růžov*" to "pink",
        "ruzov*" to "pink",
        "hněd*" to "brown",
        "hneda" to "brown",
        "hnedy" to "brown",
        "hnedou" to "brown",
        "béžov*" to "beige",
        "bezov*" to "beige",
        "krémov*" to "cream",
        "kremov*" to "cream",
        "tmav*" to "dark",
        "světl*" to "light",
        "svetl*" to "light",

        // Talking to the helper.
        "ahoj" to "hello",
        "dobrý den" to "hello",
        "dobry den" to "hello",
        "zdravím" to "hello",
        "zdravim" to "hello",
        "pomoz*" to "help",
        "pomoc" to "help",
        "co umíš" to "what can you do",
        "co umis" to "what can you do",
        "co dokážeš" to "what can you do",
        "co dokazes" to "what can you do",
        "kdo jsi" to "who are you",
        "děkuji" to "thank you",
        "dekuji" to "thank you",
        "děkuju" to "thank you",
        "dekuju" to "thank you",
        "díky" to "thanks",
        "diky" to "thanks",
        "prosím" to "please",
        "prosim" to "please",
        "wicku" to "wick",
        "viku" to "wick",
        "vik" to "wick",

        // Newer requests.
        "hleda*" to "search",
        "hledej" to "search",
        "hledá*" to "search",
        "vyhleda*" to "search",
        "vyhledá*" to "search",
        "vyhledej v" to "search in",
        "najdi píseň" to "find a song",
        "najdi pisen" to "find a song",
        "najít píseň" to "find a song",
        "najit pisen" to "find a song",
        "najdi verš" to "find a verse",
        "najdi vers" to "find a verse",
        "najít verš" to "find a verse",
        "najit vers" to "find a verse",
        "číslo písně" to "song number",
        "cislo pisne" to "song number",
        "podle čísla" to "by number",
        "podle cisla" to "by number",
        "podle názvu" to "by title",
        "podle nazvu" to "by title",
        "číslo" to "number",
        "cislo" to "number",
        "s názvem" to "called",
        "s nazvem" to "called",
        "oblíben*" to "favorite",
        "obliben*" to "favorite",
        "hvězdičk*" to "starred",
        "hvezdick*" to "starred",
        "této písni" to "this song",
        "teto pisni" to "this song",
        "této písně" to "this song",
        "teto pisne" to "this song",
        "tuto píseň" to "this song",
        "tuto pisen" to "this song",
        "tato píseň" to "this song",
        "tato pisen" to "this song",
        "každé písni" to "each song",
        "kazde pisni" to "each song",
        "každou píseň" to "each song",
        "kazdou pisen" to "each song",
        "vlastní pozadí" to "own background",
        "vlastni pozadi" to "own background",
        "samostatné pozadí" to "own background",
        "samostatne pozadi" to "own background",
        "více veršů" to "several verses",
        "vice versu" to "several verses",
        "víc veršů" to "several verses",
        "vic versu" to "several verses",
        "několik veršů" to "several verses",
        "nekolik versu" to "several verses",
        "více než jeden verš" to "more than one verse",
        "vice nez jeden vers" to "more than one verse",
        "rozsah veršů" to "range of verses",
        "rozsah versu" to "range of verses",
        "celou pasáž" to "whole passage",
        "celou pasaz" to "whole passage",
        "histori*" to "history",
        "co jsme právě ukazovali" to "what did we just show",
        "co jsme prave ukazovali" to "what did we just show",
        "co jsme právě ukázali" to "what did we just show",
        "co jsme prave ukazali" to "what did we just show",
        "co jsme ukazovali" to "what did we show",
        "co jsme ukázali" to "what did we show",
        "co jsme ukazali" to "what did we show",
        "nedávné verše" to "recent verses",
        "nedavne verse" to "recent verses",
        "související verše" to "related verses",
        "souvisejici verse" to "related verses",
        "související pasáže" to "related passages",
        "souvisejici pasaze" to "related passages",
        "paralelní místa" to "parallel passages",
        "paralelni mista" to "parallel passages",
        "křížové odkazy" to "cross references",
        "krizove odkazy" to "cross references",
        "křížov* odkaz*" to "cross references",
        "krizov* odkaz*" to "cross references",
        "webov* stránk*" to "website",
        "webov* strank*" to "website",
        "webovk*" to "website",
        "adresa url" to "url",
        "planning centeru" to "planning center",
        "planning centra" to "planning center",
        "statistik*" to "statistics",
        "kolikrát" to "how many times",
        "kolikrat" to "how many times",
        "jak často" to "how often",
        "jak casto" to "how often",
        "využití písní" to "song usage",
        "vyuziti pisni" to "song usage",
        "z telefonu" to "from the phone",
        "z mobilu" to "from the phone",
        "na telefonu" to "on my phone",
        "na mobilu" to "on my phone",
        "připoj telefon" to "connect my phone",
        "pripoj telefon" to "connect my phone",
        "dálkové ovládání" to "remote control",
        "dalkove ovladani" to "remote control",
        "ovládání z" to "control it from",
        "ovladani z" to "control it from",
        "ovládat z" to "control it from",
        "ovladat z" to "control it from",
        "qr kód" to "qr code",
        "qr kod" to "qr code",
        "minut*" to "minutes",
        "minutk*" to "timer",
        "oznam*" to "announce",
        "oznám*" to "announce",
        "řekni rodič*" to "announce",
        "rekni rodic*" to "announce",
        "zavolej rodič*" to "announce",
        "zavolej rodic*" to "announce",
        "přidám" to "add",
        "pridam" to "add",
        "vlož" to "insert",
        "vloz" to "insert",
        "do programu" to "to the schedule",
        "v programu" to "in the schedule",
        "z programu" to "from the schedule",
        "položk*" to "item",
        "polozk*" to "item",
        "co je naživo" to "what's live",
        "co je nazivo" to "what's live",
        "co se zobrazuje" to "what is showing",
        "co se promítá" to "what's showing",
        "co se promita" to "what's showing",
        "je něco naživo" to "is anything live",
        "je neco nazivo" to "is anything live",
        "jaká je to verze" to "what version is this",
        "jaka je to verze" to "what version is this",
        "jaká verze" to "what version",
        "jaka verze" to "what version",
        "která verze" to "which version",
        "ktera verze" to "which version",
        "verze aplikace" to "app version",
        "verze programu" to "app version",
        "zkontroluj aktualizac*" to "check for updates",
        "zkontrolovat aktualizac*" to "check for updates",
        "je k dispozici aktualizace" to "is there an update",
        "nejnovější verze" to "latest version",
        "nejnovejsi verze" to "latest version",
        "další bibl*" to "another bible",
        "dalsi bibl*" to "another bible",
        "udělám" to "make",
        "udelam" to "make",
        "prezentac* obrázk*" to "slideshow",
        "prezentac* obrazk*" to "slideshow",
        "na celou plochu" to "full screen",
        "celou plochu" to "full screen",
        "hromadn*" to "batch",
        "krok zpět" to "undo",
        "krok zpet" to "undo",
        "nápověd*" to "help",
        "napoved*" to "help",
        "příkazy" to "commands",
        "prikazy" to "commands",
        "seznam příkazů" to "list of commands",
        "seznam prikazu" to "list of commands",
        "co můžu napsat" to "what can i type",
        "co muzu napsat" to "what can i type",
        "co mohu napsat" to "what can i type",
        "co můžu říct" to "what can i say",
        "co muzu rict" to "what can i say",
        "čemu rozumíš" to "what do you understand",
        "cemu rozumis" to "what do you understand",

        // Look requests.
        "změním" to "change",
        "zmenim" to "change",
        "překlep*" to "typo",
        "preklep*" to "typo",
        "oprav* text písně" to "fix the lyrics",
        "oprav* text pisne" to "fix the lyrics",
        "uprav* píseň" to "edit the song",
        "uprav* pisen" to "edit the song",
        "textu písně" to "lyrics",
        "textu pisne" to "lyrics",
        "konec písně" to "end of song",
        "konec pisne" to "end of song",
        "konce písně" to "end of song",
        "konce pisne" to "end of song",
        "značk* konce" to "end marker",
        "znack* konce" to "end marker",
        "tučn*" to "bold",
        "tucn*" to "bold",
        "kurzív*" to "italic",
        "kurziv*" to "italic",
        "podtrž*" to "underline",
        "podtrz*" to "underline",
        "obrys*" to "outline",
        "stín*" to "shadow",
        "stin" to "shadow",
        "stinu" to "shadow",
        "stinem" to "shadow",
        "okraj*" to "margins",
        "nahoru" to "to the top",
        "nahoře" to "at the top",
        "nahore" to "at the top",
        "dolů" to "to the bottom",
        "dolu" to "to the bottom",
        "dole" to "at the bottom",
        "doprostřed" to "to the middle",
        "doprostred" to "to the middle",
        "uprostřed" to "in the middle",
        "uprostred" to "in the middle",
        "doleva" to "to the left",
        "vlevo" to "left",
        "doprava" to "to the right",
        "vpravo" to "right",
        "na střed" to "center",
        "na stred" to "center",
        "vycentr*" to "center",
        "zarovn*" to "align",
        "pozic*" to "position",
        "posun*" to "move",
        "název písně" to "song title",
        "nazev pisne" to "song title",
        "názvu písně" to "song title",
        "nazvu pisne" to "song title",
        "název*" to "title",
        "nazev*" to "title",
        "názv*" to "title",
        "nazv*" to "title",
        "odkaz*" to "reference",
        "vzhled*" to "look",
        "styl*" to "style",
        "formát*" to "format",
        "barv*" to "color",

        // The help table's own examples.
        "pustit naživo" to "go live",
        "spustit naživo" to "go live",
    ),
)
