package org.churchpresenter.helper.intent.glossary

internal val DUTCH = Glossary(
    "nl",
    listOf(
        // Asking where, or how.
        "waar" to "where",
        "waarheen" to "where",
        "waar vind ik" to "where",
        "waar staat" to "where",
        "hoe kan ik" to "how can i",
        "hoe moet ik" to "how do i",
        "hoe doe ik" to "how do i",
        "hoe" to "how do i",
        "kan niet vinden" to "can't find",
        "niet vinden" to "can't find",
        "vind niet" to "can't find",
        "laat me zien" to "show me",
        "toon me" to "show me",
        "toon mij" to "show me",

        // Doing.
        "toon" to "show",
        "tonen" to "show",
        "laat zien" to "show",
        "weergeven" to "display",
        "geef weer" to "display",
        "openen" to "open",
        "ga naar" to "go to",
        "schakel naar" to "switch to",
        "wissel naar" to "switch to",
        "zoek*" to "find",
        "vind" to "find",
        "vinden" to "find",
        "lees" to "read",
        "voorlezen" to "read",
        "maak*" to "make",
        "maken" to "make",
        "creëer*" to "create",
        "creeer*" to "create",
        "aanmaken" to "create",
        "toevoeg*" to "add",
        "voeg toe" to "add",
        "voeg" to "add",
        "laad*" to "load",
        "laden" to "load",
        "uploaden" to "load",
        "importeer*" to "import",
        "importeren" to "import",
        "downloaden" to "download",
        "installeer*" to "install",
        "installeren" to "install",
        "kies" to "choose",
        "kiezen" to "choose",
        "selecteer*" to "choose",
        "instellen" to "set up",
        "configureer*" to "set up",
        "configureren" to "set up",
        "verbind*" to "connect",
        "koppel*" to "connect",
        "toewijz*" to "assign",
        "verberg*" to "hide",
        "stoppen" to "stop",
        "beëindig*" to "stop",
        "beeindig*" to "stop",
        "verwijder*" to "delete",
        "wis" to "clear",
        "wissen" to "clear",
        "leegmak*" to "clear",
        "op zwart" to "black out",
        "zwart maken" to "black out",
        "leeg scherm" to "blank",
        "ongedaan*" to "undo",
        "terugdraaien" to "undo",
        "live gaan" to "go live",
        "live zetten" to "go live",
        "aanzetten" to "turn on",
        "zet aan" to "turn on",
        "inschakel*" to "turn on",
        "uitzetten" to "turn off",
        "zet uit" to "turn off",
        "uitschakel*" to "turn off",
        "omschakel*" to "toggle",
        "volgend*" to "next",
        "verder" to "next",
        "vooruit" to "forward",
        "vorig*" to "previous",
        "terug" to "back",
        "vergro*" to "increase",
        "groter" to "bigger",
        "verklein*" to "decrease",
        "kleiner" to "smaller",
        "converteer*" to "convert",
        "converteren" to "convert",
        "omzetten" to "convert",
        "overzetten" to "transfer",
        "overbreng*" to "transfer",
        "migreer*" to "migrate",
        "migreren" to "migrate",
        "bewerk*" to "edit",
        "wijzig*" to "change",
        "verander*" to "change",
        "aanpass*" to "change",
        "hernoem*" to "rename",
        "repareer*" to "fix",
        "oploss*" to "fix",
        "organiseer*" to "organize",
        "organiseren" to "organize",
        "opruim*" to "clean up",
        "vergelijk*" to "compare",
        "vertaal*" to "translate",
        "plannen" to "plan",
        "inplannen" to "plan",
        "automatiseer*" to "automate",
        "automatisch*" to "automatically",
        "herken*" to "identify",
        "nummeren" to "number the",
        "nummer de" to "number the",

        // Too small, too big, not working.
        "te klein" to "too small",
        "veel te klein" to "too small",
        "slecht leesbaar" to "hard to read",
        "moeilijk te lezen" to "hard to read",
        "niet leesbaar" to "hard to read",
        "onleesbaar" to "hard to read",
        "te groot" to "too big",
        "past niet" to "doesn't fit",
        "werkt niet" to "not working",
        "doet het niet" to "not working",
        "toont niet" to "not showing",
        "wordt niet getoond" to "not showing",
        "toont niets" to "nothing shows",
        "niets te zien" to "nothing shows",
        "zwart scherm" to "screen is black",
        "scherm is zwart" to "screen is black",
        "geen signaal" to "no signal",
        "geen beeld" to "no picture",
        "welk scherm" to "which screen",
        "welke monitor" to "which monitor",
        "welke beamer" to "which projector",
        "welke projector" to "which projector",

        // What is on screen.
        "achtergrond*" to "background",
        "liedtekst*" to "lyrics",
        "songtekst*" to "lyrics",
        "liederen" to "songs",
        "liedje*" to "song",
        "lied" to "song",
        "gezang*" to "hymn",
        "lofprijzing*" to "worship",
        "aanbidding*" to "worship",
        "bijbel*" to "bible",
        "schriftgedeelte*" to "scripture",
        "schriftlezing*" to "scripture",
        "bijbeltekst*" to "verse",
        "bijbelvers*" to "verse",
        "vers" to "verse",
        "verzen" to "verse",
        "hoofdstuk*" to "chapter",
        "lettergrootte*" to "font size",
        "tekstgrootte*" to "text size",
        "lettertype*" to "font",
        "grootte" to "size",
        "tekst*" to "text",
        "woorden" to "words",
        "diavoorstelling*" to "slideshow",
        "dia" to "slide",
        "dia's" to "slide",
        "dias" to "slide",
        "foto*" to "photo",
        "afbeelding*" to "image",
        "plaatje*" to "picture",
        "presentatie*" to "presentation",
        "filmpje*" to "clip",
        "film*" to "movie",
        "onderbalk*" to "lower third",
        "ondertitelbalk*" to "lower third",
        "naambalk*" to "name strap",
        "naam en functie" to "name and title",
        "mededeling*" to "announcement",
        "aankondiging*" to "announcement",
        "afkondiging*" to "announcement",
        "lichtkrant*" to "ticker",
        "kinderoppas*" to "nursery",
        "crèche" to "nursery",
        "creche" to "nursery",
        "kindernevendienst*" to "kids room",
        "aftellen" to "countdown",
        "aftel*" to "countdown",
        "klok*" to "clock",
        "huidige tijd" to "current time",
        "tijd" to "time",
        "notitie*" to "notes",
        "akkoord*" to "chord",
        "vertaling*" to "translation",
        "taal" to "language",
        "talen" to "language",
        "tweetalig*" to "bilingual",
        "andere taal" to "another language",
        "tweede taal" to "second language",
        "twee talen" to "two languages",

        // Screens and outputs.
        "hoofdscherm*" to "main screen",
        "volledig scherm" to "full screen",
        "volledig beeld" to "full screen",
        "schermvullend" to "fullscreen",
        "beeldvullend" to "fullscreen",
        "tweede scherm" to "second screen",
        "scherm*" to "screen",
        "beamer*" to "projector",
        "podiummonitor*" to "stage monitor",
        "podiumscherm*" to "stage monitor",
        "monitor op het podium" to "stage monitor",
        "weergave" to "display",
        "uitvoervenster*" to "output window",
        "uitvoer*" to "output",
        "podium*" to "stage",
        "zones" to "zone",
        "indeling*" to "layout",
        "opstelling*" to "arrangement",
        "bericht*" to "message",
        "stuur*" to "send",
        "verstuur*" to "send",
        "verzend*" to "send",
        "voorbeeld*" to "preview",
        "wat staat er op het scherm" to "what is on screen",
        "profiel*" to "profile",
        "uitzending*" to "stream",
        "televisie*" to "tv",

        // Pages, tabs and tools.
        "instelling*" to "settings",
        "opties" to "options",
        "voorkeur*" to "preferences",
        "installatiewizard*" to "setup wizard",
        "opnieuw beginnen" to "start over",
        "sneltoets*" to "shortcut",
        "toetscombinatie*" to "shortcut",
        "toetsenbord*" to "keyboard",
        "tabblad*" to "tab",
        "liedbibliotheek*" to "song library",
        "liederenbibliotheek*" to "song library",
        "bibliotheek*" to "library",
        "webpagina*" to "website",
        "woordenboek*" to "dictionary",
        "afstandsbediening*" to "remote",
        "op afstand" to "remote",
        "telefoon*" to "phone",
        "mobieltje*" to "phone",
        "integratie*" to "integrations",

        // Services and planning.
        "orde van dienst" to "order of service",
        "liturgie*" to "order of service",
        "draaiboek*" to "order of service",
        "kerkdienst*" to "service",
        "eredienst*" to "service",
        "dienst" to "service",
        "diensten" to "service",
        "samenkomst*" to "meeting",
        "bijeenkomst*" to "meeting",
        "zondag*" to "sunday",
        "kalender*" to "calendar",
        "programma*" to "schedule",
        "rooster*" to "schedule",
        "afspeellijst*" to "playlist",
        "elke zondag" to "every sunday",
        "iedere zondag" to "every sunday",
        "elke week" to "every week",
        "iedere week" to "every week",
        "wekelijks*" to "weekly",
        "maandelijks*" to "monthly",
        "herhaal*" to "repeat",
        "sjabloon*" to "template",

        // Many, all, both.
        "alle" to "all",
        "alles" to "everything",
        "overal" to "everything",
        "beide" to "both",
        "allebei" to "both",
        "meerdere" to "several",
        "veel" to "many",
        "tegelijk*" to "at once",
        "voor deze dienst" to "this service",
        "voor vandaag" to "for today",
        "tijdelijk*" to "temporarily",
        "voorlopig" to "for now",

        // Languages, by name.
        "russisch*" to "russian",
        "oekraïens*" to "ukrainian",
        "oekraiens*" to "ukrainian",
        "wit-russisch*" to "belarusian",
        "belarussisch*" to "belarusian",
        "engels*" to "english",
        "spaans*" to "spanish",
        "duits*" to "german",
        "frans*" to "french",
        "poolse" to "polish",
        "kazachs*" to "kazakh",
        "roemeens*" to "romanian",
        "moldavisch*" to "moldovan",
        "portugees*" to "portuguese",
        "portugese" to "portuguese",
        "italiaans*" to "italian",
        "nederlands*" to "dutch",
        "vlaams*" to "dutch",
        "tsjechisch*" to "czech",
        "slowaaks*" to "slovak",
        "kroatisch*" to "croatian",
        "servisch*" to "serbian",
        "bulgaars*" to "bulgarian",
        "hongaars*" to "hungarian",
        "grieks*" to "greek",
        "turks*" to "turkish",
        "arabisch*" to "arabic",
        "perzisch*" to "persian",
        "hebreeuws*" to "hebrew",
        "chinees*" to "chinese",
        "japans*" to "japanese",
        "koreaans*" to "korean",
        "vietnamees*" to "vietnamese",
        "indonesisch*" to "indonesian",
        "estisch*" to "estonian",
        "letse" to "latvian",
        "lettisch*" to "latvian",
        "litouws*" to "lithuanian",
        "finse" to "finnish",
        "zweeds*" to "swedish",
        "noors*" to "norwegian",
        "deens*" to "danish",
        "armeens*" to "armenian",
        "georgisch*" to "georgian",
        "latijn*" to "latin",

        // Colors.
        "donkerblauw*" to "navy",
        "marineblauw*" to "navy",
        "lichtblauw*" to "light blue",
        "hemelsblauw*" to "sky",
        "blauw*" to "blue",
        "zwart*" to "black",
        "wit" to "white",
        "witte" to "white",
        "lichtgrijs*" to "light grey",
        "donkergrijs*" to "dark grey",
        "grijs*" to "grey",
        "grijze" to "grey",
        "zilver*" to "silver",
        "rood" to "red",
        "rode" to "red",
        "donkerrood*" to "maroon",
        "bordeaux*" to "maroon",
        "oranje" to "orange",
        "geel" to "yellow",
        "gele" to "yellow",
        "goud*" to "gold",
        "lichtgroen*" to "lime",
        "donkergroen*" to "dark green",
        "groen*" to "green",
        "turkoois*" to "turquoise",
        "paars*" to "purple",
        "roze" to "pink",
        "bruin*" to "brown",
        "crème*" to "cream",
        "creme*" to "cream",
        "donker*" to "dark",
        "licht*" to "light",

        // Talking to the helper.
        "hallo" to "hello",
        "hoi" to "hello",
        "goedemorgen" to "hello",
        "goedemiddag" to "hello",
        "goedenavond" to "hello",
        "goedendag" to "hello",
        "helpen" to "help",
        "hulp" to "help",
        "wat kun je" to "what can you do",
        "wat kan je" to "what can you do",
        "wat kun jij" to "what can you do",
        "wie ben je" to "who are you",
        "wie ben jij" to "who are you",
        "dank je*" to "thanks",
        "bedankt" to "thanks",
        "dankjewel" to "thanks",
        "dank u" to "thank you",
        "dank u wel" to "thank you",
        "alsjeblieft" to "please",
        "alstublieft" to "please",
        "wik" to "wick",
    ),
)
