package org.churchpresenter.helper.intent.glossary

internal val ESTONIAN = Glossary(
    "et",
    listOf(
        // Asking where, or how.
        "kus" to "where",
        "kuhu" to "where",
        "kust" to "where",
        "kust leian" to "where",
        "kuidas ma saan" to "how can i",
        "kuidas saan" to "how can i",
        "kuidas ma" to "how do i",
        "kuidas" to "how do i",
        "ei leia" to "can't find",
        "ma ei leia" to "can't find",
        "näita mulle" to "show me",
        "naita mulle" to "show me",

        // Doing.
        "näita*" to "show",
        "naita*" to "show",
        "näitama" to "show",
        "kuva" to "display",
        "kuvada" to "display",
        "kuvama" to "display",
        "ava" to "open",
        "avada" to "open",
        "avage" to "open",
        "mine eetrisse" to "go live",
        "liigu" to "go to",
        "lülitu" to "switch to",
        "lulitu" to "switch to",
        "otsi*" to "find",
        "leia" to "find",
        "leida" to "find",
        "loe" to "read",
        "tee" to "make",
        "tehke" to "make",
        "teha" to "make",
        "loo" to "create",
        "luua" to "create",
        "lisa*" to "add",
        "laadi alla" to "download",
        "allalaadi*" to "download",
        "laadi*" to "load",
        "lae" to "load",
        "impordi*" to "import",
        "paigalda*" to "install",
        "installi*" to "install",
        "valik*" to "options",
        "vali" to "choose",
        "valida" to "choose",
        "seadista" to "set up",
        "seadistada" to "set up",
        "ühenda*" to "connect",
        "uhenda*" to "connect",
        "määra*" to "assign",
        "maara*" to "assign",
        "peida*" to "hide",
        "peata*" to "stop",
        "lõpeta*" to "stop",
        "lopeta*" to "stop",
        "kustuta*" to "delete",
        "eemalda*" to "remove",
        "tühjenda*" to "clear",
        "tuhjenda*" to "clear",
        "puhasta*" to "clear",
        "pimenda*" to "black out",
        "tühi ekraan" to "blank",
        "tuhi ekraan" to "blank",
        "võta tagasi" to "undo",
        "vota tagasi" to "undo",
        "tühista*" to "undo",
        "tuhista*" to "undo",
        "eetrisse" to "go live",
        "lülita sisse" to "turn on",
        "lulita sisse" to "turn on",
        "lülita välja" to "turn off",
        "lulita valja" to "turn off",
        "lülita*" to "toggle",
        "lulita*" to "toggle",
        "järgmine*" to "next",
        "jargmine*" to "next",
        "järgmise*" to "next",
        "edasi" to "forward",
        "eelmine*" to "previous",
        "eelmise*" to "previous",
        "tagasi" to "back",
        "suurenda*" to "increase",
        "suurem*" to "bigger",
        "vähenda*" to "decrease",
        "vahenda*" to "decrease",
        "väiksem*" to "smaller",
        "vaiksem*" to "smaller",
        "teisendaja*" to "converter",
        "konverter*" to "converter",
        "teisenda*" to "convert",
        "konverteeri*" to "convert",
        "kanna üle" to "transfer",
        "kanna ule" to "transfer",
        "üle kanda" to "transfer",
        "redigeeri*" to "edit",
        "muuda*" to "change",
        "muutmine" to "change",
        "nimeta ümber" to "rename",
        "nimeta umber" to "rename",
        "paranda*" to "fix",
        "korralda*" to "organize",
        "korrasta*" to "clean up",
        "võrdle*" to "compare",
        "vordle*" to "compare",
        "tõlgi*" to "translate",
        "tolgi*" to "translate",
        "planeeri*" to "plan",
        "kavanda*" to "plan",
        "automatiseeri*" to "automate",
        "automaatselt" to "automatically",
        "tuvasta*" to "identify",
        "nummerda*" to "number the",

        // Too small, too big, not working.
        "liiga väike" to "too small",
        "liiga vaike" to "too small",
        "liiga väikesed" to "too small",
        "liiga väikeseks" to "too small",
        "raske lugeda" to "hard to read",
        "halvasti loetav" to "hard to read",
        "ei ole loetav" to "hard to read",
        "halvasti näha" to "hard to read",
        "liiga suur" to "too big",
        "liiga suured" to "too big",
        "ei mahu" to "doesn't fit",
        "ei tööta" to "not working",
        "ei toota" to "not working",
        "ei näita" to "not showing",
        "ei naita" to "not showing",
        "ei kuva" to "not showing",
        "midagi ei näita" to "nothing shows",
        "midagi ei kuvata" to "nothing shows",
        "midagi pole näha" to "nothing shows",
        "must ekraan" to "screen is black",
        "ekraan on must" to "screen is black",
        "signaali pole" to "no signal",
        "pole signaali" to "no signal",
        "pilti pole" to "no picture",
        "pole pilti" to "no picture",
        "milline ekraan" to "which screen",
        "mis ekraan" to "which screen",
        "milline monitor" to "which monitor",
        "milline kuvar" to "which monitor",
        "milline projektor" to "which projector",

        // What is on screen.
        "taust*" to "background",
        "laulusõna*" to "lyrics",
        "laulusona*" to "lyrics",
        "laulu sõnad" to "lyrics",
        "laul*" to "song",
        "vaimulik laul" to "hymn",
        "kirikulaul*" to "hymn",
        "ülistus*" to "worship",
        "ulistus*" to "worship",
        "piibel" to "bible",
        "piibli*" to "bible",
        "pühakiri" to "scripture",
        "pühakirja*" to "scripture",
        "piiblisalm*" to "verse",
        "salm*" to "verse",
        "peatükk*" to "chapter",
        "peatuki*" to "chapter",
        "peatüki*" to "chapter",
        "fondi suurus" to "font size",
        "kirjasuurus*" to "font size",
        "teksti suurus" to "text size",
        "fondi*" to "font",
        "kirjatüüp*" to "font",
        "suurus*" to "size",
        "tekst*" to "text",
        "sõnad" to "words",
        "sonad" to "words",
        "tähed" to "letters",
        "tähti" to "letters",
        "slaidiseanss*" to "slideshow",
        "slaidiesitlus*" to "slideshow",
        "slaid*" to "slide",
        "foto*" to "photo",
        "pilt*" to "picture",
        "pildi*" to "picture",
        "kujutis*" to "image",
        "albumi*" to "album",
        "esitlus*" to "presentation",
        "videod" to "video",
        "videot" to "video",
        "filmi*" to "movie",
        "klipp*" to "clip",
        "klipi*" to "clip",
        "meedia*" to "media",
        "heli" to "audio",
        "alumine kolmandik" to "lower third",
        "alumise kolmandiku" to "lower third",
        "nimeriba*" to "name strap",
        "nimi ja ametikoht" to "name and title",
        "teadaanne*" to "announcement",
        "teadaand*" to "announcement",
        "teade" to "announcement",
        "teate*" to "announcement",
        "jooksev tekst" to "ticker",
        "jooksva teksti" to "ticker",
        "lastetuba" to "kids room",
        "lastetoa*" to "kids room",
        "lastehoid*" to "kids room",
        "pühapäevakool*" to "kids room",
        "pöördloendus*" to "countdown",
        "tagasiloendus*" to "countdown",
        "taimer*" to "timer",
        "stopper*" to "stopwatch",
        "kellaaeg*" to "current time",
        "praegune aeg" to "current time",
        "kell" to "clock",
        "kella" to "clock",
        "aeg" to "time",
        "aega" to "time",
        "märkm*" to "notes",
        "markm*" to "notes",
        "akord*" to "chord",
        "tõlge*" to "translation",
        "tõlke*" to "translation",
        "tolge*" to "translation",
        "keel" to "language",
        "keele*" to "language",
        "keelt" to "language",
        "keeled" to "language",
        "kakskeelne*" to "bilingual",
        "teises keeles" to "another language",
        "teine keel" to "second language",
        "kahes keeles" to "two languages",

        // Screens and outputs.
        "põhiekraan*" to "main screen",
        "pohiekraan*" to "main screen",
        "täisekraan*" to "full screen",
        "taisekraan*" to "full screen",
        "teine ekraan" to "second screen",
        "ekraan*" to "screen",
        "projektori*" to "projector",
        "lavamonitor*" to "stage monitor",
        "lavaekraan*" to "stage monitor",
        "monitori*" to "monitor",
        "kuvar*" to "monitor",
        "väljund*" to "output",
        "valjund*" to "output",
        "lava*" to "stage",
        "tsoon*" to "zone",
        "paigutus*" to "layout",
        "asetus*" to "arrangement",
        "sõnum*" to "message",
        "sonum*" to "message",
        "saada*" to "send",
        "eelvaade*" to "preview",
        "eelvaate*" to "preview",
        "mis on ekraanil" to "what is on screen",
        "profiil*" to "profile",
        "otseülekanne*" to "stream",
        "ülekanne*" to "stream",
        "voogedastus*" to "stream",
        "teler*" to "tv",

        // Pages, tabs and tools.
        "seadistusviisard*" to "setup wizard",
        "seaded" to "settings",
        "seadete*" to "settings",
        "sätted" to "settings",
        "seadistus*" to "settings",
        "alusta otsast" to "start over",
        "alusta uuesti" to "start over",
        "kiirklahv*" to "hotkeys",
        "otsetee*" to "shortcut",
        "klaviatuur*" to "keyboard",
        "vahekaart*" to "tab",
        "laulukogu*" to "song library",
        "raamatukogu*" to "library",
        "teek*" to "library",
        "veebileht*" to "website",
        "veebisait*" to "website",
        "veeb*" to "web",
        "brauser*" to "browser",
        "lehitseja*" to "browser",
        "sõnastik*" to "dictionary",
        "sonastik*" to "dictionary",
        "kaamera*" to "camera",
        "lõuend*" to "canvas",
        "louend*" to "canvas",
        "serveri*" to "server",
        "kaugjuhtimi*" to "remote",
        "pult*" to "remote",
        "telefon*" to "phone",
        "tahvelarvuti*" to "tablet",
        "integratsioon*" to "integrations",

        // Services and planning.
        "jumalateenistuse kava" to "order of service",
        "teenistuse kava" to "order of service",
        "jumalateenistus*" to "service",
        "teenistus*" to "service",
        "koosolek*" to "meeting",
        "koosoleku*" to "meeting",
        "pühapäev*" to "sunday",
        "puhapaev*" to "sunday",
        "kalend*" to "calendar",
        "kava*" to "schedule",
        "esitusloend*" to "playlist",
        "igal pühapäeval" to "every sunday",
        "iga nädal" to "every week",
        "iga nadal" to "every week",
        "iganädala*" to "weekly",
        "igakuu*" to "monthly",
        "korda" to "repeat",
        "kordu*" to "recurring",
        "malli*" to "template",

        // Many, all, both.
        "kõik" to "all",
        "koik" to "all",
        "kõiki" to "all",
        "kõikjal" to "everything",
        "mõlemad" to "both",
        "molemad" to "both",
        "mõlema*" to "both",
        "mitu" to "several",
        "mitmed" to "several",
        "palju" to "many",
        "korraga" to "at once",
        "selle teenistuse jaoks" to "this service",
        "tänaseks" to "for today",
        "täna" to "for today",
        "ajutiselt" to "temporarily",
        "praegu" to "for now",

        // Languages, by name.
        "valgevene*" to "belarusian",
        "vene*" to "russian",
        "ukraina*" to "ukrainian",
        "inglise*" to "english",
        "hispaania*" to "spanish",
        "saksa*" to "german",
        "prantsuse*" to "french",
        "poola*" to "polish",
        "kasahhi*" to "kazakh",
        "rumeenia*" to "romanian",
        "moldova*" to "moldovan",
        "portugali*" to "portuguese",
        "itaalia*" to "italian",
        "hollandi*" to "dutch",
        "tšehhi*" to "czech",
        "tsehhi*" to "czech",
        "slovaki*" to "slovak",
        "horvaadi*" to "croatian",
        "serbia*" to "serbian",
        "bulgaaria*" to "bulgarian",
        "ungari*" to "hungarian",
        "kreeka*" to "greek",
        "türgi*" to "turkish",
        "turgi*" to "turkish",
        "araabia*" to "arabic",
        "pärsia*" to "persian",
        "heebrea*" to "hebrew",
        "hiina*" to "chinese",
        "jaapani*" to "japanese",
        "korea*" to "korean",
        "vietnami*" to "vietnamese",
        "indoneesia*" to "indonesian",
        "eesti*" to "estonian",
        "läti*" to "latvian",
        "leedu*" to "lithuanian",
        "soome*" to "finnish",
        "rootsi*" to "swedish",
        "norra*" to "norwegian",
        "taani*" to "danish",
        "armeenia*" to "armenian",
        "gruusia*" to "georgian",
        "ladina*" to "latin",

        // Colors.
        "tumesini*" to "navy",
        "helesini*" to "light blue",
        "taevasini*" to "sky",
        "sini*" to "blue",
        "musta" to "black",
        "mustaks" to "black",
        "mustas" to "black",
        "valge*" to "white",
        "helehall*" to "light grey",
        "tumehall*" to "dark grey",
        "halli" to "grey",
        "halliks" to "grey",
        "hõbe*" to "silver",
        "hobe*" to "silver",
        "veinipuna*" to "maroon",
        "tumepuna*" to "maroon",
        "punane*" to "red",
        "punase*" to "red",
        "oranž*" to "orange",
        "oranz*" to "orange",
        "kollane*" to "yellow",
        "kollase*" to "yellow",
        "kuldne*" to "gold",
        "kuldse*" to "gold",
        "laimiroheli*" to "lime",
        "heleroheli*" to "lime",
        "tumeroheli*" to "dark green",
        "roheli*" to "green",
        "türkiis*" to "turquoise",
        "turkiis*" to "turquoise",
        "lilla*" to "purple",
        "violetne*" to "violet",
        "violetse*" to "violet",
        "roosa*" to "pink",
        "pruun*" to "brown",
        "beež*" to "beige",
        "beez*" to "beige",
        "kreem*" to "cream",
        "tume*" to "dark",
        "hele*" to "light",

        // Talking to the helper.
        "tere" to "hello",
        "tervist" to "hello",
        "tere päevast" to "hello",
        "hommikust" to "hello",
        "aita*" to "help",
        "abi" to "help",
        "mida sa oskad" to "what can you do",
        "mida sa teha oskad" to "what can you do",
        "mida sa suudad" to "what can you do",
        "kes sa oled" to "who are you",
        "aitäh" to "thanks",
        "aitah" to "thanks",
        "tänan" to "thanks",
        "suur aitäh" to "thank you",
        "tänud" to "thanks",
        "palun" to "please",
        "vikk" to "wick",

        // Newer requests.
        "otsida" to "search",
        "otsin" to "search",
        "otsing*" to "search",
        "otsi piibli*" to "search the bible",
        "otsi laul*" to "find a song",
        "otsi salm*" to "find a verse",
        "nimega" to "named",
        "lemmik*" to "favorite",
        "see laul" to "this song",
        "selle laulu" to "this song",
        "sellele laulule" to "this song",
        "iga laul" to "each song",
        "igale laulule" to "each song",
        "oma taust*" to "own background",
        "laulu lisa*" to "add a song",
        "lisada laul*" to "add a song",
        "näidata" to "show",
        "naidata" to "show",
        "mitut salmi" to "several verses",
        "mitu salmi" to "several verses",
        "mitmeid salme" to "several verses",
        "mitut" to "several",
        "mitmeid" to "several",
        "rohkem kui üks salm" to "more than one verse",
        "rohkem kui uks salm" to "more than one verse",
        "salmivahemik*" to "verse range",
        "salmide vahemik*" to "range of verses",
        "terve lõik" to "whole passage",
        "ajalugu" to "history",
        "ajaloo*" to "history",
        "mida me just näitasime" to "what did we just show",
        "mida me just naitasime" to "what did we just show",
        "mida me näitasime" to "what did we show",
        "hiljuti näidatud" to "recently shown",
        "viimased salmid" to "recent verses",
        "varem näidatud" to "shown before",
        "ristviide*" to "cross references",
        "ristviite*" to "cross references",
        "seotud salmid" to "related verses",
        "seotud salme" to "related verses",
        "sarnased salmid" to "similar verses",
        "rööpkoh*" to "parallel passages",
        "roopkoh*" to "parallel passages",
        "paralleelkoh*" to "parallel passages",
        "veebiaadress*" to "url",
        "internetileh*" to "internet page",
        "statistika*" to "statistics",
        "mitu korda" to "how many times",
        "kui tihti" to "how often",
        "kui sageli" to "how often",
        "laulude kasutus*" to "song usage",
        "lauluaruan*" to "song report",
        "ccli-aruan*" to "ccli report",
        "juhi seda" to "control it",
        "telefonist" to "from my phone",
        "minu telefonist" to "from my phone",
        "telefoniga" to "from my phone",
        "telefonis" to "on my phone",
        "ühenda telefon*" to "connect my phone",
        "uhenda telefon*" to "connect my phone",
        "kaugjuhtimine" to "remote control",
        "qr-kood*" to "qr code",
        "qr kood*" to "qr code",
        "planning center*" to "planning center",
        "openlp*" to "openlp",
        "pdf-*" to "pdf",
        "projektor" to "projector",
        "alumi* kolmandik*" to "lower third",
        "minut*" to "minutes",
        "teadaanne:" to "announce :",
        "teata" to "announce",
        "teata:" to "announce :",
        "kuuluta" to "announce",
        "kuuluta:" to "announce :",
        "pane" to "put",
        "kavasse" to "to the schedule",
        "kavva" to "to the schedule",
        "kavas" to "in the schedule",
        "kavast" to "from the schedule",
        "punkt" to "item",
        "punkti" to "item",
        "kavapunkt*" to "item",
        "mis on eetris" to "what's live",
        "mida näidatakse" to "what's showing",
        "mida naidatakse" to "what's showing",
        "kas midagi on eetris" to "is anything live",
        "mis versioon" to "what version",
        "milline versioon" to "what version",
        "versioon*" to "version",
        "rakenduse versioon" to "app version",
        "kontrolli uuendusi" to "check for updates",
        "otsi uuendusi" to "check for updates",
        "kas on uuendusi" to "is there an update",
        "kas on uuendus" to "is there an update",
        "uusim versioon" to "latest version",
        "viimane versioon" to "latest version",
        "ajakohane" to "up to date",
        "käsud" to "commands",
        "käsk*" to "commands",
        "käskude loend" to "list of commands",
        "käskude nimekiri" to "list of commands",
        "mida ma saan öelda" to "what can i say",
        "mida ma saan kirjutada" to "what can i type",
        "mida ma saan küsida" to "what can i ask",
        "mida sa mõistad" to "what do you understand",
        "mida sa aru saad" to "what do you understand",

        // Look requests.
        "muuta" to "change",
        "liiguta*" to "move",
        "nihuta*" to "move",
        "laulu sõnu" to "lyrics",
        "laulu sõnadele" to "lyrics",
        "laulu sõnade" to "lyrics",
        "laulu sonu" to "lyrics",
        "laulu sonad" to "lyrics",
        "trükivig*" to "typo",
        "trükivea*" to "typo",
        "trukivig*" to "typo",
        "trukivea*" to "typo",
        "kirjavig*" to "typo",
        "kirjavea*" to "typo",
        "rasvas*" to "bold",
        "rasvane" to "bold",
        "kaldkir*" to "italic",
        "allajoon*" to "underline",
        "kontuur*" to "outline",
        "langev vari" to "drop shadow",
        "vari" to "shadow",
        "varju" to "shadow",
        "varjud" to "shadow",
        "varjuga" to "shadow",
        "veeris*" to "margins",
        "servad" to "edges",
        "servadest" to "edges",
        "ülaossa" to "top",
        "ülaosas" to "top",
        "ulaossa" to "top",
        "ulaosas" to "top",
        "alaossa" to "bottom",
        "alaosas" to "bottom",
        "keskele" to "middle",
        "keskel" to "middle",
        "vasakule" to "left",
        "vasakul" to "left",
        "paremale" to "right",
        "paremal" to "right",
        "tsentree*" to "center",
        "joondus*" to "alignment",
        "joonda*" to "align",
        "asukoh*" to "position",
        "vertikaal*" to "vertically",
        "laulu lõpu märk*" to "end of song marker",
        "laulu lopu mark*" to "end of song marker",
        "laulu lõpu*" to "end of song",
        "laulu lõpp*" to "end of song",
        "laulu lopu*" to "end of song",
        "laulu lopp*" to "end of song",
        "lõpumärk*" to "end marker",
        "lopumark*" to "end marker",
        "laulu pealki*" to "song title",
        "pealki*" to "title",
        "laulu number*" to "song number",
        "laulu numbri*" to "song number",
        "piibliviide*" to "bible reference",
        "piibliviite*" to "bible reference",
        "viide" to "reference",
        "viidet" to "reference",
        "viite*" to "reference",
        "välimus*" to "appearance",
        "valimus*" to "appearance",
        "stiil*" to "style",
        "kujunda*" to "style",
        "vormin*" to "format",
        "värv*" to "color",
        "varv*" to "color",

        // The help table's own examples.
        "mine" to "go to",
        "juurde" to "",
        "vanema*" to "parents",
        "lastet*" to "kids room",
    ),
)
