package org.churchpresenter.helper.intent.glossary

internal val FINNISH = Glossary(
    "fi",
    listOf(
        // Asking where, or how.
        "missä" to "where",
        "missa" to "where",
        "mistä" to "where",
        "mista" to "where",
        "mihin" to "where",
        "minne" to "where",
        "miten voin" to "how can i",
        "kuinka voin" to "how can i",
        "miten saan" to "how can i",
        "miten teen" to "how do i",
        "miten" to "how do i",
        "kuinka" to "how do i",
        "en löydä" to "can't find",
        "en loyda" to "can't find",
        "ei löydy" to "can't find",
        "näytä minulle" to "show me",
        "nayta minulle" to "show me",

        // Doing.
        "näytä*" to "show",
        "nayta*" to "show",
        "näyttää" to "show",
        "avaa*" to "open",
        "mene" to "go to",
        "siirry*" to "go to",
        "vaihda*" to "change",
        "etsi*" to "find",
        "hae" to "find",
        "löydä" to "find",
        "lue" to "read",
        "tee" to "make",
        "tehdä" to "make",
        "luo" to "create",
        "luoda" to "create",
        "lisää*" to "add",
        "lisaa*" to "add",
        "lataa*" to "load",
        "tuo" to "import",
        "tuoda" to "import",
        "asenna*" to "install",
        "valitse*" to "choose",
        "valita" to "choose",
        "määritä*" to "set up",
        "maarita*" to "set up",
        "aseta*" to "set up",
        "yhdistä*" to "connect",
        "yhdista*" to "connect",
        "osoita*" to "assign",
        "piilota*" to "hide",
        "pysäytä*" to "stop",
        "pysayta*" to "stop",
        "lopeta*" to "stop",
        "poista*" to "delete",
        "tyhjennä*" to "clear",
        "tyhjenna*" to "clear",
        "pimennä*" to "black out",
        "pimenna*" to "black out",
        "tyhjä näyttö" to "blank",
        "kumoa*" to "undo",
        "peruuta*" to "undo",
        "näytä livenä" to "go live",
        "nayta livena" to "go live",
        "livenä" to "go live",
        "lähetykseen" to "go live",
        "laita päälle" to "turn on",
        "kytke päälle" to "turn on",
        "käynnistä*" to "turn on",
        "kaynnista*" to "turn on",
        "sammuta*" to "turn off",
        "laita pois" to "turn off",
        "kytke pois" to "turn off",
        "seuraava*" to "next",
        "eteenpäin" to "forward",
        "eteenpain" to "forward",
        "edellinen" to "previous",
        "edellise*" to "previous",
        "takaisin" to "back",
        "suurenna*" to "increase",
        "kasvata*" to "increase",
        "isompi" to "bigger",
        "isommaksi" to "bigger",
        "suurempi" to "bigger",
        "suuremmaksi" to "bigger",
        "pienennä*" to "decrease",
        "pienenna*" to "decrease",
        "pienempi" to "smaller",
        "pienemmäksi" to "smaller",
        "pienemmaksi" to "smaller",
        "muunna*" to "convert",
        "muuntaa" to "convert",
        "muunnin*" to "converter",
        "muuntimen" to "converter",
        "siirrä*" to "transfer",
        "siirra*" to "transfer",
        "muokkaa*" to "edit",
        "muuta" to "change",
        "muuttaa" to "change",
        "nimeä uudelleen" to "rename",
        "nimea uudelleen" to "rename",
        "korjaa*" to "fix",
        "järjestä*" to "organize",
        "jarjesta*" to "organize",
        "siivoa*" to "clean up",
        "vertaa*" to "compare",
        "käännä*" to "translate",
        "kaanna*" to "translate",
        "suunnittele*" to "plan",
        "suunnitella" to "plan",
        "automatisoi*" to "automate",
        "automaattise*" to "automatically",
        "tunnista*" to "identify",
        "numeroi*" to "number the",

        // Too small, too big, not working.
        "liian pieni" to "too small",
        "liian pienet" to "too small",
        "liian pientä" to "too small",
        "vaikea lukea" to "hard to read",
        "vaikealukuinen" to "hard to read",
        "huonosti näkyvä" to "hard to read",
        "ei erota" to "hard to read",
        "liian iso" to "too big",
        "liian isot" to "too big",
        "liian suuri" to "too big",
        "liian suuret" to "too big",
        "ei mahdu" to "doesn't fit",
        "ei toimi" to "not working",
        "ei näy" to "not showing",
        "ei nay" to "not showing",
        "ei näytä" to "not showing",
        "mitään ei näy" to "nothing shows",
        "ei näy mitään" to "nothing shows",
        "ei mitään" to "nothing shows",
        "musta näyttö" to "screen is black",
        "musta ruutu" to "screen is black",
        "näyttö on musta" to "screen is black",
        "ei signaalia" to "no signal",
        "ei kuvaa" to "no picture",
        "mikä näyttö" to "which screen",
        "mika naytto" to "which screen",
        "mikä monitori" to "which monitor",
        "mikä projektori" to "which projector",
        "mikä videotykki" to "which projector",

        // What is on screen.
        "tausta*" to "background",
        "laulun sanat" to "lyrics",
        "laulujen sanat" to "lyrics",
        "sanoitus*" to "lyrics",
        "laulu*" to "song",
        "virsi*" to "hymn",
        "virre*" to "hymn",
        "ylistys*" to "worship",
        "ylistyks*" to "worship",
        "raamattu*" to "bible",
        "raamatu*" to "bible",
        "pyhä kirjoitus" to "scripture",
        "raamatunkohta*" to "verse",
        "raamatunjae*" to "verse",
        "jae" to "verse",
        "jakeet" to "verse",
        "jakeen" to "verse",
        "jakeita" to "verse",
        "luku" to "chapter",
        "luvun" to "chapter",
        "luvut" to "chapter",
        "fonttikoko*" to "font size",
        "kirjasinkoko*" to "font size",
        "tekstin koko" to "text size",
        "fontti*" to "font",
        "kirjasin*" to "font",
        "kokoa" to "size",
        "teksti*" to "text",
        "sanat" to "words",
        "kirjaimet" to "letters",
        "kirjaimi*" to "letters",
        "diaesitys*" to "slideshow",
        "diaesityks*" to "slideshow",
        "dia" to "slide",
        "dian" to "slide",
        "diat" to "slide",
        "dioja" to "slide",
        "valokuva*" to "photo",
        "kuva*" to "picture",
        "albumi*" to "album",
        "esitys*" to "presentation",
        "esityks*" to "presentation",
        "videot" to "video",
        "videon" to "video",
        "elokuva*" to "movie",
        "leike*" to "clip",
        "mediat" to "media",
        "alapalkki*" to "lower third",
        "alapalki*" to "lower third",
        "nimipalkki*" to "name strap",
        "nimi ja titteli" to "name and title",
        "tiedote*" to "announcement",
        "tiedotte*" to "announcement",
        "ilmoitus*" to "announcement",
        "ilmoitukse*" to "announcement",
        "ilmoituks*" to "announcement",
        "juokseva teksti" to "ticker",
        "lastenhuone*" to "kids room",
        "pyhäkoulu*" to "kids room",
        "lastenhoito*" to "kids room",
        "lähtölaskenta*" to "countdown",
        "lahtolaskenta*" to "countdown",
        "ajastin*" to "timer",
        "sekuntikello*" to "stopwatch",
        "kellonaika*" to "current time",
        "nykyinen aika" to "current time",
        "kello*" to "clock",
        "aika" to "time",
        "muistiinpano*" to "notes",
        "sointu*" to "chord",
        "soinnu*" to "chord",
        "käännös*" to "translation",
        "käännökse*" to "translation",
        "kaannos*" to "translation",
        "kieli" to "language",
        "kielen" to "language",
        "kieltä" to "language",
        "kielet" to "language",
        "kielellä" to "language",
        "kielelle" to "language",
        "kieliä" to "language",
        "kaksikielinen*" to "bilingual",
        "kaksikieli*" to "bilingual",
        "toisella kielellä" to "another language",
        "toinen kieli" to "second language",
        "kahdella kielellä" to "two languages",

        // Screens and outputs.
        "päänäyttö*" to "main screen",
        "paanaytto*" to "main screen",
        "koko näyttö*" to "full screen",
        "koko naytto*" to "full screen",
        "kokoruutu*" to "fullscreen",
        "toinen näyttö" to "second screen",
        "näyttö*" to "screen",
        "naytto*" to "screen",
        "näytö*" to "screen",
        "nayto*" to "screen",
        "ruutu*" to "screen",
        "ruudu*" to "screen",
        "projektori*" to "projector",
        "videotykki*" to "projector",
        "videotyki*" to "projector",
        "lavamonitori*" to "stage monitor",
        "lavanäyttö*" to "stage monitor",
        "lavanaytto*" to "stage monitor",
        "monitori*" to "monitor",
        "ulostulo*" to "output",
        "lava*" to "stage",
        "alue*" to "zone",
        "asettelu*" to "layout",
        "järjestely*" to "arrangement",
        "viesti*" to "message",
        "lähetä*" to "send",
        "laheta*" to "send",
        "esikatselu*" to "preview",
        "mitä ruudulla on" to "what is on screen",
        "profiili*" to "profile",
        "striimi*" to "stream",
        "suoratoisto*" to "stream",
        "lähetys*" to "stream",
        "televisio*" to "tv",
        "telkkari*" to "tv",

        // Pages, tabs and tools.
        "asetukse*" to "settings",
        "asetuks*" to "settings",
        "asetus" to "settings",
        "vaihtoehdot" to "options",
        "ohjattu asennus" to "setup wizard",
        "asennusopas*" to "setup wizard",
        "aloita alusta" to "start over",
        "pikanäppäin*" to "shortcut",
        "pikanappain*" to "shortcut",
        "näppäinyhdistelmä*" to "shortcut",
        "näppäimistö*" to "keyboard",
        "nappaimisto*" to "keyboard",
        "välilehti*" to "tab",
        "välilehde*" to "tab",
        "valilehti*" to "tab",
        "laulukirjasto*" to "song library",
        "kirjasto*" to "library",
        "verkko" to "web",
        "verkkosivu*" to "website",
        "nettisivu*" to "website",
        "selain*" to "browser",
        "selaime*" to "browser",
        "sanakirja*" to "dictionary",
        "kamera*" to "camera",
        "kanvas*" to "canvas",
        "palvelin*" to "server",
        "palveline*" to "server",
        "kaukosäädin*" to "remote",
        "kaukosaadin*" to "remote",
        "etäohjaus*" to "remote",
        "puhelin*" to "phone",
        "puhelime*" to "phone",
        "kännykkä*" to "phone",
        "tabletti*" to "tablet",
        "integraatio*" to "integrations",

        // Services and planning.
        "jumalanpalveluksen järjestys" to "order of service",
        "tilaisuuden kulku" to "order of service",
        "kulkusuunnitelma*" to "order of service",
        "jumalanpalvelu*" to "service",
        "tilaisuus*" to "service",
        "tilaisuude*" to "service",
        "kokous*" to "meeting",
        "kokoukse*" to "meeting",
        "kokouks*" to "meeting",
        "sunnuntai*" to "sunday",
        "kalenteri*" to "calendar",
        "ohjelma*" to "schedule",
        "aikataulu*" to "schedule",
        "soittolista*" to "playlist",
        "joka sunnuntai" to "every sunday",
        "joka viikko" to "every week",
        "viikoittai*" to "weekly",
        "kuukausittai*" to "monthly",
        "toista*" to "repeat",
        "toistuva*" to "recurring",
        "malli*" to "template",

        // Many, all, both.
        "kaikki" to "all",
        "kaikkialla" to "everything",
        "molemmat" to "both",
        "molempiin" to "both",
        "molempia" to "both",
        "useita" to "several",
        "monta" to "many",
        "monia" to "many",
        "kerralla" to "at once",
        "samanaikaisesti" to "at once",
        "tähän tilaisuuteen" to "this service",
        "tälle päivälle" to "for today",
        "tänään" to "for today",
        "tilapäisesti" to "temporarily",
        "väliaikaisesti" to "temporarily",
        "toistaiseksi" to "for now",

        // Languages, by name.
        "venäjä*" to "russian",
        "venaja*" to "russian",
        "ukraina*" to "ukrainian",
        "valkovenäjä*" to "belarusian",
        "englanti*" to "english",
        "englanni*" to "english",
        "espanja*" to "spanish",
        "saksa*" to "german",
        "ranska*" to "french",
        "puola*" to "polish",
        "kazakki*" to "kazakh",
        "romania*" to "romanian",
        "moldova*" to "moldovan",
        "portugali*" to "portuguese",
        "italia*" to "italian",
        "hollanti*" to "dutch",
        "hollanni*" to "dutch",
        "tšekki*" to "czech",
        "tsekki*" to "czech",
        "slovakia*" to "slovak",
        "kroatia*" to "croatian",
        "serbia*" to "serbian",
        "bulgaria*" to "bulgarian",
        "unkari*" to "hungarian",
        "kreikka*" to "greek",
        "kreika*" to "greek",
        "turkki*" to "turkish",
        "turki*" to "turkish",
        "arabia*" to "arabic",
        "persia*" to "persian",
        "heprea*" to "hebrew",
        "kiina*" to "chinese",
        "japani*" to "japanese",
        "korea*" to "korean",
        "vietnami*" to "vietnamese",
        "indonesia*" to "indonesian",
        "viro" to "estonian",
        "viron" to "estonian",
        "viroksi" to "estonian",
        "latvia*" to "latvian",
        "liettua*" to "lithuanian",
        "suomi" to "finnish",
        "suome*" to "finnish",
        "ruotsi*" to "swedish",
        "norja*" to "norwegian",
        "tanska*" to "danish",
        "armenia*" to "armenian",
        "georgia*" to "georgian",
        "latina*" to "latin",

        // Colors.
        "tummansini*" to "navy",
        "laivastonsini*" to "navy",
        "vaaleansini*" to "light blue",
        "taivaansini*" to "sky",
        "sini*" to "blue",
        "musta*" to "black",
        "valkoi*" to "white",
        "valkea*" to "white",
        "vaaleanharmaa*" to "light grey",
        "tummanharmaa*" to "dark grey",
        "harmaa*" to "grey",
        "hopea*" to "silver",
        "hopei*" to "silver",
        "viininpunai*" to "maroon",
        "tummanpunai*" to "maroon",
        "vaaleanpunai*" to "pink",
        "punai*" to "red",
        "oranssi*" to "orange",
        "keltai*" to "yellow",
        "kulta*" to "gold",
        "kultai*" to "gold",
        "limenvihre*" to "lime",
        "vaaleanvihre*" to "lime",
        "tummanvihre*" to "dark green",
        "vihreä*" to "green",
        "vihrea*" to "green",
        "vihre*" to "green",
        "turkoosi*" to "turquoise",
        "violetti*" to "violet",
        "purppura*" to "purple",
        "liila*" to "purple",
        "pinkki*" to "pink",
        "ruskea*" to "brown",
        "beige*" to "beige",
        "kerma*" to "cream",
        "tumma*" to "dark",
        "vaalea*" to "light",

        // Talking to the helper.
        "hei" to "hello",
        "moi" to "hello",
        "moikka" to "hello",
        "terve" to "hello",
        "hyvää päivää" to "hello",
        "hyvaa paivaa" to "hello",
        "huomenta" to "hello",
        "apua" to "help",
        "auta*" to "help",
        "mitä osaat" to "what can you do",
        "mitä sinä osaat" to "what can you do",
        "mitä voit tehdä" to "what can you do",
        "mita osaat" to "what can you do",
        "kuka olet" to "who are you",
        "kuka sinä olet" to "who are you",
        "kiitos" to "thanks",
        "kiitos paljon" to "thank you",
        "kiitti" to "thanks",
        "ole hyvä" to "please",
        "ole kiltti" to "please",
        "olkaa hyvä" to "please",
        "vikki" to "wick",

        // Newer requests.
        "haku*" to "search",
        "hakea" to "search",
        "haen" to "search",
        "hae raamatu*" to "search the bible",
        "etsi raamatu*" to "search the bible",
        "hae laulu*" to "search for a song",
        "etsi laulu*" to "find a song",
        "etsi jae" to "find a verse",
        "etsi jake*" to "find a verse",
        "numero" to "number",
        "numerolla" to "by number",
        "nimellä" to "by title",
        "nimella" to "by title",
        "nimeltä" to "called",
        "nimelta" to "called",
        "suosik*" to "favorite",
        "tämä laulu" to "this song",
        "tama laulu" to "this song",
        "tämän laulun" to "this song",
        "tälle laululle" to "this song",
        "talle laululle" to "this song",
        "tähän lauluun" to "this song",
        "jokainen laulu" to "each song",
        "jokaiselle laululle" to "each song",
        "oma tausta*" to "own background",
        "oman tausta*" to "own background",
        "omat taustat" to "own background",
        "useita jakeita" to "several verses",
        "monta jaetta" to "several verses",
        "useampi jae" to "more than one verse",
        "useamman jakeen" to "more than one verse",
        "jaeväli*" to "verse range",
        "jaevali*" to "verse range",
        "kokonainen kohta" to "whole passage",
        "historia*" to "history",
        "mitä juuri näytimme" to "what did we just show",
        "mita juuri naytimme" to "what did we just show",
        "mitä näytimme" to "what did we show",
        "äskettäin näytetyt" to "recently shown",
        "viimeisimmät jakeet" to "recent verses",
        "aiemmin näytetyt" to "shown before",
        "ristiviittau*" to "cross references",
        "aiheeseen liittyvät jakeet" to "related verses",
        "liittyvät jakeet" to "related verses",
        "liittyvat jakeet" to "related verses",
        "samankaltaiset jakeet" to "similar verses",
        "rinnakkaiskoh*" to "parallel passages",
        "nettiosoite*" to "url",
        "verkko-osoite*" to "url",
        "internetsivu*" to "internet page",
        "tilasto*" to "statistics",
        "kuinka monta kertaa" to "how many times",
        "montako kertaa" to "how many times",
        "kuinka usein" to "how often",
        "miten usein" to "how often",
        "laulujen käyttö" to "song usage",
        "lauluraport*" to "song report",
        "ccli-raport*" to "ccli report",
        "ohjaa puhelime*" to "control it from my phone",
        "puhelimesta" to "from my phone",
        "puhelimella" to "from my phone",
        "puhelimellani" to "on my phone",
        "yhdistä puhelin" to "connect my phone",
        "yhdista puhelin" to "connect my phone",
        "kauko-ohjaus*" to "remote control",
        "qr-koodi*" to "qr code",
        "qr koodi*" to "qr code",
        "planning center*" to "planning center",
        "planningcenter*" to "planning center",
        "openlp*" to "openlp",
        "songbeamer*" to "songbeamer",
        "opensong*" to "opensong",
        "easyslides*" to "easyslides",
        "videopsalm*" to "videopsalm",
        "minuut*" to "minutes",
        "ilmoita" to "announce",
        "ilmoita:" to "announce :",
        "kuuluta" to "announce",
        "kuuluta:" to "announce :",
        "laita" to "put",
        "ohjelmaan" to "to the schedule",
        "aikatauluun" to "to the schedule",
        "ohjelmassa" to "in the schedule",
        "aikataulussa" to "in the schedule",
        "ohjelmasta" to "from the schedule",
        "lisää laulu*" to "add a song",
        "lisaa laulu*" to "add a song",
        "lisään laulu*" to "add a song",
        "lisätä laulu*" to "add a song",
        "seuraava kohta" to "next item",
        "edellinen kohta" to "previous item",
        "ohjelmakoh*" to "item",
        "mitä on livenä" to "what's live",
        "mita on livena" to "what's live",
        "mitä on ruudulla" to "what is on screen",
        "mitä näytetään" to "what's showing",
        "mitä näkyy" to "what's showing",
        "onko mitään livenä" to "is anything live",
        "valokuv*" to "photo",
        "kuvia" to "picture",
        "kuvien" to "picture",
        "pdf:*" to "pdf",
        "pdf-tiedosto*" to "pdf",
        "toistan" to "play",
        "miten teen alapalk*" to "how do i make a lower third",
        "koko näytö*" to "full screen",
        "koko nayto*" to "full screen",
        "pikanäppäim*" to "shortcut",
        "pikanappaim*" to "shortcut",
        "mikä versio" to "what version",
        "mika versio" to "what version",
        "versio*" to "version",
        "sovelluksen versio" to "app version",
        "tarkista päivity*" to "check for updates",
        "tarkista paivity*" to "check for updates",
        "onko päivityksiä" to "is there an update",
        "onko päivitystä" to "is there an update",
        "onko uutta versiota" to "is there an update",
        "uusin versio*" to "latest version",
        "viimeisin versio*" to "latest version",
        "ajan tasalla" to "up to date",
        "komento*" to "commands",
        "komennot" to "commands",
        "komentolista*" to "list of commands",
        "komentojen lista" to "list of commands",
        "mitä voin sanoa" to "what can i say",
        "mita voin sanoa" to "what can i say",
        "mitä voin kirjoittaa" to "what can i type",
        "mitä voin kysyä" to "what can i ask",
        "mitä ymmärrät" to "what do you understand",
        "mita ymmarrat" to "what do you understand",

        // Look requests.
        "muutan" to "change",
        "muutetaan" to "change",
        "siirrän" to "move",
        "siirran" to "move",
        "laulun sanoja" to "lyrics",
        "laulun sanoihin" to "lyrics",
        "laulun sanojen" to "lyrics",
        "laulun sanoissa" to "lyrics",
        "laulujen sanoja" to "lyrics",
        "kirjoitusvirh*" to "typo",
        "lyöntivirh*" to "typo",
        "lyontivirh*" to "typo",
        "lihavoi*" to "bold",
        "kursivoi*" to "italic",
        "kursiivi*" to "italic",
        "alleviiva*" to "underline",
        "ääriviiva*" to "outline",
        "aariviiva*" to "outline",
        "pudotusvarjo*" to "drop shadow",
        "varjo*" to "shadow",
        "marginaal*" to "margins",
        "reunukset" to "margins",
        "reunuksia" to "margins",
        "yläreuna*" to "top",
        "ylareuna*" to "top",
        "ylhäälle" to "top",
        "ylhaalle" to "top",
        "ylhäällä" to "top",
        "ylhaalla" to "top",
        "alareuna*" to "bottom",
        "alhaalle" to "bottom",
        "alhaalla" to "bottom",
        "keskelle" to "middle",
        "keskellä" to "middle",
        "keskella" to "middle",
        "vasemmalle" to "left",
        "vasempaan" to "left",
        "oikealle" to "right",
        "keskitä" to "center",
        "keskita" to "center",
        "keskitys*" to "center",
        "keskitetty*" to "centered",
        "tasaus*" to "alignment",
        "tasauk*" to "alignment",
        "sijainti*" to "position",
        "sijainni*" to "position",
        "pystysuun*" to "vertically",
        "laulun loppu*" to "end of song",
        "laulun lopu*" to "end of song",
        "loppumerk*" to "end marker",
        "laulun otsik*" to "song title",
        "otsik*" to "title",
        "laulun numero*" to "song number",
        "raamatunjake*" to "bible verses",
        "raamatunviit*" to "bible reference",
        "viite" to "reference",
        "viitte*" to "reference",
        "ulkoasu*" to "appearance",
        "ulkonäkö*" to "look",
        "ulkonako*" to "look",
        "tyyli*" to "style",
        "muotoil*" to "format",
        "väri" to "color",
        "värin" to "color",
        "väriä" to "color",
        "värit" to "color",
        "värejä" to "color",

        // The help table's own examples.
        "vanhemp*" to "parents",
    ),
)
