package org.churchpresenter.helper.intent.glossary

internal val FRENCH = Glossary(
    "fr",
    listOf(
        // Asking where, or how.
        "où" to "where",
        "où est" to "where",
        "où se trouve" to "where",
        "comment je" to "how do i",
        "comment puis-je" to "how can i",
        "comment puis je" to "how can i",
        "comment peut-on" to "how can i",
        "comment faire pour" to "how do i",
        "comment faire" to "how do i",
        "comment on" to "how do i",
        "comment" to "how do i",
        "je ne trouve pas" to "can't find",
        "je trouve pas" to "can't find",
        "je n'arrive pas à trouver" to "can't find",
        "impossible de trouver" to "can't find",
        "montre-moi" to "show me",
        "montre moi" to "show me",
        "montrez-moi" to "show me",
        "montrez moi" to "show me",

        // Doing.
        "affiche*" to "show",
        "afficher" to "show",
        "montre" to "show",
        "montrer" to "show",
        "montrez" to "show",
        "projette*" to "show",
        "projeter" to "show",
        "mets" to "put",
        "mettre" to "put",
        "mettez" to "put",
        "ouvr*" to "open",
        "ouvre" to "open",
        "va à" to "go to",
        "va a" to "go to",
        "va sur" to "go to",
        "aller à" to "go to",
        "aller a" to "go to",
        "allez à" to "go to",
        "passe à" to "switch to",
        "passe a" to "switch to",
        "passer à" to "switch to",
        "passez à" to "switch to",
        "bascule vers" to "switch to",
        "cherche*" to "find",
        "trouve" to "find",
        "trouver" to "find",
        "lis" to "read",
        "lire" to "read",
        "lisez" to "read",
        "fais" to "make",
        "faire" to "make",
        "faites" to "make",
        "rends" to "make",
        "rendre" to "make",
        "crée" to "create",
        "creer" to "create",
        "créer" to "create",
        "créez" to "create",
        "ajoute*" to "add",
        "ajouter" to "add",
        "charger" to "load",
        "chargez" to "load",
        "importe" to "import",
        "importer" to "import",
        "importez" to "import",
        "télécharg*" to "download",
        "telecharg*" to "download",
        "installe" to "install",
        "installer" to "install",
        "installez" to "install",
        "choisi*" to "choose",
        "sélectionne*" to "choose",
        "selectionne*" to "choose",
        "configurer" to "set up",
        "configurez" to "set up",
        "paramétrer" to "set up",
        "parametrer" to "set up",
        "connecte" to "connect",
        "connecter" to "connect",
        "connectez" to "connect",
        "branche" to "connect",
        "brancher" to "connect",
        "attribue*" to "assign",
        "assigne" to "assign",
        "assigner" to "assign",
        "masque*" to "hide",
        "masquer" to "hide",
        "cacher" to "hide",
        "cachez" to "hide",
        "enlève" to "remove",
        "enleve" to "remove",
        "enlever" to "remove",
        "retirer" to "remove",
        "retirez" to "remove",
        "arrête*" to "stop",
        "arrete*" to "stop",
        "supprim*" to "delete",
        "efface*" to "clear",
        "effacer" to "clear",
        "vider" to "clear",
        "vide l'écran" to "clear",
        "vide l'ecran" to "clear",
        "éteins l'écran" to "black out",
        "eteins l'ecran" to "black out",
        "écran vide" to "blank",
        "ecran vide" to "blank",
        "écran blanc" to "blank",
        "annule*" to "undo",
        "annuler" to "undo",
        "comme avant" to "undo",
        "diffuser en direct" to "go live",
        "passer en direct" to "go live",
        "mettre en direct" to "go live",
        "en direct" to "go live",
        "à l'antenne" to "go live",
        "allume*" to "turn on",
        "activer" to "turn on",
        "activez" to "turn on",
        "éteins" to "turn off",
        "eteins" to "turn off",
        "éteindre" to "turn off",
        "eteindre" to "turn off",
        "désactive*" to "turn off",
        "desactive*" to "turn off",
        "suivant*" to "next",
        "avance*" to "forward",
        "précédent*" to "previous",
        "precedent*" to "previous",
        "retour" to "back",
        "recule*" to "back",
        "augmente*" to "increase",
        "plus grand*" to "bigger",
        "plus gros*" to "bigger",
        "agrandi*" to "enlarge",
        "diminue*" to "decrease",
        "plus petit*" to "smaller",
        "rétréci*" to "shrink",
        "retreci*" to "shrink",
        "réduire" to "reduce",
        "reduire" to "reduce",
        "réduis" to "reduce",
        "reduis" to "reduce",
        "convertisseur*" to "converter",
        "converti*" to "convert",
        "transfère*" to "transfer",
        "transfere*" to "transfer",
        "transférer" to "transfer",
        "migrer" to "migrate",
        "modifie*" to "edit",
        "modifier" to "edit",
        "édite*" to "edit",
        "éditer" to "edit",
        "changer" to "change",
        "changez" to "change",
        "renomme*" to "rename",
        "corrige*" to "fix",
        "répare*" to "fix",
        "repare*" to "fix",
        "organise*" to "organize",
        "compare*" to "compare",
        "traduction*" to "translation",
        "tradui*" to "translate",
        "planifie*" to "plan",
        "prévoir" to "plan",
        "automatise*" to "automate",
        "automatiquement" to "automatically",
        "identifie*" to "identify",
        "numérote*" to "number the",
        "numerote*" to "number the",

        // Too small, too big, not working.
        "trop petit*" to "too small",
        "difficile à lire" to "hard to read",
        "difficile a lire" to "hard to read",
        "illisible*" to "hard to read",
        "on ne voit pas" to "hard to read",
        "on voit pas" to "hard to read",
        "je n'arrive pas à lire" to "can't read",
        "trop grand*" to "too big",
        "trop gros*" to "too big",
        "ne rentre pas" to "doesn't fit",
        "ça ne rentre pas" to "doesn't fit",
        "ne marche pas" to "not working",
        "marche pas" to "not working",
        "ne fonctionne pas" to "not working",
        "fonctionne pas" to "not working",
        "ne s'affiche pas" to "not showing",
        "s'affiche pas" to "not showing",
        "rien ne s'affiche" to "nothing shows",
        "n'affiche rien" to "nothing shows",
        "il n'y a rien" to "nothing shows",
        "écran noir" to "screen is black",
        "ecran noir" to "screen is black",
        "pas de signal" to "no signal",
        "aucun signal" to "no signal",
        "pas d'image" to "no picture",
        "aucune image" to "no picture",
        "quel écran" to "which screen",
        "quel ecran" to "which screen",
        "quel moniteur" to "which monitor",
        "quel projecteur" to "which projector",

        // What is on screen.
        "arrière-plan*" to "background",
        "arriere-plan*" to "background",
        "arrière plan*" to "background",
        "arriere plan*" to "background",
        "fond d'écran" to "background",
        "fond d'ecran" to "background",
        "le fond" to "background",
        "du fond" to "background",
        "un fond" to "background",
        "fonds" to "backgrounds",
        "paroles" to "lyrics",
        "cantique des cantiques" to "cantique des cantiques",
        "cantique" to "song",
        "cantiques" to "songs",
        "chanson*" to "song",
        "chant" to "song",
        "chants" to "songs",
        "hymne*" to "hymn",
        "louange*" to "worship",
        "adoration" to "worship",
        "écriture*" to "scripture",
        "ecriture*" to "scripture",
        "verset*" to "verse",
        "chapitre*" to "chapter",
        "taille de police" to "font size",
        "taille du texte" to "text size",
        "la police" to "font",
        "de police" to "font",
        "polices" to "fonts",
        "taille*" to "size",
        "texte*" to "text",
        "lettre*" to "letters",
        "mots" to "words",
        "diaporama*" to "slideshow",
        "diapositive*" to "slide",
        "diapo*" to "slide",
        "présentation*" to "presentation",
        "presentation*" to "presentation",
        "vidéo*" to "video",
        "média*" to "media",
        "medias" to "media",
        "tiers inférieur" to "lower third",
        "tiers inferieur" to "lower third",
        "bandeau inférieur" to "lower third",
        "bandeau inferieur" to "lower third",
        "bandeau défilant" to "ticker",
        "bandeau defilant" to "ticker",
        "bandeau*" to "lower third",
        "synthé*" to "name strap",
        "nom et fonction" to "name and title",
        "nom et titre" to "name and title",
        "annonce*" to "announcement",
        "texte défilant" to "ticker",
        "texte defilant" to "ticker",
        "garderie" to "nursery",
        "salle des enfants" to "kids room",
        "compte à rebours" to "countdown",
        "compte a rebours" to "countdown",
        "minuteur*" to "timer",
        "minuterie*" to "timer",
        "chronomètre*" to "stopwatch",
        "chronometre*" to "stopwatch",
        "horloge*" to "clock",
        "heure actuelle" to "current time",
        "l'heure" to "time",
        "heure" to "time",
        "accord" to "chord",
        "accords" to "chords",
        "langue*" to "language",
        "bilingue*" to "bilingual",
        "dans une autre langue" to "another language",
        "une autre langue" to "another language",
        "autre langue" to "another language",
        "deuxième langue" to "second language",
        "deuxieme langue" to "second language",
        "seconde langue" to "second language",
        "en deux langues" to "two languages",
        "deux langues" to "two languages",

        // Screens and outputs.
        "écran principal" to "main screen",
        "ecran principal" to "main screen",
        "plein écran" to "full screen",
        "plein ecran" to "full screen",
        "deuxième écran" to "second screen",
        "deuxieme ecran" to "second screen",
        "second écran" to "second screen",
        "second ecran" to "second screen",
        "écran*" to "screen",
        "ecran*" to "screen",
        "vidéoprojecteur*" to "projector",
        "videoprojecteur*" to "projector",
        "projecteur*" to "projector",
        "moniteur de scène" to "stage monitor",
        "moniteur de scene" to "stage monitor",
        "écran de scène" to "stage monitor",
        "ecran de scene" to "stage monitor",
        "retour scène" to "stage monitor",
        "retour scene" to "stage monitor",
        "retour de scène" to "stage monitor",
        "moniteur*" to "monitor",
        "affichage*" to "display",
        "sortie*" to "output",
        "fenêtre de sortie" to "output window",
        "fenetre de sortie" to "output window",
        "scène*" to "stage",
        "la scene" to "stage",
        "sur scene" to "stage",
        "mise en page" to "layout",
        "disposition*" to "layout",
        "agencement*" to "arrangement",
        "envoie*" to "send",
        "envoyer" to "send",
        "envoyez" to "send",
        "aperçu*" to "preview",
        "apercu*" to "preview",
        "prévisualis*" to "preview",
        "previsualis*" to "preview",
        "ce qui est à l'écran" to "what is on screen",
        "ce qui est a l'ecran" to "what is on screen",
        "profil*" to "profile",
        "diffusion*" to "stream",
        "télé" to "tv",
        "tele" to "tv",
        "téléviseur*" to "tv",
        "televiseur*" to "tv",

        // Pages, tabs and tools.
        "paramètre*" to "settings",
        "parametre*" to "settings",
        "réglage*" to "settings",
        "reglage*" to "settings",
        "préférence*" to "preferences",
        "assistant de configuration" to "setup wizard",
        "prise en main" to "getting started",
        "recommencer" to "start over",
        "tout recommencer" to "start over",
        "raccourci*" to "shortcut",
        "touches de raccourci" to "hotkeys",
        "clavier*" to "keyboard",
        "onglet*" to "tab",
        "bibliothèque de chants" to "song library",
        "bibliotheque de chants" to "song library",
        "bibliothèque de cantiques" to "song library",
        "bibliothèque*" to "library",
        "bibliotheque*" to "library",
        "site web" to "website",
        "site internet" to "website",
        "navigateur*" to "browser",
        "dictionnaire*" to "dictionary",
        "caméra*" to "camera",
        "canevas" to "canvas",
        "serveur*" to "server",
        "à distance" to "remote",
        "a distance" to "remote",
        "télécommande*" to "remote",
        "telecommande*" to "remote",
        "téléphone*" to "phone",
        "tablette*" to "tablet",
        "intégration*" to "integrations",

        // Services and planning.
        "ordre du culte" to "order of service",
        "déroulement du culte" to "order of service",
        "deroulement du culte" to "order of service",
        "programme du culte" to "order of service",
        "liturgie" to "order of service",
        "culte*" to "service",
        "réunion*" to "meeting",
        "dimanche*" to "sunday",
        "calendrier*" to "calendar",
        "programme*" to "schedule",
        "liste de lecture" to "playlist",
        "chaque dimanche" to "every sunday",
        "tous les dimanches" to "every sunday",
        "chaque semaine" to "every week",
        "toutes les semaines" to "every week",
        "hebdomadaire*" to "weekly",
        "mensuel*" to "monthly",
        "répète*" to "repeat",
        "repete*" to "repeat",
        "répéter" to "repeat",
        "récurrent*" to "recurring",
        "recurrent*" to "recurring",
        "modèle*" to "template",
        "modele*" to "template",

        // Many, all, both.
        "tout" to "all",
        "tous" to "all",
        "toutes" to "all",
        "toute" to "all",
        "partout" to "everything",
        "les deux" to "both",
        "plusieurs" to "several",
        "beaucoup" to "many",
        "à la fois" to "at once",
        "a la fois" to "at once",
        "en même temps" to "at once",
        "en meme temps" to "at once",
        "pour ce culte" to "this service",
        "pour aujourd'hui" to "for today",
        "temporairement" to "temporarily",
        "pour l'instant" to "for now",
        "pour le moment" to "for now",

        // Languages, by name.
        "anglais*" to "english",
        "espagnol*" to "spanish",
        "russe*" to "russian",
        "ukrainien*" to "ukrainian",
        "biélorusse" to "belarusian",
        "allemand*" to "german",
        "français*" to "french",
        "francais*" to "french",
        "polonais*" to "polish",
        "portugais*" to "portuguese",
        "italien*" to "italian",
        "néerlandais*" to "dutch",
        "neerlandais*" to "dutch",
        "hollandais*" to "dutch",
        "roumain*" to "romanian",
        "tchèque*" to "czech",
        "hongrois*" to "hungarian",
        "grec" to "greek",
        "grecque" to "greek",
        "turc" to "turkish",
        "turque" to "turkish",
        "arabe*" to "arabic",
        "hébreu" to "hebrew",
        "hebreu" to "hebrew",
        "chinois*" to "chinese",
        "japonais*" to "japanese",
        "coréen*" to "korean",
        "coreen*" to "korean",
        "vietnamien*" to "vietnamese",

        // Colors.
        "bleu marine" to "navy",
        "bleu clair" to "light blue",
        "bleu ciel" to "light blue",
        "bleu*" to "blue",
        "noir*" to "black",
        "blanc*" to "white",
        "gris*" to "grey",
        "argenté*" to "silver",
        "argente*" to "silver",
        "rouge*" to "red",
        "bordeaux" to "maroon",
        "cramoisi*" to "crimson",
        "jaune*" to "yellow",
        "doré*" to "gold",
        "vert citron" to "lime",
        "vert" to "green",
        "verte" to "green",
        "verts" to "green",
        "vertes" to "green",
        "sarcelle" to "teal",
        "rose*" to "pink",
        "marron*" to "brown",
        "crème" to "cream",
        "creme" to "cream",
        "foncé*" to "dark",
        "fonce*" to "dark",
        "sombre*" to "dark",
        "clair*" to "light",

        // Talking to the helper.
        "bonjour" to "hello",
        "bonsoir" to "hello",
        "salut" to "hello",
        "coucou" to "hello",
        "aide*" to "help",
        "au secours" to "help",
        "qu'est-ce que tu sais faire" to "what can you do",
        "qu'est-ce que tu peux faire" to "what can you do",
        "que sais-tu faire" to "what can you do",
        "que peux-tu faire" to "what can you do",
        "tu sais faire quoi" to "what can you do",
        "tu fais quoi" to "what do you do",
        "qui es-tu" to "who are you",
        "qui es tu" to "who are you",
        "t'es qui" to "who are you",
        "merci" to "thanks",
        "merci beaucoup" to "thank you",
        "s'il te plaît" to "please",
        "s'il te plait" to "please",
        "s'il vous plaît" to "please",
        "s'il vous plait" to "please",
        "stp" to "please",
        "svp" to "please",
        "wik" to "wick",

        // Newer requests.
        "chercher" to "search",
        "cherche* dans" to "search in",
        "cherche* un" to "search a",
        "cherche* une" to "search a",
        "recherch*" to "search",
        "un cantique" to "a song",
        "un chant" to "a song",
        "une chanson" to "a song",
        "le cantique" to "the song",
        "le chant" to "the song",
        "la chanson" to "the song",
        "un verset" to "a verse",
        "le verset" to "the verse",
        "versets" to "verses",
        "numéro du cantique" to "song number",
        "numero du cantique" to "song number",
        "numéro du chant" to "song number",
        "numero du chant" to "song number",
        "par numéro" to "by number",
        "par numero" to "by number",
        "par titre" to "by title",
        "numéro*" to "number",
        "numero*" to "number",
        "appelé*" to "called",
        "intitulé*" to "named",
        "intitule*" to "named",
        "favori*" to "favorite",
        "préféré*" to "favorite",
        "prefere*" to "favorite",
        "ce cantique" to "this song",
        "ce chant" to "this song",
        "cette chanson" to "this song",
        "chaque cantique" to "each song",
        "chaque chant" to "each song",
        "chaque chanson" to "each song",
        "par cantique" to "per song",
        "son propre fond" to "its own background",
        "son propre arrière-plan" to "its own background",
        "son propre arriere-plan" to "its own background",
        "propre fond" to "own background",
        "son propre" to "its own",
        "sa propre" to "its own",
        "plus d'un verset" to "more than one verse",
        "plage de versets" to "range of verses",
        "un passage" to "a passage",
        "passage entier" to "whole passage",
        "historique*" to "history",
        "vient d'afficher" to "what did we just show",
        "vient de montrer" to "what did we just show",
        "vient de projeter" to "what did we just show",
        "versets récents" to "recent verses",
        "versets recents" to "recent verses",
        "références croisées" to "cross references",
        "references croisees" to "cross references",
        "référence croisée" to "cross reference",
        "reference croisee" to "cross reference",
        "renvois" to "cross references",
        "versets liés" to "related verses",
        "versets lies" to "related verses",
        "versets connexes" to "related verses",
        "passages liés" to "related passages",
        "passages lies" to "related passages",
        "passages parallèles" to "parallel passages",
        "passages paralleles" to "parallel passages",
        "versets similaires" to "similar verses",
        "page web" to "web page",
        "page internet" to "internet page",
        "statistique*" to "statistics",
        "combien de fois" to "how many times",
        "à quelle fréquence" to "how often",
        "a quelle frequence" to "how often",
        "rapport des cantiques" to "song report",
        "rapport des chants" to "song report",
        "rapport de chants" to "song report",
        "utilisation des cantiques" to "song usage",
        "utilisation des chants" to "song usage",
        "depuis mon téléphone" to "from my phone",
        "depuis mon telephone" to "from my phone",
        "depuis mon portable" to "from my phone",
        "depuis mon mobile" to "from my phone",
        "depuis le téléphone" to "from the phone",
        "depuis le telephone" to "from the phone",
        "sur mon téléphone" to "on my phone",
        "sur mon telephone" to "on my phone",
        "sur mon portable" to "on my phone",
        "connect* mon téléphone" to "connect my phone",
        "connect* mon telephone" to "connect my phone",
        "connect* mon portable" to "connect my phone",
        "contrôle à distance" to "remote control",
        "controle a distance" to "remote control",
        "code qr" to "qr code",
        "le contrôler depuis" to "control it from",
        "le controler depuis" to "control it from",
        "contrôle* depuis" to "control it from",
        "controle* depuis" to "control it from",
        "piloter depuis" to "control it from",
        "minute*" to "minutes",
        "annonce :" to "announce",
        "annonce:" to "announce",
        "annoncez" to "announce",
        "annoncer" to "announce",
        "annoncez :" to "announce",
        "annoncez:" to "announce",
        "au programme" to "to the schedule",
        "dans le programme" to "in the schedule",
        "du programme" to "from the schedule",
        "aller à la" to "go to the",
        "aller a la" to "go to the",
        "aller au" to "go to the",
        "va à la" to "go to the",
        "va a la" to "go to the",
        "va au" to "go to the",
        "allez à la" to "go to the",
        "allez au" to "go to the",
        "élément*" to "item",
        "qu'est-ce qui est en direct" to "what's live",
        "qu'est ce qui est en direct" to "what's live",
        "qu'est-ce qui est à l'écran" to "what is on screen",
        "qu'est ce qui est a l'ecran" to "what is on screen",
        "qu'est-ce qui passe" to "what's showing",
        "qu'est ce qui passe" to "what's showing",
        "qu'est-ce qui s'affiche" to "what's showing",
        "qu'est ce qui s'affiche" to "what's showing",
        "quoi en direct" to "what's live",
        "y a-t-il quelque chose en direct" to "is anything live",
        "quelque chose en direct" to "is anything live",
        "quelle version" to "what version",
        "quel version" to "what version",
        "quelle est la version" to "what version",
        "version de l'application" to "app version",
        "version de l'appli" to "app version",
        "vérifier les mises à jour" to "check for updates",
        "verifier les mises a jour" to "check for updates",
        "chercher des mises à jour" to "check for updates",
        "chercher des mises a jour" to "check for updates",
        "y a-t-il une mise à jour" to "is there an update",
        "y a-t-il une mise a jour" to "is there an update",
        "une mise à jour" to "an update",
        "une mise a jour" to "an update",
        "dernière version" to "latest version",
        "derniere version" to "latest version",
        "nouvelle version" to "newer version",
        "est à jour" to "up to date",
        "est a jour" to "up to date",
        "suis à jour" to "up to date",
        "suis a jour" to "up to date",
        "commandes" to "commands",
        "commande" to "command",
        "liste des commandes" to "list of commands",
        "que puis-je dire" to "what can i say",
        "qu'est-ce que je peux dire" to "what can i say",
        "qu'est ce que je peux dire" to "what can i say",
        "que puis-je taper" to "what can i type",
        "que puis-je écrire" to "what can i type",
        "qu'est-ce que je peux taper" to "what can i type",
        "qu'est ce que je peux taper" to "what can i type",
        "qu'est-ce que je peux écrire" to "what can i type",
        "qu'est-ce que tu comprends" to "what do you understand",
        "qu'est ce que tu comprends" to "what do you understand",
        "que comprends-tu" to "what do you understand",

        // Look requests.
        "les paroles" to "the lyrics",
        "des paroles" to "the lyrics",
        "aux paroles" to "to the lyrics",
        "faute de frappe" to "typo",
        "coquille*" to "typo",
        "déplace*" to "move",
        "deplace*" to "move",
        "placer" to "put",
        "gras" to "bold",
        "en gras" to "bold",
        "italique*" to "italic",
        "soulign*" to "underline",
        "contour*" to "outline",
        "ombre*" to "shadow",
        "marge*" to "margins",
        "bords" to "edges",
        "en haut" to "at the top",
        "haut" to "top",
        "en bas" to "at the bottom",
        "bas" to "bottom",
        "milieu" to "middle",
        "au centre" to "center",
        "centre*" to "center",
        "à gauche" to "left",
        "a gauche" to "left",
        "gauche" to "left",
        "à droite" to "right",
        "a droite" to "right",
        "droite" to "right",
        "aligne*" to "align",
        "alignement*" to "alignment",
        "positionne*" to "position",
        "police de caractères" to "typeface",
        "police de caracteres" to "typeface",
        "typographie" to "typeface",
        "apparence" to "appearance",
        "l'apparence" to "the appearance",
        "l'aspect" to "the look",
        "styliser" to "style",
        "mise en forme" to "formatting",
        "couleur*" to "color",
        "titre*" to "title",
        "titre du cantique" to "song title",
        "titre du chant" to "song title",
        "référence*" to "reference",
        "la référence" to "the reference",
        "biblique*" to "bible",
        "marqueur de fin" to "end marker",
        "fin du cantique" to "end of song",
        "fin de cantique" to "end of song",
        "fin du chant" to "end of song",
        "fin de chant" to "end of song",

        // The help table's own examples.
        "fond" to "background",
        "l'horloge" to "the clock",
        "horloge" to "clock",
        "comment faire un" to "how do i make a",
        "comment faire une" to "how do i make a",
        "par lot" to "batch",
        "par lots" to "batch",
    ),
)
