package org.churchpresenter.helper.intent.glossary

internal val GERMAN = Glossary(
    "de",
    listOf(
        // Asking where, or how.
        "wo" to "where",
        "wohin" to "where",
        "wo finde ich" to "where",
        "wo ist" to "where",
        "wie kann ich" to "how can i",
        "wie könnte ich" to "how can i",
        "wie mache ich" to "how do i",
        "wie geht das" to "how do i",
        "wie" to "how do i",
        "finde nicht" to "can't find",
        "nicht finden" to "can't find",
        "zeig mir" to "show me",
        "zeige mir" to "show me",
        "zeigen sie mir" to "show me",

        // Doing.
        "zeig*" to "show",
        "einblend*" to "show",
        "anzeig*" to "display",
        "öffne*" to "open",
        "oeffne*" to "open",
        "geh zu" to "go to",
        "gehe zu" to "go to",
        "gehe zum" to "go to",
        "gehe zur" to "go to",
        "wechsel zu" to "switch to",
        "wechsle zu" to "switch to",
        "wechsle zum" to "switch to",
        "wechsle zur" to "switch to",
        "such*" to "find",
        "finde" to "find",
        "finden" to "find",
        "lies" to "read",
        "vorlesen" to "read",
        "mach*" to "make",
        "erstell*" to "create",
        "erzeug*" to "create",
        "hinzufüg*" to "add",
        "hinzufueg*" to "add",
        "füge" to "add",
        "fuege" to "add",
        "lade" to "load",
        "laden" to "load",
        "hochlad*" to "load",
        "importier*" to "import",
        "herunterlad*" to "download",
        "runterlad*" to "download",
        "installier*" to "install",
        "auswähl*" to "choose",
        "auswaehl*" to "choose",
        "wähle" to "choose",
        "waehle" to "choose",
        "wählen" to "choose",
        "einricht*" to "set up",
        "konfigurier*" to "set up",
        "verbind*" to "connect",
        "zuweis*" to "assign",
        "zuordn*" to "assign",
        "ausblend*" to "hide",
        "versteck*" to "hide",
        "stopp*" to "stop",
        "anhalt*" to "stop",
        "beend*" to "stop",
        "lösch*" to "delete",
        "loesch*" to "delete",
        "entfern*" to "remove",
        "leere" to "clear",
        "leeren" to "clear",
        "schwarz schalten" to "black out",
        "schwarzbild" to "black out",
        "abdunkeln" to "black out",
        "leerer bildschirm" to "blank",
        "rückgängig*" to "undo",
        "rueckgaengig*" to "undo",
        "live gehen" to "go live",
        "live schalten" to "go live",
        "auf sendung" to "go live",
        "einschalt*" to "turn on",
        "anschalt*" to "turn on",
        "ausschalt*" to "turn off",
        "umschalt*" to "toggle",
        "nächst*" to "next",
        "naechst*" to "next",
        "weiter" to "next",
        "vorwärts" to "forward",
        "vorwaerts" to "forward",
        "vorherig*" to "previous",
        "zurück" to "back",
        "zurueck" to "back",
        "vergrößer*" to "increase",
        "vergroesser*" to "increase",
        "vergrösser*" to "increase",
        "größer" to "bigger",
        "groesser" to "bigger",
        "grösser" to "bigger",
        "verkleiner*" to "decrease",
        "kleiner" to "smaller",
        "konvertier*" to "convert",
        "konverter*" to "converter",
        "übertrag*" to "transfer",
        "uebertrag*" to "transfer",
        "migrier*" to "migrate",
        "bearbeit*" to "edit",
        "änder*" to "change",
        "aender*" to "change",
        "umbenenn*" to "rename",
        "reparier*" to "fix",
        "beheb*" to "fix",
        "organisier*" to "organize",
        "aufräum*" to "clean up",
        "aufraeum*" to "clean up",
        "vergleich*" to "compare",
        "übersetz*" to "translate",
        "uebersetz*" to "translate",
        "planen" to "plan",
        "einplan*" to "plan",
        "automatisier*" to "automate",
        "automatisch*" to "automatically",
        "erkenn*" to "identify",
        "nummerier*" to "number the",

        // Too small, too big, not working.
        "zu klein" to "too small",
        "zu winzig" to "too small",
        "schwer zu lesen" to "hard to read",
        "schlecht lesbar" to "hard to read",
        "kaum lesbar" to "hard to read",
        "nicht lesbar" to "hard to read",
        "unleserlich" to "hard to read",
        "zu groß" to "too big",
        "zu gross" to "too big",
        "passt nicht" to "doesn't fit",
        "funktioniert nicht" to "not working",
        "geht nicht" to "not working",
        "zeigt nicht" to "not showing",
        "wird nicht angezeigt" to "not showing",
        "zeigt nichts" to "nothing shows",
        "nichts zu sehen" to "nothing shows",
        "schwarzer bildschirm" to "screen is black",
        "bildschirm ist schwarz" to "screen is black",
        "kein signal" to "no signal",
        "kein bild" to "no picture",
        "welcher bildschirm" to "which screen",
        "welcher monitor" to "which monitor",
        "welcher beamer" to "which projector",
        "welcher projektor" to "which projector",

        // What is on screen.
        "hintergrund*" to "background",
        "liedtext*" to "lyrics",
        "songtext*" to "lyrics",
        "lied*" to "song",
        "kirchenlied*" to "hymn",
        "choral*" to "hymn",
        "lobpreis*" to "worship",
        "anbetung*" to "worship",
        "bibel*" to "bible",
        "heilige schrift" to "scripture",
        "bibelstelle*" to "verse",
        "bibelvers*" to "verse",
        "vers" to "verse",
        "versen" to "verse",
        "kapitel*" to "chapter",
        "schriftgröße*" to "font size",
        "schriftgroesse*" to "font size",
        "textgröße*" to "text size",
        "textgroesse*" to "text size",
        "schriftart*" to "font",
        "schrift*" to "font",
        "größe" to "size",
        "groesse" to "size",
        "grösse" to "size",
        "text*" to "text",
        "wörter" to "words",
        "woerter" to "words",
        "buchstaben" to "letters",
        "diashow*" to "slideshow",
        "dia" to "slide",
        "dias" to "slide",
        "folie*" to "slide",
        "foto*" to "photo",
        "bilder" to "picture",
        "bild*" to "picture",
        "alben" to "album",
        "präsentation*" to "presentation",
        "praesentation*" to "presentation",
        "film*" to "movie",
        "medien" to "media",
        "unteres drittel" to "lower third",
        "unteren drittel" to "lower third",
        "bauchbinde*" to "lower third",
        "namenseinblendung*" to "name strap",
        "name und titel" to "name and title",
        "ankündigung*" to "announcement",
        "ankuendigung*" to "announcement",
        "abkündigung*" to "announcement",
        "abkuendigung*" to "announcement",
        "bekanntmachung*" to "announcement",
        "laufschrift*" to "ticker",
        "lauftext*" to "ticker",
        "kinderraum*" to "kids room",
        "kinderbetreuung*" to "kids room",
        "kindergottesdienst*" to "kids room",
        "rückwärtszähler*" to "countdown",
        "herunterzählen" to "countdown",
        "stoppuhr*" to "stopwatch",
        "uhr" to "clock",
        "uhrzeit" to "current time",
        "aktuelle uhrzeit" to "current time",
        "zeit" to "time",
        "notiz*" to "notes",
        "akkord*" to "chord",
        "übersetzung*" to "translation",
        "uebersetzung*" to "translation",
        "sprache*" to "language",
        "zweisprachig*" to "bilingual",
        "andere sprache" to "another language",
        "anderen sprache" to "another language",
        "zweite sprache" to "second language",
        "zweiten sprache" to "second language",
        "zwei sprachen" to "two languages",

        // Screens and outputs.
        "hauptbildschirm*" to "main screen",
        "vollbild*" to "full screen",
        "ganzer bildschirm" to "full screen",
        "ganzen bildschirm" to "full screen",
        "zweiter bildschirm" to "second screen",
        "zweiten bildschirm" to "second screen",
        "bildschirm*" to "screen",
        "beamer*" to "projector",
        "projektor*" to "projector",
        "bühnenmonitor*" to "stage monitor",
        "buehnenmonitor*" to "stage monitor",
        "bühnenbildschirm*" to "stage monitor",
        "monitor auf der bühne" to "stage monitor",
        "monitore" to "monitor",
        "anzeige" to "display",
        "ausgabefenster*" to "output window",
        "ausgabe*" to "output",
        "bühne*" to "stage",
        "buehne*" to "stage",
        "zonen" to "zone",
        "anordnung*" to "arrangement",
        "nachricht*" to "message",
        "senden" to "send",
        "sende" to "send",
        "schick*" to "send",
        "vorschau*" to "preview",
        "was läuft" to "what is on screen",
        "profil*" to "profile",
        "übertragung*" to "stream",
        "uebertragung*" to "stream",
        "fernseher*" to "tv",

        // Pages, tabs and tools.
        "einstellung*" to "settings",
        "optionen" to "options",
        "einrichtungsassistent*" to "setup wizard",
        "neu beginnen" to "start over",
        "von vorne" to "start over",
        "tastenkürzel*" to "shortcut",
        "tastenkuerzel*" to "shortcut",
        "tastenkombination*" to "shortcut",
        "kurzbefehl*" to "shortcut",
        "tastatur*" to "keyboard",
        "reiter*" to "tab",
        "registerkarte*" to "tab",
        "liederbibliothek*" to "song library",
        "liedbibliothek*" to "song library",
        "songbibliothek*" to "song library",
        "bibliothek*" to "library",
        "webseite*" to "website",
        "internetseite*" to "website",
        "wörterbuch*" to "dictionary",
        "woerterbuch*" to "dictionary",
        "kamera*" to "camera",
        "leinwand*" to "canvas",
        "fernbedienung*" to "remote",
        "fernsteuer*" to "remote",
        "handy*" to "phone",
        "telefon*" to "phone",
        "smartphone*" to "phone",
        "integration*" to "integrations",

        // Services and planning.
        "gottesdienstablauf*" to "order of service",
        "ablaufplan*" to "order of service",
        "ablauf" to "order of service",
        "gottesdienst*" to "service",
        "versammlung*" to "meeting",
        "treffen" to "meeting",
        "sonntag*" to "sunday",
        "kalender*" to "calendar",
        "programm" to "schedule",
        "zeitplan*" to "schedule",
        "wiedergabeliste*" to "playlist",
        "jeden sonntag" to "every sunday",
        "jede woche" to "every week",
        "wöchentlich*" to "weekly",
        "woechentlich*" to "weekly",
        "monatlich*" to "monthly",
        "wiederhol*" to "repeat",
        "vorlage*" to "template",

        // Many, all, both.
        "alle" to "all",
        "alles" to "everything",
        "überall" to "everything",
        "ueberall" to "everything",
        "beide" to "both",
        "beiden" to "both",
        "mehrere" to "several",
        "viele" to "many",
        "auf einmal" to "at once",
        "gleichzeitig" to "at once",
        "für diesen gottesdienst" to "this service",
        "fuer diesen gottesdienst" to "this service",
        "für heute" to "for today",
        "fuer heute" to "for today",
        "vorübergehend" to "temporarily",
        "voruebergehend" to "temporarily",
        "vorerst" to "for now",

        // Languages, by name.
        "russisch*" to "russian",
        "ukrainisch*" to "ukrainian",
        "weißrussisch*" to "belarusian",
        "weissrussisch*" to "belarusian",
        "belarussisch*" to "belarusian",
        "englisch*" to "english",
        "spanisch*" to "spanish",
        "deutsch*" to "german",
        "französisch*" to "french",
        "franzoesisch*" to "french",
        "polnisch*" to "polish",
        "kasachisch*" to "kazakh",
        "rumänisch*" to "romanian",
        "rumaenisch*" to "romanian",
        "moldauisch*" to "moldovan",
        "portugiesisch*" to "portuguese",
        "italienisch*" to "italian",
        "niederländisch*" to "dutch",
        "niederlaendisch*" to "dutch",
        "holländisch*" to "dutch",
        "tschechisch*" to "czech",
        "slowakisch*" to "slovak",
        "kroatisch*" to "croatian",
        "serbisch*" to "serbian",
        "bulgarisch*" to "bulgarian",
        "ungarisch*" to "hungarian",
        "griechisch*" to "greek",
        "türkisch*" to "turkish",
        "tuerkisch*" to "turkish",
        "arabisch*" to "arabic",
        "persisch*" to "persian",
        "hebräisch*" to "hebrew",
        "hebraeisch*" to "hebrew",
        "chinesisch*" to "chinese",
        "japanisch*" to "japanese",
        "koreanisch*" to "korean",
        "vietnamesisch*" to "vietnamese",
        "indonesisch*" to "indonesian",
        "estnisch*" to "estonian",
        "lettisch*" to "latvian",
        "litauisch*" to "lithuanian",
        "finnisch*" to "finnish",
        "schwedisch*" to "swedish",
        "norwegisch*" to "norwegian",
        "dänisch*" to "danish",
        "daenisch*" to "danish",
        "armenisch*" to "armenian",
        "georgisch*" to "georgian",
        "latein*" to "latin",

        // Colors.
        "dunkelblau*" to "navy",
        "marineblau*" to "navy",
        "hellblau*" to "light blue",
        "himmelblau*" to "sky",
        "blau*" to "blue",
        "schwarz*" to "black",
        "weiß*" to "white",
        "weiss*" to "white",
        "hellgrau*" to "light grey",
        "dunkelgrau*" to "dark grey",
        "grau*" to "grey",
        "silber*" to "silver",
        "rote" to "red",
        "roten" to "red",
        "roter" to "red",
        "rotes" to "red",
        "rotem" to "red",
        "dunkelrot*" to "maroon",
        "weinrot*" to "maroon",
        "bordeaux*" to "maroon",
        "orangen" to "orange",
        "orangefarb*" to "orange",
        "gelb*" to "yellow",
        "golden*" to "gold",
        "goldfarb*" to "gold",
        "hellgrün*" to "lime",
        "hellgruen*" to "lime",
        "dunkelgrün*" to "dark green",
        "dunkelgruen*" to "dark green",
        "grün*" to "green",
        "gruen*" to "green",
        "türkis*" to "turquoise",
        "tuerkis*" to "turquoise",
        "lila" to "purple",
        "violett*" to "violet",
        "rosa" to "pink",
        "braun*" to "brown",
        "creme*" to "cream",
        "dunkel*" to "dark",
        "helle" to "light",
        "hellen" to "light",
        "heller" to "light",
        "helles" to "light",

        // Talking to the helper.
        "hallo" to "hello",
        "guten tag" to "hello",
        "guten morgen" to "hello",
        "guten abend" to "hello",
        "servus" to "hello",
        "moin" to "hello",
        "grüß gott" to "hello",
        "hilf*" to "help",
        "was kannst du" to "what can you do",
        "was kannst du tun" to "what can you do",
        "wer bist du" to "who are you",
        "danke*" to "thanks",
        "vielen dank" to "thank you",
        "bitte" to "please",
        "wik" to "wick",
    ),
)
