package org.churchpresenter.helper.intent.glossary

internal val HINDI = Glossary(
    "hi",
    listOf(
        // Asking where, or how.
        "कहाँ" to "where",
        "कहां" to "where",
        "कहाँ है" to "where",
        "कहां है" to "where",
        "किधर" to "where",
        "मैं कैसे" to "how do i",
        "कैसे करूँ" to "how do i",
        "कैसे करूं" to "how do i",
        "कैसे कर सकता हूँ" to "how can i",
        "कैसे कर सकता हूं" to "how can i",
        "कैसे कर सकती हूँ" to "how can i",
        "कैसे कर सकती हूं" to "how can i",
        "कैसे" to "how do i",
        "नहीं मिल रहा" to "can't find",
        "नहीं मिल रही" to "can't find",
        "नहीं मिला" to "can't find",
        "मुझे दिखाओ" to "show me",
        "मुझे दिखाइए" to "show me",
        "बताओ" to "how do i",
        "बताइए" to "how do i",
        "kahan" to "where",
        "kidhar" to "where",
        "kaise" to "how do i",
        "kaise karu" to "how do i",
        "nahi mil raha" to "can't find",
        "mujhe dikhao" to "show me",

        // Doing.
        "दिखाओ" to "show",
        "दिखाइए" to "show",
        "दिखाएँ" to "show",
        "दिखाएं" to "show",
        "दिखाना" to "show",
        "दिखा दो" to "show",
        "स्क्रीन पर लाओ" to "show",
        "खोलो" to "open",
        "खोलें" to "open",
        "खोलिए" to "open",
        "पर जाओ" to "go to",
        "पर जाएँ" to "go to",
        "पर जाएं" to "go to",
        "में जाओ" to "go to",
        "जाओ" to "go to",
        "ढूँढो" to "find",
        "ढूंढो" to "find",
        "ढूँढें" to "find",
        "ढूंढें" to "find",
        "खोजो" to "find",
        "खोजें" to "find",
        "पढ़ो" to "read",
        "पढो" to "read",
        "पढ़ें" to "read",
        "पढें" to "read",
        "बनाओ" to "make",
        "बनाएँ" to "make",
        "बनाएं" to "make",
        "बनाइए" to "create",
        "जोड़ो" to "add",
        "जोडो" to "add",
        "जोड़ें" to "add",
        "जोडें" to "add",
        "जोड़िए" to "add",
        "जोडिए" to "add",
        "लोड करो" to "load",
        "लोड" to "load",
        "इम्पोर्ट" to "import",
        "आयात" to "import",
        "डाउनलोड" to "download",
        "इंस्टॉल" to "install",
        "चुनो" to "choose",
        "चुनें" to "choose",
        "सेट करो" to "set up",
        "सेटअप करो" to "set up",
        "कनेक्ट" to "connect",
        "जोड़ना" to "connect",
        "जोडना" to "connect",
        "असाइन" to "assign",
        "छिपाओ" to "hide",
        "छुपाओ" to "hide",
        "छिपाएँ" to "hide",
        "छिपाएं" to "hide",
        "हटाओ" to "hide",
        "हटाएँ" to "hide",
        "हटाएं" to "hide",
        "रोको" to "stop",
        "रोकें" to "stop",
        "बंद करो" to "turn off",
        "बंद करें" to "turn off",
        "डिलीट" to "delete",
        "मिटाओ" to "clear",
        "साफ़ करो" to "clear",
        "साफ करो" to "clear",
        "साफ़ करें" to "clear",
        "साफ करें" to "clear",
        "क्लियर" to "clear",
        "स्क्रीन काली करो" to "black out",
        "ब्लैक आउट" to "black out",
        "खाली स्क्रीन" to "blank",
        "पहले जैसा करो" to "undo",
        "वापस करो" to "undo",
        "अनडू" to "undo",
        "लाइव करो" to "go live",
        "चालू करो" to "turn on",
        "चालू करें" to "turn on",
        "ऑन करो" to "turn on",
        "ऑफ करो" to "turn off",
        "अगला" to "next",
        "अगली" to "next",
        "अगले" to "next",
        "आगे" to "forward",
        "पिछला" to "previous",
        "पिछली" to "previous",
        "पिछले" to "previous",
        "पीछे" to "back",
        "वापस" to "back",
        "बड़ा करो" to "bigger",
        "बडा करो" to "bigger",
        "बड़ा करें" to "bigger",
        "बडा करें" to "bigger",
        "बढ़ाओ" to "increase",
        "बढाओ" to "increase",
        "बढ़ाएँ" to "increase",
        "बढाएँ" to "increase",
        "बढ़ाएं" to "increase",
        "बढाएं" to "increase",
        "बड़ा" to "bigger",
        "बडा" to "bigger",
        "बड़े" to "bigger",
        "बडे" to "bigger",
        "बड़ी" to "bigger",
        "बडी" to "bigger",
        "छोटा करो" to "smaller",
        "छोटा करें" to "smaller",
        "घटाओ" to "decrease",
        "कम करो" to "decrease",
        "कम करें" to "decrease",
        "छोटा" to "smaller",
        "छोटे" to "smaller",
        "छोटी" to "smaller",
        "कन्वर्ट" to "convert",
        "बदलाव करो" to "change",
        "कन्वर्टर" to "converter",
        "ट्रांसफर" to "transfer",
        "एडिट" to "edit",
        "संपादित" to "edit",
        "संपादन" to "edit",
        "बदलो" to "change",
        "बदलें" to "change",
        "बदलना" to "change",
        "नाम बदलो" to "rename",
        "ठीक करो" to "fix",
        "सुधारो" to "fix",
        "व्यवस्थित करो" to "organize",
        "तुलना" to "compare",
        "अनुवाद करो" to "translate",
        "योजना बनाओ" to "plan",
        "प्लान" to "plan",
        "स्वचालित" to "automatically",
        "ऑटोमैटिक" to "automatically",
        "पहचानो" to "identify",
        "नंबर दो" to "number the",
        "dikhao" to "show",
        "dikhaye" to "show",
        "dikhaiye" to "show",
        "kholo" to "open",
        "dhundo" to "find",
        "dhoondo" to "find",
        "banao" to "make",
        "jodo" to "add",
        "chhupao" to "hide",
        "chupao" to "hide",
        "hatao" to "hide",
        "roko" to "stop",
        "band karo" to "turn off",
        "mitao" to "clear",
        "saaf karo" to "clear",
        "chalu karo" to "turn on",
        "agla" to "next",
        "agle" to "next",
        "aage" to "forward",
        "pichla" to "previous",
        "pichhla" to "previous",
        "peeche" to "back",
        "piche" to "back",
        "bada karo" to "bigger",
        "badhao" to "increase",
        "bada" to "bigger",
        "chhota karo" to "smaller",
        "chota karo" to "smaller",
        "chhota" to "smaller",
        "chota" to "smaller",
        "ghatao" to "decrease",
        "kam karo" to "decrease",
        "badlo" to "change",
        "badal do" to "change",
        "theek karo" to "fix",

        // Too small, too big, not working.
        "बहुत छोटा" to "too small",
        "बहुत छोटे" to "too small",
        "बहुत छोटी" to "too small",
        "पढ़ा नहीं जा रहा" to "hard to read",
        "पढा नहीं जा रहा" to "hard to read",
        "पढ़ने में मुश्किल" to "hard to read",
        "पढने में मुश्किल" to "hard to read",
        "दिख नहीं रहा" to "hard to read",
        "साफ़ नहीं दिख रहा" to "hard to read",
        "साफ नहीं दिख रहा" to "hard to read",
        "बहुत बड़ा" to "too big",
        "बहुत बडा" to "too big",
        "बहुत बड़े" to "too big",
        "बहुत बडे" to "too big",
        "बहुत बड़ी" to "too big",
        "बहुत बडी" to "too big",
        "फिट नहीं" to "doesn't fit",
        "नहीं समा रहा" to "doesn't fit",
        "काम नहीं कर रहा" to "not working",
        "काम नहीं कर रही" to "not working",
        "चल नहीं रहा" to "not working",
        "नहीं दिख रहा" to "not showing",
        "नहीं दिखा रहा" to "not showing",
        "कुछ नहीं दिख रहा" to "nothing shows",
        "स्क्रीन काली है" to "screen is black",
        "सिग्नल नहीं" to "no signal",
        "नो सिग्नल" to "no signal",
        "तस्वीर नहीं" to "no picture",
        "कौन सी स्क्रीन" to "which screen",
        "कौन सा मॉनिटर" to "which monitor",
        "कौन सा प्रोजेक्टर" to "which projector",
        "bahut chhota" to "too small",
        "bahut chota" to "too small",
        "bahut bada" to "too big",
        "kaam nahi kar raha" to "not working",
        "nahi dikh raha" to "not showing",
        "kaun si screen" to "which screen",

        // What is on screen.
        "बैकग्राउंड" to "background",
        "पृष्ठभूमि" to "background",
        "पीछे का रंग" to "background",
        "गाने के बोल" to "lyrics",
        "गीत के बोल" to "lyrics",
        "बोल" to "lyrics",
        "गाने" to "songs",
        "गानों" to "songs",
        "गाना" to "song",
        "गीतों" to "songs",
        "गीत" to "song",
        "भजन*" to "hymn",
        "आराधना" to "worship",
        "स्तुति" to "worship",
        "बाइबल" to "bible",
        "बाइबिल" to "bible",
        "पवित्र शास्त्र" to "scripture",
        "वचन" to "scripture",
        "आयत*" to "verse",
        "पद" to "verse",
        "अध्याय" to "chapter",
        "फ़ॉन्ट" to "font",
        "फॉन्ट" to "font",
        "अक्षर" to "letters",
        "साइज़" to "size",
        "साइज" to "size",
        "आकार" to "size",
        "टेक्स्ट" to "text",
        "पाठ" to "text",
        "शब्द" to "words",
        "स्लाइड शो" to "slideshow",
        "स्लाइडशो" to "slideshow",
        "स्लाइड" to "slide",
        "फ़ोटो" to "photo",
        "फोटो" to "photo",
        "तस्वीर*" to "picture",
        "चित्र" to "picture",
        "इमेज" to "image",
        "एल्बम" to "album",
        "प्रस्तुति" to "presentation",
        "प्रेज़ेंटेशन" to "presentation",
        "प्रेजेंटेशन" to "presentation",
        "पावरपॉइंट" to "powerpoint",
        "वीडियो" to "video",
        "फ़िल्म" to "movie",
        "फिल्म" to "movie",
        "क्लिप" to "clip",
        "मीडिया" to "media",
        "ऑडियो" to "audio",
        "लोअर थर्ड" to "lower third",
        "नाम पट्टी" to "name strap",
        "नाम और पद" to "name and title",
        "सूचना*" to "announcement",
        "घोषणा*" to "announcement",
        "अनाउंसमेंट" to "announcement",
        "चलती पट्टी" to "ticker",
        "बच्चों का कमरा" to "kids room",
        "उलटी गिनती" to "countdown",
        "काउंटडाउन" to "countdown",
        "टाइमर" to "timer",
        "स्टॉपवॉच" to "stopwatch",
        "घड़ी" to "clock",
        "घडी" to "clock",
        "मौजूदा समय" to "current time",
        "अभी का समय" to "current time",
        "समय" to "time",
        "नोट्स" to "notes",
        "कॉर्ड" to "chord",
        "अनुवाद" to "translation",
        "भाषा*" to "language",
        "द्विभाषी" to "bilingual",
        "दूसरी भाषा" to "another language",
        "अन्य भाषा" to "another language",
        "दो भाषाओं" to "two languages",
        "दो भाषा" to "two languages",
        "gaana" to "song",
        "gana" to "song",
        "gaane" to "songs",
        "gane" to "songs",
        "geet" to "song",
        "bhajan" to "hymn",
        "aradhana" to "worship",
        "aaradhana" to "worship",
        "stuti" to "worship",
        "vachan" to "scripture",
        "adhyay" to "chapter",
        "akshar" to "letters",
        "tasveer" to "picture",
        "ghoshna" to "announcement",
        "suchna" to "announcement",
        "ghadi" to "clock",
        "samay" to "time",
        "bhasha" to "language",
        "dusri bhasha" to "another language",

        // Screens and outputs.
        "मुख्य स्क्रीन" to "main screen",
        "फुल स्क्रीन" to "full screen",
        "पूरी स्क्रीन" to "full screen",
        "दूसरी स्क्रीन" to "second screen",
        "स्क्रीन" to "screen",
        "परदा" to "screen",
        "पर्दा" to "screen",
        "प्रोजेक्टर" to "projector",
        "स्टेज मॉनिटर" to "stage monitor",
        "मंच मॉनिटर" to "stage monitor",
        "मंच की स्क्रीन" to "stage monitor",
        "मॉनिटर" to "monitor",
        "डिस्प्ले" to "display",
        "आउटपुट" to "output",
        "आउटपुट विंडो" to "output window",
        "मंच" to "stage",
        "स्टेज" to "stage",
        "ज़ोन" to "zone",
        "जोन" to "zone",
        "लेआउट" to "layout",
        "संदेश" to "message",
        "मैसेज" to "message",
        "भेजो" to "send",
        "भेजें" to "send",
        "प्रीव्यू" to "preview",
        "पूर्वावलोकन" to "preview",
        "स्क्रीन पर क्या है" to "what is on screen",
        "प्रोफ़ाइल" to "profile",
        "प्रोफाइल" to "profile",
        "स्ट्रीम" to "stream",
        "प्रसारण" to "stream",
        "टीवी" to "tv",
        "parda" to "screen",
        "manch" to "stage",
        "sandesh" to "message",
        "bhejo" to "send",

        // Pages, tabs and tools.
        "सेटिंग्स" to "settings",
        "सेटिंग" to "settings",
        "विकल्प" to "options",
        "सेटअप विज़र्ड" to "setup wizard",
        "सेटअप विजर्ड" to "setup wizard",
        "फिर से शुरू" to "start over",
        "शॉर्टकट" to "shortcut",
        "हॉटकी" to "hotkeys",
        "कीबोर्ड" to "keyboard",
        "टैब" to "tab",
        "गीत लाइब्रेरी" to "song library",
        "गाना लाइब्रेरी" to "song library",
        "लाइब्रेरी" to "library",
        "पुस्तकालय" to "library",
        "वेब" to "web",
        "वेबसाइट" to "website",
        "ब्राउज़र" to "browser",
        "ब्राउजर" to "browser",
        "शब्दकोश" to "dictionary",
        "डिक्शनरी" to "dictionary",
        "स्ट्रॉन्ग" to "strong",
        "कैमरा" to "camera",
        "कैनवास" to "canvas",
        "सर्वर" to "server",
        "रिमोट" to "remote",
        "फ़ोन" to "phone",
        "फोन" to "phone",
        "मोबाइल" to "phone",
        "टैबलेट" to "tablet",
        "इंटीग्रेशन" to "integrations",

        // Services and planning.
        "आराधना का क्रम" to "order of service",
        "सभा का क्रम" to "order of service",
        "कार्यक्रम का क्रम" to "order of service",
        "आराधना सभा" to "service",
        "सभा" to "meeting",
        "मीटिंग" to "meeting",
        "सर्विस" to "service",
        "रविवार" to "sunday",
        "इतवार" to "sunday",
        "कैलेंडर" to "calendar",
        "कार्यक्रम" to "schedule",
        "शेड्यूल" to "schedule",
        "प्लेलिस्ट" to "playlist",
        "हर रविवार" to "every sunday",
        "हर इतवार" to "every sunday",
        "हर हफ़्ते" to "every week",
        "हर हफ्ते" to "every week",
        "साप्ताहिक" to "weekly",
        "मासिक" to "monthly",
        "दोहराओ" to "repeat",
        "दोहराना" to "repeat",
        "टेम्पलेट" to "template",
        "ढाँचा" to "template",
        "ढांचा" to "template",
        "ravivar" to "sunday",
        "itwar" to "sunday",
        "sabha" to "meeting",
        "har ravivar" to "every sunday",
        "har hafte" to "every week",

        // Many, all, both.
        "सब" to "all",
        "सभी" to "all",
        "सारे" to "all",
        "सारी" to "all",
        "हर जगह" to "everything",
        "दोनों" to "both",
        "कई" to "several",
        "कुछ" to "several",
        "बहुत सारे" to "many",
        "एक साथ" to "at once",
        "इस सभा के लिए" to "this service",
        "इस सर्विस के लिए" to "this service",
        "आज के लिए" to "for today",
        "अस्थायी" to "temporarily",
        "कुछ देर के लिए" to "temporarily",
        "sab" to "all",
        "sabhi" to "all",
        "dono" to "both",
        "ek saath" to "at once",
        "aaj ke liye" to "for today",

        // Languages, by name.
        "हिंदी" to "hindi",
        "हिन्दी" to "hindi",
        "अंग्रेज़ी" to "english",
        "अंग्रेजी" to "english",
        "इंग्लिश" to "english",
        "नेपाली" to "nepali",
        "तमिल" to "tamil",
        "अरबी" to "arabic",
        "फ़ारसी" to "persian",
        "फारसी" to "persian",
        "रूसी" to "russian",
        "यूक्रेनी" to "ukrainian",
        "स्पेनिश" to "spanish",
        "स्पैनिश" to "spanish",
        "जर्मन" to "german",
        "फ़्रेंच" to "french",
        "फ्रेंच" to "french",
        "फ्रांसीसी" to "french",
        "पुर्तगाली" to "portuguese",
        "इतालवी" to "italian",
        "चीनी" to "chinese",
        "जापानी" to "japanese",
        "कोरियाई" to "korean",
        "थाई" to "thai",
        "इब्रानी" to "hebrew",
        "यूनानी" to "greek",
        "लैटिन" to "latin",
        "angrezi" to "english",

        // Colors.
        "गहरा नीला" to "dark blue",
        "हल्का नीला" to "light blue",
        "आसमानी" to "sky",
        "गहरा हरा" to "dark green",
        "हल्का हरा" to "light green",
        "गहरा लाल" to "dark red",
        "नीला" to "blue",
        "नीले" to "blue",
        "नीली" to "blue",
        "काला" to "black",
        "काले" to "black",
        "काली" to "black",
        "सफ़ेद" to "white",
        "सफेद" to "white",
        "स्लेटी" to "grey",
        "धूसर" to "grey",
        "ग्रे" to "grey",
        "चाँदी" to "silver",
        "चांदी" to "silver",
        "लाल" to "red",
        "मैरून" to "maroon",
        "नारंगी" to "orange",
        "संतरी" to "orange",
        "पीला" to "yellow",
        "पीले" to "yellow",
        "पीली" to "yellow",
        "सुनहरा" to "gold",
        "सुनहरी" to "gold",
        "हरा" to "green",
        "हरे" to "green",
        "हरी" to "green",
        "फ़िरोज़ी" to "turquoise",
        "फिरोजी" to "turquoise",
        "बैंगनी" to "purple",
        "जामुनी" to "violet",
        "गुलाबी" to "pink",
        "भूरा" to "brown",
        "भूरे" to "brown",
        "क्रीम" to "cream",
        "गहरा" to "dark",
        "गहरे" to "dark",
        "हल्का" to "light",
        "हल्के" to "light",
        "neela" to "blue",
        "nila" to "blue",
        "kaala" to "black",
        "kala" to "black",
        "safed" to "white",
        "laal" to "red",
        "lal" to "red",
        "narangi" to "orange",
        "peela" to "yellow",
        "pila" to "yellow",
        "sunehra" to "gold",
        "hara" to "green",
        "baingani" to "purple",
        "gulabi" to "pink",
        "bhura" to "brown",
        "gehra" to "dark",
        "halka" to "light",

        // Talking to the helper.
        "नमस्ते" to "hello",
        "नमस्कार" to "hello",
        "जय मसीह की" to "hello",
        "हेलो" to "hello",
        "मदद" to "help",
        "मदद करो" to "help",
        "सहायता" to "help",
        "तुम क्या कर सकते हो" to "what can you do",
        "आप क्या कर सकते हैं" to "what can you do",
        "तुम कौन हो" to "who are you",
        "आप कौन हैं" to "who are you",
        "धन्यवाद" to "thanks",
        "शुक्रिया" to "thanks",
        "बहुत धन्यवाद" to "thank you",
        "कृपया" to "please",
        "विक" to "wick",
        "namaste" to "hello",
        "namaskar" to "hello",
        "jai masih ki" to "hello",
        "madad" to "help",
        "tum kya kar sakte ho" to "what can you do",
        "aap kya kar sakte hain" to "what can you do",
        "dhanyavad" to "thanks",
        "dhanyawad" to "thanks",
        "shukriya" to "thanks",
        "kripya" to "please",

        // Newer requests.
        "खोज*" to "search",
        "में खोजो" to "search in",
        "में खोजें" to "search in",
        "में ढूँढो" to "search in",
        "में ढूंढो" to "search in",
        "सर्च" to "search",
        "गीत खोजो" to "find a song",
        "गीत ढूँढो" to "find a song",
        "गीत ढूंढो" to "find a song",
        "वचन खोजो" to "find a verse",
        "वचन ढूँढो" to "find a verse",
        "वचन ढूंढो" to "find a verse",
        "गीत नंबर" to "song number",
        "नंबर से" to "by number",
        "संख्या से" to "by number",
        "नाम से" to "by title",
        "शीर्षक से" to "by title",
        "नंबर" to "number",
        "संख्या" to "number",
        "पसंदीदा*" to "favorite",
        "फ़ेवरेट" to "favorite",
        "फेवरेट" to "favorite",
        "इस गीत" to "this song",
        "इस गाने" to "this song",
        "हर गीत" to "each song",
        "हर गाने" to "each song",
        "अपना बैकग्राउंड" to "own background",
        "अपनी पृष्ठभूमि" to "own background",
        "अपना पृष्ठभूमि" to "own background",
        "अलग बैकग्राउंड" to "different background",
        "अलग पृष्ठभूमि" to "different background",
        "कई वचन" to "several verses",
        "कई पद" to "several verses",
        "कई आयत*" to "several verses",
        "एक से ज़्यादा वचन" to "more than one verse",
        "एक से ज्यादा वचन" to "more than one verse",
        "एक से अधिक वचन" to "more than one verse",
        "पूरा अंश" to "whole passage",
        "दिखाऊँ" to "show",
        "दिखाऊं" to "show",
        "हमने अभी क्या दिखाया" to "what did we just show",
        "अभी क्या दिखाया" to "what did we just show",
        "हमने क्या दिखाया" to "what did we show",
        "क्या दिखाया था" to "what did we show",
        "इतिहास" to "history",
        "हाल के वचन" to "recent verses",
        "संबंधित वचन" to "related verses",
        "सम्बन्धित वचन" to "related verses",
        "संबंधित पद" to "related verses",
        "संबंधित आयत*" to "related verses",
        "क्रॉस रेफरेंस" to "cross references",
        "क्रॉस संदर्भ" to "cross references",
        "समानांतर अंश" to "parallel passages",
        "वेब पेज" to "web page",
        "वेबपेज" to "web page",
        "इंटरनेट पेज" to "internet page",
        "यूआरएल" to "url",
        "लिंक" to "url",
        "प्लानिंग सेंटर" to "planning center",
        "प्लैनिंग सेंटर" to "planning center",
        "आँकड़े" to "statistics",
        "आंकड़े" to "statistics",
        "कितनी बार" to "how many times",
        "गीत रिपोर्ट" to "song report",
        "गीतों की रिपोर्ट" to "song report",
        "गीत उपयोग" to "song usage",
        "मेरे फ़ोन से" to "from my phone",
        "मेरे फोन से" to "from my phone",
        "मेरे मोबाइल से" to "from my phone",
        "फ़ोन से" to "from the phone",
        "फोन से" to "from the phone",
        "मोबाइल से" to "from the phone",
        "मेरे फ़ोन पर" to "on my phone",
        "मेरे फोन पर" to "on my phone",
        "रिमोट कंट्रोल" to "remote control",
        "क्यूआर कोड" to "qr code",
        "qr कोड" to "qr code",
        "फ़ोन कनेक्ट करो" to "connect my phone",
        "फोन कनेक्ट करो" to "connect my phone",
        "मिनट" to "minutes",
        "मिनटों" to "minutes",
        "मिनिट" to "minutes",
        "घोषणा:" to "announce",
        "सूचना:" to "announce",
        "घोषणा करो:" to "announce",
        "आइटम" to "item",
        "आइटम्स" to "items",
        "कार्यक्रम में" to "in the schedule",
        "शेड्यूल में" to "in the schedule",
        "अभी लाइव क्या है" to "what's live",
        "लाइव क्या है" to "what's live",
        "क्या दिख रहा है" to "what's showing",
        "क्या कुछ लाइव है" to "is anything live",
        "यह कौन-सा संस्करण है" to "what version is this",
        "यह कौन सा संस्करण है" to "what version is this",
        "कौन-सा संस्करण" to "which version",
        "कौन सा संस्करण" to "which version",
        "कौनसा संस्करण" to "which version",
        "कौन-सा वर्ज़न" to "which version",
        "कौन सा वर्ज़न" to "which version",
        "कौन सा वर्जन" to "which version",
        "ऐप का संस्करण" to "app version",
        "ऐप वर्ज़न" to "app version",
        "ऐप वर्जन" to "app version",
        "अपडेट देखो" to "check for updates",
        "अपडेट चेक करो" to "check for updates",
        "क्या अपडेट है" to "is there an update",
        "कोई अपडेट" to "any updates",
        "नवीनतम संस्करण" to "latest version",
        "लेटेस्ट वर्ज़न" to "latest version",
        "लेटेस्ट वर्जन" to "latest version",
        "अप टू डेट" to "up to date",
        "संस्करण" to "version",
        "वर्ज़न" to "version",
        "वर्जन" to "version",
        "कमांड*" to "commands",
        "आदेशों की सूची" to "list of commands",
        "कमांड की सूची" to "list of commands",
        "मैं क्या लिख सकता हूँ" to "what can i type",
        "मैं क्या लिख सकता हूं" to "what can i type",
        "मैं क्या कह सकता हूँ" to "what can i say",
        "मैं क्या कह सकता हूं" to "what can i say",
        "तुम क्या समझते हो" to "what do you understand",
        "khojo" to "search",
        "pasandida" to "favorite",
        "minat" to "minutes",
        "phone se" to "from the phone",
        "ghoshna:" to "announce",
        "एक साथ संपादित" to "batch edit",
        "पूर्ववत करो" to "undo",
        "पूर्ववत" to "undo",
        "कौन-सी स्क्रीन" to "which screen",
        "सेट करूँ" to "set up",
        "सेट करूं" to "set up",
        "फ़ुल स्क्रीन" to "full screen",
        "जोड़ूँ" to "add",
        "जोड़ूं" to "add",
        "जोडूँ" to "add",
        "नर्सरी" to "nursery",

        // Look requests.
        "गीत के बोल कैसे बदल*" to "how do i change song lyrics",
        "गाने के बोल कैसे बदल*" to "how do i change song lyrics",
        "गीत के बोल बदल*" to "change song lyrics",
        "गाने के बोल बदल*" to "change song lyrics",
        "बोल कैसे बदल*" to "how do i change the lyrics",
        "बोल बदल*" to "change the lyrics",
        "बोल एडिट" to "edit the lyrics",
        "बोल संपादित" to "edit the lyrics",
        "बोल ठीक" to "fix the lyrics",
        "बोल में गलती" to "mistake in the lyrics",
        "बोलों में गलती" to "mistake in the lyrics",
        "टाइपो" to "typo",
        "गीत के अंत का निशान" to "end of song marker",
        "गाने के अंत का निशान" to "end of song marker",
        "अंत का निशान" to "end marker",
        "गीत का अंत" to "end of song",
        "गीत के अंत" to "end of song",
        "गीत का शीर्षक" to "song title",
        "गीत के शीर्षक" to "song title",
        "गाने का शीर्षक" to "song title",
        "शीर्षक" to "title",
        "बोलों" to "lyrics",
        "पदों" to "verses",
        "संदर्भ" to "reference",
        "बोल्ड" to "bold",
        "मोटे अक्षर" to "bold letters",
        "इटैलिक" to "italic",
        "तिरछा" to "italic",
        "तिरछे" to "italic",
        "रेखांकित" to "underline",
        "अंडरलाइन" to "underline",
        "आउटलाइन" to "outline",
        "छाया" to "shadow",
        "शैडो" to "shadow",
        "मार्जिन" to "margins",
        "हाशिया" to "margins",
        "हाशिये" to "margins",
        "किनारे" to "edges",
        "किनारों" to "edges",
        "ऊपर" to "top",
        "नीचे" to "bottom",
        "बीच में" to "in the middle",
        "बाईं ओर" to "left",
        "बाएँ" to "left",
        "बाएं" to "left",
        "दाईं ओर" to "right",
        "दाएँ" to "right",
        "दाएं" to "right",
        "संरेखण" to "alignment",
        "अलाइन" to "align",
        "पोज़िशन" to "position",
        "पोजिशन" to "position",
        "का रूप" to "look",
        "दिखावट" to "appearance",
        "स्टाइल" to "style",
        "शैली" to "style",
        "रंग" to "color",
        "फ़ॉर्मेट" to "format",
        "फॉर्मेट" to "format",

        // The help table's own examples.
        "स्क्रीनें" to "screens",
        "माता-पिता" to "parents",
        "कैसे बनाऊँ" to "how do i make",
        "बनाऊँ" to "make",
    ),
)
