package org.churchpresenter.helper.intent.glossary

internal val INDONESIAN = Glossary(
    "id",
    listOf(
        // Asking where, or how.
        "di mana" to "where",
        "dimana" to "where",
        "ke mana" to "where",
        "kemana" to "where",
        "letaknya di mana" to "where",
        "bagaimana cara" to "how do i",
        "bagaimana caranya" to "how do i",
        "bagaimana saya bisa" to "how can i",
        "bagaimana saya" to "how do i",
        "bagaimana" to "how do i",
        "gimana cara" to "how do i",
        "gimana caranya" to "how do i",
        "gimana" to "how do i",
        "caranya" to "how do i",
        "cara untuk" to "how to",
        "tidak bisa menemukan" to "can't find",
        "tidak menemukan" to "can't find",
        "tidak ketemu" to "can't find",
        "nggak ketemu" to "can't find",
        "gak ketemu" to "can't find",
        "ga ketemu" to "can't find",
        "tunjukkan saya" to "show me",
        "tunjukkan ke saya" to "show me",
        "tunjukin" to "show me",
        "tolong tunjukkan" to "show me",

        // Doing.
        "tampil*" to "show",
        "menampil*" to "show",
        "ditampil*" to "show",
        "tunjuk*" to "show",
        "menunjuk*" to "show",
        "proyeksikan" to "show",
        "letakkan" to "put",
        "taruh" to "put",
        "buka*" to "open",
        "membuka*" to "open",
        "dibuka" to "open",
        "pergi ke" to "go to",
        "masuk ke" to "go to",
        "pindah ke" to "switch to",
        "beralih ke" to "switch to",
        "ganti ke" to "switch to",
        "cari" to "find",
        "carikan" to "find",
        "mencari" to "find",
        "temukan" to "find",
        "menemukan" to "find",
        "baca" to "read",
        "bacakan" to "read",
        "membaca" to "read",
        "buat*" to "make",
        "membuat*" to "make",
        "bikin*" to "make",
        "ciptakan" to "create",
        "tambah*" to "add",
        "menambah*" to "add",
        "masukkan" to "add",
        "muat*" to "load",
        "memuat*" to "load",
        "impor" to "import",
        "mengimpor" to "import",
        "unduh*" to "download",
        "mengunduh*" to "download",
        "pasang*" to "install",
        "memasang*" to "install",
        "instal" to "install",
        "menginstal" to "install",
        "pilih*" to "choose",
        "memilih" to "choose",
        "atur" to "set up",
        "aturlah" to "set up",
        "mengatur" to "set up",
        "siapkan" to "set up",
        "sambung*" to "connect",
        "menyambung*" to "connect",
        "hubungkan" to "connect",
        "menghubungkan" to "connect",
        "tetapkan" to "assign",
        "sembunyikan" to "hide",
        "menyembunyikan" to "hide",
        "hilangkan" to "remove",
        "singkirkan" to "remove",
        "hentikan" to "stop",
        "berhenti" to "stop",
        "jeda*" to "pause",
        "hapus*" to "delete",
        "menghapus*" to "delete",
        "bersihkan" to "clear",
        "kosongkan" to "clear",
        "gelapkan layar" to "black out",
        "gelapkan" to "black out",
        "layar kosong" to "blank",
        "batalkan" to "undo",
        "urungkan" to "undo",
        "kembalikan seperti semula" to "undo",
        "tayangkan" to "go live",
        "menayangkan" to "go live",
        "siarkan langsung" to "go live",
        "tayang langsung" to "go live",
        "nyalakan" to "turn on",
        "hidupkan" to "turn on",
        "aktifkan" to "turn on",
        "matikan" to "turn off",
        "nonaktifkan" to "turn off",
        "selanjutnya" to "next",
        "berikutnya" to "next",
        "lanjut" to "next",
        "maju" to "forward",
        "sebelumnya" to "previous",
        "kembali" to "back",
        "mundur" to "back",
        "perbesar" to "enlarge",
        "besarkan" to "enlarge",
        "memperbesar" to "enlarge",
        "lebih besar" to "bigger",
        "naikkan" to "increase",
        "tingkatkan" to "increase",
        "perkecil" to "shrink",
        "kecilkan" to "shrink",
        "memperkecil" to "shrink",
        "lebih kecil" to "smaller",
        "kurangi" to "decrease",
        "turunkan" to "decrease",
        "konverter" to "converter",
        "konversi*" to "convert",
        "mengonversi" to "convert",
        "pindahkan" to "transfer",
        "memindahkan" to "transfer",
        "sunting" to "edit",
        "menyunting" to "edit",
        "ganti nama" to "rename",
        "ubah nama" to "rename",
        "ubah*" to "change",
        "mengubah*" to "change",
        "ganti*" to "change",
        "mengganti*" to "change",
        "perbaiki" to "fix",
        "betulkan" to "fix",
        "rapikan" to "organize",
        "merapikan" to "organize",
        "susun" to "organize",
        "bandingkan" to "compare",
        "terjemahan*" to "translation",
        "terjemahkan" to "translate",
        "menerjemahkan" to "translate",
        "rencanakan" to "plan",
        "merencanakan" to "plan",
        "otomatiskan" to "automate",
        "otomatis" to "automatically",
        "secara otomatis" to "automatically",
        "identifikasi" to "identify",
        "beri nomor" to "number the",
        "nomori" to "number the",

        // Too small, too big, not working.
        "terlalu kecil" to "too small",
        "kekecilan" to "too small",
        "susah dibaca" to "hard to read",
        "sulit dibaca" to "hard to read",
        "kurang jelas" to "hard to read",
        "tidak terbaca" to "can't read",
        "gak kebaca" to "can't read",
        "nggak kebaca" to "can't read",
        "terlalu besar" to "too big",
        "kebesaran" to "too big",
        "tidak muat" to "doesn't fit",
        "gak muat" to "doesn't fit",
        "nggak muat" to "doesn't fit",
        "tidak berfungsi" to "not working",
        "tidak bekerja" to "not working",
        "tidak jalan" to "not working",
        "gak jalan" to "not working",
        "nggak jalan" to "not working",
        "tidak tampil" to "not showing",
        "tidak muncul" to "not showing",
        "gak muncul" to "not showing",
        "nggak muncul" to "not showing",
        "tidak ada yang muncul" to "nothing shows",
        "tidak ada apa-apa" to "nothing shows",
        "layar hitam" to "screen is black",
        "tidak ada sinyal" to "no signal",
        "tidak ada gambar" to "no picture",
        "layar yang mana" to "which screen",
        "layar mana" to "which screen",
        "monitor mana" to "which monitor",
        "proyektor mana" to "which projector",

        // What is on screen.
        "latar belakang*" to "background",
        "latar*" to "background",
        "lirik*" to "lyrics",
        "lagu*" to "song",
        "nyanyian" to "song",
        "kidung agung" to "kidung agung",
        "kidung*" to "hymn",
        "himne" to "hymn",
        "pujian" to "worship",
        "penyembahan" to "worship",
        "alkitab*" to "bible",
        "kitab suci" to "scripture",
        "firman tuhan" to "scripture",
        "firman" to "scripture",
        "ayat*" to "verse",
        "pasal*" to "chapter",
        "jenis huruf" to "font",
        "ukuran huruf" to "font size",
        "ukuran font" to "font size",
        "ukuran*" to "size",
        "huruf" to "letters",
        "teks*" to "text",
        "tulisan*" to "writing",
        "kata-kata" to "words",
        "tayangan slide" to "slideshow",
        "salindia" to "slide",
        "foto*" to "photo",
        "gambar*" to "picture",
        "presentasi*" to "presentation",
        "klip*" to "clip",
        "suara" to "audio",
        "nama dan jabatan" to "name and title",
        "pengumuman*" to "announcement",
        "umumkan" to "announce",
        "teks berjalan" to "ticker",
        "running text" to "ticker",
        "ruang anak" to "kids room",
        "sekolah minggu" to "kids room",
        "hitung mundur" to "countdown",
        "pengatur waktu" to "timer",
        "jamnya" to "clock",
        "jam dinding" to "clock",
        "waktu sekarang" to "current time",
        "jam sekarang" to "current time",
        "waktu" to "time",
        "catatan" to "notes",
        "kunci gitar" to "chord",
        "akor*" to "chord",
        "bahasa lain" to "another language",
        "bahasa kedua" to "second language",
        "dua bahasa" to "two languages",
        "dwibahasa" to "bilingual",
        "bahasa*" to "language",

        // Screens and outputs.
        "layar utama" to "main screen",
        "layar penuh" to "full screen",
        "layar kedua" to "second screen",
        "layar*" to "screen",
        "proyektor*" to "projector",
        "monitor panggung" to "stage monitor",
        "layar panggung" to "stage monitor",
        "jendela output" to "output window",
        "panggung*" to "stage",
        "zona*" to "zone",
        "tata letak" to "layout",
        "susunan" to "arrangement",
        "pesan" to "message",
        "kirim*" to "send",
        "mengirim*" to "send",
        "pratinjau" to "preview",
        "yang ada di layar" to "what is on screen",
        "apa yang di layar" to "what is on screen",
        "profil*" to "profile",
        "siaran*" to "stream",
        "televisi" to "tv",

        // Pages, tabs and tools.
        "pengaturan*" to "settings",
        "setelan*" to "settings",
        "opsi" to "options",
        "preferensi" to "preferences",
        "panduan pengaturan" to "setup wizard",
        "wisaya penyiapan" to "setup wizard",
        "panduan memulai" to "getting started",
        "mulai dari awal" to "start over",
        "mulai ulang" to "start over",
        "pintasan*" to "shortcut",
        "jalan pintas" to "shortcut",
        "tombol pintas" to "hotkeys",
        "papan ketik" to "keyboard",
        "perpustakaan lagu" to "song library",
        "pustaka lagu" to "song library",
        "perpustakaan" to "library",
        "pustaka" to "library",
        "situs*" to "website",
        "peramban" to "browser",
        "kamus*" to "dictionary",
        "kamera*" to "camera",
        "kanvas" to "canvas",
        "jarak jauh" to "remote",
        "ponsel" to "phone",
        "handphone" to "phone",
        "telepon" to "phone",
        "integrasi" to "integrations",

        // Services and planning.
        "tata ibadah" to "order of service",
        "susunan ibadah" to "order of service",
        "urutan ibadah" to "order of service",
        "liturgi" to "order of service",
        "jadwal*" to "schedule",
        "ibadah*" to "service",
        "kebaktian" to "service",
        "pertemuan" to "meeting",
        "persekutuan" to "meeting",
        "hari minggu" to "sunday",
        "kalender*" to "calendar",
        "daftar putar" to "playlist",
        "setiap hari minggu" to "every sunday",
        "tiap hari minggu" to "every sunday",
        "setiap minggu" to "every week",
        "tiap minggu" to "every week",
        "mingguan" to "weekly",
        "bulanan" to "monthly",
        "ulangi" to "repeat",
        "berulang" to "repeat",
        "templat" to "template",

        // Many, all, both.
        "semua*" to "all",
        "seluruh" to "all",
        "keduanya" to "both",
        "dua-duanya" to "both",
        "beberapa" to "several",
        "banyak" to "many",
        "sekaligus" to "at once",
        "bersamaan" to "at once",
        "untuk ibadah ini" to "this service",
        "untuk hari ini" to "for today",
        "sementara" to "temporarily",
        "untuk sekarang" to "for now",

        // Languages, by name.
        "bahasa inggris" to "english",
        "inggris" to "english",
        "bahasa spanyol" to "spanish",
        "spanyol" to "spanish",
        "bahasa rusia" to "russian",
        "rusia" to "russian",
        "ukraina" to "ukrainian",
        "jerman" to "german",
        "prancis" to "french",
        "perancis" to "french",
        "polandia" to "polish",
        "portugis" to "portuguese",
        "italia" to "italian",
        "belanda" to "dutch",
        "rumania" to "romanian",
        "yunani" to "greek",
        "turki" to "turkish",
        "bahasa arab" to "arabic",
        "persia" to "persian",
        "tionghoa" to "chinese",
        "bahasa cina" to "chinese",
        "jepang" to "japanese",
        "bahasa korea" to "korean",
        "bahasa indonesia" to "indonesian",
        "melayu" to "malay",
        "filipina" to "filipino",
        "bahasa latin" to "latin",

        // Colors.
        "biru tua" to "navy",
        "biru dongker" to "navy",
        "biru muda" to "light blue",
        "biru langit" to "light blue",
        "biru*" to "blue",
        "hitam*" to "black",
        "putih*" to "white",
        "abu-abu" to "grey",
        "abu abu" to "grey",
        "perak" to "silver",
        "merah marun" to "maroon",
        "marun" to "maroon",
        "merah tua" to "maroon",
        "merah muda" to "pink",
        "merah*" to "red",
        "oranye" to "orange",
        "jingga" to "orange",
        "kuning*" to "yellow",
        "emas" to "gold",
        "keemasan" to "gold",
        "hijau muda" to "lime",
        "hijau tosca" to "turquoise",
        "tosca" to "turquoise",
        "hijau*" to "green",
        "ungu*" to "purple",
        "cokelat" to "brown",
        "coklat" to "brown",
        "krem" to "cream",
        "gelap" to "dark",
        "terang" to "light",

        // Talking to the helper.
        "halo" to "hello",
        "hallo" to "hello",
        "hai" to "hello",
        "selamat pagi" to "hello",
        "selamat siang" to "hello",
        "selamat sore" to "hello",
        "selamat malam" to "hello",
        "bantu*" to "help",
        "bantuan" to "help",
        "tolong" to "please",
        "apa yang bisa kamu lakukan" to "what can you do",
        "apa yang bisa kamu bantu" to "what can you do",
        "kamu bisa apa" to "what can you do",
        "bisa apa saja" to "what can you do",
        "siapa kamu" to "who are you",
        "kamu siapa" to "who are you",
        "terima kasih" to "thanks",
        "makasih" to "thanks",
        "trims" to "thanks",
        "terima kasih banyak" to "thank you",
        "mohon" to "please",
        "wik" to "wick",

        // Newer requests.
        "cari di" to "search in",
        "mencari di" to "search in",
        "cari lagu" to "search songs",
        "mencari lagu" to "search songs",
        "cari ayat" to "find verses",
        "mencari ayat" to "find verses",
        "pencarian" to "search",
        "telusuri" to "search",
        "menelusuri" to "search",
        "nomor lagu" to "song number",
        "berdasarkan nomor" to "by number",
        "berdasarkan judul" to "by title",
        "nomor" to "number",
        "berjudul" to "called",
        "bernama" to "named",
        "lagu ini" to "this song",
        "setiap lagu" to "each song",
        "tiap lagu" to "each song",
        "per lagu" to "per song",
        "latarnya sendiri" to "own background",
        "latar sendiri" to "own background",
        "latar belakangnya sendiri" to "own background",
        "sendiri" to "its own",
        "beberapa ayat" to "several verses",
        "banyak ayat" to "multiple verses",
        "lebih dari satu ayat" to "more than one verse",
        "rentang ayat" to "verse range",
        "satu perikop" to "a passage",
        "perikop" to "passage",
        "riwayat*" to "history",
        "baru saja kita tampilkan" to "what did we just show",
        "baru saja ditampilkan" to "what did we just show",
        "tadi kita tampilkan" to "what did we just show",
        "ayat terbaru" to "recent verses",
        "referensi silang" to "cross references",
        "rujukan silang" to "cross references",
        "ayat terkait" to "related verses",
        "ayat-ayat terkait" to "related verses",
        "perikop terkait" to "related passages",
        "ayat paralel" to "parallel passages",
        "perikop paralel" to "parallel passages",
        "ayat serupa" to "similar verses",
        "halaman web" to "web page",
        "laman web" to "web page",
        "halaman internet" to "internet page",
        "statistik*" to "statistics",
        "berapa kali" to "how many times",
        "seberapa sering" to "how often",
        "laporan lagu" to "song report",
        "penggunaan lagu" to "song usage",
        "dari ponsel saya" to "from my phone",
        "dari hp saya" to "from my phone",
        "dari handphone saya" to "from my phone",
        "dari telepon saya" to "from my phone",
        "dari ponsel" to "from the phone",
        "di ponsel saya" to "on my phone",
        "di hp saya" to "on my phone",
        "hubungkan ponsel saya" to "connect my phone",
        "sambungkan ponsel saya" to "connect my phone",
        "hubungkan ponsel" to "connect a phone",
        "sambungkan ponsel" to "connect a phone",
        "kendali jarak jauh" to "remote control",
        "kode qr" to "qr code",
        "kendalikan dari" to "control it from",
        "kontrol dari" to "control it from",
        "menit" to "minutes",
        "mnt" to "min",
        "umumkan:" to "announce",
        "umumkanlah" to "announce",
        "ke jadwal" to "to the schedule",
        "ke dalam jadwal" to "into the schedule",
        "di jadwal" to "in the schedule",
        "dalam jadwal" to "in the schedule",
        "dari jadwal" to "from the schedule",
        "apa yang sedang tayang" to "what's live",
        "apa yang tayang" to "what's live",
        "apa yang sedang ditayangkan" to "what's live",
        "apa yang sedang live" to "what's live",
        "apa yang sedang ditampilkan" to "what's showing",
        "apakah ada yang tayang" to "is anything live",
        "ada yang tayang" to "is anything live",
        "versi berapa" to "what version",
        "versi apa" to "what version",
        "versi aplikasi" to "app version",
        "cek pembaruan" to "check for updates",
        "periksa pembaruan" to "check for updates",
        "cek update" to "check for updates",
        "ada pembaruan" to "is there an update",
        "versi terbaru" to "latest version",
        "sudah terbaru" to "up to date",
        "perintah" to "commands",
        "daftar perintah" to "list of commands",
        "apa yang bisa saya katakan" to "what can i say",
        "apa yang bisa saya ketik" to "what can i type",
        "apa yang bisa saya tanyakan" to "what can i ask",
        "apa yang kamu pahami" to "what do you understand",
        "apa yang kamu mengerti" to "what do you understand",

        // Look requests.
        "lirik lagu" to "song lyrics",
        "salah ketik" to "typo",
        "menebalkan" to "bold",
        "tebalkan" to "bold",
        "tebal" to "bold",
        "huruf tebal" to "bold",
        "cetak tebal" to "bold",
        "miring" to "italic",
        "huruf miring" to "italic",
        "garis bawah*" to "underline",
        "garis tepi" to "outline",
        "garis luar" to "outline",
        "bayangan" to "shadow",
        "bayang" to "shadow",
        "jarak tepi" to "margins",
        "tepi" to "edges",
        "pinggir" to "edges",
        "ke atas" to "to the top",
        "atas" to "top",
        "ke bawah" to "to the bottom",
        "bawah" to "bottom",
        "tengah" to "middle",
        "kiri" to "left",
        "kanan" to "right",
        "rata kiri" to "align left",
        "rata kanan" to "align right",
        "rata tengah" to "center",
        "perataan" to "alignment",
        "posisi" to "position",
        "jenis font" to "typeface",
        "tampilan" to "look",
        "gaya" to "style",
        "warna" to "color",
        "judul lagu" to "song title",
        "judul" to "title",
        "referensi" to "reference",
        "penanda akhir lagu" to "end of song marker",
        "penanda akhir" to "end marker",
        "akhir lagu" to "end of song",

        // The help table's own examples.
        "orang tua" to "parents",
        "ruang bayi" to "nursery",
        "jam" to "clock",
        "secara massal" to "batch",
    ),
)
