package org.churchpresenter.helper.intent.glossary

internal val JAPANESE = Glossary(
    "ja",
    listOf(
        // Asking where, or how.
        "どこにある" to "where",
        "どこで" to "where",
        "どこ" to "where",
        "どうやって" to "how do i",
        "どうすれば" to "how do i",
        "どうしたら" to "how do i",
        "どのように" to "how do i",
        "どうやったら" to "how can i",
        "やり方" to "how to",
        "方法" to "how to",
        "教えて" to "how do i",
        "見つからない" to "can't find",
        "見つかりません" to "can't find",
        "見当たらない" to "can't find",
        "見せて" to "show me",

        // Doing.
        "表示して" to "show",
        "表示" to "show",
        "見せる" to "show",
        "映して" to "show",
        "映す" to "show",
        "出して" to "show",
        "開いて" to "open",
        "開く" to "open",
        "開け" to "open",
        "オープン" to "open",
        "移動" to "go to",
        "切り替えて" to "switch to",
        "切り替え" to "switch to",
        "切替" to "switch to",
        "探して" to "find",
        "探す" to "find",
        "検索" to "find",
        "読んで" to "read",
        "読み上げ" to "read",
        "作って" to "make",
        "作る" to "make",
        "作成" to "create",
        "新規" to "new",
        "追加" to "add",
        "加えて" to "add",
        "読み込" to "load",
        "ロード" to "load",
        "インポート" to "import",
        "取り込" to "import",
        "アップロード" to "upload",
        "ダウンロード" to "download",
        "インストール" to "install",
        "選んで" to "choose",
        "選択" to "choose",
        "セットアップ" to "set up",
        "設定して" to "set up",
        "接続" to "connect",
        "つないで" to "connect",
        "割り当て" to "assign",
        "非表示" to "hide",
        "隠して" to "hide",
        "隠す" to "hide",
        "消して" to "clear",
        "消す" to "clear",
        "一時停止" to "pause",
        "止めて" to "stop",
        "止める" to "stop",
        "停止" to "stop",
        "削除" to "delete",
        "クリア" to "clear",
        "ブラックアウト" to "black out",
        "暗転" to "black out",
        "真っ黒にして" to "black out",
        "ブランク" to "blank",
        "空白" to "blank",
        "元に戻して" to "undo",
        "元に戻す" to "undo",
        "取り消し" to "undo",
        "取り消す" to "undo",
        "アンドゥ" to "undo",
        "ライブ表示" to "go live",
        "ライブに出" to "go live",
        "オンにして" to "turn on",
        "オンに" to "turn on",
        "オフにして" to "turn off",
        "オフに" to "turn off",
        "次へ" to "next",
        "次の" to "next",
        "次に" to "next",
        "進む" to "forward",
        "前へ" to "previous",
        "前の" to "previous",
        "戻る" to "back",
        "戻って" to "back",
        "大きくして" to "bigger",
        "大きく" to "bigger",
        "大きめ" to "bigger",
        "拡大" to "bigger",
        "小さくして" to "smaller",
        "小さく" to "smaller",
        "小さめ" to "smaller",
        "縮小" to "smaller",
        "変換ツール" to "converter",
        "コンバーター" to "converter",
        "変換" to "convert",
        "移行" to "migrate",
        "編集" to "edit",
        "名前を変更" to "rename",
        "名前変更" to "rename",
        "変更" to "change",
        "変えて" to "change",
        "変える" to "change",
        "修正" to "fix",
        "直して" to "fix",
        "整理" to "organize",
        "比較" to "compare",
        "翻訳" to "translate",
        "計画" to "plan",
        "予定を立て" to "plan",
        "自動化" to "automate",
        "自動" to "automatically",
        "識別" to "identify",
        "番号を付け" to "number the",

        // Too small, too big, not working.
        "小さすぎ" to "too small",
        "小さい" to "too small",
        "読みにくい" to "hard to read",
        "見にくい" to "hard to read",
        "見えない" to "hard to read",
        "読めない" to "can't read",
        "大きすぎ" to "too big",
        "はみ出" to "doesn't fit",
        "収まらない" to "doesn't fit",
        "入りきらない" to "doesn't fit",
        "動かない" to "not working",
        "動作しない" to "not working",
        "うまくいかない" to "not working",
        "使えない" to "not working",
        "何も表示されない" to "nothing shows",
        "何も映らない" to "nothing shows",
        "表示されない" to "not showing",
        "映らない" to "not showing",
        "画面が黒い" to "screen is black",
        "真っ黒" to "screen is black",
        "信号がない" to "no signal",
        "信号なし" to "no signal",
        "映像が出ない" to "no picture",
        "どの画面" to "which screen",
        "どのディスプレイ" to "which display",
        "どのモニター" to "which monitor",
        "どのプロジェクター" to "which projector",

        // What is on screen.
        "背景" to "background",
        "バックグラウンド" to "background",
        "歌詞" to "lyrics",
        "賛美歌ライブラリ" to "song library",
        "賛美歌" to "song",
        "讃美歌" to "song",
        "聖歌" to "hymn",
        "この歌" to "this song",
        "ソング" to "song",
        "曲" to "song",
        "賛美" to "worship",
        "讃美" to "worship",
        "ワーシップ" to "worship",
        "聖書" to "bible",
        "バイブル" to "bible",
        "御言葉" to "scripture",
        "みことば" to "scripture",
        "聖句" to "verse",
        "フォント" to "font",
        "書体" to "font",
        "文字サイズ" to "font size",
        "文字" to "text",
        "テキスト" to "text",
        "サイズ" to "size",
        "スライドショー" to "slideshow",
        "スライド" to "slide",
        "写真" to "photo",
        "画像" to "picture",
        "イメージ" to "image",
        "アルバム" to "album",
        "プレゼンテーション" to "presentation",
        "プレゼン" to "presentation",
        "パワーポイント" to "powerpoint",
        "パワポ" to "powerpoint",
        "動画" to "video",
        "ビデオ" to "video",
        "映画" to "movie",
        "クリップ" to "clip",
        "メディア" to "media",
        "音声" to "audio",
        "オーディオ" to "audio",
        "下部テロップ" to "lower third",
        "テロップ" to "lower third",
        "ローワーサード" to "lower third",
        "名前と肩書き" to "name and title",
        "お知らせ" to "announcement",
        "告知" to "announcement",
        "アナウンス" to "announcement",
        "ティッカー" to "ticker",
        "流れる文字" to "ticker",
        "託児室" to "nursery",
        "キッズルーム" to "kids room",
        "カウントダウン" to "countdown",
        "タイマー" to "timer",
        "ストップウォッチ" to "stopwatch",
        "時計" to "clock",
        "現在時刻" to "current time",
        "時刻" to "time",
        "時間" to "time",
        "説教ノート" to "sermon notes",
        "メモ" to "notes",
        "ノート" to "notes",
        "コード" to "chord",
        "訳文" to "translation",
        "言語" to "language",
        "二か国語" to "bilingual",
        "バイリンガル" to "bilingual",
        "他の言語" to "another language",
        "別の言語" to "another language",
        "第二言語" to "second language",
        "2か国語" to "two languages",

        // Screens and outputs.
        "メイン画面" to "main screen",
        "メインスクリーン" to "main screen",
        "全画面表示" to "full screen",
        "全画面" to "full screen",
        "フルスクリーン" to "full screen",
        "セカンドスクリーン" to "second screen",
        "第二画面" to "second screen",
        "サブ画面" to "second screen",
        "画面" to "screen",
        "スクリーン" to "screen",
        "プロジェクター" to "projector",
        "投影" to "projection",
        "ステージモニター" to "stage monitor",
        "ステージ画面" to "stage monitor",
        "返しモニター" to "stage monitor",
        "プロンプター" to "confidence monitor",
        "モニター" to "monitor",
        "ディスプレイ" to "display",
        "出力ウィンドウ" to "output window",
        "出力" to "output",
        "ステージ" to "stage",
        "ゾーン" to "zone",
        "レイアウト" to "layout",
        "配置" to "arrangement",
        "メッセージ" to "message",
        "送信" to "send",
        "送って" to "send",
        "送る" to "send",
        "プレビュー" to "preview",
        "画面に何が" to "what is on screen",
        "プロファイル" to "profile",
        "ストリーミング" to "stream",
        "配信" to "stream",
        "テレビ" to "tv",

        // Pages, tabs and tools.
        "環境設定" to "preferences",
        "設定" to "settings",
        "オプション" to "options",
        "セットアップウィザード" to "setup wizard",
        "はじめに" to "setup wizard",
        "最初から" to "start over",
        "やり直" to "start over",
        "キーボードショートカット" to "shortcut",
        "ショートカット" to "shortcut",
        "ホットキー" to "hotkeys",
        "キーボード" to "keyboard",
        "タブレット" to "tablet",
        "タブ" to "tab",
        "ソングライブラリ" to "song library",
        "曲ライブラリ" to "song library",
        "ライブラリ" to "library",
        "ウェブサイト" to "website",
        "サイト" to "website",
        "ウェブ" to "web",
        "ブラウザ" to "browser",
        "辞書" to "dictionary",
        "ストロング" to "strong",
        "カメラ" to "camera",
        "キャンバス" to "canvas",
        "サーバー" to "server",
        "リモート" to "remote",
        "リモコン" to "remote",
        "スマホ" to "phone",
        "携帯" to "phone",
        "コンパニオン" to "companion",
        "連携" to "integrations",

        // Services and planning.
        "式次第" to "order of service",
        "礼拝順序" to "order of service",
        "礼拝プログラム" to "order of service",
        "進行表" to "schedule",
        "礼拝" to "service",
        "集会" to "meeting",
        "毎週日曜" to "every sunday",
        "日曜日" to "sunday",
        "日曜" to "sunday",
        "主日" to "sunday",
        "カレンダー" to "calendar",
        "プレイリスト" to "playlist",
        "毎週" to "every week",
        "毎月" to "monthly",
        "繰り返し" to "repeat",
        "テンプレート" to "template",

        // Many, all, both.
        "全部" to "all",
        "すべて" to "all",
        "全て" to "all",
        "両方" to "both",
        "複数" to "multiple",
        "いくつか" to "several",
        "たくさん" to "many",
        "一括" to "batch",
        "一度に" to "at once",
        "まとめて" to "at once",
        "今回の礼拝" to "this service",
        "今日" to "for today",
        "一時的" to "temporarily",

        // Languages, by name.
        "英語" to "english",
        "スペイン語" to "spanish",
        "ロシア語" to "russian",
        "ウクライナ語" to "ukrainian",
        "ベラルーシ語" to "belarusian",
        "ポーランド語" to "polish",
        "ドイツ語" to "german",
        "フランス語" to "french",
        "ポルトガル語" to "portuguese",
        "イタリア語" to "italian",
        "オランダ語" to "dutch",
        "ルーマニア語" to "romanian",
        "チェコ語" to "czech",
        "スロバキア語" to "slovak",
        "クロアチア語" to "croatian",
        "セルビア語" to "serbian",
        "ブルガリア語" to "bulgarian",
        "ハンガリー語" to "hungarian",
        "ギリシャ語" to "greek",
        "ギリシア語" to "greek",
        "トルコ語" to "turkish",
        "アラビア語" to "arabic",
        "ペルシャ語" to "persian",
        "ペルシア語" to "persian",
        "ヘブライ語" to "hebrew",
        "ヒンディー語" to "hindi",
        "ネパール語" to "nepali",
        "タミル語" to "tamil",
        "タイ語" to "thai",
        "ラオス語" to "lao",
        "ラオ語" to "lao",
        "中国語" to "chinese",
        "北京語" to "mandarin",
        "広東語" to "cantonese",
        "日本語" to "japanese",
        "韓国語" to "korean",
        "朝鮮語" to "korean",
        "ベトナム語" to "vietnamese",
        "インドネシア語" to "indonesian",
        "マレー語" to "malay",
        "タガログ語" to "tagalog",
        "フィリピン語" to "filipino",
        "スワヒリ語" to "swahili",
        "アムハラ語" to "amharic",
        "カザフ語" to "kazakh",
        "ウズベク語" to "uzbek",
        "エストニア語" to "estonian",
        "ラトビア語" to "latvian",
        "リトアニア語" to "lithuanian",
        "フィンランド語" to "finnish",
        "スウェーデン語" to "swedish",
        "ノルウェー語" to "norwegian",
        "デンマーク語" to "danish",
        "アルメニア語" to "armenian",
        "ジョージア語" to "georgian",
        "モルドバ語" to "moldovan",
        "ラテン語" to "latin",

        // Colors.
        "紺色" to "navy",
        "紺" to "navy",
        "ネイビー" to "navy",
        "水色" to "light blue",
        "空色" to "sky",
        "青色" to "blue",
        "ブルー" to "blue",
        "青" to "blue",
        "黒色" to "black",
        "ブラック" to "black",
        "黒" to "black",
        "白色" to "white",
        "ホワイト" to "white",
        "白" to "white",
        "灰色" to "grey",
        "グレー" to "grey",
        "銀色" to "silver",
        "シルバー" to "silver",
        "ワインレッド" to "maroon",
        "赤色" to "red",
        "レッド" to "red",
        "赤" to "red",
        "オレンジ" to "orange",
        "橙色" to "orange",
        "黄緑" to "lime",
        "黄色" to "yellow",
        "イエロー" to "yellow",
        "金色" to "gold",
        "ゴールド" to "gold",
        "緑色" to "green",
        "グリーン" to "green",
        "緑" to "green",
        "オリーブ" to "olive",
        "ティール" to "teal",
        "シアン" to "cyan",
        "ターコイズ" to "turquoise",
        "紫色" to "purple",
        "パープル" to "purple",
        "紫" to "purple",
        "すみれ色" to "violet",
        "バイオレット" to "violet",
        "ラベンダー" to "lavender",
        "ピンク" to "pink",
        "桃色" to "pink",
        "マゼンタ" to "magenta",
        "茶色" to "brown",
        "ブラウン" to "brown",
        "ベージュ" to "beige",
        "クリーム色" to "cream",
        "濃い" to "dark",
        "暗い" to "dark",
        "ダーク" to "dark",
        "薄い" to "light",
        "明るい" to "light",
        "ライト" to "light",

        // Talking to the helper.
        "こんにちは" to "hello",
        "こんばんは" to "hello",
        "おはよう" to "hello",
        "ハロー" to "hello",
        "助けて" to "help",
        "手伝って" to "help",
        "ヘルプ" to "help",
        "何ができますか" to "what can you do",
        "何ができる" to "what can you do",
        "あなたは誰" to "who are you",
        "誰ですか" to "who are you",
        "ありがとうございます" to "thank you",
        "ありがとう" to "thanks",
        "どうも" to "thanks",
        "お願いします" to "please",
        "ください" to "please",
        "ウィック" to "wick",

        // Newer requests.
        "今だけ" to "for now",
        "を検索" to "search",
        "で検索" to "search",
        "検索する" to "search",
        "賛美歌を探" to "find the song",
        "曲を探" to "find the song",
        "聖句を探" to "find the verse",
        "賛美歌番号" to "song number",
        "番号で" to "by number",
        "タイトルで" to "by title",
        "曲名で" to "by title",
        "賛美歌はどこで追加" to "where do i add a song",
        "賛美歌を追加" to "add a song",
        "お気に入り" to "favorite",
        "この賛美歌" to "this song",
        "この曲" to "this song",
        "専用の" to "its own",
        "複数の節" to "several verses",
        "複数の聖句" to "several verses",
        "いくつかの節" to "several verses",
        "節の範囲" to "verse range",
        "さっき何を表示した" to "what did we just show",
        "何を表示した" to "what did we show",
        "履歴" to "history",
        "最近の聖句" to "recent verses",
        "関連する聖句" to "related verses",
        "関連聖句" to "related verses",
        "相互参照" to "cross references",
        "引照" to "cross references",
        "並行箇所" to "parallel passages",
        "ウェブページ" to "web page",
        "ホームページ" to "web page",
        "プランニングセンター" to "planning center",
        "統計" to "statistics",
        "何回" to "how many times",
        "使用状況" to "song usage",
        "スマホから" to "from my phone",
        "携帯から" to "from my phone",
        "スマホで" to "on my phone",
        "スマートフォン" to "phone",
        "遠隔操作" to "remote control",
        "リモート操作" to "remote control",
        "qrコード" to "qr code",
        "操作" to "control",
        "分間" to "minutes",
        "分のカウントダウン" to "minutes countdown",
        "分カウントダウン" to "minutes countdown",
        "分タイマー" to "minutes timer",
        "お知らせ:" to "announce",
        "告知:" to "announce",
        "項目" to "item",
        "何が表示されて" to "what's showing",
        "何が映って" to "what's showing",
        "画面を隠" to "hide the screens",
        "画面を非表示" to "hide the screens",
        "を設定" to "set up",
        "まとめて編集" to "batch edit",
        "このバージョン" to "version is this",
        "どのバージョン" to "which version",
        "最新バージョン" to "latest version",
        "最新版" to "latest version",
        "アップデートを確認" to "check for updates",
        "更新を確認" to "check for updates",
        "アップデートはありますか" to "is there an update",
        "コマンド一覧" to "list of commands",
        "コマンド" to "commands",
        "何と入力" to "what can i type",
        "何て言えば" to "what can i say",
        "何が分かる" to "what do you understand",

        // Look requests.
        "歌詞を変更" to "change the lyrics",
        "歌詞を変え" to "change the lyrics",
        "歌詞を編集" to "edit the lyrics",
        "歌詞を修正" to "fix the lyrics",
        "歌詞を直" to "fix the lyrics",
        "誤字" to "typo",
        "曲の終わり" to "end of the song",
        "賛美歌の終わり" to "end of the song",
        "終わりのマーク" to "end marker",
        "終わりマーク" to "end marker",
        "終了マーク" to "end marker",
        "エンドマーク" to "end marker",
        "タイトル" to "title",
        "題名" to "title",
        "箇所" to "reference",
        "太字" to "bold",
        "斜体" to "italic",
        "イタリック" to "italic",
        "下線" to "underline",
        "アンダーライン" to "underline",
        "縁取り" to "outline",
        "アウトライン" to "outline",
        "ドロップシャドウ" to "drop shadow",
        "シャドウ" to "shadow",
        "影を" to "shadow",
        "影の" to "shadow",
        "影付" to "shadow",
        "余白" to "margins",
        "マージン" to "margins",
        "一番上" to "top",
        "上部" to "top",
        "上端" to "top",
        "一番下" to "bottom",
        "下端" to "bottom",
        "中央" to "center",
        "真ん中" to "middle",
        "左揃え" to "align left",
        "右揃え" to "align right",
        "揃え" to "align",
        "位置" to "position",
        "見た目" to "look",
        "外観" to "appearance",
        "スタイル" to "style",
        "書式" to "format",
        "デザイン" to "design",
        "文字色" to "text color",

        // The help table's own examples.
        "を表示" to "show",
        "を進行表に追加" to "to the schedule add",
        "進行表に追加" to "to the schedule add",
        "進行表の" to "in the schedule ",
        "へ移動" to "go to",
        "保護者" to "parents",
        "両親" to "parents",
        "保育室" to "nursery",
    ),
    spaced = false,
)
