package org.churchpresenter.helper.intent.glossary

internal val KAZAKH = Glossary(
    "kk",
    listOf(
        // Asking where, or how.
        "қайда" to "where",
        "қай жерде" to "where",
        "қай жерден" to "where",
        "мен қалай" to "how do i",
        "қалай істеймін" to "how do i",
        "қалай жасаймын" to "how do i",
        "қалай болады" to "how can i",
        "қалай аламын" to "how can i",
        "қалайша" to "how do i",
        "қалай" to "how do i",
        "таба алмай жүрмін" to "can't find",
        "таба алмаймын" to "can't find",
        "таба алмадым" to "can't find",
        "таппадым" to "can't find",
        "таппай жүрмін" to "can't find",
        "маған көрсет*" to "show me",
        "кеңес бер*" to "how do i",
        "айтып бер*" to "how do i",

        // Doing.
        "көрсет*" to "show",
        "экранға шығар*" to "show",
        "шығар*" to "show",
        "бейнеле*" to "display",
        "аш" to "open",
        "ашу" to "open",
        "ашып" to "open",
        "ашшы" to "open",
        "ашыңыз" to "open",
        "ашыңызшы" to "open",
        "өт" to "go to",
        "өту" to "go to",
        "өтші" to "go to",
        "өтіңіз" to "go to",
        "ауыс" to "switch to",
        "ауысу" to "switch to",
        "ауысшы" to "switch to",
        "ауысыңыз" to "switch to",
        "тап" to "find",
        "тапшы" to "find",
        "табу" to "find",
        "тауып" to "find",
        "табыңыз" to "find",
        "ізде*" to "find",
        "оқы*" to "read",
        "жаса*" to "make",
        "құр" to "create",
        "құру" to "create",
        "құрып" to "create",
        "құршы" to "create",
        "құрыңыз" to "create",
        "қос" to "add",
        "қосу" to "add",
        "қосып" to "add",
        "қосшы" to "add",
        "қосыңыз" to "add",
        "қосамын" to "add",
        "іске қос*" to "turn on",
        "жүктеп ал*" to "download",
        "жүкте*" to "get",
        "импорт*" to "import",
        "орнат*" to "install",
        "таңда*" to "choose",
        "бапта*" to "set up",
        "қосыл*" to "connect",
        "тағайында*" to "assign",
        "жасыр*" to "hide",
        "алып таста*" to "hide",
        "тоқтат*" to "stop",
        "жой*" to "delete",
        "өшіріп таста*" to "delete",
        "тазала*" to "clear",
        "қараңғыла*" to "black out",
        "экранды өшір*" to "black out",
        "бос экран" to "blank",
        "болдырма*" to "undo",
        "кері қайтар*" to "undo",
        "бұрынғыдай қайтар*" to "undo",
        "эфирге" to "go live",
        "эфирге шығар*" to "go live",
        "эфирге жібер*" to "go live",
        "өшір*" to "turn off",
        "келесі*" to "next",
        "әрі қарай" to "next",
        "алға" to "forward",
        "алдыңғы*" to "previous",
        "артқа" to "back",
        "кейін қайт*" to "back",
        "үлкейт*" to "increase",
        "үлкенірек" to "bigger",
        "ірірек" to "bigger",
        "кішірейт*" to "decrease",
        "кішірек" to "smaller",
        "кішкенерек" to "smaller",
        "ұсағырақ" to "smaller",
        "конвертте*" to "convert",
        "түрлендір*" to "convert",
        "конвертер*" to "converter",
        "көшір*" to "transfer",
        "тасымалда*" to "transfer",
        "өңде*" to "edit",
        "атын өзгерт*" to "rename",
        "атауын өзгерт*" to "rename",
        "қайта ата*" to "rename",
        "өзгерт*" to "change",
        "ауыстыр*" to "change",
        "түзет*" to "fix",
        "ретте*" to "organize",
        "жүйеле*" to "organize",
        "тәртіпке келтір*" to "clean up",
        "салыстыр*" to "compare",
        "аудар" to "translate",
        "аудару" to "translate",
        "аударшы" to "translate",
        "аударыңыз" to "translate",
        "жоспарла*" to "plan",
        "автоматта*" to "automate",
        "автоматты*" to "automatically",
        "анықта*" to "identify",
        "нөмірле*" to "number the",

        // Too small, too big, not working.
        "тым кішкентай" to "too small",
        "тым кішкене" to "too small",
        "тым кіші" to "too small",
        "тым ұсақ" to "too small",
        "нашар көрінеді" to "hard to read",
        "көрінбейді" to "hard to read",
        "оқу қиын" to "hard to read",
        "оқылмайды" to "hard to read",
        "тым үлкен" to "too big",
        "тым ірі" to "too big",
        "сыймайды" to "doesn't fit",
        "сыяр емес" to "doesn't fit",
        "жұмыс істемейді" to "not working",
        "істемейді" to "not working",
        "көрсетпейді" to "not showing",
        "ештеңе көрсетпейді" to "nothing shows",
        "ештеңе жоқ" to "nothing shows",
        "қара экран" to "screen is black",
        "экран қара" to "screen is black",
        "сигнал жоқ" to "no signal",
        "сурет жоқ" to "no picture",
        "кескін жоқ" to "no picture",
        "қай экран" to "which screen",
        "қай монитор" to "which monitor",
        "қай проектор" to "which projector",

        // What is on screen.
        "артқы фон*" to "background",
        "фон*" to "background",
        "ән мәтіні" to "lyrics",
        "әннің мәтіні" to "lyrics",
        "әнұран мәтіні" to "lyrics",
        "әннің сөздері" to "lyrics",
        "әнұрандар*" to "songs",
        "әнұран*" to "song",
        "әндер*" to "songs",
        "ән" to "song",
        "әні" to "song",
        "әнді" to "song",
        "әннің" to "song",
        "әнін" to "song",
        "әнге" to "song",
        "әннен" to "song",
        "өлең*" to "song",
        "гимн*" to "hymn",
        "мадақ*" to "worship",
        "киелі кітап*" to "bible",
        "інжіл*" to "bible",
        "библия*" to "bible",
        "киелі жазба*" to "scripture",
        "аят*" to "verse",
        "тарау*" to "chapter",
        "қаріп*" to "font",
        "шрифт*" to "font",
        "өлшем*" to "size",
        "мөлшер*" to "size",
        "мәтін*" to "text",
        "сөздер*" to "words",
        "әріп*" to "letters",
        "слайд-шоу" to "slideshow",
        "слайдшоу" to "slideshow",
        "слайд*" to "slide",
        "фотосурет*" to "photo",
        "фото*" to "photo",
        "сурет*" to "picture",
        "кескін*" to "image",
        "альбом*" to "album",
        "презентация*" to "presentation",
        "бейнеролик*" to "clip",
        "бейне*" to "video",
        "видео*" to "video",
        "фильм*" to "movie",
        "ролик*" to "clip",
        "клип*" to "clip",
        "медиа*" to "media",
        "аудио*" to "audio",
        "төменгі үштен бір*" to "lower third",
        "титр*" to "lower third",
        "аты-жөні мен лауазымы" to "name and title",
        "есімі мен лауазымы" to "name and title",
        "хабарландыру*" to "announcement",
        "жүгіртпе жол*" to "ticker",
        "жүгірме жол*" to "ticker",
        "балалар бөлме*" to "kids room",
        "кері санақ*" to "countdown",
        "санақ*" to "countdown",
        "таймер*" to "timer",
        "секундомер*" to "stopwatch",
        "сағат*" to "clock",
        "қазіргі уақыт" to "current time",
        "ағымдағы уақыт" to "current time",
        "уақыт*" to "time",
        "жазба*" to "notes",
        "ескертпе*" to "notes",
        "аккорд*" to "chord",
        "аударма*" to "translation",
        "тіл" to "language",
        "тілі" to "language",
        "тілде" to "language",
        "тілге" to "language",
        "тілін" to "language",
        "тілінде" to "language",
        "тілдің" to "language",
        "тілдер*" to "language",
        "екі тілді*" to "bilingual",
        "басқа тілде" to "another language",
        "басқа тіл*" to "another language",
        "екінші тіл*" to "second language",
        "екі тілде" to "two languages",

        // Screens and outputs.
        "негізгі экран*" to "main screen",
        "басты экран*" to "main screen",
        "толық экран*" to "full screen",
        "бүкіл экран*" to "full screen",
        "экранның бәрі" to "full screen",
        "екінші экран*" to "second screen",
        "экран*" to "screen",
        "проектор*" to "projector",
        "сахна монитор*" to "stage monitor",
        "сахнадағы монитор*" to "stage monitor",
        "сахнаға арналған монитор*" to "stage monitor",
        "суфлер*" to "confidence monitor",
        "монитор*" to "monitor",
        "дисплей*" to "display",
        "шығыс терезе*" to "output window",
        "шығыс*" to "output",
        "сахна*" to "stage",
        "аймақ*" to "zone",
        "орналасу*" to "layout",
        "макет*" to "layout",
        "орналастыр*" to "arrangement",
        "хабарлама*" to "message",
        "жібер*" to "send",
        "алдын ала қарау" to "preview",
        "алдын ала көру" to "preview",
        "превью" to "preview",
        "экранда не бар" to "what is on screen",
        "экранда не тұр" to "what is on screen",
        "профиль*" to "profile",
        "трансляция*" to "stream",
        "тікелей эфир*" to "stream",
        "стрим*" to "stream",
        "теледидар*" to "tv",

        // Pages, tabs and tools.
        "параметр*" to "settings",
        "баптаулар*" to "settings",
        "орнату шебері" to "setup wizard",
        "баптау шебері" to "setup wizard",
        "басынан бастау" to "start over",
        "қайта бастау" to "start over",
        "пернелер тіркесім*" to "shortcut",
        "жылдам перне*" to "hotkeys",
        "ыстық перне*" to "hotkeys",
        "пернетақта*" to "keyboard",
        "қойынды*" to "tab",
        "әнұрандар жинағы*" to "song library",
        "ән кітапхана*" to "song library",
        "кітапхана*" to "library",
        "веб" to "web",
        "сайт*" to "website",
        "браузер*" to "browser",
        "сөздік*" to "dictionary",
        "стронг*" to "strong",
        "камера*" to "camera",
        "кенеп*" to "canvas",
        "сервер*" to "server",
        "қашықтан*" to "remote",
        "пульт*" to "remote",
        "телефон*" to "phone",
        "смартфон*" to "phone",
        "планшет*" to "tablet",
        "компаньон*" to "companion",
        "интеграция*" to "integrations",

        // Services and planning.
        "қызмет тәртібі*" to "order of service",
        "қызмет реті*" to "order of service",
        "қызмет ретін" to "order of service",
        "ғибадат*" to "service",
        "қызмет*" to "service",
        "жиналыс*" to "meeting",
        "жексенбі*" to "sunday",
        "күнтізбе*" to "calendar",
        "календар*" to "calendar",
        "бағдарлама*" to "schedule",
        "кесте*" to "schedule",
        "плейлист*" to "playlist",
        "әр жексенбі*" to "every sunday",
        "апта сайын" to "every week",
        "әр апта*" to "every week",
        "апталық" to "weekly",
        "ай сайын" to "monthly",
        "айлық" to "monthly",
        "қайтала*" to "repeat",
        "үлгі*" to "template",
        "шаблон*" to "template",

        // Many, all, both.
        "барлығы*" to "all",
        "барлық" to "all",
        "бәрі*" to "all",
        "барлық жерде" to "everything",
        "екеуі*" to "both",
        "екеуін" to "both",
        "бірнеше" to "several",
        "көп" to "many",
        "бірден" to "at once",
        "осы қызмет үшін" to "this service",
        "осы қызметке" to "this service",
        "бүгінге" to "for today",
        "бүгін үшін" to "for today",
        "уақытша" to "temporarily",

        // Languages, by name.
        "орысша" to "russian",
        "орыс*" to "russian",
        "украин*" to "ukrainian",
        "беларус*" to "belarusian",
        "ағылшын*" to "english",
        "испан*" to "spanish",
        "неміс*" to "german",
        "француз*" to "french",
        "поляк*" to "polish",
        "қазақша" to "kazakh",
        "қазақ*" to "kazakh",
        "өзбек*" to "uzbek",
        "румын*" to "romanian",
        "молдаван*" to "moldovan",
        "түрік*" to "turkish",
        "корей*" to "korean",
        "қытай*" to "chinese",
        "араб*" to "arabic",
        "латын*" to "latin",

        // Colors.
        "қою көк" to "navy",
        "ашық көк" to "light blue",
        "көгілдір жасыл" to "turquoise",
        "көгілдір*" to "light blue",
        "көк" to "blue",
        "көкке" to "blue",
        "көкпен" to "blue",
        "көкті" to "blue",
        "көк түс*" to "blue",
        "қара" to "black",
        "қараға" to "black",
        "қарамен" to "black",
        "қараны" to "black",
        "қара түс*" to "black",
        "ақ" to "white",
        "аққа" to "white",
        "ақпен" to "white",
        "ақты" to "white",
        "ақ түс*" to "white",
        "сұр" to "grey",
        "сұрға" to "grey",
        "сұрмен" to "grey",
        "сұр түс*" to "grey",
        "күміс*" to "silver",
        "қызыл қоңыр" to "maroon",
        "қызыл*" to "red",
        "қызғылт сары" to "orange",
        "сарғыш қызыл" to "orange",
        "сары*" to "yellow",
        "алтын*" to "gold",
        "ашық жасыл" to "lime",
        "жасыл*" to "green",
        "бирюза*" to "turquoise",
        "күлгін*" to "purple",
        "фиолет*" to "purple",
        "қызғылт*" to "pink",
        "қоңыр*" to "brown",
        "беж*" to "beige",
        "кілегей*" to "cream",
        "қою жасыл" to "dark green",
        "қою қызыл" to "dark red",
        "қою сұр" to "dark grey",
        "қараңғы*" to "dark",
        "күңгірт*" to "dark",
        "ашық" to "light",
        "ақшыл" to "light",

        // Talking to the helper.
        "сәлем*" to "hello",
        "қайырлы күн" to "hello",
        "армысыз" to "hello",
        "көмектес*" to "help",
        "көмек*" to "help",
        "сен не істей аласың" to "what can you do",
        "не істей аласың" to "what can you do",
        "не істей аласыз" to "what can you do",
        "не білесің" to "what can you do",
        "сен кімсің" to "who are you",
        "кімсің" to "who are you",
        "сіз кімсіз" to "who are you",
        "рахмет" to "thanks",
        "рақмет" to "thanks",
        "көп рахмет" to "thank you",
        "көп рақмет" to "thank you",
        "өтінемін" to "please",
        "уик" to "wick",
        "вик" to "wick",
    ),
)
