package org.churchpresenter.helper.intent.glossary

internal val LAO = Glossary(
    "lo",
    listOf(
        // Asking where, or how.
        "ຢູ່ໃສ" to "where",
        "ໄປໃສ" to "where",
        "ບ່ອນໃດ" to "where",
        "ເຮັດແນວໃດ" to "how do i",
        "ໄດ້ແນວໃດ" to "how can i",
        "ແນວໃດ" to "how do i",
        "ຈັ່ງໃດ" to "how do i",
        "ວິທີ" to "how to",
        "ຊອກບໍ່ເຫັນ" to "can't find",
        "ຫາບໍ່ເຫັນ" to "can't find",
        "ຊອກບໍ່ພົບ" to "can't find",
        "ບໍ່ພົບ" to "can't find",
        "ສະແດງໃຫ້ເບິ່ງ" to "show me",
        "ໃຫ້ເບິ່ງ" to "show me",

        // Doing.
        "ສະແດງ" to "show",
        "ເປີດໃຊ້" to "turn on",
        "ເປີດຕັ້ງຄ່າ" to "open settings",
        "ເປີດ" to "open",
        "ໄປທີ່" to "go to",
        "ໄປຫາ" to "go to",
        "ສະຫຼັບໄປ" to "switch to",
        "ປ່ຽນໄປ" to "switch to",
        "ຊອກຫາ" to "find",
        "ຄົ້ນຫາ" to "find",
        "ອ່ານ" to "read",
        "ເຮັດໃຫ້ຈໍດຳ" to "black out",
        "ເຮັດໃຫ້" to "make",
        "ສ້າງ" to "create",
        "ເພີ່ມຂະໜາດ" to "increase",
        "ເພີ່ມ" to "add",
        "ອັບໂຫຼດ" to "upload",
        "ດາວໂຫຼດ" to "download",
        "ໂຫຼດ" to "load",
        "ນຳເຂົ້າ" to "import",
        "ຕິດຕັ້ງ" to "install",
        "ເລືອກ" to "choose",
        "ຕັ້ງຄ່າ" to "set up",
        "ເຊື່ອມຕໍ່" to "connect",
        "ກຳນົດ" to "assign",
        "ເຊື່ອງ" to "hide",
        "ເອົາອອກ" to "remove",
        "ຢຸດຊົ່ວຄາວ" to "pause",
        "ຢຸດ" to "stop",
        "ລຶບ" to "delete",
        "ລ້າງຈໍ" to "clear screen",
        "ລ້າງ" to "clear",
        "ປິດຈໍ" to "black out",
        "ຈໍວ່າງ" to "blank",
        "ຍົກເລີກ" to "undo",
        "ຍ້ອນກັບ" to "undo",
        "ຂຶ້ນຈໍ" to "go live",
        "ອອກອາກາດ" to "go live",
        "ປິດ" to "turn off",
        "ສະຫຼັບ" to "toggle",
        "ຖັດໄປ" to "next",
        "ຕໍ່ໄປ" to "next",
        "ໄປໜ້າ" to "forward",
        "ກ່ອນໜ້າ" to "previous",
        "ກັບຄືນ" to "back",
        "ໃຫຍ່ຂຶ້ນ" to "bigger",
        "ຂະຫຍາຍ" to "bigger",
        "ຫຼຸດຂະໜາດ" to "decrease",
        "ນ້ອຍລົງ" to "smaller",
        "ຕົວແປງ" to "converter",
        "ແປງໄຟລ໌" to "convert",
        "ແປງ" to "convert",
        "ຍ້າຍ" to "transfer",
        "ແກ້ໄຂ" to "edit",
        "ປ່ຽນຊື່" to "rename",
        "ປ່ຽນ" to "change",
        "ແກ້" to "fix",
        "ຈັດລຽງ" to "organize",
        "ຈັດການ" to "organize",
        "ປຽບທຽບ" to "compare",
        "ແປ" to "translate",
        "ວາງແຜນ" to "plan",
        "ອັດຕະໂນມັດ" to "automatically",
        "ລະບຸ" to "identify",
        "ໃສ່ໝາຍເລກ" to "number the",

        // Too small, too big, not working.
        "ນ້ອຍເກີນໄປ" to "too small",
        "ນ້ອຍໄປ" to "too small",
        "ອ່ານຍາກ" to "hard to read",
        "ອ່ານບໍ່ອອກ" to "can't read",
        "ເບິ່ງບໍ່ເຫັນ" to "hard to read",
        "ເບິ່ງບໍ່ຊັດ" to "hard to read",
        "ໃຫຍ່ເກີນໄປ" to "too big",
        "ໃຫຍ່ໄປ" to "too big",
        "ບໍ່ພໍດີ" to "doesn't fit",
        "ລົ້ນຈໍ" to "doesn't fit",
        "ບໍ່ເຮັດວຽກ" to "not working",
        "ໃຊ້ບໍ່ໄດ້" to "not working",
        "ບໍ່ສະແດງ" to "not showing",
        "ບໍ່ຂຶ້ນ" to "not showing",
        "ບໍ່ມີຫຍັງ" to "nothing shows",
        "ຈໍດຳ" to "screen is black",
        "ຈໍມືດ" to "screen is black",
        "ບໍ່ມີສັນຍານ" to "no signal",
        "ບໍ່ມີພາບ" to "no picture",
        "ຈໍໃດ" to "which screen",
        "ມໍນິເຕີໃດ" to "which monitor",
        "ໂປເຈັກເຕີໃດ" to "which projector",

        // Songs, by the words around them.
        "ເນື້ອເພງ" to "lyrics",
        "ບົດເພງ" to "song",
        "ເພງນະມັດສະການ" to "worship song",
        "ເພງນີ້" to "this song",
        "ເພງຖັດໄປ" to "next song",
        "ເພງຕໍ່ໄປ" to "next song",
        "ເພງກ່ອນໜ້າ" to "previous song",
        "ເພງທັງໝົດ" to "all songs",
        "ເພງໃໝ່" to "new song",
        "ເພງພາສາ" to "song language",
        "ເພງແລະ" to "song and",
        "ເພງກັບ" to "song and",
        "ແຖບເພງ" to "songs tab",
        "ຄັງເພງ" to "song library",
        "ເພີ່ມເພງ" to "add song",
        "ສ້າງເພງ" to "create song",
        "ຂຽນເພງ" to "write a song",
        "ສະແດງເພງ" to "show song",
        "ເປີດເພງ" to "open song",
        "ຊອກຫາເພງ" to "find song",
        "ຄົ້ນຫາເພງ" to "search song",
        "ແກ້ໄຂເພງ" to "edit song",
        "ແປເພງ" to "translate song",
        "ພື້ນຫຼັງເພງ" to "song background",
        "ຕົວອັກສອນເພງ" to "song font",
        "ຟອນເພງ" to "song font",
        "ຄອດເພງ" to "song chord",
        "ຂອງເພງ" to "song",
        "ໃນເພງ" to "in song",
        "ຫຼາຍເພງ" to "multiple songs",
        "ທຸກເພງ" to "every song",

        // What is on screen.
        "ພື້ນຫຼັງ" to "background",
        "ພື້ນຫລັງ" to "background",
        "ຂໍ້ພຣະຄຳພີ" to "verse",
        "ຂໍ້ພະຄຳພີ" to "verse",
        "ພຣະຄຳພີ" to "bible",
        "ພະຄຳພີ" to "bible",
        "ຄຳພີ" to "bible",
        "ໄບເບິນ" to "bible",
        "ນະມັດສະການ" to "worship",
        "ຕົວອັກສອນ" to "font",
        "ຟອນ" to "font",
        "ຂະໜາດ" to "size",
        "ຂໍ້ຄວາມແລ່ນ" to "ticker",
        "ຂໍ້ຄວາມ" to "text",
        "ສະໄລໂຊ" to "slideshow",
        "ສະໄລດ໌" to "slide",
        "ສະໄລ" to "slide",
        "ຮູບພາບ" to "picture",
        "ຮູບຖ່າຍ" to "photo",
        "ພາບຖ່າຍ" to "photo",
        "ການສາຍພາບ" to "projection",
        "ຈໍພາບ" to "display",
        "ພາບ" to "picture",
        "ອັລບັ້ມ" to "album",
        "ການນຳສະເໜີ" to "presentation",
        "ພາວເວີພອຍ" to "powerpoint",
        "ວິດີໂອ" to "video",
        "ວີດີໂອ" to "video",
        "ຮູບເງົາ" to "movie",
        "ໜັງ" to "movie",
        "ຄລິບ" to "clip",
        "ສື່" to "media",
        "ສຽງ" to "audio",
        "ແຖບລຸ່ມ" to "lower third",
        "ຊື່ແລະຕຳແໜ່ງ" to "name and title",
        "ປະກາດ" to "announcement",
        "ຕົວແລ່ນ" to "ticker",
        "ຫ້ອງເດັກ" to "kids room",
        "ນັບຖອຍຫຼັງ" to "countdown",
        "ໂມງຈັບເວລາ" to "timer",
        "ຕົວຈັບເວລາ" to "timer",
        "ຈັບເວລາ" to "timer",
        "ໂມງ" to "clock",
        "ເວລາປັດຈຸບັນ" to "current time",
        "ເວລາ" to "time",
        "ໂນ້ດ" to "notes",
        "ຄອດ" to "chord",
        "ຄຳແປ" to "translation",
        "ສອງພາສາ" to "bilingual",
        "ພາສາອື່ນ" to "another language",
        "ພາສາທີສອງ" to "second language",
        "ພາສາ" to "language",

        // Screens and outputs.
        "ເຕັມຈໍ" to "full screen",
        "ຈໍຫຼັກ" to "main screen",
        "ຈໍທີສອງ" to "second screen",
        "ຈໍສອງ" to "second screen",
        "ຈໍເທິງເວທີ" to "stage monitor",
        "ຈໍຢູ່ເວທີ" to "stage monitor",
        "ຈໍເວທີ" to "stage monitor",
        "ໜ້າຈໍ" to "screen",
        "ຈໍ" to "screen",
        "ໂປເຈັກເຕີ" to "projector",
        "ໂປຣເຈັກເຕີ" to "projector",
        "ເຄື່ອງສາຍ" to "projector",
        "ມໍນິເຕີ" to "monitor",
        "ມໍນີເຕີ" to "monitor",
        "ເອົາພຸດ" to "output",
        "ເວທີ" to "stage",
        "ໂຊນ" to "zone",
        "ເຂດ" to "zone",
        "ໂຄງຮ່າງ" to "layout",
        "ການຈັດວາງ" to "arrangement",
        "ສົ່ງຂໍ້ຄວາມ" to "send message",
        "ສົ່ງ" to "send",
        "ເບິ່ງກ່ອນ" to "preview",
        "ຕົວຢ່າງ" to "preview",
        "ໂປຣໄຟລ໌" to "profile",
        "ຖ່າຍທອດສົດ" to "stream",
        "ສະຕຣີມ" to "stream",
        "ໂທລະທັດ" to "tv",
        "ທີວີ" to "tv",

        // Pages, tabs and tools.
        "ການຕັ້ງຄ່າ" to "settings",
        "ໜ້າຕັ້ງຄ່າ" to "settings",
        "ຕົວເລືອກ" to "options",
        "ເລີ່ມຕົ້ນໃຊ້ງານ" to "setup wizard",
        "ເລີ່ມໃໝ່" to "start over",
        "ປຸ່ມລັດ" to "shortcut",
        "ແປ້ນລັດ" to "shortcut",
        "ທາງລັດ" to "shortcut",
        "ແປ້ນພິມ" to "keyboard",
        "ຄີບອດ" to "keyboard",
        "ແທັບເລັດ" to "tablet",
        "ແຖບ" to "tab",
        "ຄັງ" to "library",
        "ເວັບໄຊ" to "website",
        "ເວັບ" to "web",
        "ບຣາວເຊີ" to "browser",
        "ວັດຈະນານຸກົມ" to "dictionary",
        "ສະຕຣອງ" to "strong",
        "ກ້ອງ" to "camera",
        "ຜ້າໃບ" to "canvas",
        "ເຊີບເວີ" to "server",
        "ຣີໂມດ" to "remote",
        "ລີໂມດ" to "remote",
        "ໂທລະສັບ" to "phone",
        "ມືຖື" to "phone",

        // Services and planning.
        "ລຳດັບນະມັດສະການ" to "order of service",
        "ກຳນົດການ" to "order of service",
        "ການນະມັດສະການນີ້" to "this service",
        "ການນະມັດສະການ" to "service",
        "ລາຍການ" to "schedule",
        "ປະຊຸມ" to "meeting",
        "ທຸກວັນອາທິດ" to "every sunday",
        "ວັນອາທິດ" to "sunday",
        "ປະຕິທິນ" to "calendar",
        "ເພລລິສ" to "playlist",
        "ທຸກອາທິດ" to "every week",
        "ລາຍອາທິດ" to "weekly",
        "ທຸກເດືອນ" to "monthly",
        "ລາຍເດືອນ" to "monthly",
        "ເຮັດຊ້ຳ" to "repeat",
        "ຊ້ຳ" to "repeat",
        "ແມ່ແບບ" to "template",

        // Many, all, both.
        "ທັງໝົດ" to "all",
        "ທຸກຢ່າງ" to "everything",
        "ທັງສອງ" to "both",
        "ທຸກ" to "every",
        "ຫຼາຍ" to "several",
        "ພ້ອມກັນ" to "at once",
        "ມື້ນີ້" to "for today",
        "ຊົ່ວຄາວ" to "temporarily",

        // Languages, by name.
        "ພາສາລາວ" to "lao",
        "ພາສາໄທ" to "thai",
        "ອັງກິດ" to "english",
        "ສະເປນ" to "spanish",
        "ລັດເຊຍ" to "russian",
        "ຣັດເຊຍ" to "russian",
        "ຢູເຄຣນ" to "ukrainian",
        "ເບລາຣຸດ" to "belarusian",
        "ໂປແລນ" to "polish",
        "ເຢຍລະມັນ" to "german",
        "ຝຣັ່ງ" to "french",
        "ຝະລັ່ງ" to "french",
        "ປອກຕຸຍການ" to "portuguese",
        "ອີຕາລີ" to "italian",
        "ໂຣມາເນຍ" to "romanian",
        "ເຊັກ" to "czech",
        "ຮົງກາຣີ" to "hungarian",
        "ກຣີກ" to "greek",
        "ຕວກກີ" to "turkish",
        "ອາຣັບ" to "arabic",
        "ອາຫລັບ" to "arabic",
        "ເປີເຊຍ" to "persian",
        "ພາສາເຮັບເຣີ" to "hebrew",
        "ຮິນດີ" to "hindi",
        "ເນປານ" to "nepali",
        "ທະມິນ" to "tamil",
        "ຈີນກາງ" to "mandarin",
        "ກວາງຕຸ້ງ" to "cantonese",
        "ຈີນ" to "chinese",
        "ຍີ່ປຸ່ນ" to "japanese",
        "ເກົາຫຼີ" to "korean",
        "ຫວຽດນາມ" to "vietnamese",
        "ອິນໂດເນເຊຍ" to "indonesian",
        "ມາເລເຊຍ" to "malay",
        "ຕາກາລັອກ" to "tagalog",
        "ຟີລິບປິນ" to "filipino",
        "ສະວາຮີລີ" to "swahili",
        "ຄາຊັກ" to "kazakh",
        "ອຸສເບັກ" to "uzbek",
        "ຟິນແລນ" to "finnish",
        "ສວີເດນ" to "swedish",
        "ນອກແວ" to "norwegian",
        "ເດນມາກ" to "danish",
        "ລາແຕັງ" to "latin",

        // Colors.
        "ສີຟ້າເຂັ້ມ" to "navy",
        "ສີຟ້າອ່ອນ" to "light blue",
        "ຟ້າອ່ອນ" to "light blue",
        "ສີຟ້າ" to "blue",
        "ສີດຳ" to "black",
        "ສີຂາວ" to "white",
        "ຂາວ" to "white",
        "ສີເທົາ" to "grey",
        "ສີເງິນ" to "silver",
        "ສີແດງເຂັ້ມ" to "maroon",
        "ສີແດງ" to "red",
        "ແດງ" to "red",
        "ສີສົ້ມ" to "orange",
        "ສີເຫຼືອງ" to "yellow",
        "ເຫຼືອງ" to "yellow",
        "ສີຄຳ" to "gold",
        "ຂຽວເຂັ້ມ" to "dark green",
        "ຂຽວອ່ອນ" to "light green",
        "ສີຂຽວ" to "green",
        "ຂຽວ" to "green",
        "ສີມ່ວງ" to "purple",
        "ມ່ວງ" to "purple",
        "ສີບົວ" to "pink",
        "ສີນ້ຳຕານ" to "brown",
        "ສີຄີມ" to "cream",
        "ສີເຂັ້ມ" to "dark",
        "ສີອ່ອນ" to "light",

        // Talking to the helper.
        "ສະບາຍດີ" to "hello",
        "ຊ່ວຍແດ່" to "help",
        "ຊ່ວຍດ້ວຍ" to "help",
        "ຊ່ວຍ" to "help",
        "ເຈົ້າເຮັດຫຍັງໄດ້ແດ່" to "what can you do",
        "ເຮັດຫຍັງໄດ້ແດ່" to "what can you do",
        "ເຮັດຫຍັງໄດ້" to "what can you do",
        "ເຈົ້າແມ່ນໃຜ" to "who are you",
        "ເຈົ້າເປັນໃຜ" to "who are you",
        "ຂອບໃຈຫຼາຍ" to "thank you",
        "ຂອບໃຈ" to "thanks",
        "ກະລຸນາ" to "please",
        "ແດ່" to "please",
        "ເດີ" to "please",
        "ວິກ" to "wick",

        // Newer requests.
        "ຄົ້ນຫາພຣະຄຳພີ" to "search the bible",
        "ຊອກຫາພຣະຄຳພີ" to "search the bible",
        "ຄົ້ນຫາຂໍ້ພຣະຄຳພີ" to "search verse",
        "ຕົວໜັງສື" to "text",
        "ເພງໝາຍເລກ" to "song number",
        "ເພງເລກ" to "song number",
        "ເພງຊື່" to "song called",
        "ຕາມໝາຍເລກ" to "by number",
        "ຕາມຊື່ເພງ" to "by title",
        "ໝາຍເລກ" to "number",
        "ເພງທີ່ມັກ" to "favorite song",
        "ລາຍການທີ່ມັກ" to "favorites",
        "ທີ່ມັກ" to "favorite",
        "ແຕ່ລະເພງ" to "each song",
        "ຫຼາຍຂໍ້" to "several verses",
        "ເມື່ອກີ້ເຮົາສະແດງຫຍັງ" to "what did we just show",
        "ເມື່ອກີ້ສະແດງຫຍັງ" to "what did we just show",
        "ປະຫວັດ" to "history",
        "ຂໍ້ທີ່ກ່ຽວຂ້ອງ" to "related verses",
        "ຂໍ້ອ້າງອີງ" to "cross references",
        "ໜ້າເວັບ" to "web page",
        "ແພລນນິງເຊັນເຕີ" to "planning center",
        "ສະຖິຕິ" to "statistics",
        "ຈັກເທື່ອ" to "how many times",
        "ເລື້ອຍປານໃດ" to "how often",
        "ຈາກໂທລະສັບ" to "from my phone",
        "ຈາກມືຖື" to "from my phone",
        "ໃນໂທລະສັບ" to "on my phone",
        "ຄິວອາໂຄດ" to "qr code",
        "ຄວບຄຸມ" to "control",
        "ວິນາທີ" to "seconds",
        "ນາທີ" to "minutes",
        "ປະກາດ:" to "announce",
        "ປະກາດວ່າ" to "announce",
        "ໃສ່ລາຍການ" to "to the schedule",
        "ເຂົ້າລາຍການ" to "to the schedule",
        "ໃນລາຍການ" to "in the schedule",
        "ລາຍການຖັດໄປ" to "next item",
        "ລາຍການກ່ອນໜ້າ" to "previous item",
        "ຫົວຂໍ້" to "item",
        "ຄຳເທດສະໜາ" to "sermon",
        "ເທດສະໜາ" to "sermon",
        "ຫຍັງຢູ່ເທິງຈໍ" to "what is on screen",
        "ຫຍັງຢູ່ໜ້າຈໍ" to "what is on screen",
        "ສະໄລດ໌ໂຊວ໌" to "slideshow",
        "ສະໄລໂຊວ໌" to "slideshow",
        "ເຮັດແຖບລຸ່ມ" to "make a lower third",
        "ເວີຊັນຫຍັງ" to "what version",
        "ເວີຊັນໃດ" to "which version",
        "ເວີຊັນລ່າສຸດ" to "latest version",
        "ກວດສອບອັບເດດ" to "check for updates",
        "ລາຍການຄຳສັ່ງ" to "list of commands",
        "ຄຳສັ່ງ" to "commands",

        // Look requests.
        "ແກ້ໄຂເນື້ອເພງ" to "edit lyrics",
        "ແກ້ເນື້ອເພງ" to "fix the lyrics",
        "ປ່ຽນເນື້ອເພງ" to "change the lyrics",
        "ພິມຜິດ" to "typo",
        "ເຄື່ອງໝາຍຈົບເພງ" to "end of song marker",
        "ເຄື່ອງໝາຍທ້າຍເພງ" to "end of song marker",
        "ຈົບເພງ" to "end of song",
        "ທ້າຍເພງ" to "end of the song",
        "ຊື່ເພງ" to "song title",
        "ອ້າງອີງ" to "reference",
        "ໂຕໜາ" to "bold",
        "ຕົວໜາ" to "bold",
        "ໂຕເອນ" to "italic",
        "ຕົວເອນ" to "italic",
        "ຂີດກ້ອງ" to "underline",
        "ເສັ້ນຂອບ" to "outline",
        "ເງົາ" to "shadow",
        "ໄລຍະຂອບ" to "margins",
        "ຂອບຈໍ" to "edges",
        "ດ້ານເທິງ" to "top",
        "ທາງເທິງ" to "top",
        "ດ້ານລຸ່ມ" to "bottom",
        "ທາງລຸ່ມ" to "bottom",
        "ເຄິ່ງກາງ" to "center",
        "ຕົງກາງ" to "center",
        "ກາງຈໍ" to "center",
        "ຊິດຊ້າຍ" to "align left",
        "ຊິດຂວາ" to "align right",
        "ຈັດຕຳແໜ່ງ" to "alignment",
        "ຕຳແໜ່ງ" to "position",
        "ຮູບແບບຕົວອັກສອນ" to "typeface",
        "ຮູບແບບ" to "style",
        "ສະໄຕລ໌" to "style",
        "ໜ້າຕາ" to "look",
        "ຮູບລັກ" to "appearance",
        "ສີຕົວອັກສອນ" to "text color",

        // The help table's own examples.
        "ເພງ" to "song",
        "ພໍ່ແມ່" to "parents",
    ),
    spaced = false,
)
