package org.churchpresenter.helper.intent.glossary

internal val LATVIAN = Glossary(
    "lv",
    listOf(
        // Asking where, or how.
        "kur" to "where",
        "kur atrast" to "where",
        "kur ir" to "where",
        "kā es varu" to "how can i",
        "ka es varu" to "how can i",
        "kā var" to "how can i",
        "kā lai" to "how do i",
        "ka lai" to "how do i",
        "kā" to "how do i",
        "nevaru atrast" to "can't find",
        "neatrodu" to "can't find",
        "parādi man" to "show me",
        "paradi man" to "show me",
        "parādiet man" to "show me",

        // Doing.
        "parādi*" to "show",
        "paradi*" to "show",
        "rādīt ekrānā" to "go live",
        "radit ekrana" to "go live",
        "rādīt*" to "show",
        "radit*" to "show",
        "rādi" to "show",
        "radi" to "show",
        "attēlo*" to "display",
        "attelo*" to "display",
        "atver*" to "open",
        "atvērt" to "open",
        "aiziet uz" to "go to",
        "pāriet uz" to "go to",
        "pariet uz" to "go to",
        "pārej uz" to "go to",
        "parej uz" to "go to",
        "pārslēdz uz" to "switch to",
        "parsledz uz" to "switch to",
        "pārslēgties uz" to "switch to",
        "meklē*" to "find",
        "mekle*" to "find",
        "atrodi" to "find",
        "atrast" to "find",
        "lasi" to "read",
        "nolasi" to "read",
        "izveido*" to "create",
        "uztaisi*" to "make",
        "taisi" to "make",
        "pievieno*" to "add",
        "ielādē*" to "load",
        "ielade*" to "load",
        "importē*" to "import",
        "importe*" to "import",
        "lejupielādē*" to "download",
        "lejupielade*" to "download",
        "instalē*" to "install",
        "instale*" to "install",
        "izvēlies" to "choose",
        "izvēlēties" to "choose",
        "izvēlē*" to "choose",
        "izvele*" to "choose",
        "izvelies" to "choose",
        "iestatījum*" to "settings",
        "iestatijum*" to "settings",
        "iestatī*" to "set up",
        "iestati*" to "set up",
        "konfigurē*" to "set up",
        "konfigure*" to "set up",
        "pieslēdz*" to "connect",
        "piesledz*" to "connect",
        "savieno*" to "connect",
        "piešķir*" to "assign",
        "pieskir*" to "assign",
        "paslēp*" to "hide",
        "paslep*" to "hide",
        "aptur*" to "stop",
        "beidz*" to "stop",
        "dzēs*" to "delete",
        "dzes*" to "delete",
        "noņem*" to "remove",
        "nonem*" to "remove",
        "notīr*" to "clear",
        "notir*" to "clear",
        "aptumšo*" to "black out",
        "aptumso*" to "black out",
        "tukšs ekrāns" to "blank",
        "tukss ekrans" to "blank",
        "atsauc*" to "undo",
        "atcel*" to "undo",
        "ēterā" to "go live",
        "etera" to "go live",
        "ieslēdz*" to "turn on",
        "iesledz*" to "turn on",
        "izslēdz*" to "turn off",
        "izsledz*" to "turn off",
        "pārslēdz*" to "toggle",
        "parsledz*" to "toggle",
        "nākam*" to "next",
        "nakam*" to "next",
        "tālāk" to "next",
        "talak" to "next",
        "uz priekšu" to "forward",
        "uz prieksu" to "forward",
        "iepriekšēj*" to "previous",
        "ieprieksej*" to "previous",
        "atpakaļ" to "back",
        "atpakal" to "back",
        "palielin*" to "increase",
        "lielāk*" to "bigger",
        "lielak*" to "bigger",
        "samazin*" to "decrease",
        "mazāk*" to "smaller",
        "mazak*" to "smaller",
        "konvertētāj*" to "converter",
        "konvertetaj*" to "converter",
        "konvertē*" to "convert",
        "konverte*" to "convert",
        "pārnes*" to "transfer",
        "parnes*" to "transfer",
        "pārcel*" to "transfer",
        "rediģē*" to "edit",
        "redige*" to "edit",
        "maini*" to "change",
        "mainīt" to "change",
        "izmaini*" to "change",
        "pārdēvē*" to "rename",
        "pardeve*" to "rename",
        "izlabo*" to "fix",
        "salabo*" to "fix",
        "sakārto*" to "organize",
        "sakarto*" to "organize",
        "organizē*" to "organize",
        "satīr*" to "clean up",
        "salīdzin*" to "compare",
        "salidzin*" to "compare",
        "tulkojum*" to "translation",
        "tulko*" to "translate",
        "ieplāno*" to "plan",
        "plāno*" to "plan",
        "plano*" to "plan",
        "automatizē*" to "automate",
        "automatize*" to "automate",
        "automātisk*" to "automatically",
        "automatisk*" to "automatically",
        "identificē*" to "identify",
        "nosaki" to "identify",
        "numurē*" to "number the",
        "numure*" to "number the",

        // Too small, too big, not working.
        "pārāk maz*" to "too small",
        "parak maz*" to "too small",
        "grūti lasīt" to "hard to read",
        "gruti lasit" to "hard to read",
        "grūti izlasīt" to "hard to read",
        "slikti redzams" to "hard to read",
        "slikti salasāms" to "hard to read",
        "pārāk liel*" to "too big",
        "parak liel*" to "too big",
        "neietilpst" to "doesn't fit",
        "nesaiet" to "doesn't fit",
        "nedarbojas" to "not working",
        "nestrādā" to "not working",
        "nestrada" to "not working",
        "nerāda" to "not showing",
        "nerada" to "not showing",
        "neko nerāda" to "nothing shows",
        "neko nerada" to "nothing shows",
        "nekas nav redzams" to "nothing shows",
        "melns ekrāns" to "screen is black",
        "melns ekrans" to "screen is black",
        "ekrāns ir melns" to "screen is black",
        "nav signāla" to "no signal",
        "nav signala" to "no signal",
        "nav attēla" to "no picture",
        "nav attela" to "no picture",
        "kurš ekrāns" to "which screen",
        "kurs ekrans" to "which screen",
        "kurš monitors" to "which monitor",
        "kurš projektors" to "which projector",

        // What is on screen.
        "fons" to "background",
        "fonu" to "background",
        "fonā" to "background",
        "fona" to "background",
        "fonam" to "background",
        "fona attēl*" to "background",
        "dziesmu vārdi" to "lyrics",
        "dziesmas vārdi" to "lyrics",
        "dziesmas vardi" to "lyrics",
        "dziesmu vardi" to "lyrics",
        "dziesm*" to "song",
        "garīgā dziesm*" to "hymn",
        "garīgās dziesm*" to "hymn",
        "garīgo dziesm*" to "hymn",
        "gariga dziesm*" to "hymn",
        "slavēšan*" to "worship",
        "slavesan*" to "worship",
        "pielūgsm*" to "worship",
        "bībel*" to "bible",
        "bibel*" to "bible",
        "svētie raksti" to "scripture",
        "svēto rakstu" to "scripture",
        "svētajos rakstos" to "scripture",
        "svetie raksti" to "scripture",
        "svetajos rakstos" to "scripture",
        "pants" to "verse",
        "panti" to "verse",
        "pantu" to "verse",
        "pantus" to "verse",
        "nodaļ*" to "chapter",
        "nodal*" to "chapter",
        "fonta izmēr*" to "font size",
        "fonta izmer*" to "font size",
        "burtu izmēr*" to "font size",
        "teksta izmēr*" to "text size",
        "fonts" to "font",
        "fonta" to "font",
        "fontu" to "font",
        "šrift*" to "font",
        "izmēr*" to "size",
        "izmer*" to "size",
        "teksts" to "text",
        "tekst*" to "text",
        "vārdi" to "words",
        "vardi" to "words",
        "burti" to "letters",
        "burtus" to "letters",
        "slaidrād*" to "slideshow",
        "slaidrad*" to "slideshow",
        "slaid*" to "slide",
        "fotogrāfij*" to "photo",
        "fotografij*" to "photo",
        "foto*" to "photo",
        "attēl*" to "picture",
        "attel*" to "picture",
        "bilde*" to "picture",
        "albūm*" to "album",
        "albumu" to "album",
        "prezentācij*" to "presentation",
        "prezentacij*" to "presentation",
        "videoklip*" to "clip",
        "filma*" to "movie",
        "filmu" to "movie",
        "klip*" to "clip",
        "multivid*" to "media",
        "mediji" to "media",
        "apakšjosl*" to "lower third",
        "apaksjosl*" to "lower third",
        "vārda josl*" to "name strap",
        "varda josl*" to "name strap",
        "vārds un amats" to "name and title",
        "paziņojum*" to "announcement",
        "pazinojum*" to "announcement",
        "slīdošais teksts" to "ticker",
        "slidosais teksts" to "ticker",
        "skrejošā rinda" to "ticker",
        "bērnu istab*" to "kids room",
        "bernu istab*" to "kids room",
        "svētdienas skol*" to "kids room",
        "atpakaļskaitīšan*" to "countdown",
        "atpakalskaitisan*" to "countdown",
        "atskait*" to "countdown",
        "taimer*" to "timer",
        "hronometr*" to "stopwatch",
        "pašreizējais laiks" to "current time",
        "pulkstenis" to "clock",
        "pulkst*" to "clock",
        "laiks" to "time",
        "laiku" to "time",
        "piezīm*" to "notes",
        "piezim*" to "notes",
        "akord*" to "chord",
        "valod*" to "language",
        "divvalod*" to "bilingual",
        "citā valodā" to "another language",
        "cita valoda" to "another language",
        "otrā valoda" to "second language",
        "otra valoda" to "second language",
        "divās valodās" to "two languages",
        "divas valodas" to "two languages",

        // Screens and outputs.
        "galvenais ekrān*" to "main screen",
        "galveno ekrān*" to "main screen",
        "galvenajā ekrān*" to "main screen",
        "galvenais ekran*" to "main screen",
        "galveno ekran*" to "main screen",
        "pilnekrān*" to "full screen",
        "pilnekran*" to "full screen",
        "pilnā ekrānā" to "full screen",
        "visā ekrānā" to "full screen",
        "otrais ekrān*" to "second screen",
        "otro ekrān*" to "second screen",
        "otrajā ekrān*" to "second screen",
        "otrais ekran*" to "second screen",
        "otro ekran*" to "second screen",
        "ekrān*" to "screen",
        "ekran*" to "screen",
        "projektor*" to "projector",
        "skatuves monitor*" to "stage monitor",
        "skatuves ekrān*" to "stage monitor",
        "monitori" to "monitor",
        "monitoru" to "monitor",
        "displej*" to "display",
        "izvades log*" to "output window",
        "izvad*" to "output",
        "skatuv*" to "stage",
        "zona" to "zone",
        "zonas" to "zone",
        "zonu" to "zone",
        "zonā" to "zone",
        "izkārtojum*" to "layout",
        "izkartojum*" to "layout",
        "novietojum*" to "arrangement",
        "ziņa" to "message",
        "ziņu" to "message",
        "ziņas" to "message",
        "zinu" to "message",
        "ziņojum*" to "message",
        "nosūti*" to "send",
        "nosuti*" to "send",
        "sūti*" to "send",
        "suti*" to "send",
        "priekšskatījum*" to "preview",
        "prieksskatijum*" to "preview",
        "kas ir ekrānā" to "what is on screen",
        "profil*" to "profile",
        "tiešraid*" to "stream",
        "tiesraid*" to "stream",
        "straum*" to "stream",
        "televizor*" to "tv",

        // Pages, tabs and tools.
        "opcij*" to "options",
        "iestatīšanas vednis" to "setup wizard",
        "vednis" to "setup wizard",
        "sākt no jauna" to "start over",
        "sakt no jauna" to "start over",
        "īsinājumtaustiņ*" to "shortcut",
        "isinajumtaustin*" to "shortcut",
        "karstie taustiņi" to "hotkeys",
        "tastatūr*" to "keyboard",
        "tastatur*" to "keyboard",
        "cilne" to "tab",
        "ciln*" to "tab",
        "dziesmu bibliotēk*" to "song library",
        "dziesmu bibliotek*" to "song library",
        "bibliotēk*" to "library",
        "bibliotek*" to "library",
        "tīmekļa vietn*" to "website",
        "timekla vietn*" to "website",
        "vietn*" to "website",
        "tīmekl*" to "web",
        "timekl*" to "web",
        "pārlūk*" to "browser",
        "parluk*" to "browser",
        "vārdnīc*" to "dictionary",
        "vardnic*" to "dictionary",
        "kamer*" to "camera",
        "audekl*" to "canvas",
        "server*" to "server",
        "tālvadīb*" to "remote",
        "talvadib*" to "remote",
        "pults" to "remote",
        "tālrun*" to "phone",
        "talrun*" to "phone",
        "telefon*" to "phone",
        "planšet*" to "tablet",
        "planset*" to "tablet",
        "integrācij*" to "integrations",
        "integracij*" to "integrations",

        // Services and planning.
        "dievkalpojuma kārtība" to "order of service",
        "dievkalpojuma kartiba" to "order of service",
        "norises kārtīb*" to "order of service",
        "norises kartib*" to "order of service",
        "dievkalpojum*" to "service",
        "sapulc*" to "meeting",
        "svētdien*" to "sunday",
        "svetdien*" to "sunday",
        "kalendār*" to "calendar",
        "kalendar*" to "calendar",
        "programm*" to "schedule",
        "atskaņošanas sarakst*" to "playlist",
        "katru svētdienu" to "every sunday",
        "katru svetdienu" to "every sunday",
        "katru nedēļu" to "every week",
        "katru nedelu" to "every week",
        "iknedēļ*" to "weekly",
        "iknedel*" to "weekly",
        "ikmēneš*" to "monthly",
        "ikmenes*" to "monthly",
        "atkārto*" to "repeat",
        "atkarto*" to "repeat",
        "veidn*" to "template",

        // Many, all, both.
        "visi" to "all",
        "visus" to "all",
        "visas" to "all",
        "viss" to "everything",
        "visu" to "all",
        "visur" to "everything",
        "abi" to "both",
        "abus" to "both",
        "abas" to "both",
        "vairāki" to "several",
        "vairākus" to "several",
        "vairaki" to "several",
        "daudz" to "many",
        "uzreiz" to "at once",
        "vienlaikus" to "at once",
        "šim dievkalpojumam" to "this service",
        "sim dievkalpojumam" to "this service",
        "šodienai" to "for today",
        "šodien" to "for today",
        "sodien" to "for today",
        "īslaicīgi" to "temporarily",
        "islaicigi" to "temporarily",
        "pagaidām" to "for now",
        "pagaidam" to "for now",

        // Languages, by name.
        "krievu" to "russian",
        "krieviski" to "russian",
        "ukraiņu" to "ukrainian",
        "ukrainu" to "ukrainian",
        "baltkrievu" to "belarusian",
        "angļu" to "english",
        "anglu" to "english",
        "angliski" to "english",
        "spāņu" to "spanish",
        "spanu" to "spanish",
        "vācu" to "german",
        "vacu" to "german",
        "franču" to "french",
        "francu" to "french",
        "poļu" to "polish",
        "polu" to "polish",
        "kazahu" to "kazakh",
        "rumāņu" to "romanian",
        "rumanu" to "romanian",
        "moldāvu" to "moldovan",
        "portugāļu" to "portuguese",
        "itāļu" to "italian",
        "italu" to "italian",
        "nīderlandiešu" to "dutch",
        "holandiešu" to "dutch",
        "čehu" to "czech",
        "cehu" to "czech",
        "slovāku" to "slovak",
        "horvātu" to "croatian",
        "serbu" to "serbian",
        "bulgāru" to "bulgarian",
        "ungāru" to "hungarian",
        "grieķu" to "greek",
        "turku" to "turkish",
        "arābu" to "arabic",
        "persiešu" to "persian",
        "ebreju" to "hebrew",
        "ķīniešu" to "chinese",
        "kiniesu" to "chinese",
        "japāņu" to "japanese",
        "korejiešu" to "korean",
        "vjetnamiešu" to "vietnamese",
        "indonēziešu" to "indonesian",
        "igauņu" to "estonian",
        "igaunu" to "estonian",
        "latviešu" to "latvian",
        "latviesu" to "latvian",
        "latviski" to "latvian",
        "lietuviešu" to "lithuanian",
        "lietuviesu" to "lithuanian",
        "somu" to "finnish",
        "zviedru" to "swedish",
        "norvēģu" to "norwegian",
        "norvegu" to "norwegian",
        "dāņu" to "danish",
        "armēņu" to "armenian",
        "gruzīnu" to "georgian",
        "latīņu" to "latin",

        // Colors.
        "tumši zil*" to "navy",
        "tumsi zil*" to "navy",
        "tumšzil*" to "navy",
        "gaiši zil*" to "light blue",
        "gaisi zil*" to "light blue",
        "gaišzil*" to "light blue",
        "debeszil*" to "sky",
        "zils" to "blue",
        "zilu" to "blue",
        "zila*" to "blue",
        "zilā" to "blue",
        "melns" to "black",
        "melnu" to "black",
        "melna*" to "black",
        "melnā" to "black",
        "balts" to "white",
        "baltu" to "white",
        "balta*" to "white",
        "baltā" to "white",
        "gaiši pelēk*" to "light grey",
        "tumši pelēk*" to "dark grey",
        "pelēk*" to "grey",
        "pelek*" to "grey",
        "sudrab*" to "silver",
        "tumši sarkan*" to "maroon",
        "bordo*" to "maroon",
        "sarkan*" to "red",
        "oranž*" to "orange",
        "oranz*" to "orange",
        "dzelten*" to "yellow",
        "zelt*" to "gold",
        "gaiši zaļ*" to "lime",
        "gaisi zal*" to "lime",
        "tumši zaļ*" to "dark green",
        "zaļš" to "green",
        "zaļu" to "green",
        "zaļa*" to "green",
        "zaļā" to "green",
        "zals" to "green",
        "zalu" to "green",
        "tirkīz*" to "turquoise",
        "tirkiz*" to "turquoise",
        "violet*" to "violet",
        "purpur*" to "purple",
        "lillā" to "purple",
        "lilla" to "purple",
        "rozā" to "pink",
        "roza" to "pink",
        "brūn*" to "brown",
        "bēš*" to "beige",
        "krēmkrās*" to "cream",
        "krēmīg*" to "cream",
        "tumš*" to "dark",
        "tums*" to "dark",
        "gaiš*" to "light",
        "gais*" to "light",

        // Talking to the helper.
        "sveiki" to "hello",
        "sveiks" to "hello",
        "labdien" to "hello",
        "labrīt" to "hello",
        "labrit" to "hello",
        "čau" to "hello",
        "cau" to "hello",
        "palīdz*" to "help",
        "palidz*" to "help",
        "ko tu proti" to "what can you do",
        "ko tu vari" to "what can you do",
        "ko tu māki" to "what can you do",
        "kas tu esi" to "who are you",
        "paldies" to "thanks",
        "liels paldies" to "thank you",
        "lūdzu" to "please",
        "ludzu" to "please",
        "viks" to "wick",
    ),
)
