package org.churchpresenter.helper.intent.glossary

internal val MALAY = Glossary(
    "ms",
    listOf(
        // Asking where, or how.
        "di mana" to "where",
        "dimana" to "where",
        "ke mana" to "where",
        "kat mana" to "where",
        "bagaimana cara" to "how do i",
        "bagaimana caranya" to "how do i",
        "bagaimana saya boleh" to "how can i",
        "bagaimana saya" to "how do i",
        "bagaimana" to "how do i",
        "macam mana" to "how do i",
        "camne" to "how do i",
        "camana" to "how do i",
        "cara nak" to "how do i",
        "tak jumpa" to "can't find",
        "tidak jumpa" to "can't find",
        "tak dapat cari" to "can't find",
        "tidak dapat mencari" to "can't find",
        "tak dapat jumpa" to "can't find",
        "tunjukkan saya" to "show me",
        "tunjuk saya" to "show me",
        "tolong tunjukkan" to "show me",

        // Doing.
        "tunjukkan" to "show",
        "tunjuk" to "show",
        "menunjukkan" to "show",
        "papar*" to "display",
        "memapar*" to "display",
        "tayangkan" to "show",
        "letak" to "put",
        "letakkan" to "put",
        "buka*" to "open",
        "membuka*" to "open",
        "pergi ke" to "go to",
        "masuk ke" to "go to",
        "tukar ke" to "switch to",
        "beralih ke" to "switch to",
        "pindah ke" to "switch to",
        "cari" to "find",
        "carikan" to "find",
        "mencari" to "find",
        "jumpa*" to "find",
        "baca" to "read",
        "bacakan" to "read",
        "membaca" to "read",
        "buat*" to "make",
        "membuat*" to "make",
        "cipta*" to "create",
        "mencipta*" to "create",
        "tambah*" to "add",
        "menambah*" to "add",
        "masukkan" to "add",
        "muat turun" to "download",
        "muat naik" to "upload",
        "muatkan" to "load",
        "memuatkan" to "load",
        "pasang*" to "install",
        "memasang*" to "install",
        "pilih" to "choose",
        "pilihlah" to "choose",
        "memilih" to "choose",
        "tetapkan" to "set up",
        "sediakan" to "set up",
        "sambung*" to "connect",
        "menyambung*" to "connect",
        "sembunyi*" to "hide",
        "menyembunyikan" to "hide",
        "buang" to "remove",
        "keluarkan" to "remove",
        "henti*" to "stop",
        "berhenti" to "stop",
        "jeda" to "pause",
        "padam*" to "delete",
        "memadam*" to "delete",
        "kosongkan" to "clear",
        "bersihkan" to "clear",
        "gelapkan skrin" to "black out",
        "gelapkan" to "black out",
        "skrin kosong" to "blank",
        "batal*" to "undo",
        "buat asal" to "undo",
        "kembalikan" to "undo",
        "siar langsung" to "go live",
        "siarkan langsung" to "go live",
        "siarkan" to "go live",
        "hidupkan" to "turn on",
        "aktifkan" to "turn on",
        "matikan" to "turn off",
        "nyahaktifkan" to "turn off",
        "seterusnya" to "next",
        "berikutnya" to "next",
        "maju" to "forward",
        "sebelumnya" to "previous",
        "sebelum ini" to "previous",
        "kembali" to "back",
        "undur" to "back",
        "besarkan" to "enlarge",
        "membesarkan" to "enlarge",
        "lebih besar" to "bigger",
        "naikkan" to "increase",
        "tingkatkan" to "increase",
        "kecilkan" to "shrink",
        "mengecilkan" to "shrink",
        "lebih kecil" to "smaller",
        "kurangkan" to "decrease",
        "turunkan" to "decrease",
        "penukar" to "converter",
        "tukar format" to "convert",
        "tukarkan" to "convert",
        "pindahkan" to "transfer",
        "memindahkan" to "transfer",
        "sunting" to "edit",
        "menyunting" to "edit",
        "namakan semula" to "rename",
        "tukar nama" to "rename",
        "tukar*" to "change",
        "menukar*" to "change",
        "ubah*" to "change",
        "mengubah*" to "change",
        "betulkan" to "fix",
        "baiki" to "fix",
        "membaiki" to "fix",
        "susun atur" to "layout",
        "susun*" to "organize",
        "menyusun*" to "organize",
        "kemaskan" to "organize",
        "bandingkan" to "compare",
        "terjemahan*" to "translation",
        "terjemah*" to "translate",
        "menterjemah*" to "translate",
        "rancang*" to "plan",
        "merancang*" to "plan",
        "automatikkan" to "automate",
        "automatik" to "automatically",
        "secara automatik" to "automatically",
        "kenal pasti" to "identify",
        "nomborkan" to "number the",
        "beri nombor" to "number the",

        // Too small, too big, not working.
        "terlalu kecil" to "too small",
        "kecil sangat" to "too small",
        "susah nak baca" to "hard to read",
        "susah dibaca" to "hard to read",
        "sukar dibaca" to "hard to read",
        "tak nampak" to "hard to read",
        "tidak nampak" to "hard to read",
        "tak boleh baca" to "can't read",
        "terlalu besar" to "too big",
        "besar sangat" to "too big",
        "tak muat" to "doesn't fit",
        "tidak muat" to "doesn't fit",
        "tak berfungsi" to "not working",
        "tidak berfungsi" to "not working",
        "tak jalan" to "not working",
        "rosak" to "not working",
        "tak keluar" to "not showing",
        "tidak keluar" to "not showing",
        "tak muncul" to "not showing",
        "tidak muncul" to "not showing",
        "tiada apa-apa" to "nothing shows",
        "tak ada apa-apa" to "nothing shows",
        "tiada apa yang keluar" to "nothing shows",
        "skrin hitam" to "screen is black",
        "tiada isyarat" to "no signal",
        "tiada signal" to "no signal",
        "tiada gambar" to "no picture",
        "skrin mana" to "which screen",
        "skrin yang mana" to "which screen",
        "monitor mana" to "which monitor",
        "projektor mana" to "which projector",

        // What is on screen.
        "latar belakang*" to "background",
        "latar*" to "background",
        "lirik*" to "lyrics",
        "lagu*" to "song",
        "nyanyian" to "song",
        "kidung agung" to "kidung agung",
        "himne" to "hymn",
        "lagu pujian" to "worship",
        "pujian" to "worship",
        "penyembahan" to "worship",
        "alkitab*" to "bible",
        "kitab suci" to "scripture",
        "firman" to "scripture",
        "ayat*" to "verse",
        "pasal*" to "chapter",
        "bab" to "chapter",
        "saiz fon" to "font size",
        "saiz tulisan" to "font size",
        "jenis fon" to "font",
        "fon" to "font",
        "saiz*" to "size",
        "teks*" to "text",
        "tulisan*" to "writing",
        "huruf" to "letters",
        "perkataan" to "words",
        "tayangan slaid" to "slideshow",
        "slaid*" to "slide",
        "foto*" to "photo",
        "gambar*" to "picture",
        "imej" to "image",
        "persembahan*" to "presentation",
        "pembentangan" to "presentation",
        "filem*" to "movie",
        "klip*" to "clip",
        "bunyi" to "audio",
        "nama dan jawatan" to "name and title",
        "pengumuman*" to "announcement",
        "makluman" to "notice",
        "teks bergerak" to "ticker",
        "bilik kanak-kanak" to "kids room",
        "sekolah minggu" to "kids room",
        "kiraan detik" to "countdown",
        "kira detik" to "countdown",
        "undur masa" to "countdown",
        "pemasa" to "timer",
        "jam randik" to "stopwatch",
        "jam dinding" to "clock",
        "masa sekarang" to "current time",
        "masa" to "time",
        "nota" to "notes",
        "kord*" to "chord",
        "bahasa lain" to "another language",
        "bahasa kedua" to "second language",
        "dua bahasa" to "two languages",
        "dwibahasa" to "bilingual",
        "bahasa*" to "language",

        // Screens and outputs.
        "skrin utama" to "main screen",
        "skrin penuh" to "full screen",
        "skrin kedua" to "second screen",
        "skrin*" to "screen",
        "projektor*" to "projector",
        "monitor pentas" to "stage monitor",
        "skrin pentas" to "stage monitor",
        "tetingkap output" to "output window",
        "pentas*" to "stage",
        "zon" to "zone",
        "susunan" to "arrangement",
        "mesej*" to "message",
        "hantar*" to "send",
        "menghantar*" to "send",
        "pratonton" to "preview",
        "apa di skrin" to "what is on screen",
        "apa yang ada di skrin" to "what is on screen",
        "profil*" to "profile",
        "strim*" to "stream",
        "penstriman" to "stream",
        "televisyen" to "tv",

        // Pages, tabs and tools.
        "tetapan*" to "settings",
        "pilihan" to "options",
        "keutamaan" to "preferences",
        "wizard persediaan" to "setup wizard",
        "mula menggunakan" to "getting started",
        "mula semula" to "start over",
        "pintasan*" to "shortcut",
        "kekunci pintas" to "hotkeys",
        "papan kekunci" to "keyboard",
        "perpustakaan lagu" to "song library",
        "pustaka lagu" to "song library",
        "perpustakaan" to "library",
        "pustaka" to "library",
        "laman web" to "website",
        "pelayar" to "browser",
        "kamus" to "dictionary",
        "kamera*" to "camera",
        "kanvas" to "canvas",
        "pelayan" to "server",
        "kawalan jauh" to "remote",
        "alat kawalan jauh" to "remote",
        "telefon*" to "phone",
        "integrasi" to "integrations",

        // Services and planning.
        "aturcara ibadah" to "order of service",
        "atur cara ibadah" to "order of service",
        "susunan ibadah" to "order of service",
        "aturcara kebaktian" to "order of service",
        "aturcara" to "schedule",
        "jadual*" to "schedule",
        "ibadah*" to "service",
        "kebaktian" to "service",
        "perjumpaan" to "meeting",
        "persekutuan" to "meeting",
        "hari ahad" to "sunday",
        "ahad" to "sunday",
        "kalendar*" to "calendar",
        "senarai main" to "playlist",
        "setiap ahad" to "every sunday",
        "tiap-tiap ahad" to "every sunday",
        "setiap minggu" to "every week",
        "mingguan" to "weekly",
        "bulanan" to "monthly",
        "ulang" to "repeat",
        "ulangi" to "repeat",
        "berulang" to "repeat",
        "templat" to "template",

        // Many, all, both.
        "semua*" to "all",
        "seluruh" to "all",
        "kedua-duanya" to "both",
        "kedua dua" to "both",
        "dua-dua" to "both",
        "beberapa" to "several",
        "banyak" to "many",
        "serentak" to "at once",
        "sekali gus" to "at once",
        "sekaligus" to "at once",
        "untuk ibadah ini" to "this service",
        "untuk hari ini" to "for today",
        "buat sementara" to "temporarily",
        "sementara" to "temporarily",
        "buat masa ini" to "for now",
        "buat sekarang" to "for now",

        // Languages, by name.
        "bahasa inggeris" to "english",
        "inggeris" to "english",
        "bahasa sepanyol" to "spanish",
        "sepanyol" to "spanish",
        "bahasa rusia" to "russian",
        "rusia" to "russian",
        "jerman" to "german",
        "perancis" to "french",
        "bahasa poland" to "polish",
        "portugis" to "portuguese",
        "bahasa itali" to "italian",
        "belanda" to "dutch",
        "yunani" to "greek",
        "bahasa turki" to "turkish",
        "bahasa arab" to "arabic",
        "bahasa cina" to "chinese",
        "jepun" to "japanese",
        "bahasa korea" to "korean",
        "bahasa indonesia" to "indonesian",
        "bahasa melayu" to "malay",
        "melayu" to "malay",
        "bahasa latin" to "latin",

        // Colors.
        "biru tua" to "navy",
        "biru gelap" to "navy",
        "biru muda" to "light blue",
        "biru langit" to "light blue",
        "biru kehijauan" to "teal",
        "biru*" to "blue",
        "hitam*" to "black",
        "putih*" to "white",
        "kelabu*" to "grey",
        "perak" to "silver",
        "merah tua" to "maroon",
        "merah marun" to "maroon",
        "marun" to "maroon",
        "merah jambu" to "pink",
        "merah*" to "red",
        "jingga" to "orange",
        "oren" to "orange",
        "kuning*" to "yellow",
        "emas" to "gold",
        "keemasan" to "gold",
        "hijau muda" to "lime",
        "hijau*" to "green",
        "firus" to "turquoise",
        "ungu*" to "purple",
        "lembayung" to "violet",
        "coklat" to "brown",
        "koko" to "brown",
        "krim" to "cream",
        "gelap" to "dark",
        "cerah" to "light",

        // Talking to the helper.
        "helo" to "hello",
        "hai" to "hello",
        "selamat pagi" to "hello",
        "selamat tengah hari" to "hello",
        "selamat petang" to "hello",
        "selamat malam" to "hello",
        "bantu*" to "help",
        "bantuan" to "help",
        "tolong" to "please",
        "apa yang awak boleh buat" to "what can you do",
        "apa yang kamu boleh buat" to "what can you do",
        "awak boleh buat apa" to "what can you do",
        "boleh buat apa" to "what can you do",
        "siapa awak" to "who are you",
        "awak siapa" to "who are you",
        "terima kasih" to "thanks",
        "terima kasih banyak" to "thank you",
        "ribuan terima kasih" to "thank you",
        "sila" to "please",
        "wik" to "wick",
    ),
)
