package org.churchpresenter.helper.intent.glossary

internal val NEPALI = Glossary(
    "ne",
    listOf(
        // Asking where, or how.
        "कहाँ" to "where",
        "कहां" to "where",
        "कता" to "where",
        "म कसरी" to "how do i",
        "कसरी गर्ने" to "how do i",
        "कसरी गर्न सकिन्छ" to "how can i",
        "कसरी गर्न सक्छु" to "how can i",
        "कसरी" to "how do i",
        "भेटिएन" to "can't find",
        "फेला परेन" to "can't find",
        "भेट्टाउन सकिनँ" to "can't find",
        "भेट्टाउन सकिनं" to "can't find",
        "मलाई देखाउनुहोस्" to "show me",
        "मलाई देखाऊ" to "show me",
        "kaha" to "where",
        "kahaa" to "where",
        "kasari" to "how do i",
        "bhetiyena" to "can't find",
        "malai dekhau" to "show me",

        // Doing.
        "देखाउ*" to "show",
        "देखाऊ" to "show",
        "स्क्रिनमा ल्याउनुहोस्" to "show",
        "खोल्नु*" to "open",
        "खोल" to "open",
        "मा जानुहोस्" to "go to",
        "मा जाऊ" to "go to",
        "जानुहोस्" to "go to",
        "खोज्नु*" to "find",
        "खोज" to "find",
        "पढ्नु*" to "read",
        "बनाउ*" to "make",
        "बनाऊ" to "make",
        "सिर्जना" to "create",
        "थप्नु*" to "add",
        "थप" to "add",
        "लोड" to "load",
        "आयात" to "import",
        "इम्पोर्ट" to "import",
        "डाउनलोड" to "download",
        "इन्स्टल" to "install",
        "स्थापना" to "install",
        "छान्नु*" to "choose",
        "छान" to "choose",
        "सेट गर्नु*" to "set up",
        "सेटअप" to "set up",
        "जोड्नु*" to "connect",
        "कनेक्ट" to "connect",
        "तोक्नु*" to "assign",
        "लुकाउ*" to "hide",
        "लुकाऊ" to "hide",
        "हटाउ*" to "hide",
        "हटाऊ" to "hide",
        "रोक्नु*" to "stop",
        "रोक" to "stop",
        "मेटाउ*" to "delete",
        "मेट्नु*" to "delete",
        "सफा गर्नु*" to "clear",
        "सफा" to "clear",
        "स्क्रिन कालो गर्नु*" to "black out",
        "खाली स्क्रिन" to "blank",
        "पहिलेजस्तै गर्नु*" to "undo",
        "पहिले जस्तै" to "undo",
        "अनडु" to "undo",
        "लाइभ गर्नु*" to "go live",
        "लाइभमा" to "go live",
        "चालु गर्नु*" to "turn on",
        "बन्द गर्नु*" to "turn off",
        "बन्द" to "turn off",
        "अर्को" to "next",
        "अगाडि" to "forward",
        "अघिल्लो" to "previous",
        "पछाडि" to "back",
        "फिर्ता" to "back",
        "ठूलो बनाउ*" to "bigger",
        "ठूलो गर्नु*" to "bigger",
        "बढाउ*" to "increase",
        "ठूलो" to "bigger",
        "सानो बनाउ*" to "smaller",
        "सानो गर्नु*" to "smaller",
        "घटाउ*" to "decrease",
        "सानो" to "smaller",
        "रूपान्तरण" to "convert",
        "कन्भर्ट" to "convert",
        "कन्भर्टर" to "converter",
        "सार्नु*" to "transfer",
        "ट्रान्सफर" to "transfer",
        "सम्पादन" to "edit",
        "एडिट" to "edit",
        "परिवर्तन" to "change",
        "बदल्नु*" to "change",
        "बदल" to "change",
        "नाम बदल्नु*" to "rename",
        "ठीक पार्नु*" to "fix",
        "मिलाउ*" to "fix",
        "व्यवस्थित" to "organize",
        "तुलना" to "compare",
        "अनुवाद गर्नु*" to "translate",
        "योजना" to "plan",
        "स्वचालित" to "automatically",
        "पहिचान" to "identify",
        "नम्बर दिनु*" to "number the",
        "dekhau" to "show",
        "dekhaunus" to "show",
        "dekhaunuhos" to "show",
        "kholnus" to "open",
        "khojnus" to "find",
        "banau" to "make",
        "thapnus" to "add",
        "lukau" to "hide",
        "hatau" to "hide",
        "roknus" to "stop",
        "metau" to "delete",
        "saphaa" to "clear",
        "arko" to "next",
        "aghillo" to "previous",
        "thulo" to "bigger",
        "sano" to "smaller",
        "badhau" to "increase",
        "ghatau" to "decrease",
        "badalnus" to "change",

        // Too small, too big, not working.
        "धेरै सानो" to "too small",
        "एकदम सानो" to "too small",
        "पढ्न गाह्रो" to "hard to read",
        "पढ्न सकिँदैन" to "hard to read",
        "पढ्न सकिंदैन" to "hard to read",
        "राम्रोसँग देखिँदैन" to "hard to read",
        "राम्रोसंग देखिंदैन" to "hard to read",
        "धेरै ठूलो" to "too big",
        "एकदम ठूलो" to "too big",
        "अटाउँदैन" to "doesn't fit",
        "अटाउंदैन" to "doesn't fit",
        "नअटाएको" to "doesn't fit",
        "काम गर्दैन" to "not working",
        "काम गरेन" to "not working",
        "चलेन" to "not working",
        "देखिँदैन" to "not showing",
        "देखिंदैन" to "not showing",
        "देखाउँदैन" to "not showing",
        "देखाउंदैन" to "not showing",
        "केही देखिँदैन" to "nothing shows",
        "केही देखिंदैन" to "nothing shows",
        "केही पनि देखिँदैन" to "nothing shows",
        "केही पनि देखिंदैन" to "nothing shows",
        "स्क्रिन कालो छ" to "screen is black",
        "सिग्नल छैन" to "no signal",
        "तस्बिर छैन" to "no picture",
        "कुन स्क्रिन" to "which screen",
        "कुन मनिटर" to "which monitor",
        "कुन प्रोजेक्टर" to "which projector",
        "dherai sano" to "too small",
        "dherai thulo" to "too big",
        "kaam gardaina" to "not working",
        "kun screen" to "which screen",

        // What is on screen.
        "पृष्ठभूमि*" to "background",
        "ब्याकग्राउन्ड*" to "background",
        "गीतका शब्द*" to "lyrics",
        "गीतहरू" to "songs",
        "गीतहरु" to "songs",
        "गीत*" to "song",
        "भजन*" to "hymn",
        "आराधना*" to "worship",
        "प्रशंसा" to "worship",
        "बाइबल*" to "bible",
        "धर्मशास्त्र*" to "scripture",
        "वचन" to "scripture",
        "पद" to "verse",
        "पदहरू" to "verse",
        "अध्याय*" to "chapter",
        "फन्ट*" to "font",
        "अक्षर*" to "letters",
        "आकार*" to "size",
        "साइज" to "size",
        "पाठ*" to "text",
        "टेक्स्ट" to "text",
        "शब्दहरू" to "words",
        "स्लाइड शो" to "slideshow",
        "स्लाइडशो" to "slideshow",
        "स्लाइड*" to "slide",
        "फोटो*" to "photo",
        "तस्बिर*" to "picture",
        "तस्वीर*" to "picture",
        "चित्र*" to "picture",
        "एल्बम*" to "album",
        "प्रस्तुति*" to "presentation",
        "पावरपोइन्ट" to "powerpoint",
        "भिडियो*" to "video",
        "चलचित्र*" to "movie",
        "फिल्म*" to "movie",
        "क्लिप*" to "clip",
        "मिडिया" to "media",
        "अडियो" to "audio",
        "लोअर थर्ड" to "lower third",
        "नाम पट्टी" to "name strap",
        "नाम र पद" to "name and title",
        "सूचना*" to "announcement",
        "घोषणा*" to "announcement",
        "चल्ने पट्टी" to "ticker",
        "बालबालिकाको कोठा" to "kids room",
        "उल्टो गन्ती" to "countdown",
        "काउन्टडाउन" to "countdown",
        "टाइमर*" to "timer",
        "स्टपवाच" to "stopwatch",
        "घडी" to "clock",
        "अहिलेको समय" to "current time",
        "समय" to "time",
        "नोट*" to "notes",
        "टिपोट*" to "notes",
        "कर्ड*" to "chord",
        "अनुवाद*" to "translation",
        "भाषा*" to "language",
        "द्विभाषी" to "bilingual",
        "अर्को भाषा*" to "another language",
        "अन्य भाषा*" to "another language",
        "दोस्रो भाषा*" to "second language",
        "दुई भाषा*" to "two languages",
        "geet" to "song",
        "geetharu" to "songs",
        "bhajan" to "hymn",
        "aradhana" to "worship",
        "adhyaya" to "chapter",
        "tasbir" to "picture",
        "suchana" to "announcement",
        "ghadi" to "clock",
        "bhasa" to "language",
        "bhasha" to "language",
        "prishthabhumi" to "background",

        // Screens and outputs.
        "मुख्य स्क्रिन" to "main screen",
        "पूरा स्क्रिन" to "full screen",
        "फुल स्क्रिन" to "full screen",
        "दोस्रो स्क्रिन" to "second screen",
        "स्क्रिन*" to "screen",
        "पर्दा*" to "screen",
        "प्रोजेक्टर*" to "projector",
        "स्टेज मनिटर" to "stage monitor",
        "मञ्च मनिटर" to "stage monitor",
        "मञ्चको स्क्रिन" to "stage monitor",
        "मनिटर*" to "monitor",
        "डिस्प्ले" to "display",
        "आउटपुट विन्डो" to "output window",
        "आउटपुट*" to "output",
        "मञ्च*" to "stage",
        "स्टेज" to "stage",
        "जोन" to "zone",
        "लेआउट" to "layout",
        "सन्देश*" to "message",
        "म्यासेज" to "message",
        "पठाउ*" to "send",
        "पूर्वावलोकन" to "preview",
        "प्रिभ्यु" to "preview",
        "स्क्रिनमा के छ" to "what is on screen",
        "प्रोफाइल*" to "profile",
        "स्ट्रिम" to "stream",
        "प्रसारण" to "stream",
        "टिभी" to "tv",
        "parda" to "screen",
        "manch" to "stage",
        "sandesh" to "message",

        // Pages, tabs and tools.
        "सेटिङ*" to "settings",
        "विकल्प*" to "options",
        "सेटअप विजार्ड" to "setup wizard",
        "फेरि सुरु" to "start over",
        "सर्टकट*" to "shortcut",
        "हटकी" to "hotkeys",
        "किबोर्ड" to "keyboard",
        "ट्याब*" to "tab",
        "गीत पुस्तकालय" to "song library",
        "गीत लाइब्रेरी" to "song library",
        "पुस्तकालय*" to "library",
        "लाइब्रेरी" to "library",
        "वेब" to "web",
        "वेबसाइट" to "website",
        "ब्राउजर" to "browser",
        "शब्दकोश*" to "dictionary",
        "स्ट्रङ" to "strong",
        "क्यामेरा*" to "camera",
        "क्यानभास" to "canvas",
        "सर्भर*" to "server",
        "रिमोट" to "remote",
        "फोन*" to "phone",
        "मोबाइल*" to "phone",
        "ट्याब्लेट" to "tablet",
        "एकीकरण" to "integrations",

        // Services and planning.
        "आराधनाको क्रम" to "order of service",
        "सेवाको क्रम" to "order of service",
        "कार्यक्रमको क्रम" to "order of service",
        "आराधना सभा" to "service",
        "सेवा*" to "service",
        "सभा*" to "meeting",
        "बैठक*" to "meeting",
        "आइतबार*" to "sunday",
        "क्यालेन्डर*" to "calendar",
        "पात्रो" to "calendar",
        "तालिका*" to "schedule",
        "कार्यतालिका" to "schedule",
        "प्लेलिस्ट" to "playlist",
        "हरेक आइतबार" to "every sunday",
        "हरेक हप्ता" to "every week",
        "साप्ताहिक" to "weekly",
        "मासिक" to "monthly",
        "दोहोर्याउ*" to "repeat",
        "टेम्प्लेट" to "template",
        "ढाँचा*" to "template",
        "ढांचा*" to "template",
        "aaitabar" to "sunday",
        "aitabar" to "sunday",
        "sabha" to "meeting",
        "harek aaitabar" to "every sunday",
        "harek hapta" to "every week",

        // Many, all, both.
        "सबै" to "all",
        "सबैतिर" to "everything",
        "दुवै" to "both",
        "दुबै" to "both",
        "केही" to "several",
        "धेरै" to "many",
        "एकैपटक" to "at once",
        "एकै पटक" to "at once",
        "यो सेवाको लागि" to "this service",
        "आजको लागि" to "for today",
        "अस्थायी*" to "temporarily",
        "sabai" to "all",
        "duwai" to "both",

        // Languages, by name.
        "नेपाली" to "nepali",
        "अंग्रेजी" to "english",
        "अङ्ग्रेजी" to "english",
        "हिन्दी" to "hindi",
        "हिंदी" to "hindi",
        "तामिल" to "tamil",
        "रुसी" to "russian",
        "युक्रेनी" to "ukrainian",
        "स्पेनिस" to "spanish",
        "जर्मन" to "german",
        "फ्रेन्च" to "french",
        "पोर्चुगिज" to "portuguese",
        "चिनियाँ" to "chinese",
        "चिनियां" to "chinese",
        "जापानी" to "japanese",
        "कोरियाली" to "korean",
        "अरबी" to "arabic",
        "फारसी" to "persian",
        "थाई" to "thai",
        "हिब्रू" to "hebrew",
        "ग्रीक" to "greek",
        "ल्याटिन" to "latin",
        "angreji" to "english",

        // Colors.
        "गाढा निलो" to "dark blue",
        "गाढा नीलो" to "dark blue",
        "हल्का निलो" to "light blue",
        "हल्का नीलो" to "light blue",
        "आकाशे" to "sky",
        "गाढा हरियो" to "dark green",
        "हल्का हरियो" to "light green",
        "गाढा रातो" to "dark red",
        "निलो" to "blue",
        "नीलो" to "blue",
        "कालो" to "black",
        "सेतो" to "white",
        "खरानी" to "grey",
        "चाँदी*" to "silver",
        "चांदी*" to "silver",
        "रातो" to "red",
        "मरुन" to "maroon",
        "सुन्तला*" to "orange",
        "सुन्तले" to "orange",
        "पहेँलो" to "yellow",
        "पहेंलो" to "yellow",
        "सुनौलो" to "gold",
        "हरियो" to "green",
        "फिरोजी" to "turquoise",
        "बैजनी" to "purple",
        "गुलाबी" to "pink",
        "खैरो" to "brown",
        "क्रिम" to "cream",
        "गाढा" to "dark",
        "हल्का" to "light",
        "nilo" to "blue",
        "kalo" to "black",
        "seto" to "white",
        "rato" to "red",
        "pahelo" to "yellow",
        "hariyo" to "green",
        "baijani" to "purple",
        "khairo" to "brown",
        "gadha" to "dark",
        "halka" to "light",

        // Talking to the helper.
        "नमस्ते" to "hello",
        "नमस्कार" to "hello",
        "जय मसीह" to "hello",
        "हेलो" to "hello",
        "सहयोग" to "help",
        "मद्दत" to "help",
        "मद्दत गर्नु*" to "help",
        "तपाईं के गर्न सक्नुहुन्छ" to "what can you do",
        "तिमी के गर्न सक्छौ" to "what can you do",
        "तपाईं को हो" to "who are you",
        "तिमी को हौ" to "who are you",
        "धन्यवाद" to "thanks",
        "धन्यबाद" to "thanks",
        "कृपया" to "please",
        "विक" to "wick",
        "namaste" to "hello",
        "namaskar" to "hello",
        "jaya masih" to "hello",
        "sahayog" to "help",
        "maddat" to "help",
        "dhanyabad" to "thanks",
        "dhanyavad" to "thanks",
        "kripaya" to "please",

        // Newer requests.
        "खोज*" to "search",
        "खोज्ने" to "search",
        "सर्च" to "search",
        "बाइबलमा खोज*" to "search the bible",
        "गीत खोज" to "find a song",
        "पद खोज" to "find a verse",
        "गीत नम्बर" to "song number",
        "नम्बरबाट" to "by number",
        "नम्बर अनुसार" to "by number",
        "शीर्षकबाट" to "by title",
        "शीर्षक अनुसार" to "by title",
        "नामबाट" to "by title",
        "नम्बर" to "number",
        "मनपर्ने" to "favorite",
        "मनपर्दो" to "favorite",
        "मन पर्ने" to "favorite",
        "फेभरेट" to "favorite",
        "यो गीत*" to "this song",
        "हरेक गीत*" to "each song",
        "प्रत्येक गीत*" to "each song",
        "आफ्नै पृष्ठभूमि*" to "own background",
        "आफ्नो पृष्ठभूमि*" to "own background",
        "आफ्नै ब्याकग्राउन्ड*" to "own background",
        "आफ्नो ब्याकग्राउन्ड*" to "own background",
        "छुट्टै पृष्ठभूमि*" to "own background",
        "धेरै पद*" to "several verses",
        "केही पद*" to "a few verses",
        "एकभन्दा बढी पद*" to "more than one verse",
        "एक भन्दा बढी पद*" to "more than one verse",
        "पद दायरा" to "verse range",
        "पदहरूको दायरा" to "range of verses",
        "भर्खर के देखायौँ" to "what did we just show",
        "भर्खर के देखायौं" to "what did we just show",
        "हामीले भर्खर के देखायौँ" to "what did we just show",
        "हामीले भर्खर के देखायौं" to "what did we just show",
        "के देखायौँ" to "what did we show",
        "के देखायौं" to "what did we show",
        "इतिहास" to "history",
        "हालका पदहरू" to "recent verses",
        "भर्खरका पदहरू" to "recent verses",
        "सम्बन्धित पद*" to "related verses",
        "संबन्धित पद*" to "related verses",
        "सम्बन्धित खण्ड*" to "related passages",
        "क्रस रेफरेन्स" to "cross references",
        "समानान्तर खण्ड*" to "parallel passages",
        "वेब पेज" to "web page",
        "वेबपेज" to "web page",
        "इन्टरनेट पेज" to "internet page",
        "युआरएल" to "url",
        "लिङ्क" to "url",
        "लिंक" to "url",
        "प्लानिङ सेन्टर" to "planning center",
        "प्लानिङ् सेन्टर" to "planning center",
        "तथ्याङ्क" to "statistics",
        "तथ्यांक" to "statistics",
        "कति पटक" to "how many times",
        "गीत प्रतिवेदन" to "song report",
        "गीत रिपोर्ट" to "song report",
        "मेरो फोनबाट" to "from my phone",
        "मेरो मोबाइलबाट" to "from my phone",
        "फोनबाट" to "from the phone",
        "मोबाइलबाट" to "from the phone",
        "मेरो फोनमा" to "on my phone",
        "रिमोट कन्ट्रोल" to "remote control",
        "क्युआर कोड" to "qr code",
        "qr कोड" to "qr code",
        "फोन जोड*" to "connect my phone",
        "मिनेट*" to "minutes",
        "मिनट*" to "minutes",
        "घोषणा:" to "announce",
        "सूचना:" to "announce",
        "घोषणा गर:" to "announce",
        "वस्तु" to "item",
        "आइटम*" to "item",
        "तालिकामा" to "to the schedule",
        "अहिले के देखिँदै छ" to "what's showing",
        "अहिले के देखिंदै छ" to "what's showing",
        "के देखिँदै छ" to "what's showing",
        "के देखिंदै छ" to "what's showing",
        "अहिले लाइभमा के छ" to "what's live",
        "के लाइभ छ" to "what is live",
        "यो कुन संस्करण हो" to "what version is this",
        "कुन संस्करण" to "which version",
        "कुन भर्सन" to "which version",
        "संस्करण*" to "version",
        "भर्सन" to "version",
        "पछिल्लो संस्करण" to "latest version",
        "नयाँ संस्करण" to "newer version",
        "अपडेट जाँच*" to "check for updates",
        "अपडेट छ" to "is there an update",
        "सहायता" to "help",
        "आदेशहरू" to "commands",
        "आदेशहरु" to "commands",
        "कमान्ड*" to "commands",
        "आदेशको सूची" to "list of commands",
        "आदेशहरूको सूची" to "list of commands",
        "म के लेख्न सक्छु" to "what can i type",
        "म के भन्न सक्छु" to "what can i say",
        "तिमी के बुझ्छौ" to "what do you understand",
        "एकसाथ" to "together",
        "पूर्ववत्*" to "undo",
        "खाली गर" to "clear",
        "प्रस्तुत गर" to "go live",
        "मिलाऊ" to "set up",
        "कुन पर्दा*" to "which screen",
        "पूरा पर्दा*" to "full screen",
        "थप्ने" to "add",
        "अर्को बाइबल*" to "another bible",
        "तल्लो पट्टी" to "lower third",

        // Look requests.
        "गीतको बोल कसरी बदल*" to "how do i change song lyrics",
        "गीतको बोल बदल*" to "change song lyrics",
        "बोल कसरी बदल*" to "how do i change the lyrics",
        "बोल बदल*" to "change the lyrics",
        "बोल सम्पादन" to "edit the lyrics",
        "बोल सच्याउ*" to "fix the lyrics",
        "बोलमा गल्ती" to "mistake in the lyrics",
        "टाइपो" to "typo",
        "गीतको बोलमा" to "to the lyrics",
        "गीतको बोल" to "lyrics",
        "बोलमा" to "lyrics",
        "बोलहरू" to "lyrics",
        "बोल" to "lyrics",
        "गीत अन्त्यको चिन्ह" to "end of song marker",
        "गीतको अन्त्यको चिन्ह" to "end of song marker",
        "अन्त्यको चिन्ह" to "end marker",
        "गीतको अन्त्य" to "end of song",
        "गीतको शीर्षक" to "song title",
        "शीर्षक*" to "title",
        "पदको" to "verse",
        "पदका" to "verse",
        "सन्दर्भ*" to "reference",
        "मोटो" to "bold",
        "छड्के" to "italic",
        "अधोरेखा" to "underline",
        "रूपरेखा" to "outline",
        "छाया" to "shadow",
        "मार्जिन" to "margins",
        "किनारा*" to "edges",
        "माथि" to "top",
        "तल" to "bottom",
        "बीचमा" to "in the middle",
        "बायाँ" to "left",
        "दायाँ" to "right",
        "पङ्क्तिबद्धता" to "alignment",
        "स्थान" to "position",
        "सार्ने" to "move",
        "रूप" to "look",
        "शैली" to "style",
        "रङ" to "color",
        "देखावट" to "appearance",

        // The help table's own examples.
        "जाऊ" to "go to",
        "आमाबुबा*" to "parents",
        "शिशु कोठा*" to "nursery",
    ),
)
