package org.churchpresenter.helper.intent.glossary

internal val NORWEGIAN = Glossary(
    "no",
    listOf(
        // Asking where, or how.
        "hvor" to "where",
        "hvor finner jeg" to "where",
        "hvor er" to "where",
        "hvordan kan jeg" to "how can i",
        "hvordan gjør jeg" to "how do i",
        "hvordan gjor jeg" to "how do i",
        "hvordan" to "how do i",
        "finner ikke" to "can't find",
        "kan ikke finne" to "can't find",
        "vis meg" to "show me",

        // Doing.
        "vis" to "show",
        "vise*" to "show",
        "åpne*" to "open",
        "apne*" to "open",
        "gå til" to "go to",
        "ga til" to "go to",
        "bytt til" to "switch to",
        "skift til" to "switch to",
        "bytt over til" to "switch to",
        "søk" to "find",
        "søke" to "find",
        "finn" to "find",
        "finne" to "find",
        "les" to "read",
        "les opp" to "read",
        "lage" to "make",
        "lag en" to "make a",
        "lag et" to "make a",
        "opprett*" to "create",
        "legg til" to "add",
        "legge til" to "add",
        "last opp" to "load",
        "laste opp" to "load",
        "last inn" to "load",
        "laste inn" to "load",
        "importer*" to "import",
        "last ned" to "download",
        "laste ned" to "download",
        "installer*" to "install",
        "velg*" to "choose",
        "sett opp" to "set up",
        "konfigurer*" to "set up",
        "koble*" to "connect",
        "tilordne*" to "assign",
        "tildel*" to "assign",
        "skjul*" to "hide",
        "gjem*" to "hide",
        "stopp*" to "stop",
        "avslutt*" to "stop",
        "slett*" to "delete",
        "fjern*" to "remove",
        "tøm" to "clear",
        "tømme" to "clear",
        "nullstill*" to "clear",
        "mørklegg*" to "black out",
        "morklegg*" to "black out",
        "blank skjerm" to "blank",
        "tom skjerm" to "blank",
        "angre*" to "undo",
        "gå live" to "go live",
        "ga live" to "go live",
        "slå på" to "turn on",
        "sla pa" to "turn on",
        "skru på" to "turn on",
        "skru pa" to "turn on",
        "slå av" to "turn off",
        "sla av" to "turn off",
        "skru av" to "turn off",
        "veksle*" to "toggle",
        "neste" to "next",
        "videre" to "next",
        "fremover" to "forward",
        "framover" to "forward",
        "forrige" to "previous",
        "tilbake" to "back",
        "øke" to "increase",
        "øk" to "increase",
        "forstørr*" to "increase",
        "forstorr*" to "increase",
        "større" to "bigger",
        "storre" to "bigger",
        "reduser*" to "decrease",
        "minske" to "decrease",
        "mindre" to "smaller",
        "konverter*" to "convert",
        "overfør*" to "transfer",
        "overfor*" to "transfer",
        "flytt over" to "transfer",
        "migrer*" to "migrate",
        "rediger*" to "edit",
        "endre*" to "change",
        "bytt navn" to "rename",
        "gi nytt navn" to "rename",
        "fiks*" to "fix",
        "reparer*" to "fix",
        "organiser*" to "organize",
        "rydd*" to "clean up",
        "sammenlign*" to "compare",
        "oversett*" to "translate",
        "planlegg*" to "plan",
        "automatiser*" to "automate",
        "automatisk*" to "automatically",
        "identifiser*" to "identify",
        "nummerer*" to "number the",

        // Too small, too big, not working.
        "for liten" to "too small",
        "for lite" to "too small",
        "for små" to "too small",
        "for sma" to "too small",
        "vanskelig å lese" to "hard to read",
        "vanskelig a lese" to "hard to read",
        "dårlig lesbar" to "hard to read",
        "darlig lesbar" to "hard to read",
        "ser ikke" to "hard to read",
        "for stor" to "too big",
        "for stort" to "too big",
        "for store" to "too big",
        "får ikke plass" to "doesn't fit",
        "far ikke plass" to "doesn't fit",
        "passer ikke" to "doesn't fit",
        "virker ikke" to "not working",
        "fungerer ikke" to "not working",
        "funker ikke" to "not working",
        "vises ikke" to "not showing",
        "viser ikke" to "not showing",
        "viser ingenting" to "nothing shows",
        "ingenting vises" to "nothing shows",
        "svart skjerm" to "screen is black",
        "skjermen er svart" to "screen is black",
        "ingen signal" to "no signal",
        "ikke noe signal" to "no signal",
        "ikke noe bilde" to "no picture",
        "ingen bilde" to "no picture",
        "hvilken skjerm" to "which screen",
        "hvilken monitor" to "which monitor",
        "hvilken projektor" to "which projector",

        // What is on screen.
        "bakgrunn*" to "background",
        "sangtekst*" to "lyrics",
        "sang*" to "song",
        "lovsang*" to "worship",
        "tilbedelse*" to "worship",
        "bibel*" to "bible",
        "skriften" to "scripture",
        "skriftsted*" to "verse",
        "bibelvers*" to "verse",
        "vers" to "verse",
        "versene" to "verse",
        "kapittel*" to "chapter",
        "kapitlet" to "chapter",
        "skriftstørrelse*" to "font size",
        "skriftstorrelse*" to "font size",
        "tekststørrelse*" to "text size",
        "skrifttype*" to "font",
        "skrift*" to "font",
        "størrelse*" to "size",
        "storrelse*" to "size",
        "tekst*" to "text",
        "ord" to "words",
        "ordene" to "words",
        "bokstaver*" to "letters",
        "lysbildefremvisning*" to "slideshow",
        "lysbildeshow*" to "slideshow",
        "lysbilde*" to "slide",
        "bilde*" to "picture",
        "bilder" to "picture",
        "foto*" to "photo",
        "presentasjon*" to "presentation",
        "filmer" to "movie",
        "filmen" to "movie",
        "klipp*" to "clip",
        "nedre tredjedel*" to "lower third",
        "navneskilt*" to "name strap",
        "navnestripe*" to "name strap",
        "navn og tittel" to "name and title",
        "kunngjøring*" to "announcement",
        "kunngjoring*" to "announcement",
        "rulletekst*" to "ticker",
        "barnerom*" to "kids room",
        "barnepass*" to "kids room",
        "søndagsskole*" to "kids room",
        "nedtelling*" to "countdown",
        "telle ned" to "countdown",
        "tidtaker*" to "timer",
        "stoppeklokke*" to "stopwatch",
        "klokke*" to "clock",
        "klokka" to "clock",
        "nåværende tid" to "current time",
        "tid" to "time",
        "tiden" to "time",
        "notat*" to "notes",
        "akkord*" to "chord",
        "oversettelse*" to "translation",
        "språk*" to "language",
        "sprak*" to "language",
        "tospråklig*" to "bilingual",
        "tosprakl*" to "bilingual",
        "et annet språk" to "another language",
        "annet språk" to "another language",
        "andre språk" to "another language",
        "to språk" to "two languages",

        // Screens and outputs.
        "hovedskjerm*" to "main screen",
        "fullskjerm*" to "full screen",
        "hele skjermen" to "full screen",
        "andre skjerm" to "second screen",
        "andre skjermen" to "second screen",
        "skjerm*" to "screen",
        "projektor*" to "projector",
        "scenemonitor*" to "stage monitor",
        "sceneskjerm*" to "stage monitor",
        "monitorer" to "monitor",
        "visning*" to "display",
        "utgang*" to "output",
        "scenen" to "stage",
        "sone" to "zone",
        "soner" to "zone",
        "sonen" to "zone",
        "oppsett*" to "layout",
        "oppstilling*" to "arrangement",
        "send melding" to "send message",
        "melding*" to "message",
        "sende" to "send",
        "forhåndsvisning*" to "preview",
        "forhandsvisning*" to "preview",
        "hva som vises" to "what is on screen",
        "profil*" to "profile",
        "strømming*" to "stream",
        "direktesending*" to "stream",
        "tv-en" to "tv",

        // Pages, tabs and tools.
        "innstilling*" to "settings",
        "alternativer" to "options",
        "oppsettsveiviser*" to "setup wizard",
        "veiviser*" to "setup wizard",
        "start på nytt" to "start over",
        "begynn på nytt" to "start over",
        "hurtigtast*" to "hotkeys",
        "tastatursnarvei*" to "shortcut",
        "snarvei*" to "shortcut",
        "tastatur*" to "keyboard",
        "fane" to "tab",
        "fanen" to "tab",
        "faner" to "tab",
        "sangbibliotek*" to "song library",
        "bibliotek*" to "library",
        "nett" to "web",
        "nettside*" to "website",
        "nettsted*" to "website",
        "nettleser*" to "browser",
        "ordbok*" to "dictionary",
        "kamera*" to "camera",
        "lerret*" to "canvas",
        "fjernkontroll*" to "remote",
        "fjernstyr*" to "remote",
        "telefon*" to "phone",
        "mobilen" to "phone",
        "nettbrett*" to "tablet",
        "integrasjon*" to "integrations",

        // Services and planning.
        "gudstjenesteordning*" to "order of service",
        "liturgi*" to "order of service",
        "gudstjeneste*" to "service",
        "møte" to "meeting",
        "møtet" to "meeting",
        "møter" to "meeting",
        "samling*" to "meeting",
        "søndag*" to "sunday",
        "sondag*" to "sunday",
        "kalender*" to "calendar",
        "kjøreplan*" to "schedule",
        "kjoreplan*" to "schedule",
        "timeplan*" to "schedule",
        "spilleliste*" to "playlist",
        "hver søndag" to "every sunday",
        "hver sondag" to "every sunday",
        "hver uke" to "every week",
        "ukentlig*" to "weekly",
        "månedlig*" to "monthly",
        "manedlig*" to "monthly",
        "gjenta*" to "repeat",
        "mal" to "template",
        "malen" to "template",
        "maler" to "template",

        // Many, all, both.
        "alle" to "all",
        "alt" to "everything",
        "overalt" to "everything",
        "begge" to "both",
        "flere" to "several",
        "mange" to "many",
        "samtidig" to "at once",
        "på en gang" to "at once",
        "for denne gudstjenesten" to "this service",
        "for i dag" to "for today",
        "midlertidig" to "temporarily",
        "for nå" to "for now",

        // Languages, by name.
        "russisk*" to "russian",
        "ukrainsk*" to "ukrainian",
        "hviterussisk*" to "belarusian",
        "belarusisk*" to "belarusian",
        "engelsk*" to "english",
        "spansk*" to "spanish",
        "tysk*" to "german",
        "fransk*" to "french",
        "polsk*" to "polish",
        "kasakhisk*" to "kazakh",
        "rumensk*" to "romanian",
        "moldovsk*" to "moldovan",
        "portugisisk*" to "portuguese",
        "italiensk*" to "italian",
        "nederlandsk*" to "dutch",
        "tsjekkisk*" to "czech",
        "slovakisk*" to "slovak",
        "kroatisk*" to "croatian",
        "serbisk*" to "serbian",
        "bulgarsk*" to "bulgarian",
        "ungarsk*" to "hungarian",
        "gresk*" to "greek",
        "tyrkisk*" to "turkish",
        "arabisk*" to "arabic",
        "persisk*" to "persian",
        "hebraisk*" to "hebrew",
        "kinesisk*" to "chinese",
        "japansk*" to "japanese",
        "koreansk*" to "korean",
        "vietnamesisk*" to "vietnamese",
        "indonesisk*" to "indonesian",
        "estisk*" to "estonian",
        "latvisk*" to "latvian",
        "litauisk*" to "lithuanian",
        "finsk*" to "finnish",
        "svensk*" to "swedish",
        "norsk*" to "norwegian",
        "dansk*" to "danish",
        "armensk*" to "armenian",
        "georgisk*" to "georgian",
        "latinsk*" to "latin",

        // Colors.
        "mørkeblå*" to "navy",
        "morkebla*" to "navy",
        "marineblå*" to "navy",
        "lyseblå*" to "light blue",
        "lysebla*" to "light blue",
        "himmelblå*" to "sky",
        "blå*" to "blue",
        "svart" to "black",
        "svarte" to "black",
        "hvit*" to "white",
        "grå*" to "grey",
        "sølv*" to "silver",
        "solv*" to "silver",
        "rød*" to "red",
        "vinrød*" to "maroon",
        "oransje" to "orange",
        "gul" to "yellow",
        "gule" to "yellow",
        "gult" to "yellow",
        "gull" to "gold",
        "gullfarg*" to "gold",
        "limegrønn*" to "lime",
        "lysegrønn*" to "lime",
        "grønn*" to "green",
        "gronn*" to "green",
        "turkis*" to "turquoise",
        "lilla" to "purple",
        "fiolett*" to "violet",
        "rosa" to "pink",
        "brun" to "brown",
        "brune" to "brown",
        "brunt" to "brown",
        "kremfarg*" to "cream",
        "mørk*" to "dark",
        "mork*" to "dark",
        "lys" to "light",
        "lyse" to "light",
        "lyst" to "light",

        // Talking to the helper.
        "hei" to "hello",
        "hallo" to "hello",
        "heisann" to "hello",
        "god morgen" to "hello",
        "god dag" to "hello",
        "hjelp*" to "help",
        "hva kan du" to "what can you do",
        "hva kan du gjøre" to "what can you do",
        "hvem er du" to "who are you",
        "takk" to "thanks",
        "tusen takk" to "thank you",
        "takk skal du ha" to "thank you",
        "vær så snill" to "please",
        "vaer sa snill" to "please",
        "vennligst" to "please",
        "vick" to "wick",
    ),
)
