package org.churchpresenter.helper.intent.glossary

internal val PERSIAN = Glossary(
    "fa",
    listOf(
        // Asking where, or how.
        "کجا" to "where",
        "كجا" to "where",
        "کجاست" to "where",
        "كجاست" to "where",
        "چطور می توانم" to "how can i",
        "چطور مي توانم" to "how can i",
        "چطور میتوانم" to "how can i",
        "چطور ميتوانم" to "how can i",
        "چطوری می تونم" to "how can i",
        "چطوري مي تونم" to "how can i",
        "چطوری میتونم" to "how can i",
        "چطوري ميتونم" to "how can i",
        "چگونه می توانم" to "how can i",
        "چگونه مي توانم" to "how can i",
        "چگونه میتوانم" to "how can i",
        "چگونه ميتوانم" to "how can i",
        "چطور" to "how do i",
        "چطوری" to "how do i",
        "چطوري" to "how do i",
        "چگونه" to "how do i",
        "پیدا نمی کنم" to "can't find",
        "پيدا نمي كنم" to "can't find",
        "پیدا نمیکنم" to "can't find",
        "پيدا نميكنم" to "can't find",
        "نمی توانم پیدا کنم" to "can't find",
        "نمي توانم پيدا كنم" to "can't find",
        "نمیتوانم پیدا کنم" to "can't find",
        "نميتوانم پيدا كنم" to "can't find",
        "نمیتونم پیدا کنم" to "can't find",
        "نميتونم پيدا كنم" to "can't find",
        "به من نشان بده" to "show me",
        "نشانم بده" to "show me",
        "نشونم بده" to "show me",

        // Doing.
        "نشان بده" to "show",
        "نشون بده" to "show",
        "نمایش بده" to "show",
        "نمايش بده" to "show",
        "نمایش" to "show",
        "نمايش" to "show",
        "روی صفحه بیاور" to "show",
        "روي صفحه بياور" to "show",
        "باز کن" to "open",
        "باز كن" to "open",
        "بازکن" to "open",
        "بازكن" to "open",
        "برو به" to "go to",
        "برو" to "go to",
        "تغییر به" to "switch to",
        "تغيير به" to "switch to",
        "پیدا کن" to "find",
        "پيدا كن" to "find",
        "جستجو کن" to "find",
        "جستجو كن" to "find",
        "جستجو" to "find",
        "بخوان" to "read",
        "بخون" to "read",
        "بکن" to "make",
        "بكن" to "make",
        "درست کن" to "make",
        "درست كن" to "make",
        "بساز" to "create",
        "ایجاد کن" to "create",
        "ايجاد كن" to "create",
        "ایجاد" to "create",
        "ايجاد" to "create",
        "اضافه کن" to "add",
        "اضافه كن" to "add",
        "اضافه" to "add",
        "افزودن" to "add",
        "بارگذاری" to "load",
        "بارگذاري" to "load",
        "بارگذاری کن" to "load",
        "بارگذاري كن" to "load",
        "وارد کن" to "import",
        "وارد كن" to "import",
        "وارد کردن" to "import",
        "وارد كردن" to "import",
        "دانلود" to "download",
        "بارگیری" to "download",
        "بارگيري" to "download",
        "نصب" to "install",
        "انتخاب کن" to "choose",
        "انتخاب كن" to "choose",
        "انتخاب" to "choose",
        "تنظیم کن" to "set up",
        "تنظيم كن" to "set up",
        "راه اندازی" to "set up",
        "راه اندازي" to "set up",
        "راهاندازی" to "set up",
        "راهاندازي" to "set up",
        "وصل کن" to "connect",
        "وصل كن" to "connect",
        "اتصال" to "connect",
        "اختصاص بده" to "assign",
        "مخفی کن" to "hide",
        "مخفي كن" to "hide",
        "پنهان کن" to "hide",
        "پنهان كن" to "hide",
        "قایم کن" to "hide",
        "قايم كن" to "hide",
        "بردار" to "hide",
        "متوقف کن" to "stop",
        "متوقف كن" to "stop",
        "توقف" to "stop",
        "قطع کن" to "stop",
        "قطع كن" to "stop",
        "حذف کن" to "delete",
        "حذف كن" to "delete",
        "حذف" to "delete",
        "پاک کن" to "clear",
        "پاك كن" to "clear",
        "پاک کردن" to "clear",
        "پاك كردن" to "clear",
        "صفحه سیاه" to "black out",
        "صفحه سياه" to "black out",
        "صفحه را سیاه کن" to "black out",
        "صفحه را سياه كن" to "black out",
        "صفحه خالی" to "blank",
        "صفحه خالي" to "blank",
        "برگردان" to "undo",
        "لغو کن" to "undo",
        "لغو كن" to "undo",
        "واگرد" to "undo",
        "پخش زنده" to "go live",
        "روی آنتن" to "go live",
        "روي آنتن" to "go live",
        "روی انتن" to "go live",
        "روشن کن" to "turn on",
        "روشن كن" to "turn on",
        "فعال کن" to "turn on",
        "فعال كن" to "turn on",
        "خاموش کن" to "turn off",
        "خاموش كن" to "turn off",
        "غیرفعال کن" to "turn off",
        "غيرفعال كن" to "turn off",
        "سوئیچ کن" to "toggle",
        "سوئيچ كن" to "toggle",
        "بعدی" to "next",
        "بعدي" to "next",
        "جلو" to "forward",
        "قبلی" to "previous",
        "قبلي" to "previous",
        "عقب" to "back",
        "برگرد" to "back",
        "بزرگ کن" to "increase",
        "بزرگ كن" to "increase",
        "افزایش" to "increase",
        "افزايش" to "increase",
        "بزرگتر" to "bigger",
        "بزرگ تر" to "bigger",
        "درشت تر" to "bigger",
        "درشتتر" to "bigger",
        "کوچک کن" to "decrease",
        "كوچك كن" to "decrease",
        "کاهش" to "decrease",
        "كاهش" to "decrease",
        "کوچکتر" to "smaller",
        "كوچكتر" to "smaller",
        "کوچک تر" to "smaller",
        "كوچك تر" to "smaller",
        "ریزتر" to "smaller",
        "ريزتر" to "smaller",
        "تبدیل" to "convert",
        "تبديل" to "convert",
        "مبدل" to "converter",
        "انتقال" to "transfer",
        "منتقل کن" to "transfer",
        "منتقل كن" to "transfer",
        "ویرایش" to "edit",
        "ويرايش" to "edit",
        "ویرایش کن" to "edit",
        "ويرايش كن" to "edit",
        "تغییر بده" to "change",
        "تغيير بده" to "change",
        "عوض کن" to "change",
        "عوض كن" to "change",
        "تغییر" to "change",
        "تغيير" to "change",
        "تغییر نام" to "rename",
        "تغيير نام" to "rename",
        "درست کردن" to "fix",
        "درست كردن" to "fix",
        "اصلاح" to "fix",
        "مرتب کن" to "organize",
        "مرتب كن" to "organize",
        "مرتب سازی" to "organize",
        "مرتب سازي" to "organize",
        "مرتبسازی" to "organize",
        "مرتبسازي" to "organize",
        "سازماندهی" to "organize",
        "سازماندهي" to "organize",
        "مقایسه" to "compare",
        "مقايسه" to "compare",
        "ترجمه کن" to "translate",
        "ترجمه كن" to "translate",
        "برنامه ریزی" to "plan",
        "برنامه ريزي" to "plan",
        "برنامهریزی" to "plan",
        "برنامهريزي" to "plan",
        "برنامه ریزی کن" to "plan",
        "برنامه ريزي كن" to "plan",
        "خودکارسازی" to "automate",
        "خودكارسازي" to "automate",
        "خودکار" to "automatically",
        "خودكار" to "automatically",
        "شناسایی" to "identify",
        "شناسايي" to "identify",
        "شماره گذاری" to "number the",
        "شماره گذاري" to "number the",
        "شمارهگذاری" to "number the",
        "شمارهگذاري" to "number the",

        // Too small, too big, not working.
        "خیلی کوچک" to "too small",
        "خيلي كوچك" to "too small",
        "خیلی کوچیک" to "too small",
        "خيلي كوچيك" to "too small",
        "خیلی ریز" to "too small",
        "خيلي ريز" to "too small",
        "خوانا نیست" to "hard to read",
        "خوانا نيست" to "hard to read",
        "خونده نمیشه" to "hard to read",
        "خونده نميشه" to "hard to read",
        "سخت خوانده می شود" to "hard to read",
        "سخت خوانده مي شود" to "hard to read",
        "سخت خوانده میشود" to "hard to read",
        "سخت خوانده ميشود" to "hard to read",
        "دیده نمی شود" to "hard to read",
        "ديده نمي شود" to "hard to read",
        "دیده نمیشود" to "hard to read",
        "ديده نميشود" to "hard to read",
        "خیلی بزرگ" to "too big",
        "خيلي بزرگ" to "too big",
        "خیلی درشت" to "too big",
        "خيلي درشت" to "too big",
        "جا نمی شود" to "doesn't fit",
        "جا نمي شود" to "doesn't fit",
        "جا نمیشود" to "doesn't fit",
        "جا نميشود" to "doesn't fit",
        "جا نمیشه" to "doesn't fit",
        "جا نميشه" to "doesn't fit",
        "کار نمی کند" to "not working",
        "كار نمي كند" to "not working",
        "کار نمیکند" to "not working",
        "كار نميكند" to "not working",
        "کار نمیکنه" to "not working",
        "كار نميكنه" to "not working",
        "نمایش نمی دهد" to "not showing",
        "نمايش نمي دهد" to "not showing",
        "نمایش نمیدهد" to "not showing",
        "نمايش نميدهد" to "not showing",
        "نشان نمی دهد" to "not showing",
        "نشان نمي دهد" to "not showing",
        "نشان نمیدهد" to "not showing",
        "نشان نميدهد" to "not showing",
        "هیچی نشون نمیده" to "nothing shows",
        "هيچي نشون نميده" to "nothing shows",
        "هیچ چیز نمایش داده نمی شود" to "nothing shows",
        "هيچ چيز نمايش داده نمي شود" to "nothing shows",
        "هیچ چیز نمایش داده نمیشود" to "nothing shows",
        "هيچ چيز نمايش داده نميشود" to "nothing shows",
        "صفحه سیاه است" to "screen is black",
        "صفحه سياه است" to "screen is black",
        "بدون سیگنال" to "no signal",
        "بدون سيگنال" to "no signal",
        "سیگنال نیست" to "no signal",
        "سيگنال نيست" to "no signal",
        "تصویر نیست" to "no picture",
        "تصوير نيست" to "no picture",
        "بدون تصویر" to "no picture",
        "بدون تصوير" to "no picture",
        "کدام صفحه" to "which screen",
        "كدام صفحه" to "which screen",
        "کدوم صفحه" to "which screen",
        "كدوم صفحه" to "which screen",
        "کدام نمایشگر" to "which monitor",
        "كدام نمايشگر" to "which monitor",
        "کدام پروژکتور" to "which projector",
        "كدام پروژكتور" to "which projector",

        // What is on screen.
        "پس زمینه*" to "background",
        "پس زمينه*" to "background",
        "پسزمینه*" to "background",
        "پسزمينه*" to "background",
        "زمینه" to "background",
        "زمينه" to "background",
        "بک گراند" to "background",
        "بك گراند" to "background",
        "بکگراند" to "background",
        "بكگراند" to "background",
        "متن سرود" to "lyrics",
        "متن آهنگ" to "lyrics",
        "متن اهنگ" to "lyrics",
        "شعر سرود" to "lyrics",
        "سرودها" to "songs",
        "سرود*" to "song",
        "آهنگ ها" to "songs",
        "آهنگها" to "songs",
        "آهنگ*" to "song",
        "پرستش" to "worship",
        "نیایش" to "worship",
        "نيايش" to "worship",
        "حمد" to "hymn",
        "کتاب مقدس" to "bible",
        "كتاب مقدس" to "bible",
        "کتابمقدس" to "bible",
        "كتابمقدس" to "bible",
        "انجیل" to "bible",
        "انجيل" to "bible",
        "کلام خدا" to "scripture",
        "كلام خدا" to "scripture",
        "آیه*" to "verse",
        "آيه*" to "verse",
        "آیات" to "verse",
        "آيات" to "verse",
        "باب" to "chapter",
        "فصل" to "chapter",
        "فونت*" to "font",
        "قلم" to "font",
        "اندازه" to "size",
        "سایز" to "size",
        "سايز" to "size",
        "متن*" to "text",
        "کلمات" to "words",
        "كلمات" to "words",
        "حروف" to "letters",
        "نمایش اسلاید" to "slideshow",
        "نمايش اسلايد" to "slideshow",
        "اسلایدشو" to "slideshow",
        "اسلايدشو" to "slideshow",
        "اسلاید*" to "slide",
        "اسلايد*" to "slide",
        "عکس*" to "photo",
        "عكس*" to "photo",
        "تصویر*" to "picture",
        "تصوير*" to "picture",
        "تصاویر" to "picture",
        "تصاوير" to "picture",
        "آلبوم*" to "album",
        "ارائه*" to "presentation",
        "پاورپوینت" to "powerpoint",
        "پاورپوينت" to "powerpoint",
        "ویدیو*" to "video",
        "ويديو*" to "video",
        "ویدئو*" to "video",
        "ويدئو*" to "video",
        "فیلم*" to "movie",
        "فيلم*" to "movie",
        "کلیپ*" to "clip",
        "كليپ*" to "clip",
        "رسانه*" to "media",
        "صدا" to "audio",
        "یک سوم پایین" to "lower third",
        "يك سوم پايين" to "lower third",
        "یکسوم پایین" to "lower third",
        "يكسوم پايين" to "lower third",
        "زیرنویس نام" to "name strap",
        "زيرنويس نام" to "name strap",
        "نام و عنوان" to "name and title",
        "اطلاعیه*" to "announcement",
        "اطلاعيه*" to "announcement",
        "اعلان*" to "announcement",
        "متن متحرک" to "ticker",
        "متن متحرك" to "ticker",
        "زیرنویس متحرک" to "ticker",
        "زيرنويس متحرك" to "ticker",
        "اتاق کودکان" to "kids room",
        "اتاق كودكان" to "kids room",
        "مهدکودک" to "kids room",
        "مهدكودك" to "kids room",
        "شمارش معکوس" to "countdown",
        "شمارش معكوس" to "countdown",
        "تایمر*" to "timer",
        "تايمر*" to "timer",
        "زمان سنج" to "timer",
        "زمانسنج" to "timer",
        "کرنومتر" to "stopwatch",
        "كرنومتر" to "stopwatch",
        "ساعت" to "clock",
        "زمان فعلی" to "current time",
        "زمان فعلي" to "current time",
        "ساعت فعلی" to "current time",
        "ساعت فعلي" to "current time",
        "زمان" to "time",
        "یادداشت*" to "notes",
        "يادداشت*" to "notes",
        "آکورد*" to "chord",
        "آكورد*" to "chord",
        "ترجمه*" to "translation",
        "زبان*" to "language",
        "دوزبانه" to "bilingual",
        "دو زبانه" to "bilingual",
        "زبان دیگر" to "another language",
        "زبان ديگر" to "another language",
        "به زبان دیگر" to "another language",
        "به زبان ديگر" to "another language",
        "زبان دوم" to "second language",
        "دو زبان" to "two languages",

        // Screens and outputs.
        "صفحه اصلی" to "main screen",
        "صفحه اصلي" to "main screen",
        "صفحه نمایش اصلی" to "main screen",
        "صفحه نمايش اصلي" to "main screen",
        "صفحهنمایش اصلی" to "main screen",
        "صفحهنمايش اصلي" to "main screen",
        "تمام صفحه" to "full screen",
        "تمامصفحه" to "fullscreen",
        "صفحه دوم" to "second screen",
        "صفحه نمایش*" to "screen",
        "صفحه نمايش*" to "screen",
        "صفحهنمایش*" to "screen",
        "صفحهنمايش*" to "screen",
        "صفحه" to "screen",
        "اسکرین" to "screen",
        "اسكرين" to "screen",
        "پروژکتور*" to "projector",
        "پروژكتور*" to "projector",
        "ویدئو پروژکتور" to "projector",
        "ويدئو پروژكتور" to "projector",
        "مانیتور صحنه" to "stage monitor",
        "مانيتور صحنه" to "stage monitor",
        "نمایشگر صحنه" to "stage monitor",
        "نمايشگر صحنه" to "stage monitor",
        "مانیتور سن" to "stage monitor",
        "مانيتور سن" to "stage monitor",
        "مانیتور*" to "monitor",
        "مانيتور*" to "monitor",
        "نمایشگر*" to "display",
        "نمايشگر*" to "display",
        "خروجی*" to "output",
        "خروجي*" to "output",
        "پنجره خروجی" to "output window",
        "پنجره خروجي" to "output window",
        "صحنه" to "stage",
        "ناحیه*" to "zone",
        "ناحيه*" to "zone",
        "چیدمان" to "layout",
        "چيدمان" to "layout",
        "طرح بندی" to "layout",
        "طرح بندي" to "layout",
        "طرحبندی" to "layout",
        "طرحبندي" to "layout",
        "پیام*" to "message",
        "پيام*" to "message",
        "بفرست" to "send",
        "ارسال" to "send",
        "پیش نمایش" to "preview",
        "پيش نمايش" to "preview",
        "پیشنمایش" to "preview",
        "پيشنمايش" to "preview",
        "چه چیزی روی صفحه است" to "what is on screen",
        "چه چيزي روي صفحه است" to "what is on screen",
        "پروفایل*" to "profile",
        "پروفايل*" to "profile",
        "نمایه*" to "profile",
        "نمايه*" to "profile",
        "پخش*" to "stream",
        "استریم" to "stream",
        "استريم" to "stream",
        "تلویزیون" to "tv",
        "تلويزيون" to "tv",

        // Pages, tabs and tools.
        "تنظیمات" to "settings",
        "تنظيمات" to "settings",
        "گزینه*" to "options",
        "گزينه*" to "options",
        "جادوگر راه اندازی" to "setup wizard",
        "جادوگر راه اندازي" to "setup wizard",
        "جادوگر راهاندازی" to "setup wizard",
        "جادوگر راهاندازي" to "setup wizard",
        "از اول شروع کن" to "start over",
        "از اول شروع كن" to "start over",
        "میانبر*" to "shortcut",
        "ميانبر*" to "shortcut",
        "کلید میانبر" to "hotkeys",
        "كليد ميانبر" to "hotkeys",
        "کلیدهای میانبر" to "hotkeys",
        "كليدهاي ميانبر" to "hotkeys",
        "صفحه کلید" to "keyboard",
        "صفحه كليد" to "keyboard",
        "صفحهکلید" to "keyboard",
        "صفحهكليد" to "keyboard",
        "کیبورد" to "keyboard",
        "كيبورد" to "keyboard",
        "زبانه*" to "tab",
        "کتابخانه سرود" to "song library",
        "كتابخانه سرود" to "song library",
        "کتابخانه آهنگ" to "song library",
        "كتابخانه آهنگ" to "song library",
        "کتابخانه اهنگ" to "song library",
        "کتابخانه*" to "library",
        "كتابخانه*" to "library",
        "وب" to "web",
        "وب سایت" to "website",
        "وب سايت" to "website",
        "وبسایت" to "website",
        "وبسايت" to "website",
        "سایت" to "website",
        "سايت" to "website",
        "مرورگر*" to "browser",
        "فرهنگ لغت" to "dictionary",
        "لغت نامه" to "dictionary",
        "لغتنامه" to "dictionary",
        "استرانگ" to "strong",
        "دوربین*" to "camera",
        "دوربين*" to "camera",
        "بوم" to "canvas",
        "سرور*" to "server",
        "از راه دور" to "remote",
        "ریموت" to "remote",
        "ريموت" to "remote",
        "کنترل از راه دور" to "remote",
        "كنترل از راه دور" to "remote",
        "گوشی" to "phone",
        "گوشي" to "phone",
        "تلفن" to "phone",
        "موبایل" to "phone",
        "موبايل" to "phone",
        "تبلت" to "tablet",
        "یکپارچه سازی" to "integrations",
        "يكپارچه سازي" to "integrations",
        "یکپارچهسازی" to "integrations",
        "يكپارچهسازي" to "integrations",

        // Services and planning.
        "ترتیب جلسه" to "order of service",
        "ترتيب جلسه" to "order of service",
        "برنامه جلسه" to "order of service",
        "برنامه عبادت" to "order of service",
        "عبادت" to "service",
        "جلسه*" to "meeting",
        "یکشنبه*" to "sunday",
        "يكشنبه*" to "sunday",
        "تقویم*" to "calendar",
        "تقويم*" to "calendar",
        "برنامه" to "schedule",
        "فهرست پخش" to "playlist",
        "پلی لیست" to "playlist",
        "پلي ليست" to "playlist",
        "پلیلیست" to "playlist",
        "پليليست" to "playlist",
        "هر یکشنبه" to "every sunday",
        "هر يكشنبه" to "every sunday",
        "هر هفته" to "every week",
        "هفتگی" to "weekly",
        "هفتگي" to "weekly",
        "ماهانه" to "monthly",
        "تکرار*" to "repeat",
        "تكرار*" to "repeat",
        "الگو*" to "template",
        "قالب*" to "template",

        // Many, all, both.
        "همه" to "all",
        "همه ی" to "all",
        "همه ي" to "all",
        "همهی" to "all",
        "همهي" to "all",
        "تمام" to "all",
        "همه جا" to "everything",
        "هر دو" to "both",
        "چند" to "several",
        "چندین" to "several",
        "چندين" to "several",
        "بسیاری" to "many",
        "بسياري" to "many",
        "زیاد" to "many",
        "زياد" to "many",
        "یکجا" to "at once",
        "يكجا" to "at once",
        "یک باره" to "at once",
        "يك باره" to "at once",
        "یکباره" to "at once",
        "يكباره" to "at once",
        "برای این جلسه" to "this service",
        "براي اين جلسه" to "this service",
        "برای امروز" to "for today",
        "براي امروز" to "for today",
        "موقتاً" to "temporarily",
        "موقتا" to "temporarily",
        "موقت" to "temporarily",

        // Languages, by name.
        "فارسی" to "farsi",
        "فارسي" to "farsi",
        "انگلیسی" to "english",
        "انگليسي" to "english",
        "عربی" to "arabic",
        "عربي" to "arabic",
        "روسی" to "russian",
        "روسي" to "russian",
        "اوکراینی" to "ukrainian",
        "اوكرايني" to "ukrainian",
        "بلاروسی" to "belarusian",
        "بلاروسي" to "belarusian",
        "اسپانیایی" to "spanish",
        "اسپانيايي" to "spanish",
        "آلمانی" to "german",
        "آلماني" to "german",
        "فرانسوی" to "french",
        "فرانسوي" to "french",
        "لهستانی" to "polish",
        "لهستاني" to "polish",
        "پرتغالی" to "portuguese",
        "پرتغالي" to "portuguese",
        "ایتالیایی" to "italian",
        "ايتاليايي" to "italian",
        "هلندی" to "dutch",
        "هلندي" to "dutch",
        "رومانیایی" to "romanian",
        "رومانيايي" to "romanian",
        "ترکی" to "turkish",
        "تركي" to "turkish",
        "عبری" to "hebrew",
        "عبري" to "hebrew",
        "یونانی" to "greek",
        "يوناني" to "greek",
        "هندی" to "hindi",
        "هندي" to "hindi",
        "نپالی" to "nepali",
        "نپالي" to "nepali",
        "تامیلی" to "tamil",
        "تاميلي" to "tamil",
        "چینی" to "chinese",
        "چيني" to "chinese",
        "ژاپنی" to "japanese",
        "ژاپني" to "japanese",
        "کره ای" to "korean",
        "كره اي" to "korean",
        "کرهای" to "korean",
        "كرهاي" to "korean",
        "ارمنی" to "armenian",
        "ارمني" to "armenian",
        "گرجی" to "georgian",
        "گرجي" to "georgian",
        "ازبکی" to "uzbek",
        "ازبكي" to "uzbek",
        "قزاقی" to "kazakh",
        "قزاقي" to "kazakh",
        "لاتین" to "latin",
        "لاتين" to "latin",

        // Colors.
        "آبی تیره" to "dark blue",
        "آبي تيره" to "dark blue",
        "آبی روشن" to "light blue",
        "آبي روشن" to "light blue",
        "سبز تیره" to "dark green",
        "سبز تيره" to "dark green",
        "سبز روشن" to "light green",
        "قرمز تیره" to "dark red",
        "قرمز تيره" to "dark red",
        "خاکستری تیره" to "dark grey",
        "خاكستري تيره" to "dark grey",
        "خاکستری روشن" to "light grey",
        "خاكستري روشن" to "light grey",
        "سرمه ای" to "navy",
        "سرمه اي" to "navy",
        "سرمهای" to "navy",
        "سرمهاي" to "navy",
        "آسمانی" to "sky",
        "آسماني" to "sky",
        "آبی" to "blue",
        "آبي" to "blue",
        "مشکی" to "black",
        "مشكي" to "black",
        "سیاه" to "black",
        "سياه" to "black",
        "سفید" to "white",
        "سفيد" to "white",
        "خاکستری" to "grey",
        "خاكستري" to "grey",
        "طوسی" to "grey",
        "طوسي" to "grey",
        "نقره ای" to "silver",
        "نقره اي" to "silver",
        "نقرهای" to "silver",
        "نقرهاي" to "silver",
        "قرمز" to "red",
        "سرخ" to "red",
        "زرشکی" to "maroon",
        "زرشكي" to "maroon",
        "نارنجی" to "orange",
        "نارنجي" to "orange",
        "زرد" to "yellow",
        "طلایی" to "gold",
        "طلايي" to "gold",
        "سبز" to "green",
        "سبز لیمویی" to "lime",
        "سبز ليمويي" to "lime",
        "فیروزه ای" to "turquoise",
        "فيروزه اي" to "turquoise",
        "فیروزهای" to "turquoise",
        "فيروزهاي" to "turquoise",
        "بنفش" to "purple",
        "ارغوانی" to "violet",
        "ارغواني" to "violet",
        "یاسی" to "lavender",
        "ياسي" to "lavender",
        "صورتی" to "pink",
        "صورتي" to "pink",
        "قهوه ای" to "brown",
        "قهوه اي" to "brown",
        "قهوهای" to "brown",
        "قهوهاي" to "brown",
        "بژ" to "beige",
        "کرم" to "cream",
        "كرم" to "cream",
        "کرمی" to "cream",
        "كرمي" to "cream",
        "تیره" to "dark",
        "تيره" to "dark",
        "پررنگ" to "dark",
        "روشن" to "light",
        "کم رنگ" to "light",
        "كم رنگ" to "light",
        "کمرنگ" to "light",
        "كمرنگ" to "light",

        // Talking to the helper.
        "سلام" to "hello",
        "درود" to "hello",
        "وقت بخیر" to "hello",
        "وقت بخير" to "hello",
        "کمک" to "help",
        "كمك" to "help",
        "کمکم کن" to "help",
        "كمكم كن" to "help",
        "کمک کن" to "help",
        "كمك كن" to "help",
        "راهنمایی" to "help",
        "راهنمايي" to "help",
        "چه کار می توانی بکنی" to "what can you do",
        "چه كار مي تواني بكني" to "what can you do",
        "چه کار میتوانی بکنی" to "what can you do",
        "چه كار ميتواني بكني" to "what can you do",
        "چیکار میتونی بکنی" to "what can you do",
        "چيكار ميتوني بكني" to "what can you do",
        "چه کارهایی بلدی" to "what can you do",
        "چه كارهايي بلدي" to "what can you do",
        "تو کی هستی" to "who are you",
        "تو كي هستي" to "who are you",
        "کی هستی" to "who are you",
        "كي هستي" to "who are you",
        "مرسی" to "thanks",
        "مرسي" to "thanks",
        "ممنون" to "thanks",
        "ممنونم" to "thank you",
        "متشکرم" to "thank you",
        "متشكرم" to "thank you",
        "سپاس" to "thank you",
        "خواهش می کنم" to "please",
        "خواهش مي كنم" to "please",
        "خواهش میکنم" to "please",
        "خواهش ميكنم" to "please",
        "لطفاً" to "please",
        "لطفا" to "please",
        "ویک" to "wick",
        "ويك" to "wick",
    ),
)
