package org.churchpresenter.helper.intent.glossary

internal val PORTUGUESE = Glossary(
    "pt",
    listOf(
        // Asking where, or how.
        "onde" to "where",
        "onde fica" to "where",
        "onde está" to "where",
        "onde esta" to "where",
        "cadê" to "where",
        "cade" to "where",
        "como faço para" to "how do i",
        "como faco para" to "how do i",
        "como faço" to "how do i",
        "como faco" to "how do i",
        "como eu" to "how do i",
        "como posso" to "how can i",
        "como é que" to "how do i",
        "como" to "how do i",
        "não encontro" to "can't find",
        "nao encontro" to "can't find",
        "não acho" to "can't find",
        "nao acho" to "can't find",
        "não consigo encontrar" to "can't find",
        "nao consigo encontrar" to "can't find",
        "não consigo achar" to "can't find",
        "nao consigo achar" to "can't find",
        "me mostra" to "show me",
        "me mostre" to "show me",
        "mostre-me" to "show me",
        "mostra-me" to "show me",

        // Doing.
        "mostr*" to "show",
        "exib*" to "display",
        "projeta*" to "show",
        "projete" to "show",
        "coloca*" to "put",
        "coloque" to "put",
        "põe" to "put",
        "poe" to "put",
        "abre" to "open",
        "abra" to "open",
        "abrir" to "open",
        "vai para" to "go to",
        "vá para" to "go to",
        "va para" to "go to",
        "ir para" to "go to",
        "vai pra" to "go to",
        "muda para" to "switch to",
        "mude para" to "switch to",
        "mudar para" to "switch to",
        "troca para" to "switch to",
        "troque para" to "switch to",
        "procur*" to "find",
        "busca*" to "find",
        "busque" to "find",
        "encontr*" to "find",
        "acha" to "find",
        "achar" to "find",
        "leia" to "read",
        "ler" to "read",
        "faz" to "make",
        "faça" to "make",
        "faca" to "make",
        "fazer" to "make",
        "cria" to "create",
        "crie" to "create",
        "criar" to "create",
        "adicion*" to "add",
        "acrescent*" to "add",
        "carreg*" to "load",
        "importa" to "import",
        "importar" to "import",
        "importe" to "import",
        "baixa" to "download",
        "baixe" to "download",
        "baixar" to "download",
        "instal*" to "install",
        "escolh*" to "choose",
        "selecion*" to "choose",
        "configura" to "set up",
        "configurar" to "set up",
        "configure" to "set up",
        "conect*" to "connect",
        "atribu*" to "assign",
        "escond*" to "hide",
        "ocult*" to "hide",
        "tira" to "remove",
        "tire" to "remove",
        "tirar" to "remove",
        "pare" to "stop",
        "parar" to "stop",
        "pausa*" to "pause",
        "exclua" to "delete",
        "excluir" to "delete",
        "exclui" to "delete",
        "apaga a tela" to "black out",
        "apague a tela" to "black out",
        "apaga*" to "clear",
        "apague" to "clear",
        "limpa" to "clear",
        "limpe" to "clear",
        "limpar" to "clear",
        "tela em branco" to "blank",
        "desfaz*" to "undo",
        "desfaça" to "undo",
        "desfaca" to "undo",
        "como estava" to "undo",
        "ao vivo" to "go live",
        "transmitir" to "go live",
        "transmite" to "go live",
        "liga" to "turn on",
        "ligue" to "turn on",
        "ligar" to "turn on",
        "ativa" to "turn on",
        "ative" to "turn on",
        "ativar" to "turn on",
        "desliga*" to "turn off",
        "desligue" to "turn off",
        "desativ*" to "turn off",
        "próxim*" to "next",
        "proximo" to "next",
        "proxima" to "next",
        "seguinte" to "next",
        "avança*" to "forward",
        "avanca*" to "forward",
        "anterior" to "previous",
        "volta" to "back",
        "volte" to "back",
        "voltar" to "back",
        "aument*" to "increase",
        "maior" to "bigger",
        "amplia*" to "enlarge",
        "diminu*" to "decrease",
        "menor" to "smaller",
        "reduz*" to "reduce",
        "converte" to "convert",
        "converter" to "convert",
        "converta" to "convert",
        "conversor*" to "converter",
        "transfir*" to "transfer",
        "transferir" to "transfer",
        "migra" to "migrate",
        "migrar" to "migrate",
        "edita" to "edit",
        "edite" to "edit",
        "editar" to "edit",
        "altera*" to "change",
        "altere" to "change",
        "muda" to "change",
        "mude" to "change",
        "mudar" to "change",
        "troca" to "change",
        "troque" to "change",
        "trocar" to "change",
        "renome*" to "rename",
        "corrig*" to "fix",
        "consert*" to "fix",
        "organiza" to "organize",
        "organizar" to "organize",
        "compara" to "compare",
        "comparar" to "compare",
        "traduz*" to "translate",
        "planej*" to "plan",
        "automatiz*" to "automate",
        "automaticamente" to "automatically",
        "identifica*" to "identify",
        "identifique" to "identify",
        "numera" to "number the",
        "numere" to "number the",
        "numerar" to "number the",

        // Too small, too big, not working.
        "muito pequen*" to "too small",
        "pequeno demais" to "too small",
        "pequena demais" to "too small",
        "muito miúd*" to "too small",
        "difícil de ler" to "hard to read",
        "dificil de ler" to "hard to read",
        "não dá para ler" to "can't read",
        "nao da para ler" to "can't read",
        "não dá pra ler" to "can't read",
        "nao da pra ler" to "can't read",
        "não consigo ler" to "can't read",
        "nao consigo ler" to "can't read",
        "muito grande" to "too big",
        "grande demais" to "too big",
        "não cabe" to "doesn't fit",
        "nao cabe" to "doesn't fit",
        "não funciona" to "not working",
        "nao funciona" to "not working",
        "não está funcionando" to "not working",
        "nao esta funcionando" to "not working",
        "não mostra" to "not showing",
        "nao mostra" to "not showing",
        "não aparece" to "not showing",
        "nao aparece" to "not showing",
        "não aparece nada" to "nothing shows",
        "nao aparece nada" to "nothing shows",
        "nada aparece" to "nothing shows",
        "tela preta" to "screen is black",
        "sem sinal" to "no signal",
        "sem imagem" to "no picture",
        "qual tela" to "which screen",
        "qual monitor" to "which monitor",
        "qual projetor" to "which projector",

        // What is on screen.
        "plano de fundo" to "background",
        "fundo*" to "background",
        "letra da música" to "lyrics",
        "letra da musica" to "lyrics",
        "tamanho da letra" to "font size",
        "tamanho da fonte" to "font size",
        "letra*" to "lyrics",
        "música" to "song",
        "musica" to "song",
        "músicas" to "songs",
        "musicas" to "songs",
        "canção" to "song",
        "cancao" to "song",
        "canções" to "songs",
        "cancoes" to "songs",
        "louvor*" to "worship",
        "adoração" to "worship",
        "adoracao" to "worship",
        "hino*" to "hymn",
        "bíblia" to "bible",
        "biblia" to "bible",
        "escritura*" to "scripture",
        "versículo*" to "verse",
        "versiculo*" to "verse",
        "capítulo*" to "chapter",
        "capitulo*" to "chapter",
        "fonte*" to "font",
        "tamanh*" to "size",
        "texto*" to "text",
        "palavras" to "words",
        "apresentação de slides" to "slideshow",
        "apresentacao de slides" to "slideshow",
        "foto*" to "photo",
        "imagem" to "image",
        "imagens" to "images",
        "álbum" to "album",
        "álbuns" to "albums",
        "albuns" to "albums",
        "apresentaç*" to "presentation",
        "apresentac*" to "presentation",
        "vídeo*" to "video",
        "filme*" to "movie",
        "mídia" to "media",
        "midia" to "media",
        "terço inferior" to "lower third",
        "terco inferior" to "lower third",
        "tarja*" to "lower third",
        "nome e cargo" to "name and title",
        "anúnci*" to "announcement",
        "anunci*" to "announcement",
        "aviso" to "notice",
        "avisos" to "notices",
        "letreiro*" to "ticker",
        "texto rolando" to "ticker",
        "berçário" to "nursery",
        "bercario" to "nursery",
        "sala das crianças" to "kids room",
        "sala das criancas" to "kids room",
        "sala infantil" to "kids room",
        "contagem regressiva" to "countdown",
        "temporizador*" to "timer",
        "cronômetr*" to "stopwatch",
        "cronometr*" to "stopwatch",
        "relógio*" to "clock",
        "relogio*" to "clock",
        "hora atual" to "current time",
        "hora" to "time",
        "anotações" to "notes",
        "anotacoes" to "notes",
        "notas" to "notes",
        "acorde*" to "chord",
        "cifra*" to "chord",
        "traduç*" to "translation",
        "traduc*" to "translation",
        "idioma*" to "language",
        "língua*" to "language",
        "lingua*" to "language",
        "bilíngu*" to "bilingual",
        "bilingu*" to "bilingual",
        "em outro idioma" to "another language",
        "em outra língua" to "another language",
        "em outra lingua" to "another language",
        "outro idioma" to "another language",
        "segundo idioma" to "second language",
        "dois idiomas" to "two languages",
        "duas línguas" to "two languages",
        "duas linguas" to "two languages",

        // Screens and outputs.
        "tela principal" to "main screen",
        "tela cheia" to "full screen",
        "segunda tela" to "second screen",
        "tela*" to "screen",
        "projetor*" to "projector",
        "monitor de palco" to "stage monitor",
        "monitor do palco" to "stage monitor",
        "tela do palco" to "stage monitor",
        "tela de palco" to "stage monitor",
        "retorno de palco" to "stage monitor",
        "retorno" to "foldback",
        "monitores" to "monitors",
        "saída*" to "output",
        "saida*" to "output",
        "janela de saída" to "output window",
        "janela de saida" to "output window",
        "palco*" to "stage",
        "zona*" to "zone",
        "disposição" to "layout",
        "disposicao" to "layout",
        "arranjo*" to "arrangement",
        "mensage*" to "message",
        "envia" to "send",
        "envie" to "send",
        "enviar" to "send",
        "pré-visualiz*" to "preview",
        "pre-visualiz*" to "preview",
        "previsualiz*" to "preview",
        "prévia" to "preview",
        "o que está na tela" to "what is on screen",
        "o que esta na tela" to "what is on screen",
        "perfil" to "profile",
        "perfis" to "profiles",
        "transmissão" to "stream",
        "transmissao" to "stream",
        "televisão" to "tv",
        "televisao" to "tv",
        "televisor*" to "tv",

        // Pages, tabs and tools.
        "configuraç*" to "settings",
        "configurac*" to "settings",
        "ajustes" to "settings",
        "opções" to "options",
        "opcoes" to "options",
        "preferências" to "preferences",
        "preferencias" to "preferences",
        "assistente de configuração" to "setup wizard",
        "assistente de configuracao" to "setup wizard",
        "introdução" to "getting started",
        "introducao" to "getting started",
        "começar de novo" to "start over",
        "comecar de novo" to "start over",
        "recomeçar" to "start over",
        "atalho*" to "shortcut",
        "teclas de atalho" to "hotkeys",
        "teclado*" to "keyboard",
        "aba" to "tab",
        "abas" to "tab",
        "guia" to "tab",
        "guias" to "tab",
        "biblioteca de músicas" to "song library",
        "biblioteca de musicas" to "song library",
        "biblioteca*" to "library",
        "site*" to "website",
        "navegador*" to "browser",
        "dicionário*" to "dictionary",
        "dicionario*" to "dictionary",
        "câmera*" to "camera",
        "camera*" to "camera",
        "servidor*" to "server",
        "controle remoto" to "remote",
        "remoto*" to "remote",
        "celular*" to "phone",
        "telefone*" to "phone",
        "integraç*" to "integrations",
        "integrac*" to "integrations",

        // Services and planning.
        "ordem do culto" to "order of service",
        "ordem de culto" to "order of service",
        "programação do culto" to "order of service",
        "programacao do culto" to "order of service",
        "liturgia" to "order of service",
        "roteiro*" to "schedule",
        "programação" to "schedule",
        "programacao" to "schedule",
        "culto*" to "service",
        "reunião*" to "meeting",
        "reuniao*" to "meeting",
        "reuniões" to "meetings",
        "domingo*" to "sunday",
        "calendário*" to "calendar",
        "calendario*" to "calendar",
        "lista de reprodução" to "playlist",
        "lista de reproducao" to "playlist",
        "todo domingo" to "every sunday",
        "todos os domingos" to "every sunday",
        "toda semana" to "every week",
        "todas as semanas" to "every week",
        "semanal*" to "weekly",
        "mensal*" to "monthly",
        "repet*" to "repeat",
        "modelo*" to "template",

        // Many, all, both.
        "todos" to "all",
        "todas" to "all",
        "tudo" to "everything",
        "ambos" to "both",
        "ambas" to "both",
        "os dois" to "both",
        "as duas" to "both",
        "vários" to "several",
        "varios" to "several",
        "várias" to "several",
        "varias" to "several",
        "muitos" to "many",
        "muitas" to "many",
        "de uma vez" to "at once",
        "ao mesmo tempo" to "at once",
        "para este culto" to "this service",
        "só neste culto" to "this service",
        "para hoje" to "for today",
        "temporariamente" to "temporarily",
        "por enquanto" to "for now",

        // Languages, by name.
        "inglês" to "english",
        "ingles" to "english",
        "espanhol*" to "spanish",
        "russo" to "russian",
        "russa" to "russian",
        "ucraniano*" to "ukrainian",
        "alemão" to "german",
        "alemao" to "german",
        "alemã" to "german",
        "francês" to "french",
        "frances*" to "french",
        "polonês" to "polish",
        "polones*" to "polish",
        "português" to "portuguese",
        "portugues*" to "portuguese",
        "italiano*" to "italian",
        "holandês" to "dutch",
        "holandes*" to "dutch",
        "romeno*" to "romanian",
        "chinês" to "chinese",
        "chines*" to "chinese",
        "japonês" to "japanese",
        "japones*" to "japanese",
        "coreano*" to "korean",
        "árabe" to "arabic",
        "arabe" to "arabic",
        "hebraico*" to "hebrew",
        "grego*" to "greek",
        "turco*" to "turkish",
        "suaíli" to "swahili",
        "suaili" to "swahili",
        "indonésio" to "indonesian",
        "indonesio" to "indonesian",
        "latim" to "latin",

        // Colors.
        "azul-marinho" to "navy",
        "azul marinho" to "navy",
        "azul-claro" to "light blue",
        "azul claro" to "light blue",
        "azul celeste" to "light blue",
        "azul*" to "blue",
        "preto*" to "black",
        "preta*" to "black",
        "branco" to "white",
        "branca" to "white",
        "brancos" to "white",
        "brancas" to "white",
        "cinza*" to "grey",
        "prata" to "silver",
        "prateado*" to "silver",
        "vermelh*" to "red",
        "bordô" to "maroon",
        "vinho" to "maroon",
        "laranja*" to "orange",
        "amarel*" to "yellow",
        "dourad*" to "gold",
        "ouro" to "gold",
        "verde-limão" to "lime",
        "verde limão" to "lime",
        "verde limao" to "lime",
        "verde-água" to "teal",
        "verde agua" to "teal",
        "verde*" to "green",
        "ciano" to "cyan",
        "turquesa" to "turquoise",
        "roxo*" to "purple",
        "roxa*" to "purple",
        "violeta" to "violet",
        "lilás" to "lavender",
        "lilas" to "lavender",
        "rosa" to "pink",
        "rosas" to "pink",
        "marrom" to "brown",
        "castanho*" to "brown",
        "bege" to "beige",
        "creme" to "cream",
        "escur*" to "dark",
        "claro" to "light",
        "clara" to "light",
        "claros" to "light",
        "claras" to "light",

        // Talking to the helper.
        "olá" to "hello",
        "ola" to "hello",
        "oi" to "hello",
        "bom dia" to "hello",
        "boa tarde" to "hello",
        "boa noite" to "hello",
        "ajuda*" to "help",
        "ajude*" to "help",
        "o que você pode fazer" to "what can you do",
        "o que voce pode fazer" to "what can you do",
        "o que você sabe fazer" to "what can you do",
        "o que voce sabe fazer" to "what can you do",
        "o que você faz" to "what do you do",
        "o que voce faz" to "what do you do",
        "quem é você" to "who are you",
        "quem e voce" to "who are you",
        "quem é vc" to "who are you",
        "obrigad*" to "thanks",
        "valeu" to "thanks",
        "muito obrigado" to "thank you",
        "muito obrigada" to "thank you",
        "por favor" to "please",
        "wik" to "wick",

        // Newer requests.
        "pesquis*" to "search",
        "busca* um" to "search a",
        "busca* uma" to "search a",
        "busca* na" to "search in",
        "busca* no" to "search in",
        "procur* um" to "search a",
        "procur* uma" to "search a",
        "procur* na" to "search in",
        "procur* no" to "search in",
        "consultar" to "look up",
        "uma música" to "a song",
        "uma musica" to "a song",
        "uma canção" to "a song",
        "uma cancao" to "a song",
        "a música" to "the song",
        "a musica" to "the song",
        "um versículo" to "a verse",
        "um versiculo" to "a verse",
        "o versículo" to "the verse",
        "o versiculo" to "the verse",
        "versículos" to "verses",
        "versiculos" to "verses",
        "número da música" to "song number",
        "numero da musica" to "song number",
        "número do hino" to "song number",
        "numero do hino" to "song number",
        "por número" to "by number",
        "por numero" to "by number",
        "por título" to "by title",
        "por titulo" to "by title",
        "número" to "number",
        "numero" to "number",
        "chamada" to "called",
        "chamado" to "called",
        "intitulada" to "named",
        "intitulado" to "named",
        "preferid*" to "favorite",
        "com estrela" to "starred",
        "esta música" to "this song",
        "esta musica" to "this song",
        "essa música" to "this song",
        "essa musica" to "this song",
        "esta canção" to "this song",
        "esta cancao" to "this song",
        "cada música" to "each song",
        "cada musica" to "each song",
        "por música" to "per song",
        "por musica" to "per song",
        "seu próprio fundo" to "its own background",
        "seu proprio fundo" to "its own background",
        "próprio fundo" to "own background",
        "proprio fundo" to "own background",
        "fundo próprio" to "own background",
        "fundo proprio" to "own background",
        "seu próprio" to "its own",
        "seu proprio" to "its own",
        "sua própria" to "its own",
        "sua propria" to "its own",
        "mais de um versículo" to "more than one verse",
        "mais de um versiculo" to "more than one verse",
        "intervalo de versículos" to "range of verses",
        "intervalo de versiculos" to "range of verses",
        "uma passagem" to "a passage",
        "passagem inteira" to "whole passage",
        "passagem" to "passage",
        "passagens" to "passages",
        "histórico*" to "history",
        "historico*" to "history",
        "acabamos de mostrar" to "what did we just show",
        "acabamos de exibir" to "what did we just show",
        "versículos recentes" to "recent verses",
        "versiculos recentes" to "recent verses",
        "referências cruzadas" to "cross references",
        "referencias cruzadas" to "cross references",
        "referência cruzada" to "cross reference",
        "referencia cruzada" to "cross reference",
        "versículos relacionados" to "related verses",
        "versiculos relacionados" to "related verses",
        "passagens relacionadas" to "related passages",
        "passagens paralelas" to "parallel passages",
        "textos paralelos" to "parallel passages",
        "versículos semelhantes" to "similar verses",
        "versiculos semelhantes" to "similar verses",
        "página da web" to "web page",
        "pagina da web" to "web page",
        "página web" to "web page",
        "pagina web" to "web page",
        "página da internet" to "internet page",
        "pagina da internet" to "internet page",
        "estatística*" to "statistics",
        "estatistica*" to "statistics",
        "quantas vezes" to "how many times",
        "com que frequência" to "how often",
        "com que frequencia" to "how often",
        "relatório de músicas" to "song report",
        "relatorio de musicas" to "song report",
        "uso das músicas" to "song usage",
        "uso das musicas" to "song usage",
        "uso de músicas" to "song usage",
        "uso de musicas" to "song usage",
        "do meu celular" to "from my phone",
        "pelo meu celular" to "from my phone",
        "do meu telefone" to "from my phone",
        "pelo meu telefone" to "from my phone",
        "pelo celular" to "from the phone",
        "pelo telefone" to "from the phone",
        "do celular" to "from the phone",
        "no meu celular" to "on my phone",
        "no meu telefone" to "on my phone",
        "no celular" to "on my phone",
        "conect* meu celular" to "connect my phone",
        "conect* meu telefone" to "connect my phone",
        "conect* o celular" to "connect a phone",
        "código qr" to "qr code",
        "codigo qr" to "qr code",
        "controla* pelo" to "control it from",
        "controla* do" to "control it from",
        "controla* de" to "control it from",
        "minuto*" to "minutes",
        "anuncia" to "announce",
        "anuncie" to "announce",
        "anunciar" to "announce",
        "anúncio:" to "announce",
        "anuncio:" to "announce",
        "anuncia:" to "announce",
        "anuncie:" to "announce",
        "aviso:" to "announce",
        "ao roteiro" to "to the schedule",
        "no roteiro" to "in the schedule",
        "do roteiro" to "from the schedule",
        "à programação" to "to the schedule",
        "na programação" to "in the schedule",
        "na programacao" to "in the schedule",
        "ir para a" to "go to the",
        "ir para o" to "go to the",
        "vai para a" to "go to the",
        "vai para o" to "go to the",
        "vá para a" to "go to the",
        "vá para o" to "go to the",
        "va para a" to "go to the",
        "va para o" to "go to the",
        "itens" to "items",
        "o que está no ar" to "what's live",
        "o que esta no ar" to "what's live",
        "o que está ao vivo" to "what's live",
        "o que esta ao vivo" to "what's live",
        "o que está passando" to "what's showing",
        "o que esta passando" to "what's showing",
        "o que está sendo mostrado" to "what's showing",
        "o que esta sendo mostrado" to "what's showing",
        "tem algo ao vivo" to "is anything live",
        "tem alguma coisa ao vivo" to "is anything live",
        "qual é a versão" to "what version",
        "qual e a versao" to "what version",
        "qual versão" to "which version",
        "qual versao" to "which version",
        "que versão" to "what version",
        "que versao" to "what version",
        "versão do aplicativo" to "app version",
        "versao do aplicativo" to "app version",
        "versão do app" to "app version",
        "versao do app" to "app version",
        "verificar atualizações" to "check for updates",
        "verificar atualizacoes" to "check for updates",
        "procurar atualizações" to "check for updates",
        "procurar atualizacoes" to "check for updates",
        "buscar atualizações" to "check for updates",
        "buscar atualizacoes" to "check for updates",
        "tem atualização" to "is there an update",
        "tem atualizacao" to "is there an update",
        "há atualização" to "is there an update",
        "ha atualizacao" to "is there an update",
        "última versão" to "latest version",
        "ultima versao" to "latest version",
        "nova versão" to "newer version",
        "nova versao" to "newer version",
        "está atualizado" to "up to date",
        "esta atualizado" to "up to date",
        "comandos" to "commands",
        "lista de comandos" to "list of commands",
        "o que posso dizer" to "what can i say",
        "o que eu posso dizer" to "what can i say",
        "o que posso digitar" to "what can i type",
        "o que eu posso digitar" to "what can i type",
        "o que posso escrever" to "what can i type",
        "o que posso perguntar" to "what can i ask",
        "o que você entende" to "what do you understand",
        "o que voce entende" to "what do you understand",

        // Look requests.
        "mudo" to "change",
        "altero" to "change",
        "troco" to "change",
        "edito" to "edit",
        "corrijo" to "fix",
        "a letra da música" to "the lyrics",
        "a letra da musica" to "the lyrics",
        "a letra*" to "the lyrics",
        "as letras" to "the lyrics",
        "na letra" to "to the lyrics",
        "erro de digitação" to "typo",
        "erro de digitacao" to "typo",
        "movo" to "move",
        "mover" to "move",
        "mova" to "move",
        "deixo" to "make",
        "deixar" to "make",
        "coloco" to "put",
        "negrito" to "bold",
        "itálico" to "italic",
        "italico" to "italic",
        "sublinhad*" to "underline",
        "sublinhar" to "underline",
        "contorno*" to "outline",
        "sombra*" to "shadow",
        "margem" to "margin",
        "margens" to "margins",
        "bordas" to "edges",
        "para cima" to "to the top",
        "em cima" to "top",
        "parte de cima" to "top",
        "topo" to "top",
        "para baixo" to "to the bottom",
        "embaixo" to "bottom",
        "em baixo" to "bottom",
        "parte de baixo" to "bottom",
        "no meio" to "middle",
        "centro" to "center",
        "centraliz*" to "center",
        "esquerda" to "left",
        "direita" to "right",
        "alinh*" to "align",
        "posição" to "position",
        "posicao" to "position",
        "tipo de letra" to "typeface",
        "tipografia" to "typeface",
        "aparência" to "appearance",
        "aparencia" to "appearance",
        "aspecto" to "look",
        "visual" to "look",
        "estilo*" to "style",
        "formatação" to "formatting",
        "formatacao" to "formatting",
        "título" to "title",
        "títulos" to "titles",
        "titulo" to "title",
        "titulos" to "titles",
        "título da música" to "song title",
        "titulo da musica" to "song title",
        "referência" to "reference",
        "referências" to "references",
        "referencia" to "reference",
        "referencias" to "references",
        "bíblic*" to "bible",
        "biblic*" to "bible",
        "marcador de fim" to "end marker",
        "fim da música" to "end of song",
        "fim da musica" to "end of song",
        "final da música" to "end of song",
        "final da musica" to "end of song",

        // The help table's own examples.
        "pais" to "parents",
        "sequência de fotos" to "slideshow",
        "sequencia de fotos" to "slideshow",
        "como faço um" to "how do i make a",
        "como faco um" to "how do i make a",
        "como faço uma" to "how do i make a",
        "configuro" to "set up",
        "em lote" to "batch",
    ),
)
