package org.churchpresenter.helper.intent.glossary

internal val PORTUGUESE = Glossary(
    "pt",
    listOf(
        // Asking where, or how.
        "onde" to "where",
        "onde fica" to "where",
        "onde está" to "where",
        "onde esta" to "where",
        "cadê" to "where",
        "cade" to "where",
        "como faço para" to "how do i",
        "como faco para" to "how do i",
        "como faço" to "how do i",
        "como faco" to "how do i",
        "como eu" to "how do i",
        "como posso" to "how can i",
        "como é que" to "how do i",
        "como" to "how do i",
        "não encontro" to "can't find",
        "nao encontro" to "can't find",
        "não acho" to "can't find",
        "nao acho" to "can't find",
        "não consigo encontrar" to "can't find",
        "nao consigo encontrar" to "can't find",
        "não consigo achar" to "can't find",
        "nao consigo achar" to "can't find",
        "me mostra" to "show me",
        "me mostre" to "show me",
        "mostre-me" to "show me",
        "mostra-me" to "show me",

        // Doing.
        "mostr*" to "show",
        "exib*" to "display",
        "projeta*" to "show",
        "projete" to "show",
        "coloca*" to "put",
        "coloque" to "put",
        "põe" to "put",
        "poe" to "put",
        "abre" to "open",
        "abra" to "open",
        "abrir" to "open",
        "vai para" to "go to",
        "vá para" to "go to",
        "va para" to "go to",
        "ir para" to "go to",
        "vai pra" to "go to",
        "muda para" to "switch to",
        "mude para" to "switch to",
        "mudar para" to "switch to",
        "troca para" to "switch to",
        "troque para" to "switch to",
        "procur*" to "find",
        "busca*" to "find",
        "busque" to "find",
        "encontr*" to "find",
        "acha" to "find",
        "achar" to "find",
        "leia" to "read",
        "ler" to "read",
        "faz" to "make",
        "faça" to "make",
        "faca" to "make",
        "fazer" to "make",
        "cria" to "create",
        "crie" to "create",
        "criar" to "create",
        "adicion*" to "add",
        "acrescent*" to "add",
        "carreg*" to "load",
        "importa" to "import",
        "importar" to "import",
        "importe" to "import",
        "baixa" to "download",
        "baixe" to "download",
        "baixar" to "download",
        "instal*" to "install",
        "escolh*" to "choose",
        "selecion*" to "choose",
        "configura" to "set up",
        "configurar" to "set up",
        "configure" to "set up",
        "conect*" to "connect",
        "atribu*" to "assign",
        "escond*" to "hide",
        "ocult*" to "hide",
        "tira" to "remove",
        "tire" to "remove",
        "tirar" to "remove",
        "pare" to "stop",
        "parar" to "stop",
        "pausa*" to "pause",
        "exclua" to "delete",
        "excluir" to "delete",
        "exclui" to "delete",
        "apaga a tela" to "black out",
        "apague a tela" to "black out",
        "apaga*" to "clear",
        "apague" to "clear",
        "limpa" to "clear",
        "limpe" to "clear",
        "limpar" to "clear",
        "tela em branco" to "blank",
        "desfaz*" to "undo",
        "desfaça" to "undo",
        "desfaca" to "undo",
        "como estava" to "undo",
        "ao vivo" to "go live",
        "transmitir" to "go live",
        "transmite" to "go live",
        "liga" to "turn on",
        "ligue" to "turn on",
        "ligar" to "turn on",
        "ativa" to "turn on",
        "ative" to "turn on",
        "ativar" to "turn on",
        "desliga*" to "turn off",
        "desligue" to "turn off",
        "desativ*" to "turn off",
        "próxim*" to "next",
        "proximo" to "next",
        "proxima" to "next",
        "seguinte" to "next",
        "avança*" to "forward",
        "avanca*" to "forward",
        "anterior" to "previous",
        "volta" to "back",
        "volte" to "back",
        "voltar" to "back",
        "aument*" to "increase",
        "maior" to "bigger",
        "amplia*" to "enlarge",
        "diminu*" to "decrease",
        "menor" to "smaller",
        "reduz*" to "reduce",
        "converte" to "convert",
        "converter" to "convert",
        "converta" to "convert",
        "conversor*" to "converter",
        "transfir*" to "transfer",
        "transferir" to "transfer",
        "migra" to "migrate",
        "migrar" to "migrate",
        "edita" to "edit",
        "edite" to "edit",
        "editar" to "edit",
        "altera*" to "change",
        "altere" to "change",
        "muda" to "change",
        "mude" to "change",
        "mudar" to "change",
        "troca" to "change",
        "troque" to "change",
        "trocar" to "change",
        "renome*" to "rename",
        "corrig*" to "fix",
        "consert*" to "fix",
        "organiza" to "organize",
        "organizar" to "organize",
        "compara" to "compare",
        "comparar" to "compare",
        "traduz*" to "translate",
        "planej*" to "plan",
        "automatiz*" to "automate",
        "automaticamente" to "automatically",
        "identifica*" to "identify",
        "identifique" to "identify",
        "numera" to "number the",
        "numere" to "number the",
        "numerar" to "number the",

        // Too small, too big, not working.
        "muito pequen*" to "too small",
        "pequeno demais" to "too small",
        "pequena demais" to "too small",
        "muito miúd*" to "too small",
        "difícil de ler" to "hard to read",
        "dificil de ler" to "hard to read",
        "não dá para ler" to "can't read",
        "nao da para ler" to "can't read",
        "não dá pra ler" to "can't read",
        "nao da pra ler" to "can't read",
        "não consigo ler" to "can't read",
        "nao consigo ler" to "can't read",
        "muito grande" to "too big",
        "grande demais" to "too big",
        "não cabe" to "doesn't fit",
        "nao cabe" to "doesn't fit",
        "não funciona" to "not working",
        "nao funciona" to "not working",
        "não está funcionando" to "not working",
        "nao esta funcionando" to "not working",
        "não mostra" to "not showing",
        "nao mostra" to "not showing",
        "não aparece" to "not showing",
        "nao aparece" to "not showing",
        "não aparece nada" to "nothing shows",
        "nao aparece nada" to "nothing shows",
        "nada aparece" to "nothing shows",
        "tela preta" to "screen is black",
        "sem sinal" to "no signal",
        "sem imagem" to "no picture",
        "qual tela" to "which screen",
        "qual monitor" to "which monitor",
        "qual projetor" to "which projector",

        // What is on screen.
        "plano de fundo" to "background",
        "fundo*" to "background",
        "letra da música" to "lyrics",
        "letra da musica" to "lyrics",
        "tamanho da letra" to "font size",
        "tamanho da fonte" to "font size",
        "letra*" to "lyrics",
        "música" to "song",
        "musica" to "song",
        "músicas" to "songs",
        "musicas" to "songs",
        "canção" to "song",
        "cancao" to "song",
        "canções" to "songs",
        "cancoes" to "songs",
        "louvor*" to "worship",
        "adoração" to "worship",
        "adoracao" to "worship",
        "hino*" to "hymn",
        "bíblia" to "bible",
        "biblia" to "bible",
        "escritura*" to "scripture",
        "versículo*" to "verse",
        "versiculo*" to "verse",
        "capítulo*" to "chapter",
        "capitulo*" to "chapter",
        "fonte*" to "font",
        "tamanh*" to "size",
        "texto*" to "text",
        "palavras" to "words",
        "apresentação de slides" to "slideshow",
        "apresentacao de slides" to "slideshow",
        "foto*" to "photo",
        "imagem" to "image",
        "imagens" to "images",
        "álbum" to "album",
        "álbuns" to "albums",
        "albuns" to "albums",
        "apresentaç*" to "presentation",
        "apresentac*" to "presentation",
        "vídeo*" to "video",
        "filme*" to "movie",
        "mídia" to "media",
        "midia" to "media",
        "terço inferior" to "lower third",
        "terco inferior" to "lower third",
        "tarja*" to "lower third",
        "nome e cargo" to "name and title",
        "anúnci*" to "announcement",
        "anunci*" to "announcement",
        "aviso" to "notice",
        "avisos" to "notices",
        "letreiro*" to "ticker",
        "texto rolando" to "ticker",
        "berçário" to "nursery",
        "bercario" to "nursery",
        "sala das crianças" to "kids room",
        "sala das criancas" to "kids room",
        "sala infantil" to "kids room",
        "contagem regressiva" to "countdown",
        "temporizador*" to "timer",
        "cronômetr*" to "stopwatch",
        "cronometr*" to "stopwatch",
        "relógio*" to "clock",
        "relogio*" to "clock",
        "hora atual" to "current time",
        "hora" to "time",
        "anotações" to "notes",
        "anotacoes" to "notes",
        "notas" to "notes",
        "acorde*" to "chord",
        "cifra*" to "chord",
        "traduç*" to "translation",
        "traduc*" to "translation",
        "idioma*" to "language",
        "língua*" to "language",
        "lingua*" to "language",
        "bilíngu*" to "bilingual",
        "bilingu*" to "bilingual",
        "em outro idioma" to "another language",
        "em outra língua" to "another language",
        "em outra lingua" to "another language",
        "outro idioma" to "another language",
        "segundo idioma" to "second language",
        "dois idiomas" to "two languages",
        "duas línguas" to "two languages",
        "duas linguas" to "two languages",

        // Screens and outputs.
        "tela principal" to "main screen",
        "tela cheia" to "full screen",
        "segunda tela" to "second screen",
        "tela*" to "screen",
        "projetor*" to "projector",
        "monitor de palco" to "stage monitor",
        "monitor do palco" to "stage monitor",
        "tela do palco" to "stage monitor",
        "tela de palco" to "stage monitor",
        "retorno de palco" to "stage monitor",
        "retorno" to "foldback",
        "monitores" to "monitors",
        "saída*" to "output",
        "saida*" to "output",
        "janela de saída" to "output window",
        "janela de saida" to "output window",
        "palco*" to "stage",
        "zona*" to "zone",
        "disposição" to "layout",
        "disposicao" to "layout",
        "arranjo*" to "arrangement",
        "mensage*" to "message",
        "envia" to "send",
        "envie" to "send",
        "enviar" to "send",
        "pré-visualiz*" to "preview",
        "pre-visualiz*" to "preview",
        "previsualiz*" to "preview",
        "prévia" to "preview",
        "o que está na tela" to "what is on screen",
        "o que esta na tela" to "what is on screen",
        "perfil" to "profile",
        "perfis" to "profiles",
        "transmissão" to "stream",
        "transmissao" to "stream",
        "televisão" to "tv",
        "televisao" to "tv",
        "televisor*" to "tv",

        // Pages, tabs and tools.
        "configuraç*" to "settings",
        "configurac*" to "settings",
        "ajustes" to "settings",
        "opções" to "options",
        "opcoes" to "options",
        "preferências" to "preferences",
        "preferencias" to "preferences",
        "assistente de configuração" to "setup wizard",
        "assistente de configuracao" to "setup wizard",
        "introdução" to "getting started",
        "introducao" to "getting started",
        "começar de novo" to "start over",
        "comecar de novo" to "start over",
        "recomeçar" to "start over",
        "atalho*" to "shortcut",
        "teclas de atalho" to "hotkeys",
        "teclado*" to "keyboard",
        "aba" to "tab",
        "abas" to "tab",
        "guia" to "tab",
        "guias" to "tab",
        "biblioteca de músicas" to "song library",
        "biblioteca de musicas" to "song library",
        "biblioteca*" to "library",
        "site*" to "website",
        "navegador*" to "browser",
        "dicionário*" to "dictionary",
        "dicionario*" to "dictionary",
        "câmera*" to "camera",
        "camera*" to "camera",
        "servidor*" to "server",
        "controle remoto" to "remote",
        "remoto*" to "remote",
        "celular*" to "phone",
        "telefone*" to "phone",
        "integraç*" to "integrations",
        "integrac*" to "integrations",

        // Services and planning.
        "ordem do culto" to "order of service",
        "ordem de culto" to "order of service",
        "programação do culto" to "order of service",
        "programacao do culto" to "order of service",
        "liturgia" to "order of service",
        "roteiro*" to "schedule",
        "programação" to "schedule",
        "programacao" to "schedule",
        "culto*" to "service",
        "reunião*" to "meeting",
        "reuniao*" to "meeting",
        "reuniões" to "meetings",
        "domingo*" to "sunday",
        "calendário*" to "calendar",
        "calendario*" to "calendar",
        "lista de reprodução" to "playlist",
        "lista de reproducao" to "playlist",
        "todo domingo" to "every sunday",
        "todos os domingos" to "every sunday",
        "toda semana" to "every week",
        "todas as semanas" to "every week",
        "semanal*" to "weekly",
        "mensal*" to "monthly",
        "repet*" to "repeat",
        "modelo*" to "template",

        // Many, all, both.
        "todos" to "all",
        "todas" to "all",
        "tudo" to "everything",
        "ambos" to "both",
        "ambas" to "both",
        "os dois" to "both",
        "as duas" to "both",
        "vários" to "several",
        "varios" to "several",
        "várias" to "several",
        "varias" to "several",
        "muitos" to "many",
        "muitas" to "many",
        "de uma vez" to "at once",
        "ao mesmo tempo" to "at once",
        "para este culto" to "this service",
        "só neste culto" to "this service",
        "para hoje" to "for today",
        "temporariamente" to "temporarily",
        "por enquanto" to "for now",

        // Languages, by name.
        "inglês" to "english",
        "ingles" to "english",
        "espanhol*" to "spanish",
        "russo" to "russian",
        "russa" to "russian",
        "ucraniano*" to "ukrainian",
        "alemão" to "german",
        "alemao" to "german",
        "alemã" to "german",
        "francês" to "french",
        "frances*" to "french",
        "polonês" to "polish",
        "polones*" to "polish",
        "português" to "portuguese",
        "portugues*" to "portuguese",
        "italiano*" to "italian",
        "holandês" to "dutch",
        "holandes*" to "dutch",
        "romeno*" to "romanian",
        "chinês" to "chinese",
        "chines*" to "chinese",
        "japonês" to "japanese",
        "japones*" to "japanese",
        "coreano*" to "korean",
        "árabe" to "arabic",
        "arabe" to "arabic",
        "hebraico*" to "hebrew",
        "grego*" to "greek",
        "turco*" to "turkish",
        "suaíli" to "swahili",
        "suaili" to "swahili",
        "indonésio" to "indonesian",
        "indonesio" to "indonesian",
        "latim" to "latin",

        // Colors.
        "azul-marinho" to "navy",
        "azul marinho" to "navy",
        "azul-claro" to "light blue",
        "azul claro" to "light blue",
        "azul celeste" to "light blue",
        "azul*" to "blue",
        "preto*" to "black",
        "preta*" to "black",
        "branco" to "white",
        "branca" to "white",
        "brancos" to "white",
        "brancas" to "white",
        "cinza*" to "grey",
        "prata" to "silver",
        "prateado*" to "silver",
        "vermelh*" to "red",
        "bordô" to "maroon",
        "vinho" to "maroon",
        "laranja*" to "orange",
        "amarel*" to "yellow",
        "dourad*" to "gold",
        "ouro" to "gold",
        "verde-limão" to "lime",
        "verde limão" to "lime",
        "verde limao" to "lime",
        "verde-água" to "teal",
        "verde agua" to "teal",
        "verde*" to "green",
        "ciano" to "cyan",
        "turquesa" to "turquoise",
        "roxo*" to "purple",
        "roxa*" to "purple",
        "violeta" to "violet",
        "lilás" to "lavender",
        "lilas" to "lavender",
        "rosa" to "pink",
        "rosas" to "pink",
        "marrom" to "brown",
        "castanho*" to "brown",
        "bege" to "beige",
        "creme" to "cream",
        "escur*" to "dark",
        "claro" to "light",
        "clara" to "light",
        "claros" to "light",
        "claras" to "light",

        // Talking to the helper.
        "olá" to "hello",
        "ola" to "hello",
        "oi" to "hello",
        "bom dia" to "hello",
        "boa tarde" to "hello",
        "boa noite" to "hello",
        "ajuda*" to "help",
        "ajude*" to "help",
        "o que você pode fazer" to "what can you do",
        "o que voce pode fazer" to "what can you do",
        "o que você sabe fazer" to "what can you do",
        "o que voce sabe fazer" to "what can you do",
        "o que você faz" to "what do you do",
        "o que voce faz" to "what do you do",
        "quem é você" to "who are you",
        "quem e voce" to "who are you",
        "quem é vc" to "who are you",
        "obrigad*" to "thanks",
        "valeu" to "thanks",
        "muito obrigado" to "thank you",
        "muito obrigada" to "thank you",
        "por favor" to "please",
        "wik" to "wick",
    ),
)
