package org.churchpresenter.helper.intent.glossary

internal val ROMANIAN = Glossary(
    "ro",
    listOf(
        // Asking where, or how.
        "unde" to "where",
        "cum pot" to "how can i",
        "cum se poate" to "how can i",
        "cum fac" to "how do i",
        "cum" to "how do i",
        "nu găsesc" to "can't find",
        "nu gasesc" to "can't find",
        "nu pot găsi" to "can't find",
        "nu pot gasi" to "can't find",
        "arată-mi" to "show me",
        "arata-mi" to "show me",
        "arătați-mi" to "show me",
        "aratati-mi" to "show me",
        "spune-mi cum" to "how do i",

        // Doing.
        "arată" to "show",
        "arata" to "show",
        "arătați" to "show",
        "aratati" to "show",
        "afișează" to "display",
        "afiseaza" to "display",
        "afișați" to "display",
        "afisati" to "display",
        "afișa" to "display",
        "afisa" to "display",
        "proiectează" to "go live",
        "proiecteaza" to "go live",
        "deschide*" to "open",
        "mergi la" to "go to",
        "du-te la" to "go to",
        "du-mă la" to "go to",
        "du-ma la" to "go to",
        "treci la" to "go to",
        "comută la" to "switch to",
        "comuta la" to "switch to",
        "schimbă la" to "switch to",
        "schimba la" to "switch to",
        "găsește" to "find",
        "gaseste" to "find",
        "găsi" to "find",
        "gasi" to "find",
        "caută" to "find",
        "cauta" to "find",
        "citește" to "read",
        "citeste" to "read",
        "fă-l" to "make",
        "fa-l" to "make",
        "fă" to "make",
        "creează" to "create",
        "creeaza" to "create",
        "creați" to "create",
        "creati" to "create",
        "adaugă" to "add",
        "adauga" to "add",
        "adăuga" to "add",
        "adăugați" to "add",
        "adaugati" to "add",
        "încarcă" to "load",
        "incarca" to "load",
        "încărca" to "load",
        "încărcați" to "load",
        "incarcati" to "load",
        "importă" to "import",
        "importa" to "import",
        "importați" to "import",
        "importati" to "import",
        "descarcă" to "download",
        "descarca" to "download",
        "descărca" to "download",
        "descărcați" to "download",
        "descarcati" to "download",
        "instalează" to "install",
        "instaleaza" to "install",
        "instala" to "install",
        "alege*" to "choose",
        "selectează" to "choose",
        "selecteaza" to "choose",
        "configurează" to "set up",
        "configureaza" to "set up",
        "configura" to "set up",
        "setează" to "set up",
        "seteaza" to "set up",
        "setați" to "set up",
        "setati" to "set up",
        "conectează" to "connect",
        "conecteaza" to "connect",
        "conecta" to "connect",
        "atribuie" to "assign",
        "atribui" to "assign",
        "asociază" to "assign",
        "asociaza" to "assign",
        "ascunde*" to "hide",
        "oprește" to "stop",
        "opreste" to "stop",
        "opri" to "stop",
        "șterge" to "delete",
        "sterge" to "delete",
        "ștergeți" to "delete",
        "stergeti" to "delete",
        "elimină" to "delete",
        "elimina" to "delete",
        "golește" to "clear",
        "goleste" to "clear",
        "goli" to "clear",
        "curăță" to "clear",
        "curata" to "clear",
        "întunecă ecranul" to "black out",
        "intuneca ecranul" to "black out",
        "ecran gol" to "blank",
        "anulează" to "undo",
        "anuleaza" to "undo",
        "anula" to "undo",
        "anulați" to "undo",
        "anulati" to "undo",
        "în direct" to "go live",
        "in direct" to "go live",
        "pornește" to "turn on",
        "porneste" to "turn on",
        "activează" to "turn on",
        "activeaza" to "turn on",
        "dezactivează" to "turn off",
        "dezactiveaza" to "turn off",
        "comută" to "toggle",
        "comuta" to "toggle",
        "următor*" to "next",
        "urmator*" to "next",
        "înainte" to "forward",
        "inainte" to "forward",
        "precedent*" to "previous",
        "anterioară" to "previous",
        "anterioara" to "previous",
        "înapoi" to "back",
        "inapoi" to "back",
        "mărește" to "increase",
        "mareste" to "increase",
        "măriți" to "increase",
        "mariti" to "increase",
        "crește" to "increase",
        "creste" to "increase",
        "mai mare" to "bigger",
        "mai mari" to "bigger",
        "micșorează" to "decrease",
        "micsoreaza" to "decrease",
        "micșora" to "decrease",
        "micsora" to "decrease",
        "scade" to "decrease",
        "mai mic" to "smaller",
        "mai mică" to "smaller",
        "mai mica" to "smaller",
        "mai mici" to "smaller",
        "convertește" to "convert",
        "converteste" to "convert",
        "converti" to "convert",
        "conversie" to "convert",
        "convertor*" to "converter",
        "transferă" to "transfer",
        "transfera" to "transfer",
        "mută" to "transfer",
        "muta" to "transfer",
        "editează" to "edit",
        "editeaza" to "edit",
        "edita" to "edit",
        "modifică" to "change",
        "modifica" to "change",
        "schimbă" to "change",
        "schimba" to "change",
        "redenumește" to "rename",
        "redenumeste" to "rename",
        "redenumi" to "rename",
        "repară" to "fix",
        "repara" to "fix",
        "corectează" to "fix",
        "corecteaza" to "fix",
        "organizează" to "organize",
        "organizeaza" to "organize",
        "organiza" to "organize",
        "ordonează" to "organize",
        "ordoneaza" to "organize",
        "fă ordine" to "clean up",
        "fa ordine" to "clean up",
        "compară" to "compare",
        "compara" to "compare",
        "tradu" to "translate",
        "traduce" to "translate",
        "traduceți" to "translate",
        "traduceti" to "translate",
        "planifică" to "plan",
        "planifica" to "plan",
        "plănuiește" to "plan",
        "planuieste" to "plan",
        "automatizează" to "automate",
        "automatizeaza" to "automate",
        "automatiza" to "automate",
        "automat*" to "automatically",
        "identifică" to "identify",
        "identifica" to "identify",
        "numerotează" to "number the",
        "numeroteaza" to "number the",

        // Too small, too big, not working.
        "prea mic*" to "too small",
        "se vede greu" to "hard to read",
        "se vede prost" to "hard to read",
        "nu se vede" to "hard to read",
        "greu de citit" to "hard to read",
        "ilizibil*" to "hard to read",
        "prea mare" to "too big",
        "prea mari" to "too big",
        "nu încape" to "doesn't fit",
        "nu incape" to "doesn't fit",
        "nu se încadrează" to "doesn't fit",
        "nu se incadreaza" to "doesn't fit",
        "nu merge" to "not working",
        "nu funcționează" to "not working",
        "nu functioneaza" to "not working",
        "nu afișează" to "not showing",
        "nu afiseaza" to "not showing",
        "nu se afișează" to "not showing",
        "nu se afiseaza" to "not showing",
        "nu apare" to "not showing",
        "nu se vede nimic" to "nothing shows",
        "nu apare nimic" to "nothing shows",
        "nimic pe ecran" to "nothing shows",
        "ecran negru" to "screen is black",
        "ecranul e negru" to "screen is black",
        "fără semnal" to "no signal",
        "fara semnal" to "no signal",
        "fără imagine" to "no picture",
        "fara imagine" to "no picture",
        "care ecran" to "which screen",
        "ce ecran" to "which screen",
        "care monitor" to "which monitor",
        "care proiector" to "which projector",

        // What is on screen.
        "fundal*" to "background",
        "versurile cântării" to "lyrics",
        "versurile cantarii" to "lyrics",
        "textul cântării" to "lyrics",
        "textul cantarii" to "lyrics",
        "versuri*" to "lyrics",
        "cântarea cântărilor" to "cântarea cântărilor",
        "cantarea cantarilor" to "cantarea cantarilor",
        "cântarea" to "cântarea",
        "cantarea" to "cantarea",
        "cântări" to "songs",
        "cantari" to "songs",
        "cântăr*" to "song",
        "cantar*" to "song",
        "cântare" to "song",
        "cantare" to "song",
        "cântec*" to "song",
        "cantec*" to "song",
        "imn" to "hymn",
        "imnul" to "hymn",
        "imnuri" to "hymn",
        "imnurile" to "hymn",
        "închinare" to "worship",
        "inchinare" to "worship",
        "laudă și închinare" to "worship",
        "lauda si inchinare" to "worship",
        "bibli*" to "bible",
        "scriptur*" to "scripture",
        "verset*" to "verse",
        "capitol*" to "chapter",
        "dimensiun*" to "size",
        "mărime*" to "size",
        "marime*" to "size",
        "textul" to "text",
        "cuvinte*" to "words",
        "litere*" to "letters",
        "prezentare de diapozitive" to "slideshow",
        "prezentare de imagini" to "slideshow",
        "diapozitiv*" to "slide",
        "slide-ul" to "slide",
        "slide-uri" to "slide",
        "slide-urile" to "slide",
        "fotografi*" to "photo",
        "poze" to "photo",
        "poza" to "photo",
        "poză" to "photo",
        "pozele" to "photo",
        "imagini" to "picture",
        "imaginea" to "picture",
        "imaginile" to "picture",
        "prezentar*" to "presentation",
        "videoclip*" to "video",
        "filmul" to "movie",
        "filme" to "movie",
        "filmuleț" to "clip",
        "filmulet" to "clip",
        "sunet*" to "audio",
        "treimea inferioară" to "lower third",
        "treimea inferioara" to "lower third",
        "treime inferioară" to "lower third",
        "treime inferioara" to "lower third",
        "bandă de jos" to "lower third",
        "banda de jos" to "lower third",
        "bandă cu nume" to "name strap",
        "banda cu nume" to "name strap",
        "nume și funcție" to "name and title",
        "nume si functie" to "name and title",
        "anunț*" to "announcement",
        "anunt*" to "announcement",
        "text derulant" to "ticker",
        "bandă derulantă" to "ticker",
        "banda derulanta" to "ticker",
        "camera copiilor" to "kids room",
        "camera pentru copii" to "kids room",
        "sala copiilor" to "kids room",
        "numărătoare inversă" to "countdown",
        "numaratoare inversa" to "countdown",
        "temporizator*" to "timer",
        "cronometru*" to "stopwatch",
        "ceas*" to "clock",
        "ora curentă" to "current time",
        "ora curenta" to "current time",
        "ora exactă" to "current time",
        "ora exacta" to "current time",
        "ora" to "time",
        "timp*" to "time",
        "notițe*" to "notes",
        "notite*" to "notes",
        "acord*" to "chord",
        "traducer*" to "translation",
        "limba" to "language",
        "limbă" to "language",
        "limbi" to "language",
        "limbile" to "language",
        "limbii" to "language",
        "limbaj*" to "language",
        "bilingv*" to "bilingual",
        "în altă limbă" to "another language",
        "in alta limba" to "another language",
        "altă limbă" to "another language",
        "alta limba" to "another language",
        "a doua limbă" to "second language",
        "a doua limba" to "second language",
        "în două limbi" to "two languages",
        "in doua limbi" to "two languages",

        // Screens and outputs.
        "ecranul principal" to "main screen",
        "ecran principal" to "main screen",
        "ecran complet" to "full screen",
        "pe tot ecranul" to "full screen",
        "al doilea ecran" to "second screen",
        "ecranul secundar" to "second screen",
        "ecran secundar" to "second screen",
        "ecran*" to "screen",
        "proiector*" to "projector",
        "monitorul de scenă" to "stage monitor",
        "monitorul de scena" to "stage monitor",
        "monitor de scenă" to "stage monitor",
        "monitor de scena" to "stage monitor",
        "monitorul scenei" to "stage monitor",
        "sufleur*" to "confidence monitor",
        "monitorul" to "monitor",
        "monitoare*" to "monitor",
        "afișaj*" to "display",
        "afisaj*" to "display",
        "fereastra de ieșire" to "output window",
        "fereastra de iesire" to "output window",
        "ieșir*" to "output",
        "iesir*" to "output",
        "proiecți*" to "projection",
        "proiecti*" to "projection",
        "scenă" to "stage",
        "scena" to "stage",
        "scenei" to "stage",
        "zonă" to "zone",
        "zona" to "zone",
        "zonele" to "zone",
        "zonei" to "zone",
        "dispunere*" to "layout",
        "aranjament*" to "arrangement",
        "mesaj*" to "message",
        "trimite*" to "send",
        "previzualizar*" to "preview",
        "ce e pe ecran" to "what is on screen",
        "ce este pe ecran" to "what is on screen",
        "profil*" to "profile",
        "transmisi*" to "stream",
        "televizor*" to "tv",

        // Pages, tabs and tools.
        "setăr*" to "settings",
        "setar*" to "settings",
        "opțiun*" to "options",
        "optiun*" to "options",
        "asistent de configurare" to "setup wizard",
        "noțiuni de bază" to "setup wizard",
        "notiuni de baza" to "setup wizard",
        "ia-o de la capăt" to "start over",
        "ia-o de la capat" to "start over",
        "de la capăt" to "start over",
        "de la capat" to "start over",
        "scurtătur*" to "shortcut",
        "scurtatur*" to "shortcut",
        "tastatur*" to "keyboard",
        "filă" to "tab",
        "fila" to "tab",
        "filele" to "tab",
        "filei" to "tab",
        "biblioteca de cântări" to "song library",
        "biblioteca de cantari" to "song library",
        "biblioteca de cântece" to "song library",
        "biblioteca de cantece" to "song library",
        "bibliotec*" to "library",
        "pagina web" to "website",
        "pagină web" to "website",
        "site-ul" to "website",
        "navigator*" to "browser",
        "dicționar*" to "dictionary",
        "dictionar*" to "dictionary",
        "cameră" to "camera",
        "camere" to "camera",
        "camerei" to "camera",
        "pânză" to "canvas",
        "panza" to "canvas",
        "serverul" to "server",
        "servere" to "server",
        "telecomand*" to "remote",
        "la distanță" to "remote",
        "la distanta" to "remote",
        "telefon*" to "phone",
        "tabletă" to "tablet",
        "tableta" to "tablet",
        "integrăr*" to "integrations",
        "integrar*" to "integrations",

        // Services and planning.
        "ordinea serviciului" to "order of service",
        "ordinea slujbei" to "order of service",
        "programul serviciului" to "order of service",
        "desfășurarea serviciului" to "order of service",
        "desfasurarea serviciului" to "order of service",
        "desfășurarea" to "order of service",
        "desfasurarea" to "order of service",
        "serviciu*" to "service",
        "slujb*" to "service",
        "întâlnir*" to "meeting",
        "intalnir*" to "meeting",
        "adunar*" to "meeting",
        "duminic*" to "sunday",
        "calendarul" to "calendar",
        "programul" to "schedule",
        "listă de redare" to "playlist",
        "lista de redare" to "playlist",
        "în fiecare duminică" to "every sunday",
        "in fiecare duminica" to "every sunday",
        "fiecare duminică" to "every sunday",
        "fiecare duminica" to "every sunday",
        "în fiecare săptămână" to "every week",
        "in fiecare saptamana" to "every week",
        "fiecare săptămână" to "every week",
        "fiecare saptamana" to "every week",
        "săptămânal*" to "weekly",
        "saptamanal*" to "weekly",
        "în fiecare lună" to "monthly",
        "in fiecare luna" to "monthly",
        "lunară" to "monthly",
        "lunara" to "monthly",
        "lunare" to "monthly",
        "repet*" to "repeat",
        "șablon*" to "template",
        "sablon*" to "template",

        // Many, all, both.
        "toate" to "all",
        "toți" to "all",
        "toti" to "all",
        "peste tot" to "everything",
        "pretutindeni" to "everything",
        "ambele" to "both",
        "amândouă" to "both",
        "amandoua" to "both",
        "amândoi" to "both",
        "amandoi" to "both",
        "câteva" to "several",
        "cateva" to "several",
        "mai multe" to "several",
        "multe" to "many",
        "mulți" to "many",
        "deodată" to "at once",
        "deodata" to "at once",
        "simultan" to "at once",
        "pentru acest serviciu" to "this service",
        "pentru serviciul acesta" to "this service",
        "pentru azi" to "for today",
        "pentru astăzi" to "for today",
        "pentru astazi" to "for today",
        "temporar" to "temporarily",

        // Languages, by name.
        "rusă" to "russian",
        "rusa" to "russian",
        "rusesc*" to "russian",
        "rusește" to "russian",
        "ruseste" to "russian",
        "ucrainean*" to "ukrainian",
        "belarus*" to "belarusian",
        "englez*" to "english",
        "spaniol*" to "spanish",
        "germană" to "german",
        "germana" to "german",
        "nemțește" to "german",
        "nemteste" to "german",
        "francez*" to "french",
        "polonez*" to "polish",
        "cehă" to "czech",
        "ceha" to "czech",
        "cehesc*" to "czech",
        "slovac*" to "slovak",
        "croat*" to "croatian",
        "sârb*" to "serbian",
        "sarb*" to "serbian",
        "portughez*" to "portuguese",
        "italiană" to "italian",
        "italiana" to "italian",
        "kazah*" to "kazakh",
        "română" to "romanian",
        "romana" to "romanian",
        "românesc*" to "romanian",
        "romanesc*" to "romanian",
        "românește" to "romanian",
        "romaneste" to "romanian",
        "moldovenesc*" to "moldovan",
        "moldoveneșt*" to "moldovan",
        "moldovenest*" to "moldovan",
        "latină" to "latin",
        "latina" to "latin",
        "maghiar*" to "hungarian",
        "bulgar*" to "bulgarian",

        // Colors.
        "bleumarin" to "navy",
        "albastru închis" to "navy",
        "albastru inchis" to "navy",
        "albastru deschis" to "light blue",
        "bleu" to "light blue",
        "albastr*" to "blue",
        "albaștri" to "blue",
        "verde închis" to "dark green",
        "verde inchis" to "dark green",
        "verde deschis" to "light green",
        "roșu închis" to "dark red",
        "rosu inchis" to "dark red",
        "gri închis" to "dark grey",
        "gri inchis" to "dark grey",
        "gri deschis" to "light grey",
        "mov închis" to "dark purple",
        "mov inchis" to "dark purple",
        "mov deschis" to "lavender",
        "negr*" to "black",
        "neagră" to "black",
        "neagra" to "black",
        "alb" to "white",
        "albă" to "white",
        "alba" to "white",
        "albe" to "white",
        "albi" to "white",
        "gri" to "grey",
        "argint*" to "silver",
        "roșu" to "red",
        "rosu" to "red",
        "roșie" to "red",
        "rosie" to "red",
        "roșii" to "red",
        "rosii" to "red",
        "vișiniu" to "maroon",
        "visiniu" to "maroon",
        "grena" to "maroon",
        "portocali*" to "orange",
        "galben*" to "yellow",
        "auri*" to "gold",
        "verde" to "green",
        "verzi" to "green",
        "turcoaz" to "turquoise",
        "mov" to "purple",
        "roz" to "pink",
        "maro" to "brown",
        "bej" to "beige",
        "crem" to "cream",
        "întunecat*" to "dark",
        "intunecat*" to "dark",
        "luminos" to "light",
        "luminoasă" to "light",
        "luminoasa" to "light",

        // Talking to the helper.
        "salut*" to "hello",
        "bună ziua" to "hello",
        "buna ziua" to "hello",
        "bună seara" to "hello",
        "buna seara" to "hello",
        "bună" to "hello",
        "buna" to "hello",
        "ajut*" to "help",
        "ce poți face" to "what can you do",
        "ce poti face" to "what can you do",
        "ce știi să faci" to "what can you do",
        "ce stii sa faci" to "what can you do",
        "cine ești" to "who are you",
        "cine esti" to "who are you",
        "mulțumesc" to "thank you",
        "multumesc" to "thank you",
        "mulțumim" to "thank you",
        "multumim" to "thank you",
        "mersi" to "thanks",
        "vă rog" to "please",
        "va rog" to "please",
        "te rog" to "please",
        "uic" to "wick",
        "uik" to "wick",
    ),
)
