package org.churchpresenter.helper.intent.glossary

internal val SLOVAK = Glossary(
    "sk",
    listOf(
        // Asking where, or how.
        "kde" to "where",
        "kam" to "where",
        "ako môžem" to "how can i",
        "ako mozem" to "how can i",
        "ako sa dá" to "how can i",
        "ako sa da" to "how can i",
        "ako" to "how do i",
        "nemôžem nájsť" to "can't find",
        "nemozem najst" to "can't find",
        "neviem nájsť" to "can't find",
        "neviem najst" to "can't find",
        "ukáž mi" to "show me",
        "ukaz mi" to "show me",
        "poraď" to "how do i",
        "poraďte" to "how do i",
        "poradte" to "how do i",

        // Doing.
        "ukáž" to "show",
        "ukaz" to "show",
        "ukázať" to "show",
        "ukazat" to "show",
        "ukážte" to "show",
        "ukazte" to "show",
        "zobraz*" to "display",
        "otvor" to "open",
        "otvoriť" to "open",
        "otvorit" to "open",
        "otvorte" to "open",
        "prejdi na" to "go to",
        "prejdi do" to "go to",
        "prejsť na" to "go to",
        "prejst na" to "go to",
        "choď na" to "go to",
        "chod na" to "go to",
        "choď do" to "go to",
        "chod do" to "go to",
        "prepni na" to "switch to",
        "prepnúť na" to "switch to",
        "prepnut na" to "switch to",
        "nájdi" to "find",
        "najdi" to "find",
        "nájsť" to "find",
        "najst" to "find",
        "vyhľadaj" to "find",
        "vyhladaj" to "find",
        "prečítaj" to "read",
        "precitaj" to "read",
        "urob" to "make",
        "urobiť" to "make",
        "urobit" to "make",
        "sprav" to "make",
        "spraviť" to "make",
        "spravit" to "make",
        "vytvor" to "create",
        "vytvoriť" to "create",
        "vytvorit" to "create",
        "pridaj*" to "add",
        "pridať" to "add",
        "pridat" to "add",
        "načítaj*" to "load",
        "nacitaj*" to "load",
        "nahraj*" to "load",
        "importuj*" to "import",
        "stiahni" to "download",
        "stiahnuť" to "download",
        "stiahnut" to "download",
        "nainštaluj*" to "install",
        "nainstaluj*" to "install",
        "vyber*" to "choose",
        "vybrať" to "choose",
        "vybrat" to "choose",
        "nastav*" to "set up",
        "nakonfiguruj*" to "set up",
        "pripoj*" to "connect",
        "priraď" to "assign",
        "prirad" to "assign",
        "priradiť" to "assign",
        "priradit" to "assign",
        "skry*" to "hide",
        "schovaj*" to "hide",
        "zastav*" to "stop",
        "zmaž" to "delete",
        "zmaz" to "delete",
        "zmazať" to "delete",
        "zmazat" to "delete",
        "odstráň" to "delete",
        "odstran" to "delete",
        "odstrániť" to "delete",
        "odstranit" to "delete",
        "vymaž" to "clear",
        "vymaz" to "clear",
        "vymazať" to "clear",
        "vymazat" to "clear",
        "vyčisti" to "clear",
        "vycisti" to "clear",
        "zatemni*" to "black out",
        "prázdna obrazovka" to "blank",
        "prazdna obrazovka" to "blank",
        "vráť späť" to "undo",
        "vrat spat" to "undo",
        "vrátiť späť" to "undo",
        "vratit spat" to "undo",
        "zruš*" to "undo",
        "zrus*" to "undo",
        "naživo" to "go live",
        "nazivo" to "go live",
        "na živo" to "go live",
        "na zivo" to "go live",
        "spustiť naživo" to "go live",
        "spustit nazivo" to "go live",
        "spusti naživo" to "go live",
        "spusti nazivo" to "go live",
        "zapni*" to "turn on",
        "vypni*" to "turn off",
        "prepni*" to "toggle",
        "ďalš*" to "next",
        "dalsi*" to "next",
        "ďalej" to "next",
        "dalej" to "next",
        "dopredu" to "forward",
        "vpred" to "forward",
        "predchádzajúc*" to "previous",
        "predchadzajuc*" to "previous",
        "predošl*" to "previous",
        "predosl*" to "previous",
        "späť" to "back",
        "naspäť" to "back",
        "naspat" to "back",
        "zväčš*" to "increase",
        "zvacs*" to "increase",
        "zvýš*" to "increase",
        "zvys*" to "increase",
        "väčš*" to "bigger",
        "vacs*" to "bigger",
        "zmenš*" to "decrease",
        "zmens*" to "decrease",
        "menší" to "smaller",
        "mensi" to "smaller",
        "menšie" to "smaller",
        "mensie" to "smaller",
        "konvertuj*" to "convert",
        "prekonvertuj*" to "convert",
        "preveď" to "convert",
        "preved" to "convert",
        "previesť" to "convert",
        "previest" to "convert",
        "konvertor*" to "converter",
        "prevodník*" to "converter",
        "prevodnik*" to "converter",
        "prenes*" to "transfer",
        "uprav*" to "edit",
        "úprav*" to "edit",
        "edituj*" to "edit",
        "zmeň" to "change",
        "zmen" to "change",
        "zmeniť" to "change",
        "zmenit" to "change",
        "premenuj*" to "rename",
        "oprav*" to "fix",
        "usporiadaj*" to "organize",
        "usporiadať" to "organize",
        "usporiadat" to "organize",
        "uprac*" to "clean up",
        "porovnaj*" to "compare",
        "porovnať" to "compare",
        "porovnat" to "compare",
        "prelož" to "translate",
        "preloz" to "translate",
        "preložiť" to "translate",
        "prelozit" to "translate",
        "naplánuj*" to "plan",
        "naplanuj*" to "plan",
        "plánuj*" to "plan",
        "planuj*" to "plan",
        "zautomatizuj*" to "automate",
        "automatizuj*" to "automate",
        "automatick*" to "automatically",
        "identifikuj*" to "identify",
        "očísluj*" to "number the",
        "ocisluj*" to "number the",

        // Too small, too big, not working.
        "príliš mal*" to "too small",
        "prilis mal*" to "too small",
        "moc mal*" to "too small",
        "zle vidieť" to "hard to read",
        "zle vidiet" to "hard to read",
        "nie je vidieť" to "hard to read",
        "nie je vidiet" to "hard to read",
        "zle čitateľn*" to "hard to read",
        "zle citateln*" to "hard to read",
        "nečitateľn*" to "hard to read",
        "necitateln*" to "hard to read",
        "príliš veľk*" to "too big",
        "prilis velk*" to "too big",
        "moc veľk*" to "too big",
        "moc velk*" to "too big",
        "nezmestí sa" to "doesn't fit",
        "nezmesti sa" to "doesn't fit",
        "nefunguje" to "not working",
        "nezobrazuje" to "not showing",
        "nič sa nezobrazuje" to "nothing shows",
        "nic sa nezobrazuje" to "nothing shows",
        "nič nezobrazuje" to "nothing shows",
        "nic nezobrazuje" to "nothing shows",
        "nič tam nie je" to "nothing shows",
        "nic tam nie je" to "nothing shows",
        "čierna obrazovka" to "screen is black",
        "cierna obrazovka" to "screen is black",
        "žiadny signál" to "no signal",
        "ziadny signal" to "no signal",
        "bez signálu" to "no signal",
        "bez signalu" to "no signal",
        "žiadny obraz" to "no picture",
        "ziadny obraz" to "no picture",
        "ktorá obrazovka" to "which screen",
        "ktora obrazovka" to "which screen",
        "ktorý monitor" to "which monitor",
        "ktory monitor" to "which monitor",
        "ktorý projektor" to "which projector",
        "ktory projektor" to "which projector",

        // What is on screen.
        "pozadi*" to "background",
        "pozadím" to "background",
        "text piesne" to "lyrics",
        "slová piesne" to "lyrics",
        "slova piesne" to "lyrics",
        "pieseň piesní" to "pieseň piesní",
        "piesen piesni" to "piesen piesni",
        "piesní" to "songs",
        "piesni" to "songs",
        "pieseň" to "song",
        "piesen" to "song",
        "piesn*" to "song",
        "pesničk*" to "song",
        "pesnick*" to "song",
        "chvál*" to "worship",
        "chval*" to "worship",
        "bibli*" to "bible",
        "písmo sväté" to "scripture",
        "pismo svate" to "scripture",
        "sväté písmo" to "scripture",
        "svate pismo" to "scripture",
        "svätého písma" to "scripture",
        "svateho pisma" to "scripture",
        "písmo" to "font",
        "pismo" to "font",
        "písma" to "font",
        "pisma" to "font",
        "verš*" to "verse",
        "vers" to "verse",
        "versa" to "verse",
        "versi" to "verse",
        "versov" to "verse",
        "kapitol*" to "chapter",
        "veľkos*" to "size",
        "velkos*" to "size",
        "slová" to "words",
        "slova" to "words",
        "písmen*" to "letters",
        "pismen*" to "letters",
        "snímk*" to "slide",
        "snimk*" to "slide",
        "slajd*" to "slide",
        "fotk*" to "photo",
        "fotografi*" to "photo",
        "obrazovk*" to "screen",
        "obrazovke" to "screen",
        "obrazoviek" to "screen",
        "obráz*" to "picture",
        "obraz*" to "picture",
        "prezentáci*" to "presentation",
        "prezentaci*" to "presentation",
        "videá" to "video",
        "videa" to "video",
        "film*" to "movie",
        "klip*" to "clip",
        "médiá" to "media",
        "média" to "media",
        "zvuk*" to "audio",
        "spodná tretina" to "lower third",
        "spodna tretina" to "lower third",
        "dolná tretina" to "lower third",
        "dolna tretina" to "lower third",
        "spodnej tretiny" to "lower third",
        "dolnej tretiny" to "lower third",
        "menovk*" to "name strap",
        "meno a funkcia" to "name and title",
        "oznámen*" to "announcement",
        "oznam*" to "announcement",
        "bežiaci text" to "ticker",
        "beziaci text" to "ticker",
        "detský kútik" to "kids room",
        "detsky kutik" to "kids room",
        "detská miestnosť" to "kids room",
        "detska miestnost" to "kids room",
        "odpočet*" to "countdown",
        "odpocet*" to "countdown",
        "odpočítavani*" to "countdown",
        "odpocitavani*" to "countdown",
        "časovač*" to "timer",
        "casovac*" to "timer",
        "stopk*" to "stopwatch",
        "hodiny" to "clock",
        "aktuálny čas" to "current time",
        "aktualny cas" to "current time",
        "čas" to "time",
        "cas" to "time",
        "poznámk*" to "notes",
        "poznamk*" to "notes",
        "akord*" to "chord",
        "preklad*" to "translation",
        "jazyk*" to "language",
        "dvojjazyčn*" to "bilingual",
        "dvojjazycn*" to "bilingual",
        "v inom jazyku" to "another language",
        "iný jazyk" to "another language",
        "iny jazyk" to "another language",
        "druhý jazyk" to "second language",
        "druhy jazyk" to "second language",
        "v dvoch jazykoch" to "two languages",
        "vo dvoch jazykoch" to "two languages",

        // Screens and outputs.
        "hlavná obrazovka" to "main screen",
        "hlavna obrazovka" to "main screen",
        "hlavnej obrazovke" to "main screen",
        "celá obrazovka" to "full screen",
        "cela obrazovka" to "full screen",
        "na celú obrazovku" to "full screen",
        "na celu obrazovku" to "full screen",
        "celej obrazovke" to "full screen",
        "celoobrazovk*" to "fullscreen",
        "druhá obrazovka" to "second screen",
        "druha obrazovka" to "second screen",
        "druhej obrazovke" to "second screen",
        "druhú obrazovku" to "second screen",
        "druhu obrazovku" to "second screen",
        "projektor*" to "projector",
        "dataprojektor*" to "projector",
        "monitor javiska" to "stage monitor",
        "monitora javiska" to "stage monitor",
        "monitor na javisku" to "stage monitor",
        "monitor na pódiu" to "stage monitor",
        "monitor na podiu" to "stage monitor",
        "odposluch*" to "stage monitor",
        "suflér*" to "confidence monitor",
        "sufler*" to "confidence monitor",
        "monitor*" to "monitor",
        "displej*" to "display",
        "výstupné okno" to "output window",
        "vystupne okno" to "output window",
        "výstup*" to "output",
        "vystup*" to "output",
        "projekci*" to "projection",
        "javisk*" to "stage",
        "pódium" to "stage",
        "podium" to "stage",
        "pódiu" to "stage",
        "podiu" to "stage",
        "scéna" to "stage",
        "scena" to "stage",
        "scény" to "stage",
        "sceny" to "stage",
        "zóna" to "zone",
        "zona" to "zone",
        "zóny" to "zone",
        "zony" to "zone",
        "zónu" to "zone",
        "zonu" to "zone",
        "rozloženi*" to "layout",
        "rozlozeni*" to "layout",
        "usporiadani*" to "arrangement",
        "správ*" to "message",
        "sprava" to "message",
        "spravu" to "message",
        "spravy" to "message",
        "pošli" to "send",
        "posli" to "send",
        "poslať" to "send",
        "poslat" to "send",
        "odošli" to "send",
        "odosli" to "send",
        "odoslať" to "send",
        "odoslat" to "send",
        "náhľad*" to "preview",
        "nahlad*" to "preview",
        "čo je na obrazovke" to "what is on screen",
        "co je na obrazovke" to "what is on screen",
        "profil*" to "profile",
        "prenos*" to "stream",
        "vysielani*" to "stream",
        "televíz*" to "tv",
        "televiz*" to "tv",

        // Pages, tabs and tools.
        "nastaveni*" to "settings",
        "možnost*" to "options",
        "moznost*" to "options",
        "sprievodca nastavením" to "setup wizard",
        "sprievodca nastavenim" to "setup wizard",
        "začíname" to "setup wizard",
        "zaciname" to "setup wizard",
        "začať odznova" to "start over",
        "zacat odznova" to "start over",
        "odznova" to "start over",
        "od začiatku" to "start over",
        "od zaciatku" to "start over",
        "klávesová skratka" to "shortcut",
        "klavesova skratka" to "shortcut",
        "klávesové skratky" to "shortcut",
        "klavesove skratky" to "shortcut",
        "skratk*" to "shortcut",
        "klávesnic*" to "keyboard",
        "klavesnic*" to "keyboard",
        "záložk*" to "tab",
        "zalozk*" to "tab",
        "kart*" to "tab",
        "knižnica piesní" to "song library",
        "kniznica piesni" to "song library",
        "knižnicu piesní" to "song library",
        "kniznicu piesni" to "song library",
        "knižnici piesní" to "song library",
        "kniznici piesni" to "song library",
        "knižnic*" to "library",
        "kniznic*" to "library",
        "webová stránka" to "website",
        "webova stranka" to "website",
        "webovú stránku" to "website",
        "webovu stranku" to "website",
        "prehliadač*" to "browser",
        "prehliadac*" to "browser",
        "slovník*" to "dictionary",
        "slovnik*" to "dictionary",
        "kamer*" to "camera",
        "plátno" to "canvas",
        "platno" to "canvas",
        "plátna" to "canvas",
        "serveri" to "server",
        "serveru" to "server",
        "vzdialen*" to "remote",
        "ovládač*" to "remote",
        "ovladac*" to "remote",
        "telefón*" to "phone",
        "telefon*" to "phone",
        "mobil*" to "phone",
        "integráci*" to "integrations",
        "integraci*" to "integrations",

        // Services and planning.
        "priebeh bohoslužby" to "order of service",
        "priebeh bohosluzby" to "order of service",
        "program bohoslužby" to "order of service",
        "program bohosluzby" to "order of service",
        "poriadok bohoslužby" to "order of service",
        "poriadok bohosluzby" to "order of service",
        "bohoslužb*" to "service",
        "bohosluzb*" to "service",
        "zhromažden*" to "meeting",
        "zhromazden*" to "meeting",
        "stretnuti*" to "meeting",
        "nedeľ*" to "sunday",
        "nedel*" to "sunday",
        "kalendár*" to "calendar",
        "kalendar*" to "calendar",
        "rozvrh*" to "schedule",
        "harmonogram*" to "schedule",
        "každú nedeľu" to "every sunday",
        "kazdu nedelu" to "every sunday",
        "každý týždeň" to "every week",
        "kazdy tyzden" to "every week",
        "týždenn*" to "weekly",
        "tyzdenn*" to "weekly",
        "mesačn*" to "monthly",
        "mesacn*" to "monthly",
        "opakuj*" to "repeat",
        "opakov*" to "repeat",
        "šablón*" to "template",
        "sablon*" to "template",

        // Many, all, both.
        "všetk*" to "all",
        "vsetk*" to "all",
        "všade" to "everything",
        "vsade" to "everything",
        "oba" to "both",
        "obe" to "both",
        "obidva" to "both",
        "oboch" to "both",
        "niekoľko" to "several",
        "niekolko" to "several",
        "veľa" to "many",
        "vela" to "many",
        "mnoho" to "many",
        "naraz" to "at once",
        "súčasne" to "at once",
        "sucasne" to "at once",
        "pre túto bohoslužbu" to "this service",
        "pre tuto bohosluzbu" to "this service",
        "na dnes" to "for today",
        "pre dnešok" to "for today",
        "pre dnesok" to "for today",
        "dočasne" to "temporarily",
        "docasne" to "temporarily",

        // Languages, by name.
        "rusk*" to "russian",
        "ruštin*" to "russian",
        "rustin*" to "russian",
        "ukrajinsk*" to "ukrainian",
        "ukrajinčin*" to "ukrainian",
        "ukrajincin*" to "ukrainian",
        "bielorus*" to "belarusian",
        "anglick*" to "english",
        "angličtin*" to "english",
        "anglictin*" to "english",
        "španiel*" to "spanish",
        "spanielsk*" to "spanish",
        "spanielcin*" to "spanish",
        "nemeck*" to "german",
        "nemčin*" to "german",
        "nemcin*" to "german",
        "francúz*" to "french",
        "francuz*" to "french",
        "poľsk*" to "polish",
        "polsk*" to "polish",
        "poľštin*" to "polish",
        "polstin*" to "polish",
        "česk*" to "czech",
        "cesk*" to "czech",
        "češtin*" to "czech",
        "cestin*" to "czech",
        "slovensk*" to "slovak",
        "slovenčin*" to "slovak",
        "slovencin*" to "slovak",
        "chorvátsk*" to "croatian",
        "chorvatsk*" to "croatian",
        "chorvátčin*" to "croatian",
        "chorvatcin*" to "croatian",
        "srbsk*" to "serbian",
        "portugalsk*" to "portuguese",
        "taliansk*" to "italian",
        "taliančin*" to "italian",
        "taliancin*" to "italian",
        "kazašsk*" to "kazakh",
        "kazassk*" to "kazakh",
        "rumunsk*" to "romanian",
        "rumunčin*" to "romanian",
        "rumuncin*" to "romanian",
        "moldavsk*" to "moldovan",
        "latinsk*" to "latin",
        "latinčin*" to "latin",
        "latincin*" to "latin",

        // Colors.
        "tmavomodr*" to "navy",
        "námornícka" to "navy",
        "namornicka" to "navy",
        "svetlomodr*" to "light blue",
        "bledomodr*" to "light blue",
        "svetlo modr*" to "light blue",
        "modr*" to "blue",
        "čiern*" to "black",
        "ciern*" to "black",
        "biel*" to "white",
        "sivá" to "grey",
        "siva" to "grey",
        "sivý" to "grey",
        "sivy" to "grey",
        "sivé" to "grey",
        "sive" to "grey",
        "sivou" to "grey",
        "šed*" to "grey",
        "strieborn*" to "silver",
        "červen*" to "red",
        "cerven*" to "red",
        "bordov*" to "maroon",
        "oranžov*" to "orange",
        "oranzov*" to "orange",
        "žlt*" to "yellow",
        "zlta" to "yellow",
        "zlty" to "yellow",
        "zlte" to "yellow",
        "zltou" to "yellow",
        "zlat*" to "gold",
        "zelen*" to "green",
        "limetkov*" to "lime",
        "tyrkysov*" to "turquoise",
        "fialov*" to "purple",
        "levanduľov*" to "lavender",
        "levandulov*" to "lavender",
        "ružov*" to "pink",
        "ruzov*" to "pink",
        "hnedá" to "brown",
        "hneda" to "brown",
        "hnedý" to "brown",
        "hnedy" to "brown",
        "hnedé" to "brown",
        "hnede" to "brown",
        "hnedou" to "brown",
        "hnedej" to "brown",
        "béžov*" to "beige",
        "bezov*" to "beige",
        "krémov*" to "cream",
        "kremov*" to "cream",
        "tmav*" to "dark",
        "svetl*" to "light",

        // Talking to the helper.
        "ahoj" to "hello",
        "čau" to "hello",
        "dobrý deň" to "hello",
        "dobry den" to "hello",
        "zdravím" to "hello",
        "zdravim" to "hello",
        "pomôž*" to "help",
        "pomoz*" to "help",
        "pomoc" to "help",
        "čo vieš robiť" to "what can you do",
        "co vies robit" to "what can you do",
        "čo vieš" to "what can you do",
        "co vies" to "what can you do",
        "čo dokážeš" to "what can you do",
        "co dokazes" to "what can you do",
        "kto si" to "who are you",
        "ďakujem" to "thank you",
        "dakujem" to "thank you",
        "vďaka" to "thanks",
        "vdaka" to "thanks",
        "prosím" to "please",
        "prosim" to "please",
        "wicku" to "wick",
        "viku" to "wick",
        "vik" to "wick",
    ),
)
