package org.churchpresenter.helper.intent.glossary

internal val SPANISH = Glossary(
    "es",
    listOf(
        // Asking where, or how.
        "dónde" to "where",
        "donde" to "where",
        "adónde" to "where",
        "adonde" to "where",
        "dónde está" to "where",
        "donde esta" to "where",
        "cómo hago para" to "how do i",
        "como hago para" to "how do i",
        "cómo hago" to "how do i",
        "como hago" to "how do i",
        "cómo puedo" to "how can i",
        "como puedo" to "how can i",
        "cómo se puede" to "how can i",
        "como se puede" to "how can i",
        "cómo se" to "how do i",
        "como se" to "how do i",
        "cómo" to "how do i",
        "como" to "how do i",
        "no encuentro" to "can't find",
        "no puedo encontrar" to "can't find",
        "no lo encuentro" to "can't find",
        "muéstrame" to "show me",
        "muestrame" to "show me",
        "muéstreme" to "show me",
        "muestreme" to "show me",
        "enséñame" to "show me",
        "enseñame" to "show me",
        "ensename" to "show me",

        // Doing.
        "mostr*" to "show",
        "muestr*" to "show",
        "enseña" to "show",
        "ensena" to "show",
        "pon en pantalla" to "show",
        "poner en pantalla" to "show",
        "proyecta*" to "show",
        "despliega*" to "display",
        "pon" to "put",
        "ponga" to "put",
        "poner" to "put",
        "coloca*" to "put",
        "abre" to "open",
        "abra" to "open",
        "abrir" to "open",
        "ábreme" to "open",
        "ve a" to "go to",
        "ir a" to "go to",
        "vaya a" to "go to",
        "pasa a" to "go to",
        "llévame a" to "go to",
        "llevame a" to "go to",
        "cambia a" to "switch to",
        "cambiar a" to "switch to",
        "cambie a" to "switch to",
        "busca*" to "find",
        "encuentra" to "find",
        "encontrar" to "find",
        "leer" to "read",
        "lea" to "read",
        "haz" to "make",
        "hazme" to "make",
        "haga" to "make",
        "hacer" to "make",
        "crea" to "create",
        "crear" to "create",
        "cree" to "create",
        "agrega*" to "add",
        "agregue" to "add",
        "añad*" to "add",
        "anad*" to "add",
        "carga*" to "load",
        "cargue" to "load",
        "importa" to "import",
        "importar" to "import",
        "importe" to "import",
        "descarga*" to "download",
        "descargue" to "download",
        "instala*" to "install",
        "instale" to "install",
        "elige" to "choose",
        "elegir" to "choose",
        "elija" to "choose",
        "escog*" to "choose",
        "selecciona*" to "choose",
        "seleccione" to "choose",
        "configura" to "set up",
        "configurar" to "set up",
        "configure" to "set up",
        "conecta*" to "connect",
        "conecte" to "connect",
        "asigna*" to "assign",
        "asigne" to "assign",
        "oculta*" to "hide",
        "oculte" to "hide",
        "escond*" to "hide",
        "quita*" to "remove",
        "quite" to "remove",
        "detén" to "stop",
        "deten" to "stop",
        "detener" to "stop",
        "detenga" to "stop",
        "pausa*" to "pause",
        "elimina*" to "delete",
        "elimine" to "delete",
        "borra*" to "clear",
        "borre" to "clear",
        "limpia*" to "clear",
        "limpie" to "clear",
        "apaga la pantalla" to "black out",
        "oscurece la pantalla" to "black out",
        "pantalla en blanco" to "blank",
        "deshac*" to "undo",
        "deshaz" to "undo",
        "como estaba" to "undo",
        "presentar en vivo" to "go live",
        "en vivo" to "go live",
        "al aire" to "go live",
        "enciend*" to "turn on",
        "encender" to "turn on",
        "activa*" to "turn on",
        "apaga*" to "turn off",
        "apague" to "turn off",
        "desactiva*" to "turn off",
        "siguiente" to "next",
        "adelante" to "forward",
        "anterior" to "previous",
        "atrás" to "back",
        "atras" to "back",
        "regresa*" to "back",
        "vuelve" to "back",
        "aumenta*" to "increase",
        "aumente" to "increase",
        "más grande*" to "bigger",
        "mas grande*" to "bigger",
        "agranda*" to "enlarge",
        "agrande" to "enlarge",
        "disminu*" to "decrease",
        "más pequeñ*" to "smaller",
        "mas pequeñ*" to "smaller",
        "mas pequen*" to "smaller",
        "más chic*" to "smaller",
        "mas chic*" to "smaller",
        "achica*" to "shrink",
        "reduc*" to "reduce",
        "convierte*" to "convert",
        "convertir" to "convert",
        "convierta" to "convert",
        "convertidor*" to "converter",
        "transfier*" to "transfer",
        "transferir" to "transfer",
        "migra*" to "migrate",
        "edita*" to "edit",
        "edite" to "edit",
        "modifica*" to "modify",
        "modifique" to "modify",
        "cambia*" to "change",
        "cambie" to "change",
        "renombra*" to "rename",
        "renombre" to "rename",
        "arregla*" to "fix",
        "corrige*" to "fix",
        "corregir" to "fix",
        "organiza*" to "organize",
        "organice" to "organize",
        "ordena*" to "organize",
        "compara*" to "compare",
        "traducci*" to "translation",
        "traduc*" to "translate",
        "planifica*" to "plan",
        "planea" to "plan",
        "planear" to "plan",
        "automatiza*" to "automate",
        "automáticamente" to "automatically",
        "automaticamente" to "automatically",
        "identifica*" to "identify",
        "numera*" to "number the",

        // Too small, too big, not working.
        "muy pequeñ*" to "too small",
        "muy pequen*" to "too small",
        "demasiado pequeñ*" to "too small",
        "demasiado pequen*" to "too small",
        "muy chic*" to "too small",
        "no se ve" to "hard to read",
        "no se lee" to "hard to read",
        "difícil de leer" to "hard to read",
        "dificil de leer" to "hard to read",
        "no se puede leer" to "can't read",
        "no puedo leer" to "can't read",
        "muy grande" to "too big",
        "demasiado grande" to "too big",
        "no cabe" to "doesn't fit",
        "no funciona" to "not working",
        "no sirve" to "not working",
        "no muestra" to "not showing",
        "no se muestra" to "not showing",
        "no aparece" to "not showing",
        "no sale nada" to "nothing shows",
        "no hay nada" to "nothing shows",
        "no aparece nada" to "nothing shows",
        "pantalla negra" to "screen is black",
        "sin señal" to "no signal",
        "sin senal" to "no signal",
        "no hay señal" to "no signal",
        "no hay senal" to "no signal",
        "sin imagen" to "no picture",
        "no hay imagen" to "no picture",
        "qué pantalla" to "which screen",
        "que pantalla" to "which screen",
        "cuál pantalla" to "which screen",
        "cual pantalla" to "which screen",
        "qué monitor" to "which monitor",
        "que monitor" to "which monitor",
        "qué proyector" to "which projector",
        "que proyector" to "which projector",

        // What is on screen.
        "fondo*" to "background",
        "letra de la canción" to "lyrics",
        "letra de la cancion" to "lyrics",
        "letras de canciones" to "lyrics",
        "tamaño de letra" to "font size",
        "tamano de letra" to "font size",
        "tipo de letra" to "font",
        "letra*" to "lyrics",
        "canción" to "song",
        "cancion" to "song",
        "canciones" to "songs",
        "canto" to "song",
        "cantos" to "songs",
        "corito*" to "song",
        "himno*" to "hymn",
        "alabanza*" to "worship",
        "adoración" to "worship",
        "adoracion" to "worship",
        "biblia*" to "bible",
        "escritura*" to "scripture",
        "versículo*" to "verse",
        "versiculo*" to "verse",
        "capítulo*" to "chapter",
        "capitulo*" to "chapter",
        "fuente*" to "font",
        "tipografía" to "font",
        "tipografia" to "font",
        "tamaño*" to "size",
        "tamano*" to "size",
        "texto*" to "text",
        "palabras" to "words",
        "presentación de diapositivas" to "slideshow",
        "presentacion de diapositivas" to "slideshow",
        "pase de diapositivas" to "slideshow",
        "diapositiva*" to "slide",
        "foto*" to "photo",
        "imagen*" to "image",
        "imágenes" to "images",
        "álbum*" to "album",
        "presentación" to "presentation",
        "presentacion" to "presentation",
        "presentaciones" to "presentations",
        "vídeo*" to "video",
        "película*" to "movie",
        "pelicula*" to "movie",
        "multimedia" to "media",
        "medios" to "media",
        "tercio inferior" to "lower third",
        "rótulo*" to "lower third",
        "rotulo*" to "lower third",
        "cintillo*" to "lower third",
        "nombre y cargo" to "name and title",
        "anuncio*" to "announcement",
        "aviso*" to "notice",
        "texto en movimiento" to "ticker",
        "sala de niños" to "kids room",
        "sala de ninos" to "kids room",
        "guardería" to "nursery",
        "guarderia" to "nursery",
        "cuenta regresiva" to "countdown",
        "cuenta atrás" to "countdown",
        "cuenta atras" to "countdown",
        "temporizador*" to "timer",
        "cronómetro*" to "stopwatch",
        "cronometro*" to "stopwatch",
        "reloj*" to "clock",
        "hora actual" to "current time",
        "hora" to "time",
        "notas" to "notes",
        "acorde*" to "chord",
        "idioma*" to "language",
        "bilingüe*" to "bilingual",
        "bilingue*" to "bilingual",
        "en otro idioma" to "another language",
        "otro idioma" to "another language",
        "segundo idioma" to "second language",
        "en dos idiomas" to "two languages",
        "dos idiomas" to "two languages",

        // Screens and outputs.
        "pantalla principal" to "main screen",
        "pantalla completa" to "full screen",
        "segunda pantalla" to "second screen",
        "pantalla*" to "screen",
        "proyector*" to "projector",
        "monitor de escenario" to "stage monitor",
        "monitor del escenario" to "stage monitor",
        "pantalla de escenario" to "stage monitor",
        "pantalla del escenario" to "stage monitor",
        "monitor de retorno" to "confidence monitor",
        "monitores" to "monitors",
        "salida*" to "output",
        "ventana de salida" to "output window",
        "escenario*" to "stage",
        "zona*" to "zone",
        "diseño" to "layout",
        "diseno" to "layout",
        "disposición" to "layout",
        "disposicion" to "layout",
        "distribución" to "arrangement",
        "distribucion" to "arrangement",
        "mensaje*" to "message",
        "envía*" to "send",
        "envia*" to "send",
        "enviar" to "send",
        "envíe" to "send",
        "vista previa" to "preview",
        "previsualiza*" to "preview",
        "lo que está en pantalla" to "what is on screen",
        "lo que esta en pantalla" to "what is on screen",
        "qué hay en pantalla" to "what is on screen",
        "que hay en pantalla" to "what is on screen",
        "perfil*" to "profile",
        "transmisión" to "stream",
        "transmision" to "stream",
        "televisor*" to "tv",
        "televisión" to "tv",
        "television" to "tv",

        // Pages, tabs and tools.
        "configuraci*" to "settings",
        "ajustes" to "settings",
        "opciones" to "options",
        "preferencias" to "preferences",
        "asistente de configuración" to "setup wizard",
        "asistente de configuracion" to "setup wizard",
        "primeros pasos" to "getting started",
        "empezar de nuevo" to "start over",
        "comenzar de nuevo" to "start over",
        "atajo*" to "shortcut",
        "teclas rápidas" to "hotkeys",
        "teclas rapidas" to "hotkeys",
        "teclado*" to "keyboard",
        "pestaña*" to "tab",
        "pestana*" to "tab",
        "biblioteca de canciones" to "song library",
        "biblioteca de cantos" to "song library",
        "biblioteca*" to "library",
        "sitio web" to "website",
        "página web" to "website",
        "pagina web" to "website",
        "navegador*" to "browser",
        "diccionario*" to "dictionary",
        "cámara*" to "camera",
        "camara*" to "camera",
        "lienzo*" to "canvas",
        "servidor*" to "server",
        "control remoto" to "remote",
        "remoto*" to "remote",
        "teléfono*" to "phone",
        "telefono*" to "phone",
        "celular*" to "phone",
        "móvil" to "phone",
        "tableta*" to "tablet",
        "integraci*" to "integrations",

        // Services and planning.
        "orden del culto" to "order of service",
        "orden de culto" to "order of service",
        "orden del servicio" to "order of service",
        "orden de servicio" to "order of service",
        "programa del culto" to "order of service",
        "culto*" to "service",
        "servicio*" to "service",
        "reunión*" to "meeting",
        "reunion*" to "meeting",
        "domingo*" to "sunday",
        "calendario*" to "calendar",
        "programa*" to "schedule",
        "lista de reproducción" to "playlist",
        "lista de reproduccion" to "playlist",
        "cada domingo" to "every sunday",
        "todos los domingos" to "every sunday",
        "cada semana" to "every week",
        "todas las semanas" to "every week",
        "semanal*" to "weekly",
        "mensual*" to "monthly",
        "repet*" to "repeat",
        "repit*" to "repeat",
        "plantilla*" to "template",

        // Many, all, both.
        "todos" to "all",
        "todas" to "all",
        "todo" to "all",
        "ambos" to "both",
        "ambas" to "both",
        "los dos" to "both",
        "las dos" to "both",
        "varios" to "several",
        "varias" to "several",
        "muchos" to "many",
        "muchas" to "many",
        "a la vez" to "at once",
        "al mismo tiempo" to "at once",
        "para este culto" to "this service",
        "para este servicio" to "this service",
        "para hoy" to "for today",
        "temporalmente" to "temporarily",
        "por ahora" to "for now",

        // Languages, by name.
        "inglés" to "english",
        "ingles" to "english",
        "español*" to "spanish",
        "espanol*" to "spanish",
        "castellano" to "spanish",
        "ruso" to "russian",
        "rusa" to "russian",
        "ucraniano*" to "ukrainian",
        "alemán" to "german",
        "aleman*" to "german",
        "francés" to "french",
        "frances*" to "french",
        "polaco*" to "polish",
        "portugués" to "portuguese",
        "portugues*" to "portuguese",
        "italiano*" to "italian",
        "holandés" to "dutch",
        "holandes*" to "dutch",
        "neerlandés" to "dutch",
        "rumano*" to "romanian",
        "chino" to "chinese",
        "japonés" to "japanese",
        "japones*" to "japanese",
        "coreano*" to "korean",
        "árabe" to "arabic",
        "arabe" to "arabic",
        "hebreo" to "hebrew",
        "griego*" to "greek",
        "turco*" to "turkish",
        "tagalo" to "tagalog",
        "suajili" to "swahili",

        // Colors.
        "azul marino" to "navy",
        "azul claro" to "light blue",
        "celeste" to "light blue",
        "azul*" to "blue",
        "negr*" to "black",
        "blanc*" to "white",
        "gris*" to "grey",
        "plateado*" to "silver",
        "plata" to "silver",
        "rojo*" to "red",
        "roja*" to "red",
        "granate" to "maroon",
        "carmesí" to "crimson",
        "carmesi" to "crimson",
        "naranja*" to "orange",
        "anaranjad*" to "orange",
        "amarill*" to "yellow",
        "dorad*" to "gold",
        "oro" to "gold",
        "verde lima" to "lime",
        "verde azulado" to "teal",
        "verde*" to "green",
        "cian" to "cyan",
        "turquesa*" to "turquoise",
        "morad*" to "purple",
        "púrpura" to "purple",
        "purpura" to "purple",
        "violeta*" to "violet",
        "lavanda" to "lavender",
        "rosa" to "pink",
        "rosas" to "pink",
        "rosad*" to "pink",
        "marrón" to "brown",
        "marron" to "brown",
        "crema" to "cream",
        "oscur*" to "dark",
        "claro" to "light",
        "clara" to "light",
        "claros" to "light",
        "claras" to "light",

        // Talking to the helper.
        "hola" to "hello",
        "buenos días" to "hello",
        "buenos dias" to "hello",
        "buenas tardes" to "hello",
        "buenas noches" to "hello",
        "buenas" to "hello",
        "ayuda*" to "help",
        "ayúdame" to "help",
        "ayúdeme" to "help",
        "qué puedes hacer" to "what can you do",
        "que puedes hacer" to "what can you do",
        "qué sabes hacer" to "what can you do",
        "que sabes hacer" to "what can you do",
        "qué haces" to "what do you do",
        "que haces" to "what do you do",
        "quién eres" to "who are you",
        "quien eres" to "who are you",
        "gracias" to "thanks",
        "muchas gracias" to "thank you",
        "por favor" to "please",
        "wik" to "wick",

        // Newer requests.
        "buscar" to "search",
        "busco" to "search",
        "busque" to "search",
        "buscando" to "search",
        "busca* en" to "search in",
        "busca* un" to "search a",
        "busca* una" to "search a",
        "búsqueda*" to "search",
        "busqueda*" to "search",
        "consultar" to "look up",
        "un canto" to "a song",
        "una canción" to "a song",
        "una cancion" to "a song",
        "el canto" to "the song",
        "la canción" to "the song",
        "la cancion" to "the song",
        "un versículo" to "a verse",
        "un versiculo" to "a verse",
        "el versículo" to "the verse",
        "el versiculo" to "the verse",
        "versículos" to "verses",
        "versiculos" to "verses",
        "número de canto" to "song number",
        "numero de canto" to "song number",
        "número de canción" to "song number",
        "numero de cancion" to "song number",
        "por número" to "by number",
        "por numero" to "by number",
        "por título" to "by title",
        "por titulo" to "by title",
        "número" to "number",
        "numero" to "number",
        "llamado" to "called",
        "llamada" to "called",
        "titulado" to "named",
        "titulada" to "named",
        "preferid*" to "favorite",
        "con estrella" to "starred",
        "este canto" to "this song",
        "esta canción" to "this song",
        "esta cancion" to "this song",
        "cada canto" to "each song",
        "cada canción" to "each song",
        "cada cancion" to "each song",
        "por canto" to "per song",
        "su propio fondo" to "its own background",
        "su fondo propio" to "its own background",
        "propio fondo" to "own background",
        "fondo propio" to "own background",
        "su propio" to "its own",
        "su propia" to "its own",
        "más de un versículo" to "more than one verse",
        "mas de un versiculo" to "more than one verse",
        "rango de versículos" to "range of verses",
        "rango de versiculos" to "range of verses",
        "un pasaje" to "a passage",
        "pasaje completo" to "whole passage",
        "pasaje*" to "passage",
        "historial*" to "history",
        "acabamos de mostrar" to "what did we just show",
        "acabamos de proyectar" to "what did we just show",
        "versículos recientes" to "recent verses",
        "versiculos recientes" to "recent verses",
        "referencias cruzadas" to "cross references",
        "referencia cruzada" to "cross reference",
        "versículos relacionados" to "related verses",
        "versiculos relacionados" to "related verses",
        "pasajes relacionados" to "related passages",
        "pasajes paralelos" to "parallel passages",
        "textos paralelos" to "parallel passages",
        "versículos similares" to "similar verses",
        "versiculos similares" to "similar verses",
        "página de internet" to "internet page",
        "pagina de internet" to "internet page",
        "estadística*" to "statistics",
        "estadistica*" to "statistics",
        "cuántas veces" to "how many times",
        "cuantas veces" to "how many times",
        "con qué frecuencia" to "how often",
        "con que frecuencia" to "how often",
        "informe de cantos" to "song report",
        "informe de canciones" to "song report",
        "reporte de cantos" to "song report",
        "reporte de canciones" to "song report",
        "uso de cantos" to "song usage",
        "uso de canciones" to "song usage",
        "desde mi teléfono" to "from my phone",
        "desde mi telefono" to "from my phone",
        "desde mi celular" to "from my phone",
        "desde mi móvil" to "from my phone",
        "desde mi movil" to "from my phone",
        "desde el teléfono" to "from the phone",
        "desde el telefono" to "from the phone",
        "desde el celular" to "from the phone",
        "en mi teléfono" to "on my phone",
        "en mi telefono" to "on my phone",
        "en mi celular" to "on my phone",
        "conecta* mi teléfono" to "connect my phone",
        "conecta* mi telefono" to "connect my phone",
        "conecta* mi celular" to "connect my phone",
        "mando a distancia" to "remote control",
        "código qr" to "qr code",
        "codigo qr" to "qr code",
        "controla* desde" to "control it from",
        "minuto*" to "minutes",
        "anuncia" to "announce",
        "anuncie" to "announce",
        "anunciar" to "announce",
        "anuncio:" to "announce",
        "anuncia:" to "announce",
        "anuncie:" to "announce",
        "anunciar:" to "announce",
        "al programa" to "to the schedule",
        "en el programa" to "in the schedule",
        "del programa" to "from the schedule",
        "ir al" to "go to the",
        "ve al" to "go to the",
        "vaya al" to "go to the",
        "pasa al" to "go to the",
        "elemento*" to "item",
        "ítem*" to "item",
        "qué está en vivo" to "what's live",
        "que esta en vivo" to "what's live",
        "qué hay en vivo" to "what's live",
        "que hay en vivo" to "what's live",
        "qué está al aire" to "what's live",
        "que esta al aire" to "what's live",
        "qué está en pantalla" to "what is on screen",
        "que esta en pantalla" to "what is on screen",
        "qué se está mostrando" to "what's showing",
        "que se esta mostrando" to "what's showing",
        "qué se muestra" to "what's showing",
        "que se muestra" to "what's showing",
        "hay algo en vivo" to "is anything live",
        "qué versión" to "what version",
        "que version" to "what version",
        "cuál versión" to "which version",
        "cual version" to "which version",
        "cuál es la versión" to "what version",
        "cual es la version" to "what version",
        "versión de la aplicación" to "app version",
        "version de la aplicacion" to "app version",
        "buscar actualizaciones" to "check for updates",
        "comprobar actualizaciones" to "check for updates",
        "hay actualizaciones" to "any updates",
        "hay una actualización" to "is there an update",
        "hay una actualizacion" to "is there an update",
        "última versión" to "latest version",
        "ultima version" to "latest version",
        "nueva versión" to "newer version",
        "nueva version" to "newer version",
        "está actualizado" to "up to date",
        "esta actualizado" to "up to date",
        "actualizar la aplicación" to "update the app",
        "actualizar la aplicacion" to "update the app",
        "comandos" to "commands",
        "lista de comandos" to "list of commands",
        "qué puedo decir" to "what can i say",
        "que puedo decir" to "what can i say",
        "qué puedo escribir" to "what can i type",
        "que puedo escribir" to "what can i type",
        "qué puedo preguntar" to "what can i ask",
        "que puedo preguntar" to "what can i ask",
        "qué entiendes" to "what do you understand",
        "que entiendes" to "what do you understand",

        // Look requests.
        "cambio" to "change",
        "cambiar la letra" to "change the lyrics",
        "edito" to "edit",
        "corrijo" to "fix",
        "pongo" to "put",
        "agrego" to "add",
        "agrando" to "enlarge",
        "la letra*" to "the lyrics",
        "las letras" to "the lyrics",
        "error de tipeo" to "typo",
        "errata*" to "typo",
        "muev*" to "move",
        "mover" to "move",
        "negrita*" to "bold",
        "cursiva*" to "italic",
        "itálica*" to "italic",
        "italica*" to "italic",
        "subraya*" to "underline",
        "contorno*" to "outline",
        "sombra*" to "shadow",
        "margen" to "margin",
        "márgenes" to "margins",
        "margenes" to "margins",
        "bordes" to "edges",
        "arriba" to "top",
        "abajo" to "bottom",
        "parte superior" to "top",
        "parte inferior" to "bottom",
        "en medio" to "middle",
        "centro" to "center",
        "centrad*" to "centered",
        "izquierda" to "left",
        "derecha" to "right",
        "alinea*" to "align",
        "posición" to "position",
        "posicion" to "position",
        "aspecto" to "look",
        "apariencia" to "appearance",
        "estilo*" to "style",
        "formato*" to "format",
        "título" to "title",
        "títulos" to "titles",
        "titulo" to "title",
        "titulos" to "titles",
        "título del canto" to "song title",
        "titulo del canto" to "song title",
        "título de la canción" to "song title",
        "titulo de la cancion" to "song title",
        "referencia" to "reference",
        "referencias" to "references",
        "bíblic*" to "bible",
        "biblic*" to "bible",
        "marcador de fin" to "end marker",
        "fin de canto" to "end of song",
        "fin del canto" to "end of song",
        "fin de la canción" to "end of song",
        "fin de la cancion" to "end of song",
        "final del canto" to "end of song",
        "final de la canción" to "end of song",
        "final de la cancion" to "end of song",

        // The help table's own examples.
        "rótulo inferior" to "lower third",
        "rotulo inferior" to "lower third",
        "cómo hago un" to "how do i make a",
        "como hago un" to "how do i make a",
        "cómo hago una" to "how do i make a",
        "como hago una" to "how do i make a",
        "configuro" to "set up",
        "por lotes" to "batch",
        "por lote" to "batch",
        "padres" to "parents",
    ),
)
