package org.churchpresenter.helper.intent.glossary

internal val SWAHILI = Glossary(
    "sw",
    listOf(
        // Asking where, or how.
        "wapi" to "where",
        "iko wapi" to "where",
        "ziko wapi" to "where",
        "nitapata wapi" to "where",
        "nitafanyaje" to "how do i",
        "ninafanyaje" to "how do i",
        "nifanyeje" to "how do i",
        "jinsi ya" to "how to",
        "jinsi gani" to "how do i",
        "vipi" to "how do i",
        "ninawezaje" to "how can i",
        "naweza kufanyaje" to "how can i",
        "nawezaje" to "how can i",
        "siwezi kupata" to "can't find",
        "sipati" to "can't find",
        "sioni" to "can't find",
        "nimeshindwa kupata" to "can't find",
        "nionyeshe" to "show me",
        "unionyeshe" to "show me",

        // Doing.
        "onyesha moja kwa moja" to "go live",
        "onyesha live" to "go live",
        "onyesha*" to "show",
        "kuonyesha" to "show",
        "ionyeshe" to "show",
        "weka" to "put",
        "kuweka" to "put",
        "fungua" to "open",
        "kufungua" to "open",
        "ifungue" to "open",
        "nenda kwenye" to "go to",
        "nenda kwa" to "go to",
        "nenda" to "go to",
        "elekea" to "go to",
        "hamia" to "switch to",
        "hamia kwenye" to "switch to",
        "badilisha kwenda" to "switch to",
        "tafuta*" to "find",
        "kutafuta" to "find",
        "soma" to "read",
        "kusoma" to "read",
        "fanya" to "make",
        "kufanya" to "make",
        "tengeneza*" to "create",
        "kutengeneza" to "create",
        "unda" to "create",
        "kuunda" to "create",
        "ongeza ukubwa" to "increase",
        "ongeza*" to "add",
        "kuongeza" to "add",
        "pakia*" to "load",
        "kupakia" to "load",
        "ingiza" to "import",
        "kuingiza" to "import",
        "leta" to "import",
        "pakua*" to "download",
        "kupakua" to "download",
        "sakinisha" to "install",
        "kusakinisha" to "install",
        "chagua*" to "choose",
        "kuchagua" to "choose",
        "sanidi" to "set up",
        "kusanidi" to "set up",
        "andaa" to "set up",
        "unganisha" to "connect",
        "kuunganisha" to "connect",
        "kabidhi" to "assign",
        "ficha*" to "hide",
        "kuficha" to "hide",
        "ondoa*" to "remove",
        "kuondoa" to "remove",
        "simamisha*" to "stop",
        "acha" to "stop",
        "sitisha" to "pause",
        "futa*" to "clear",
        "kufuta" to "clear",
        "zima skrini" to "black out",
        "skrini tupu" to "blank",
        "tendua" to "undo",
        "rudisha kama ilivyokuwa" to "undo",
        "rudisha" to "undo",
        "moja kwa moja" to "go live",
        "washa" to "turn on",
        "washe" to "turn on",
        "kuwasha" to "turn on",
        "zima*" to "turn off",
        "kuzima" to "turn off",
        "inayofuata" to "next",
        "ifuatayo" to "next",
        "unaofuata" to "next",
        "ufuatao" to "next",
        "mbele" to "forward",
        "iliyopita" to "previous",
        "uliopita" to "previous",
        "nyuma" to "back",
        "rudi nyuma" to "go back",
        "rudi" to "back",
        "kuza" to "enlarge",
        "ikuze" to "enlarge",
        "kukuza" to "enlarge",
        "kubwa zaidi" to "bigger",
        "punguza ukubwa" to "decrease",
        "punguza*" to "decrease",
        "ndogo zaidi" to "smaller",
        "kigeuzi" to "converter",
        "geuza" to "convert",
        "kugeuza" to "convert",
        "hamisha" to "transfer",
        "kuhamisha" to "transfer",
        "hariri*" to "edit",
        "kuhariri" to "edit",
        "badilisha jina" to "rename",
        "badili jina" to "rename",
        "badilisha*" to "change",
        "kubadilisha" to "change",
        "badili" to "change",
        "rekebisha" to "fix",
        "kurekebisha" to "fix",
        "panga*" to "organize",
        "kupanga" to "organize",
        "linganisha" to "compare",
        "kulinganisha" to "compare",
        "tafsiri" to "translate",
        "kutafsiri" to "translate",
        "tafsiri ya" to "translation",
        "panga ratiba" to "plan",
        "kiotomatiki" to "automatically",
        "kwa kiotomatiki" to "automatically",
        "tambua" to "identify",
        "kutambua" to "identify",
        "weka namba" to "number the",

        // Too small, too big, not working.
        "ndogo sana" to "too small",
        "ndogo mno" to "too small",
        "haisomeki" to "hard to read",
        "vigumu kusoma" to "hard to read",
        "si rahisi kusoma" to "hard to read",
        "siwezi kusoma" to "can't read",
        "kubwa sana" to "too big",
        "kubwa mno" to "too big",
        "haitoshei" to "doesn't fit",
        "haienei" to "doesn't fit",
        "haifanyi kazi" to "not working",
        "haifanyi" to "not working",
        "haionyeshi" to "not showing",
        "haionekani" to "not showing",
        "hakuna kinachoonekana" to "nothing shows",
        "hakuna kitu" to "nothing shows",
        "skrini nyeusi" to "screen is black",
        "hakuna ishara" to "no signal",
        "hakuna mawimbi" to "no signal",
        "hakuna picha" to "no picture",
        "skrini ipi" to "which screen",
        "skrini gani" to "which screen",
        "kifuatiliaji kipi" to "which monitor",
        "kifuatiliaji gani" to "which monitor",
        "projekta ipi" to "which projector",
        "projekta gani" to "which projector",

        // What is on screen.
        "usuli" to "background",
        "mandharinyuma" to "background",
        "mandhari ya nyuma" to "background",
        "maneno ya wimbo" to "lyrics",
        "maneno ya nyimbo" to "lyrics",
        "wimbo ulio bora" to "wimbo ulio bora",
        "wimbo" to "song",
        "nyimbo" to "songs",
        "tenzi" to "hymn",
        "utenzi" to "hymn",
        "tenzi za rohoni" to "hymn",
        "kusifu" to "worship",
        "kuabudu" to "worship",
        "sifa na kuabudu" to "worship",
        "biblia" to "bible",
        "maandiko" to "scripture",
        "neno la mungu" to "scripture",
        "mstari" to "verse",
        "mistari" to "verses",
        "sura" to "chapter",
        "ukubwa wa fonti" to "font size",
        "ukubwa wa herufi" to "font size",
        "ukubwa wa maandishi" to "text size",
        "fonti" to "font",
        "ukubwa" to "size",
        "maandishi" to "text",
        "herufi" to "letters",
        "maneno" to "words",
        "onyesho la slaidi" to "slideshow",
        "slaidi" to "slide",
        "picha" to "picture",
        "albamu" to "album",
        "wasilisho" to "presentation",
        "mawasilisho" to "presentation",
        "filamu" to "movie",
        "sauti" to "audio",
        "jina na cheo" to "name and title",
        "jina na wadhifa" to "name and title",
        "tangazo" to "announcement",
        "matangazo" to "announcements",
        "tangaza" to "announce",
        "maandishi yanayosonga" to "ticker",
        "maandishi yanayotembea" to "ticker",
        "chumba cha watoto" to "kids room",
        "kuhesabu kurudi nyuma" to "countdown",
        "hesabu ya kurudi nyuma" to "countdown",
        "kuhesabu kushuka" to "countdown",
        "kipima muda" to "timer",
        "kipima wakati" to "timer",
        "saa ya kusimamisha" to "stopwatch",
        "saa ya sasa" to "current time",
        "muda wa sasa" to "current time",
        "saa" to "clock",
        "muda" to "time",
        "wakati" to "time",
        "maelezo" to "notes",
        "kodi za gitaa" to "chords",
        "lugha nyingine" to "another language",
        "lugha ya pili" to "second language",
        "lugha mbili" to "two languages",
        "lugha*" to "language",

        // Screens and outputs.
        "skrini kuu" to "main screen",
        "skrini nzima" to "full screen",
        "skrini kamili" to "full screen",
        "skrini ya pili" to "second screen",
        "skrini*" to "screen",
        "projekta" to "projector",
        "kifuatiliaji cha jukwaa" to "stage monitor",
        "kifuatiliaji cha jukwaani" to "stage monitor",
        "skrini ya jukwaa" to "stage monitor",
        "skrini ya jukwaani" to "stage monitor",
        "kifuatiliaji" to "monitor",
        "vifuatiliaji" to "monitors",
        "towe" to "output",
        "dirisha la towe" to "output window",
        "jukwaa*" to "stage",
        "eneo" to "zone",
        "maeneo" to "zones",
        "mpangilio" to "layout",
        "ujumbe" to "message",
        "tuma*" to "send",
        "kutuma" to "send",
        "hakiki*" to "preview",
        "onyesho la awali" to "preview",
        "kilicho kwenye skrini" to "what is on screen",
        "nini kiko kwenye skrini" to "what is on screen",
        "wasifu" to "profile",
        "mtiririko" to "stream",
        "runinga" to "tv",
        "televisheni" to "tv",

        // Pages, tabs and tools.
        "mipangilio" to "settings",
        "chaguo" to "options",
        "machaguo" to "options",
        "mapendeleo" to "preferences",
        "mchawi wa kusanidi" to "setup wizard",
        "kuanza kutumia" to "getting started",
        "anza upya" to "start over",
        "anza tena" to "start over",
        "njia ya mkato" to "shortcut",
        "njia za mkato" to "shortcut",
        "kibodi" to "keyboard",
        "kichupo" to "tab",
        "vichupo" to "tab",
        "maktaba ya nyimbo" to "song library",
        "maktaba" to "library",
        "tovuti" to "website",
        "wavuti" to "web",
        "kivinjari" to "browser",
        "kamusi" to "dictionary",
        "kamera" to "camera",
        "seva" to "server",
        "kwa mbali" to "remote",
        "rimoti" to "remote",
        "simu" to "phone",
        "kompyuta kibao" to "tablet",
        "muunganisho" to "integrations",
        "miunganisho" to "integrations",

        // Services and planning.
        "ratiba ya ibada" to "order of service",
        "mpangilio wa ibada" to "order of service",
        "utaratibu wa ibada" to "order of service",
        "ratiba" to "schedule",
        "ibada" to "service",
        "mkutano" to "meeting",
        "mikutano" to "meetings",
        "jumapili" to "sunday",
        "kalenda" to "calendar",
        "orodha ya kucheza" to "playlist",
        "kila jumapili" to "every sunday",
        "kila wiki" to "every week",
        "kila juma" to "every week",
        "kila mwezi" to "monthly",
        "kwa wiki" to "weekly",
        "rudia" to "repeat",
        "kurudia" to "repeat",
        "kiolezo" to "template",
        "violezo" to "template",

        // Many, all, both.
        "zote mbili" to "both",
        "vyote viwili" to "both",
        "yote mawili" to "both",
        "wote wawili" to "both",
        "zote" to "all",
        "yote" to "all",
        "wote" to "all",
        "vyote" to "all",
        "kila kitu" to "everything",
        "kadhaa" to "several",
        "nyingi" to "many",
        "kwa pamoja" to "at once",
        "kwa wakati mmoja" to "at once",
        "kwa ibada hii" to "this service",
        "kwa leo" to "for today",
        "kwa muda" to "temporarily",
        "kwa sasa" to "for now",

        // Languages, by name.
        "kiingereza" to "english",
        "kihispania" to "spanish",
        "kirusi" to "russian",
        "kiukreni" to "ukrainian",
        "kijerumani" to "german",
        "kifaransa" to "french",
        "kipolandi" to "polish",
        "kireno" to "portuguese",
        "kiitaliano" to "italian",
        "kiholanzi" to "dutch",
        "kiromania" to "romanian",
        "kigiriki" to "greek",
        "kituruki" to "turkish",
        "kiarabu" to "arabic",
        "kiajemi" to "persian",
        "kiebrania" to "hebrew",
        "kihindi" to "hindi",
        "kichina" to "chinese",
        "kijapani" to "japanese",
        "kikorea" to "korean",
        "kiindonesia" to "indonesian",
        "kimalei" to "malay",
        "kiswahili" to "swahili",
        "kiamhari" to "amharic",
        "kilatini" to "latin",

        // Colors.
        "buluu iliyokolea" to "navy",
        "samawati" to "light blue",
        "buluu" to "blue",
        "bluu" to "blue",
        "nyeusi" to "black",
        "mweusi" to "black",
        "cheusi" to "black",
        "nyeupe" to "white",
        "mweupe" to "white",
        "cheupe" to "white",
        "kijivu" to "grey",
        "fedha" to "silver",
        "nyekundu" to "red",
        "mwekundu" to "red",
        "chekundu" to "red",
        "rangi ya chungwa" to "orange",
        "machungwa" to "orange",
        "njano" to "yellow",
        "manjano" to "yellow",
        "dhahabu" to "gold",
        "kijani kibichi" to "green",
        "kijani" to "green",
        "zambarau" to "purple",
        "urujuani" to "violet",
        "waridi" to "pink",
        "pinki" to "pink",
        "kahawia" to "brown",
        "hudhurungi" to "brown",
        "krimu" to "cream",
        "iliyokolea" to "dark",
        "giza" to "dark",
        "angavu" to "light",
        "nyepesi" to "light",

        // Talking to the helper.
        "habari" to "hello",
        "habari yako" to "hello",
        "hujambo" to "hello",
        "jambo" to "hello",
        "mambo" to "hello",
        "salamu" to "hello",
        "shikamoo" to "hello",
        "msaada" to "help",
        "nisaidie" to "help",
        "saidia" to "help",
        "unaweza kufanya nini" to "what can you do",
        "unajua kufanya nini" to "what can you do",
        "unafanya nini" to "what do you do",
        "wewe ni nani" to "who are you",
        "u nani" to "who are you",
        "asante" to "thanks",
        "ahsante" to "thanks",
        "asanteni" to "thanks",
        "asante sana" to "thank you",
        "tafadhali" to "please",
        "wik" to "wick",

        // Newer requests.
        "tafuta kwenye" to "search in",
        "tafuta katika" to "search in",
        "tafuta wimbo" to "search song",
        "ninatafutaje" to "how do i search",
        "utafutaji" to "search",
        "ninaonyeshaje" to "how do i show",
        "namba ya wimbo" to "song number",
        "kwa namba" to "by number",
        "kwa kichwa" to "by title",
        "namba" to "number",
        "unaoitwa" to "called",
        "kinachoitwa" to "called",
        "kipendwa" to "favorite",
        "vipendwa" to "favorites",
        "unaopendwa" to "favorite",
        "wimbo huu" to "this song",
        "kila wimbo" to "each song",
        "usuli wake mwenyewe" to "its own background",
        "usuli wake" to "its own background",
        "wake mwenyewe" to "its own",
        "mistari kadhaa" to "several verses",
        "mistari mingi" to "multiple verses",
        "zaidi ya mstari mmoja" to "more than one verse",
        "kifungu kizima" to "whole passage",
        "kifungu" to "passage",
        "historia" to "history",
        "tumeonyesha nini" to "what did we just show",
        "mistari ya hivi karibuni" to "recent verses",
        "marejeo mtambuka" to "cross references",
        "mistari inayohusiana" to "related verses",
        "vifungu vinavyohusiana" to "related passages",
        "vifungu sambamba" to "parallel passages",
        "mistari inayofanana" to "similar verses",
        "ukurasa wa wavuti" to "web page",
        "ukurasa wa mtandao" to "internet page",
        "takwimu" to "statistics",
        "mara ngapi" to "how many times",
        "ripoti ya nyimbo" to "song report",
        "matumizi ya nyimbo" to "song usage",
        "kutoka kwenye simu yangu" to "from my phone",
        "kutoka simu yangu" to "from my phone",
        "kwenye simu yangu" to "on my phone",
        "unganisha simu yangu" to "connect my phone",
        "udhibiti wa mbali" to "remote control",
        "msimbo wa qr" to "qr code",
        "idhibiti kutoka" to "control it from",
        "dhibiti kutoka" to "control it from",
        "dakika*" to "minutes",
        "hesabu ya dakika 1" to "countdown 1 minutes",
        "hesabu ya dakika 2" to "countdown 2 minutes",
        "hesabu ya dakika 3" to "countdown 3 minutes",
        "hesabu ya dakika 4" to "countdown 4 minutes",
        "hesabu ya dakika 5" to "countdown 5 minutes",
        "hesabu ya dakika 6" to "countdown 6 minutes",
        "hesabu ya dakika 7" to "countdown 7 minutes",
        "hesabu ya dakika 8" to "countdown 8 minutes",
        "hesabu ya dakika 9" to "countdown 9 minutes",
        "hesabu ya dakika 10" to "countdown 10 minutes",
        "hesabu ya dakika 12" to "countdown 12 minutes",
        "hesabu ya dakika 15" to "countdown 15 minutes",
        "hesabu ya dakika 20" to "countdown 20 minutes",
        "hesabu ya dakika 25" to "countdown 25 minutes",
        "hesabu ya dakika 30" to "countdown 30 minutes",
        "hesabu ya dakika 40" to "countdown 40 minutes",
        "hesabu ya dakika 45" to "countdown 45 minutes",
        "hesabu ya dakika 60" to "countdown 60 minutes",
        "hesabu ya dakika 90" to "countdown 90 minutes",
        "dakika 1" to "1 minutes",
        "dakika 2" to "2 minutes",
        "dakika 3" to "3 minutes",
        "dakika 4" to "4 minutes",
        "dakika 5" to "5 minutes",
        "dakika 6" to "6 minutes",
        "dakika 7" to "7 minutes",
        "dakika 8" to "8 minutes",
        "dakika 9" to "9 minutes",
        "dakika 10" to "10 minutes",
        "dakika 12" to "12 minutes",
        "dakika 15" to "15 minutes",
        "dakika 20" to "20 minutes",
        "dakika 25" to "25 minutes",
        "dakika 30" to "30 minutes",
        "dakika 40" to "40 minutes",
        "dakika 45" to "45 minutes",
        "dakika 60" to "60 minutes",
        "dakika 90" to "90 minutes",
        "tangaza:" to "announce",
        "kwenye ratiba" to "in the schedule",
        "katika ratiba" to "in the schedule",
        "kutoka kwenye ratiba" to "from the schedule",
        "kipengele" to "item",
        "vipengele" to "items",
        "kinachofuata" to "next",
        "kilichopita" to "previous",
        "nini kiko live" to "what's live",
        "nini kiko hewani" to "what's live",
        "nini kinaonyeshwa" to "what's showing",
        "toleo gani" to "what version",
        "toleo la programu" to "app version",
        "angalia masasisho" to "check for updates",
        "kuna sasisho" to "is there an update",
        "toleo jipya zaidi" to "latest version",
        "toleo la karibuni" to "latest version",
        "imesasishwa" to "up to date",
        "amri" to "commands",
        "orodha ya amri" to "list of commands",
        "naweza kusema nini" to "what can i say",
        "naweza kuandika nini" to "what can i type",
        "unaelewa nini" to "what do you understand",

        // Look requests.
        "ninabadilishaje" to "how do i change",
        "nitabadilishaje" to "how do i change",
        "ninaongezaje" to "how do i add",
        "ninahamishaje" to "how do i move",
        "ninasogezaje" to "how do i move",
        "ninakuzaje" to "how do i enlarge",
        "ninawekaje" to "how do i set up",
        "ninaharirije" to "how do i edit",
        "sogeza" to "move",
        "badilisha maneno" to "change the words",
        "hariri maneno" to "edit the words",
        "rekebisha maneno" to "fix the lyrics",
        "kosa kwenye maneno" to "mistake in the lyrics",
        "kosa la tahajia" to "typo",
        "alama ya mwisho wa wimbo" to "end of song marker",
        "alama ya mwisho" to "end marker",
        "mwisho wa wimbo" to "end of song",
        "kichwa cha wimbo" to "song title",
        "kichwa" to "title",
        "rejeleo" to "reference",
        "marejeleo" to "references",
        "nene" to "bold",
        "herufi nzito" to "bold",
        "italiki" to "italic",
        "pigia mstari" to "underline",
        "mstari wa nje" to "outline",
        "kivuli" to "shadow",
        "vivuli" to "shadows",
        "pambizo" to "margins",
        "ukingo" to "edge",
        "kingo" to "edges",
        "kwenda juu" to "to the top",
        "juu kabisa" to "top",
        "kwenda chini" to "to the bottom",
        "chini kabisa" to "bottom",
        "katikati" to "middle",
        "kushoto" to "left",
        "kulia" to "right",
        "pangilia" to "align",
        "mwonekano" to "look",
        "mtindo" to "style",
        "rangi" to "color",

        // The help table's own examples.
        "ninaongeza" to "add",
        "kodi" to "chords",
        "safisha" to "clear",
        "weka projekta" to "set up the projector",
        "kioo cha jukwaani" to "stage monitor",
        "onyesho" to "display",
        "mfululizo wa picha" to "slideshow",
        "ninatengenezaje" to "how do i make",
        "kwa wingi" to "batch",
        "wazazi" to "parents",
    ),
)
