package org.churchpresenter.helper.intent.glossary

internal val SWAHILI = Glossary(
    "sw",
    listOf(
        // Asking where, or how.
        "wapi" to "where",
        "iko wapi" to "where",
        "ziko wapi" to "where",
        "nitapata wapi" to "where",
        "nitafanyaje" to "how do i",
        "ninafanyaje" to "how do i",
        "nifanyeje" to "how do i",
        "jinsi ya" to "how to",
        "jinsi gani" to "how do i",
        "vipi" to "how do i",
        "ninawezaje" to "how can i",
        "naweza kufanyaje" to "how can i",
        "nawezaje" to "how can i",
        "siwezi kupata" to "can't find",
        "sipati" to "can't find",
        "sioni" to "can't find",
        "nimeshindwa kupata" to "can't find",
        "nionyeshe" to "show me",
        "unionyeshe" to "show me",

        // Doing.
        "onyesha moja kwa moja" to "go live",
        "onyesha live" to "go live",
        "onyesha*" to "show",
        "kuonyesha" to "show",
        "ionyeshe" to "show",
        "weka" to "put",
        "kuweka" to "put",
        "fungua" to "open",
        "kufungua" to "open",
        "ifungue" to "open",
        "nenda kwenye" to "go to",
        "nenda kwa" to "go to",
        "nenda" to "go to",
        "elekea" to "go to",
        "hamia" to "switch to",
        "hamia kwenye" to "switch to",
        "badilisha kwenda" to "switch to",
        "tafuta*" to "find",
        "kutafuta" to "find",
        "soma" to "read",
        "kusoma" to "read",
        "fanya" to "make",
        "kufanya" to "make",
        "tengeneza*" to "create",
        "kutengeneza" to "create",
        "unda" to "create",
        "kuunda" to "create",
        "ongeza ukubwa" to "increase",
        "ongeza*" to "add",
        "kuongeza" to "add",
        "pakia*" to "load",
        "kupakia" to "load",
        "ingiza" to "import",
        "kuingiza" to "import",
        "leta" to "import",
        "pakua*" to "download",
        "kupakua" to "download",
        "sakinisha" to "install",
        "kusakinisha" to "install",
        "chagua*" to "choose",
        "kuchagua" to "choose",
        "sanidi" to "set up",
        "kusanidi" to "set up",
        "andaa" to "set up",
        "unganisha" to "connect",
        "kuunganisha" to "connect",
        "kabidhi" to "assign",
        "ficha*" to "hide",
        "kuficha" to "hide",
        "ondoa*" to "remove",
        "kuondoa" to "remove",
        "simamisha*" to "stop",
        "acha" to "stop",
        "sitisha" to "pause",
        "futa*" to "clear",
        "kufuta" to "clear",
        "zima skrini" to "black out",
        "skrini tupu" to "blank",
        "tendua" to "undo",
        "rudisha kama ilivyokuwa" to "undo",
        "rudisha" to "undo",
        "moja kwa moja" to "go live",
        "washa" to "turn on",
        "washe" to "turn on",
        "kuwasha" to "turn on",
        "zima*" to "turn off",
        "kuzima" to "turn off",
        "inayofuata" to "next",
        "ifuatayo" to "next",
        "unaofuata" to "next",
        "ufuatao" to "next",
        "mbele" to "forward",
        "iliyopita" to "previous",
        "uliopita" to "previous",
        "nyuma" to "back",
        "rudi nyuma" to "go back",
        "rudi" to "back",
        "kuza" to "enlarge",
        "ikuze" to "enlarge",
        "kukuza" to "enlarge",
        "kubwa zaidi" to "bigger",
        "punguza ukubwa" to "decrease",
        "punguza*" to "decrease",
        "ndogo zaidi" to "smaller",
        "kigeuzi" to "converter",
        "geuza" to "convert",
        "kugeuza" to "convert",
        "hamisha" to "transfer",
        "kuhamisha" to "transfer",
        "hariri*" to "edit",
        "kuhariri" to "edit",
        "badilisha jina" to "rename",
        "badili jina" to "rename",
        "badilisha*" to "change",
        "kubadilisha" to "change",
        "badili" to "change",
        "rekebisha" to "fix",
        "kurekebisha" to "fix",
        "panga*" to "organize",
        "kupanga" to "organize",
        "linganisha" to "compare",
        "kulinganisha" to "compare",
        "tafsiri" to "translate",
        "kutafsiri" to "translate",
        "tafsiri ya" to "translation",
        "panga ratiba" to "plan",
        "kiotomatiki" to "automatically",
        "kwa kiotomatiki" to "automatically",
        "tambua" to "identify",
        "kutambua" to "identify",
        "weka namba" to "number the",

        // Too small, too big, not working.
        "ndogo sana" to "too small",
        "ndogo mno" to "too small",
        "haisomeki" to "hard to read",
        "vigumu kusoma" to "hard to read",
        "si rahisi kusoma" to "hard to read",
        "siwezi kusoma" to "can't read",
        "kubwa sana" to "too big",
        "kubwa mno" to "too big",
        "haitoshei" to "doesn't fit",
        "haienei" to "doesn't fit",
        "haifanyi kazi" to "not working",
        "haifanyi" to "not working",
        "haionyeshi" to "not showing",
        "haionekani" to "not showing",
        "hakuna kinachoonekana" to "nothing shows",
        "hakuna kitu" to "nothing shows",
        "skrini nyeusi" to "screen is black",
        "hakuna ishara" to "no signal",
        "hakuna mawimbi" to "no signal",
        "hakuna picha" to "no picture",
        "skrini ipi" to "which screen",
        "skrini gani" to "which screen",
        "kifuatiliaji kipi" to "which monitor",
        "kifuatiliaji gani" to "which monitor",
        "projekta ipi" to "which projector",
        "projekta gani" to "which projector",

        // What is on screen.
        "usuli" to "background",
        "mandharinyuma" to "background",
        "mandhari ya nyuma" to "background",
        "maneno ya wimbo" to "lyrics",
        "maneno ya nyimbo" to "lyrics",
        "wimbo ulio bora" to "wimbo ulio bora",
        "wimbo" to "song",
        "nyimbo" to "songs",
        "tenzi" to "hymn",
        "utenzi" to "hymn",
        "tenzi za rohoni" to "hymn",
        "kusifu" to "worship",
        "kuabudu" to "worship",
        "sifa na kuabudu" to "worship",
        "biblia" to "bible",
        "maandiko" to "scripture",
        "neno la mungu" to "scripture",
        "mstari" to "verse",
        "mistari" to "verses",
        "sura" to "chapter",
        "ukubwa wa fonti" to "font size",
        "ukubwa wa herufi" to "font size",
        "ukubwa wa maandishi" to "text size",
        "fonti" to "font",
        "ukubwa" to "size",
        "maandishi" to "text",
        "herufi" to "letters",
        "maneno" to "words",
        "onyesho la slaidi" to "slideshow",
        "slaidi" to "slide",
        "picha" to "picture",
        "albamu" to "album",
        "wasilisho" to "presentation",
        "mawasilisho" to "presentation",
        "filamu" to "movie",
        "sauti" to "audio",
        "jina na cheo" to "name and title",
        "jina na wadhifa" to "name and title",
        "tangazo" to "announcement",
        "matangazo" to "announcements",
        "tangaza" to "announce",
        "maandishi yanayosonga" to "ticker",
        "maandishi yanayotembea" to "ticker",
        "chumba cha watoto" to "kids room",
        "kuhesabu kurudi nyuma" to "countdown",
        "hesabu ya kurudi nyuma" to "countdown",
        "kuhesabu kushuka" to "countdown",
        "kipima muda" to "timer",
        "kipima wakati" to "timer",
        "saa ya kusimamisha" to "stopwatch",
        "saa ya sasa" to "current time",
        "muda wa sasa" to "current time",
        "saa" to "clock",
        "muda" to "time",
        "wakati" to "time",
        "maelezo" to "notes",
        "kodi za gitaa" to "chords",
        "lugha nyingine" to "another language",
        "lugha ya pili" to "second language",
        "lugha mbili" to "two languages",
        "lugha*" to "language",

        // Screens and outputs.
        "skrini kuu" to "main screen",
        "skrini nzima" to "full screen",
        "skrini kamili" to "full screen",
        "skrini ya pili" to "second screen",
        "skrini*" to "screen",
        "projekta" to "projector",
        "kifuatiliaji cha jukwaa" to "stage monitor",
        "kifuatiliaji cha jukwaani" to "stage monitor",
        "skrini ya jukwaa" to "stage monitor",
        "skrini ya jukwaani" to "stage monitor",
        "kifuatiliaji" to "monitor",
        "vifuatiliaji" to "monitors",
        "towe" to "output",
        "dirisha la towe" to "output window",
        "jukwaa*" to "stage",
        "eneo" to "zone",
        "maeneo" to "zones",
        "mpangilio" to "layout",
        "ujumbe" to "message",
        "tuma*" to "send",
        "kutuma" to "send",
        "hakiki*" to "preview",
        "onyesho la awali" to "preview",
        "kilicho kwenye skrini" to "what is on screen",
        "nini kiko kwenye skrini" to "what is on screen",
        "wasifu" to "profile",
        "mtiririko" to "stream",
        "runinga" to "tv",
        "televisheni" to "tv",

        // Pages, tabs and tools.
        "mipangilio" to "settings",
        "chaguo" to "options",
        "machaguo" to "options",
        "mapendeleo" to "preferences",
        "mchawi wa kusanidi" to "setup wizard",
        "kuanza kutumia" to "getting started",
        "anza upya" to "start over",
        "anza tena" to "start over",
        "njia ya mkato" to "shortcut",
        "njia za mkato" to "shortcut",
        "kibodi" to "keyboard",
        "kichupo" to "tab",
        "vichupo" to "tab",
        "maktaba ya nyimbo" to "song library",
        "maktaba" to "library",
        "tovuti" to "website",
        "wavuti" to "web",
        "kivinjari" to "browser",
        "kamusi" to "dictionary",
        "kamera" to "camera",
        "seva" to "server",
        "kwa mbali" to "remote",
        "rimoti" to "remote",
        "simu" to "phone",
        "kompyuta kibao" to "tablet",
        "muunganisho" to "integrations",
        "miunganisho" to "integrations",

        // Services and planning.
        "ratiba ya ibada" to "order of service",
        "mpangilio wa ibada" to "order of service",
        "utaratibu wa ibada" to "order of service",
        "ratiba" to "schedule",
        "ibada" to "service",
        "mkutano" to "meeting",
        "mikutano" to "meetings",
        "jumapili" to "sunday",
        "kalenda" to "calendar",
        "orodha ya kucheza" to "playlist",
        "kila jumapili" to "every sunday",
        "kila wiki" to "every week",
        "kila juma" to "every week",
        "kila mwezi" to "monthly",
        "kwa wiki" to "weekly",
        "rudia" to "repeat",
        "kurudia" to "repeat",
        "kiolezo" to "template",
        "violezo" to "template",

        // Many, all, both.
        "zote mbili" to "both",
        "vyote viwili" to "both",
        "yote mawili" to "both",
        "wote wawili" to "both",
        "zote" to "all",
        "yote" to "all",
        "wote" to "all",
        "vyote" to "all",
        "kila kitu" to "everything",
        "kadhaa" to "several",
        "nyingi" to "many",
        "kwa pamoja" to "at once",
        "kwa wakati mmoja" to "at once",
        "kwa ibada hii" to "this service",
        "kwa leo" to "for today",
        "kwa muda" to "temporarily",
        "kwa sasa" to "for now",

        // Languages, by name.
        "kiingereza" to "english",
        "kihispania" to "spanish",
        "kirusi" to "russian",
        "kiukreni" to "ukrainian",
        "kijerumani" to "german",
        "kifaransa" to "french",
        "kipolandi" to "polish",
        "kireno" to "portuguese",
        "kiitaliano" to "italian",
        "kiholanzi" to "dutch",
        "kiromania" to "romanian",
        "kigiriki" to "greek",
        "kituruki" to "turkish",
        "kiarabu" to "arabic",
        "kiajemi" to "persian",
        "kiebrania" to "hebrew",
        "kihindi" to "hindi",
        "kichina" to "chinese",
        "kijapani" to "japanese",
        "kikorea" to "korean",
        "kiindonesia" to "indonesian",
        "kimalei" to "malay",
        "kiswahili" to "swahili",
        "kiamhari" to "amharic",
        "kilatini" to "latin",

        // Colors.
        "buluu iliyokolea" to "navy",
        "samawati" to "light blue",
        "buluu" to "blue",
        "bluu" to "blue",
        "nyeusi" to "black",
        "mweusi" to "black",
        "cheusi" to "black",
        "nyeupe" to "white",
        "mweupe" to "white",
        "cheupe" to "white",
        "kijivu" to "grey",
        "fedha" to "silver",
        "nyekundu" to "red",
        "mwekundu" to "red",
        "chekundu" to "red",
        "rangi ya chungwa" to "orange",
        "machungwa" to "orange",
        "njano" to "yellow",
        "manjano" to "yellow",
        "dhahabu" to "gold",
        "kijani kibichi" to "green",
        "kijani" to "green",
        "zambarau" to "purple",
        "urujuani" to "violet",
        "waridi" to "pink",
        "pinki" to "pink",
        "kahawia" to "brown",
        "hudhurungi" to "brown",
        "krimu" to "cream",
        "iliyokolea" to "dark",
        "giza" to "dark",
        "angavu" to "light",
        "nyepesi" to "light",

        // Talking to the helper.
        "habari" to "hello",
        "habari yako" to "hello",
        "hujambo" to "hello",
        "jambo" to "hello",
        "mambo" to "hello",
        "salamu" to "hello",
        "shikamoo" to "hello",
        "msaada" to "help",
        "nisaidie" to "help",
        "saidia" to "help",
        "unaweza kufanya nini" to "what can you do",
        "unajua kufanya nini" to "what can you do",
        "unafanya nini" to "what do you do",
        "wewe ni nani" to "who are you",
        "u nani" to "who are you",
        "asante" to "thanks",
        "ahsante" to "thanks",
        "asanteni" to "thanks",
        "asante sana" to "thank you",
        "tafadhali" to "please",
        "wik" to "wick",
    ),
)
