package org.churchpresenter.helper.intent.glossary

internal val SWEDISH = Glossary(
    "sv",
    listOf(
        // Asking where, or how.
        "var" to "where",
        "vart" to "where",
        "var finns" to "where",
        "var hittar jag" to "where",
        "hur kan jag" to "how can i",
        "hur gör jag" to "how do i",
        "hur gor jag" to "how do i",
        "hur gör man" to "how do i",
        "hur" to "how do i",
        "hittar inte" to "can't find",
        "kan inte hitta" to "can't find",
        "visa mig" to "show me",

        // Doing.
        "visa*" to "show",
        "öppna*" to "open",
        "oppna*" to "open",
        "gå till" to "go to",
        "ga till" to "go to",
        "byt till" to "switch to",
        "växla till" to "switch to",
        "vaxla till" to "switch to",
        "sök" to "find",
        "söka" to "find",
        "sök efter" to "find",
        "hitta" to "find",
        "läs" to "read",
        "läs upp" to "read",
        "gör" to "make",
        "göra" to "make",
        "skapa*" to "create",
        "lägg till" to "add",
        "lagg till" to "add",
        "lägga till" to "add",
        "ladda upp" to "load",
        "ladda in" to "load",
        "ladda" to "load",
        "importera*" to "import",
        "ladda ner" to "download",
        "ladda ned" to "download",
        "installera*" to "install",
        "välj*" to "choose",
        "valj*" to "choose",
        "ställ in" to "set up",
        "stall in" to "set up",
        "konfigurera*" to "set up",
        "anslut*" to "connect",
        "koppla*" to "connect",
        "tilldela*" to "assign",
        "dölj*" to "hide",
        "dolj*" to "hide",
        "göm*" to "hide",
        "stoppa*" to "stop",
        "avsluta*" to "stop",
        "ta bort" to "delete",
        "radera*" to "delete",
        "rensa*" to "clear",
        "töm" to "clear",
        "tömma" to "clear",
        "släck skärmen" to "black out",
        "slack skarmen" to "black out",
        "mörklägg*" to "black out",
        "tom skärm" to "blank",
        "ångra*" to "undo",
        "angra*" to "undo",
        "gå live" to "go live",
        "ga live" to "go live",
        "sätt på" to "turn on",
        "slå på" to "turn on",
        "sla pa" to "turn on",
        "stäng av" to "turn off",
        "slå av" to "turn off",
        "sla av" to "turn off",
        "växla*" to "toggle",
        "vaxla*" to "toggle",
        "nästa" to "next",
        "nasta" to "next",
        "vidare" to "next",
        "framåt" to "forward",
        "framat" to "forward",
        "föregående*" to "previous",
        "foregaende*" to "previous",
        "tillbaka" to "back",
        "förstora*" to "increase",
        "forstora*" to "increase",
        "öka" to "increase",
        "större" to "bigger",
        "storre" to "bigger",
        "minska*" to "decrease",
        "förminska*" to "decrease",
        "mindre" to "smaller",
        "konvertera*" to "convert",
        "omvandla*" to "convert",
        "överför*" to "transfer",
        "overfor*" to "transfer",
        "migrera*" to "migrate",
        "redigera*" to "edit",
        "ändra*" to "change",
        "byt namn" to "rename",
        "döp om" to "rename",
        "fixa*" to "fix",
        "laga" to "fix",
        "åtgärda*" to "fix",
        "organisera*" to "organize",
        "städa*" to "clean up",
        "stada*" to "clean up",
        "jämför*" to "compare",
        "jamfor*" to "compare",
        "översätt*" to "translate",
        "oversatt*" to "translate",
        "planera*" to "plan",
        "automatisera*" to "automate",
        "automatiskt" to "automatically",
        "identifiera*" to "identify",
        "numrera*" to "number the",

        // Too small, too big, not working.
        "för liten" to "too small",
        "for liten" to "too small",
        "för litet" to "too small",
        "för små" to "too small",
        "for sma" to "too small",
        "svårläst*" to "hard to read",
        "svarlast*" to "hard to read",
        "svårt att läsa" to "hard to read",
        "svart att lasa" to "hard to read",
        "syns inte" to "hard to read",
        "för stor" to "too big",
        "for stor" to "too big",
        "för stort" to "too big",
        "för stora" to "too big",
        "får inte plats" to "doesn't fit",
        "ryms inte" to "doesn't fit",
        "fungerar inte" to "not working",
        "funkar inte" to "not working",
        "visas inte" to "not showing",
        "visar inte" to "not showing",
        "visar ingenting" to "nothing shows",
        "ingenting visas" to "nothing shows",
        "svart skärm" to "screen is black",
        "svart skarm" to "screen is black",
        "skärmen är svart" to "screen is black",
        "ingen signal" to "no signal",
        "ingen bild" to "no picture",
        "vilken skärm" to "which screen",
        "vilken skarm" to "which screen",
        "vilken monitor" to "which monitor",
        "vilken projektor" to "which projector",

        // What is on screen.
        "bakgrund*" to "background",
        "sångtext*" to "lyrics",
        "sangtext*" to "lyrics",
        "låttext*" to "lyrics",
        "sång*" to "song",
        "sånger" to "songs",
        "sanger" to "songs",
        "låten" to "song",
        "låtar" to "songs",
        "lovsång*" to "worship",
        "lovsang*" to "worship",
        "tillbedjan" to "worship",
        "bibel*" to "bible",
        "skriften" to "scripture",
        "skriftställe*" to "verse",
        "bibelvers*" to "verse",
        "vers" to "verse",
        "verser" to "verse",
        "kapitel" to "chapter",
        "kapitlet" to "chapter",
        "teckenstorlek*" to "font size",
        "textstorlek*" to "text size",
        "typsnitt*" to "font",
        "teckensnitt*" to "font",
        "storlek*" to "size",
        "text*" to "text",
        "ord" to "words",
        "orden" to "words",
        "bokstäver*" to "letters",
        "bokstaver*" to "letters",
        "bildspel*" to "slideshow",
        "bilder" to "picture",
        "bild*" to "picture",
        "foto*" to "photo",
        "filmer" to "movie",
        "filmen" to "movie",
        "klipp*" to "clip",
        "nedre tredjedel*" to "lower third",
        "namnskylt*" to "name strap",
        "namnbanner*" to "name strap",
        "namn och titel" to "name and title",
        "meddelande*" to "announcement",
        "kungörelse*" to "announcement",
        "annons*" to "announcement",
        "rullande text" to "ticker",
        "textremsa*" to "ticker",
        "barnrum*" to "kids room",
        "barnpassning*" to "kids room",
        "söndagsskola*" to "kids room",
        "nedräkning*" to "countdown",
        "nedrakning*" to "countdown",
        "räkna ner" to "countdown",
        "tidtagarur*" to "stopwatch",
        "stoppur*" to "stopwatch",
        "klocka*" to "clock",
        "klockan" to "clock",
        "aktuell tid" to "current time",
        "tid" to "time",
        "tiden" to "time",
        "anteckning*" to "notes",
        "ackord*" to "chord",
        "översättning*" to "translation",
        "oversattning*" to "translation",
        "språk*" to "language",
        "sprak*" to "language",
        "tvåspråkig*" to "bilingual",
        "tvasprakig*" to "bilingual",
        "annat språk" to "another language",
        "ett annat språk" to "another language",
        "andra språk" to "another language",
        "ett andra språk" to "second language",
        "två språk" to "two languages",
        "tva sprak" to "two languages",

        // Screens and outputs.
        "huvudskärm*" to "main screen",
        "huvudskarm*" to "main screen",
        "helskärm*" to "full screen",
        "helskarm*" to "full screen",
        "hela skärmen" to "full screen",
        "andra skärmen" to "second screen",
        "skärm*" to "screen",
        "skarm*" to "screen",
        "projektor*" to "projector",
        "scenmonitor*" to "stage monitor",
        "scenskärm*" to "stage monitor",
        "scenskarm*" to "stage monitor",
        "monitorer" to "monitor",
        "visning*" to "display",
        "utgång*" to "output",
        "utgang*" to "output",
        "utmatning*" to "output",
        "scenen" to "stage",
        "zoner" to "zone",
        "zon" to "zone",
        "arrangemang*" to "arrangement",
        "skicka meddelande" to "send message",
        "skicka*" to "send",
        "förhandsvisning*" to "preview",
        "forhandsvisning*" to "preview",
        "vad som visas" to "what is on screen",
        "profil*" to "profile",
        "sändning*" to "stream",
        "strömning*" to "stream",
        "tv-apparat*" to "tv",

        // Pages, tabs and tools.
        "inställning*" to "settings",
        "installning*" to "settings",
        "alternativ" to "options",
        "installationsguide*" to "setup wizard",
        "börja om" to "start over",
        "borja om" to "start over",
        "kortkommando*" to "shortcut",
        "snabbtangent*" to "hotkeys",
        "tangentbord*" to "keyboard",
        "flik*" to "tab",
        "sångbibliotek*" to "song library",
        "sangbibliotek*" to "song library",
        "bibliotek*" to "library",
        "webbplats*" to "website",
        "hemsida*" to "website",
        "webbläsare*" to "browser",
        "webblasare*" to "browser",
        "webb*" to "web",
        "lexikon" to "dictionary",
        "ordbok*" to "dictionary",
        "kamera*" to "camera",
        "servern" to "server",
        "fjärrkontroll*" to "remote",
        "fjarrkontroll*" to "remote",
        "fjärrstyr*" to "remote",
        "telefon*" to "phone",
        "mobilen" to "phone",
        "surfplatta*" to "tablet",
        "surfplattor" to "tablet",
        "integration*" to "integrations",

        // Services and planning.
        "gudstjänstordning*" to "order of service",
        "körschema*" to "order of service",
        "korschema*" to "order of service",
        "gudstjänst*" to "service",
        "gudstjanst*" to "service",
        "möte" to "meeting",
        "mötet" to "meeting",
        "möten" to "meeting",
        "söndag*" to "sunday",
        "sondag*" to "sunday",
        "kalender*" to "calendar",
        "programmet" to "schedule",
        "schema*" to "schedule",
        "spellista*" to "playlist",
        "varje söndag" to "every sunday",
        "varje sondag" to "every sunday",
        "varje vecka" to "every week",
        "veckovis" to "weekly",
        "varje månad" to "monthly",
        "månatlig*" to "monthly",
        "upprepa*" to "repeat",
        "återkommande" to "recurring",
        "mallen" to "template",
        "mallar" to "template",

        // Many, all, both.
        "alla" to "all",
        "allt" to "everything",
        "överallt" to "everything",
        "båda" to "both",
        "bägge" to "both",
        "flera" to "several",
        "många" to "many",
        "samtidigt" to "at once",
        "på en gång" to "at once",
        "för den här gudstjänsten" to "this service",
        "för idag" to "for today",
        "för i dag" to "for today",
        "tillfälligt" to "temporarily",
        "tillfalligt" to "temporarily",
        "för nu" to "for now",

        // Languages, by name.
        "ryska*" to "russian",
        "ukrainska*" to "ukrainian",
        "vitryska*" to "belarusian",
        "belarusiska*" to "belarusian",
        "engelska*" to "english",
        "spanska*" to "spanish",
        "tyska*" to "german",
        "franska*" to "french",
        "polska*" to "polish",
        "kazakiska*" to "kazakh",
        "rumänska*" to "romanian",
        "rumanska*" to "romanian",
        "moldaviska*" to "moldovan",
        "portugisiska*" to "portuguese",
        "italienska*" to "italian",
        "nederländska*" to "dutch",
        "holländska*" to "dutch",
        "tjeckiska*" to "czech",
        "slovakiska*" to "slovak",
        "kroatiska*" to "croatian",
        "serbiska*" to "serbian",
        "bulgariska*" to "bulgarian",
        "ungerska*" to "hungarian",
        "grekiska*" to "greek",
        "turkiska*" to "turkish",
        "arabiska*" to "arabic",
        "persiska*" to "persian",
        "hebreiska*" to "hebrew",
        "kinesiska*" to "chinese",
        "japanska*" to "japanese",
        "koreanska*" to "korean",
        "vietnamesiska*" to "vietnamese",
        "indonesiska*" to "indonesian",
        "estniska*" to "estonian",
        "lettiska*" to "latvian",
        "litauiska*" to "lithuanian",
        "finska*" to "finnish",
        "svenska*" to "swedish",
        "norska*" to "norwegian",
        "danska*" to "danish",
        "armeniska*" to "armenian",
        "georgiska*" to "georgian",
        "latinska*" to "latin",

        // Colors.
        "mörkblå*" to "navy",
        "morkbla*" to "navy",
        "marinblå*" to "navy",
        "ljusblå*" to "light blue",
        "ljusbla*" to "light blue",
        "himmelsblå*" to "sky",
        "blå*" to "blue",
        "svart" to "black",
        "svarta" to "black",
        "vit" to "white",
        "vita" to "white",
        "vitt" to "white",
        "grå*" to "grey",
        "silvrig*" to "silver",
        "röd*" to "red",
        "rött" to "red",
        "vinröd*" to "maroon",
        "vinrod*" to "maroon",
        "gul" to "yellow",
        "gula" to "yellow",
        "gult" to "yellow",
        "guld*" to "gold",
        "limegrön*" to "lime",
        "ljusgrön*" to "lime",
        "grön*" to "green",
        "gron*" to "green",
        "turkos*" to "turquoise",
        "lila" to "purple",
        "violett*" to "violet",
        "rosa" to "pink",
        "brun" to "brown",
        "bruna" to "brown",
        "brunt" to "brown",
        "krämvit*" to "cream",
        "krämfärg*" to "cream",
        "mörk*" to "dark",
        "mork*" to "dark",
        "ljus*" to "light",

        // Talking to the helper.
        "hej" to "hello",
        "hejsan" to "hello",
        "hallå" to "hello",
        "god morgon" to "hello",
        "goddag" to "hello",
        "tjena" to "hello",
        "hjälp*" to "help",
        "hjalp*" to "help",
        "vad kan du" to "what can you do",
        "vad kan du göra" to "what can you do",
        "vem är du" to "who are you",
        "vem ar du" to "who are you",
        "tack" to "thanks",
        "tack så mycket" to "thank you",
        "tusen tack" to "thank you",
        "snälla" to "please",
        "var snäll" to "please",
        "var så snäll" to "please",
        "vick" to "wick",
    ),
)
