package org.churchpresenter.helper.intent.glossary

internal val SWEDISH = Glossary(
    "sv",
    listOf(
        // Asking where, or how.
        "var" to "where",
        "vart" to "where",
        "var finns" to "where",
        "var hittar jag" to "where",
        "hur kan jag" to "how can i",
        "hur gör jag" to "how do i",
        "hur gor jag" to "how do i",
        "hur gör man" to "how do i",
        "hur" to "how do i",
        "hittar inte" to "can't find",
        "kan inte hitta" to "can't find",
        "visa mig" to "show me",

        // Doing.
        "visa*" to "show",
        "öppna*" to "open",
        "oppna*" to "open",
        "gå till" to "go to",
        "ga till" to "go to",
        "byt till" to "switch to",
        "växla till" to "switch to",
        "vaxla till" to "switch to",
        "sök" to "find",
        "söka" to "find",
        "sök efter" to "find",
        "hitta" to "find",
        "läs" to "read",
        "läs upp" to "read",
        "gör" to "make",
        "göra" to "make",
        "skapa*" to "create",
        "lägg till" to "add",
        "lagg till" to "add",
        "lägga till" to "add",
        "ladda upp" to "load",
        "ladda in" to "load",
        "ladda" to "load",
        "importera*" to "import",
        "ladda ner" to "download",
        "ladda ned" to "download",
        "installera*" to "install",
        "välj*" to "choose",
        "valj*" to "choose",
        "ställ in" to "set up",
        "stall in" to "set up",
        "konfigurera*" to "set up",
        "anslut*" to "connect",
        "koppla*" to "connect",
        "tilldela*" to "assign",
        "dölj*" to "hide",
        "dolj*" to "hide",
        "göm*" to "hide",
        "stoppa*" to "stop",
        "avsluta*" to "stop",
        "ta bort" to "delete",
        "radera*" to "delete",
        "rensa*" to "clear",
        "töm" to "clear",
        "tömma" to "clear",
        "släck skärmen" to "black out",
        "slack skarmen" to "black out",
        "mörklägg*" to "black out",
        "tom skärm" to "blank",
        "ångra*" to "undo",
        "angra*" to "undo",
        "gå live" to "go live",
        "ga live" to "go live",
        "sätt på" to "turn on",
        "slå på" to "turn on",
        "sla pa" to "turn on",
        "stäng av" to "turn off",
        "slå av" to "turn off",
        "sla av" to "turn off",
        "växla*" to "toggle",
        "vaxla*" to "toggle",
        "nästa" to "next",
        "nasta" to "next",
        "vidare" to "next",
        "framåt" to "forward",
        "framat" to "forward",
        "föregående*" to "previous",
        "foregaende*" to "previous",
        "tillbaka" to "back",
        "förstora*" to "increase",
        "forstora*" to "increase",
        "öka" to "increase",
        "större" to "bigger",
        "storre" to "bigger",
        "minska*" to "decrease",
        "förminska*" to "decrease",
        "mindre" to "smaller",
        "konvertera*" to "convert",
        "omvandla*" to "convert",
        "överför*" to "transfer",
        "overfor*" to "transfer",
        "migrera*" to "migrate",
        "redigera*" to "edit",
        "ändra*" to "change",
        "byt namn" to "rename",
        "döp om" to "rename",
        "fixa*" to "fix",
        "laga" to "fix",
        "åtgärda*" to "fix",
        "organisera*" to "organize",
        "städa*" to "clean up",
        "stada*" to "clean up",
        "jämför*" to "compare",
        "jamfor*" to "compare",
        "översätt*" to "translate",
        "oversatt*" to "translate",
        "planera*" to "plan",
        "automatisera*" to "automate",
        "automatiskt" to "automatically",
        "identifiera*" to "identify",
        "numrera*" to "number the",

        // Too small, too big, not working.
        "för liten" to "too small",
        "for liten" to "too small",
        "för litet" to "too small",
        "för små" to "too small",
        "for sma" to "too small",
        "svårläst*" to "hard to read",
        "svarlast*" to "hard to read",
        "svårt att läsa" to "hard to read",
        "svart att lasa" to "hard to read",
        "syns inte" to "hard to read",
        "för stor" to "too big",
        "for stor" to "too big",
        "för stort" to "too big",
        "för stora" to "too big",
        "får inte plats" to "doesn't fit",
        "ryms inte" to "doesn't fit",
        "fungerar inte" to "not working",
        "funkar inte" to "not working",
        "visas inte" to "not showing",
        "visar inte" to "not showing",
        "visar ingenting" to "nothing shows",
        "ingenting visas" to "nothing shows",
        "svart skärm" to "screen is black",
        "svart skarm" to "screen is black",
        "skärmen är svart" to "screen is black",
        "ingen signal" to "no signal",
        "ingen bild" to "no picture",
        "vilken skärm" to "which screen",
        "vilken skarm" to "which screen",
        "vilken monitor" to "which monitor",
        "vilken projektor" to "which projector",

        // What is on screen.
        "bakgrund*" to "background",
        "sångtext*" to "lyrics",
        "sangtext*" to "lyrics",
        "låttext*" to "lyrics",
        "sång*" to "song",
        "sånger" to "songs",
        "sanger" to "songs",
        "låten" to "song",
        "låtar" to "songs",
        "lovsång*" to "worship",
        "lovsang*" to "worship",
        "tillbedjan" to "worship",
        "bibel*" to "bible",
        "skriften" to "scripture",
        "skriftställe*" to "verse",
        "bibelvers*" to "verse",
        "vers" to "verse",
        "verser" to "verse",
        "kapitel" to "chapter",
        "kapitlet" to "chapter",
        "teckenstorlek*" to "font size",
        "textstorlek*" to "text size",
        "typsnitt*" to "font",
        "teckensnitt*" to "font",
        "storlek*" to "size",
        "text*" to "text",
        "ord" to "words",
        "orden" to "words",
        "bokstäver*" to "letters",
        "bokstaver*" to "letters",
        "bildspel*" to "slideshow",
        "bilder" to "picture",
        "bild*" to "picture",
        "foto*" to "photo",
        "filmer" to "movie",
        "filmen" to "movie",
        "klipp*" to "clip",
        "nedre tredjedel*" to "lower third",
        "namnskylt*" to "name strap",
        "namnbanner*" to "name strap",
        "namn och titel" to "name and title",
        "meddelande*" to "announcement",
        "kungörelse*" to "announcement",
        "annons*" to "announcement",
        "rullande text" to "ticker",
        "textremsa*" to "ticker",
        "barnrum*" to "kids room",
        "barnpassning*" to "kids room",
        "söndagsskola*" to "kids room",
        "nedräkning*" to "countdown",
        "nedrakning*" to "countdown",
        "räkna ner" to "countdown",
        "tidtagarur*" to "stopwatch",
        "stoppur*" to "stopwatch",
        "klocka*" to "clock",
        "klockan" to "clock",
        "aktuell tid" to "current time",
        "tid" to "time",
        "tiden" to "time",
        "anteckning*" to "notes",
        "ackord*" to "chord",
        "översättning*" to "translation",
        "oversattning*" to "translation",
        "språk*" to "language",
        "sprak*" to "language",
        "tvåspråkig*" to "bilingual",
        "tvasprakig*" to "bilingual",
        "annat språk" to "another language",
        "ett annat språk" to "another language",
        "andra språk" to "another language",
        "ett andra språk" to "second language",
        "två språk" to "two languages",
        "tva sprak" to "two languages",

        // Screens and outputs.
        "huvudskärm*" to "main screen",
        "huvudskarm*" to "main screen",
        "helskärm*" to "full screen",
        "helskarm*" to "full screen",
        "hela skärmen" to "full screen",
        "andra skärmen" to "second screen",
        "skärm*" to "screen",
        "skarm*" to "screen",
        "projektor*" to "projector",
        "scenmonitor*" to "stage monitor",
        "scenskärm*" to "stage monitor",
        "scenskarm*" to "stage monitor",
        "monitorer" to "monitor",
        "visning*" to "display",
        "utgång*" to "output",
        "utgang*" to "output",
        "utmatning*" to "output",
        "scenen" to "stage",
        "zoner" to "zone",
        "zon" to "zone",
        "arrangemang*" to "arrangement",
        "skicka meddelande" to "send message",
        "skicka*" to "send",
        "förhandsvisning*" to "preview",
        "forhandsvisning*" to "preview",
        "vad som visas" to "what is on screen",
        "profil*" to "profile",
        "sändning*" to "stream",
        "strömning*" to "stream",
        "tv-apparat*" to "tv",

        // Pages, tabs and tools.
        "inställning*" to "settings",
        "installning*" to "settings",
        "alternativ" to "options",
        "installationsguide*" to "setup wizard",
        "börja om" to "start over",
        "borja om" to "start over",
        "kortkommando*" to "shortcut",
        "snabbtangent*" to "hotkeys",
        "tangentbord*" to "keyboard",
        "flik*" to "tab",
        "sångbibliotek*" to "song library",
        "sangbibliotek*" to "song library",
        "bibliotek*" to "library",
        "webbplats*" to "website",
        "hemsida*" to "website",
        "webbläsare*" to "browser",
        "webblasare*" to "browser",
        "webb*" to "web",
        "lexikon" to "dictionary",
        "ordbok*" to "dictionary",
        "kamera*" to "camera",
        "servern" to "server",
        "fjärrkontroll*" to "remote",
        "fjarrkontroll*" to "remote",
        "fjärrstyr*" to "remote",
        "telefon*" to "phone",
        "mobilen" to "phone",
        "surfplatta*" to "tablet",
        "surfplattor" to "tablet",
        "integration*" to "integrations",

        // Services and planning.
        "gudstjänstordning*" to "order of service",
        "körschema*" to "order of service",
        "korschema*" to "order of service",
        "gudstjänst*" to "service",
        "gudstjanst*" to "service",
        "möte" to "meeting",
        "mötet" to "meeting",
        "möten" to "meeting",
        "söndag*" to "sunday",
        "sondag*" to "sunday",
        "kalender*" to "calendar",
        "programmet" to "schedule",
        "schema*" to "schedule",
        "spellista*" to "playlist",
        "varje söndag" to "every sunday",
        "varje sondag" to "every sunday",
        "varje vecka" to "every week",
        "veckovis" to "weekly",
        "varje månad" to "monthly",
        "månatlig*" to "monthly",
        "upprepa*" to "repeat",
        "återkommande" to "recurring",
        "mallen" to "template",
        "mallar" to "template",

        // Many, all, both.
        "alla" to "all",
        "allt" to "everything",
        "överallt" to "everything",
        "båda" to "both",
        "bägge" to "both",
        "flera" to "several",
        "många" to "many",
        "samtidigt" to "at once",
        "på en gång" to "at once",
        "för den här gudstjänsten" to "this service",
        "för idag" to "for today",
        "för i dag" to "for today",
        "tillfälligt" to "temporarily",
        "tillfalligt" to "temporarily",
        "för nu" to "for now",

        // Languages, by name.
        "ryska*" to "russian",
        "ukrainska*" to "ukrainian",
        "vitryska*" to "belarusian",
        "belarusiska*" to "belarusian",
        "engelska*" to "english",
        "spanska*" to "spanish",
        "tyska*" to "german",
        "franska*" to "french",
        "polska*" to "polish",
        "kazakiska*" to "kazakh",
        "rumänska*" to "romanian",
        "rumanska*" to "romanian",
        "moldaviska*" to "moldovan",
        "portugisiska*" to "portuguese",
        "italienska*" to "italian",
        "nederländska*" to "dutch",
        "holländska*" to "dutch",
        "tjeckiska*" to "czech",
        "slovakiska*" to "slovak",
        "kroatiska*" to "croatian",
        "serbiska*" to "serbian",
        "bulgariska*" to "bulgarian",
        "ungerska*" to "hungarian",
        "grekiska*" to "greek",
        "turkiska*" to "turkish",
        "arabiska*" to "arabic",
        "persiska*" to "persian",
        "hebreiska*" to "hebrew",
        "kinesiska*" to "chinese",
        "japanska*" to "japanese",
        "koreanska*" to "korean",
        "vietnamesiska*" to "vietnamese",
        "indonesiska*" to "indonesian",
        "estniska*" to "estonian",
        "lettiska*" to "latvian",
        "litauiska*" to "lithuanian",
        "finska*" to "finnish",
        "svenska*" to "swedish",
        "norska*" to "norwegian",
        "danska*" to "danish",
        "armeniska*" to "armenian",
        "georgiska*" to "georgian",
        "latinska*" to "latin",

        // Colors.
        "mörkblå*" to "navy",
        "morkbla*" to "navy",
        "marinblå*" to "navy",
        "ljusblå*" to "light blue",
        "ljusbla*" to "light blue",
        "himmelsblå*" to "sky",
        "blå*" to "blue",
        "svart" to "black",
        "svarta" to "black",
        "vit" to "white",
        "vita" to "white",
        "vitt" to "white",
        "grå*" to "grey",
        "silvrig*" to "silver",
        "röd*" to "red",
        "rött" to "red",
        "vinröd*" to "maroon",
        "vinrod*" to "maroon",
        "gul" to "yellow",
        "gula" to "yellow",
        "gult" to "yellow",
        "guld*" to "gold",
        "limegrön*" to "lime",
        "ljusgrön*" to "lime",
        "grön*" to "green",
        "gron*" to "green",
        "turkos*" to "turquoise",
        "lila" to "purple",
        "violett*" to "violet",
        "rosa" to "pink",
        "brun" to "brown",
        "bruna" to "brown",
        "brunt" to "brown",
        "krämvit*" to "cream",
        "krämfärg*" to "cream",
        "mörk*" to "dark",
        "mork*" to "dark",
        "ljus*" to "light",

        // Talking to the helper.
        "hej" to "hello",
        "hejsan" to "hello",
        "hallå" to "hello",
        "god morgon" to "hello",
        "goddag" to "hello",
        "tjena" to "hello",
        "hjälp*" to "help",
        "hjalp*" to "help",
        "vad kan du" to "what can you do",
        "vad kan du göra" to "what can you do",
        "vem är du" to "who are you",
        "vem ar du" to "who are you",
        "tack" to "thanks",
        "tack så mycket" to "thank you",
        "tusen tack" to "thank you",
        "snälla" to "please",
        "var snäll" to "please",
        "var så snäll" to "please",
        "vick" to "wick",

        // Newer requests.
        "sök i" to "search in",
        "sok i" to "search in",
        "söker" to "search",
        "soker" to "search",
        "söker jag efter" to "search for",
        "soker jag efter" to "search for",
        "sökning*" to "search",
        "sokning*" to "search",
        "slå upp" to "look up",
        "sla upp" to "look up",
        "leta upp" to "look up",
        "sök upp" to "look up",
        "leta efter" to "look for",
        "sök en" to "find a",
        "hitta en" to "find a",
        "nummer" to "number",
        "som heter" to "called",
        "kallad" to "called",
        "kallas" to "called",
        "favorit*" to "favorite",
        "stjärnmärk*" to "favorite",
        "stjarnmark*" to "favorite",
        "den här sången" to "this song",
        "den har sangen" to "this song",
        "den här låten" to "this song",
        "denna sång" to "this song",
        "varje sång" to "each song",
        "varje sang" to "each song",
        "sin egen" to "its own",
        "egen bakgrund*" to "own background",
        "sångbakgrund*" to "song background",
        "sangbakgrund*" to "song background",
        "för stunden" to "for now",
        "för tillfället" to "for now",
        "for tillfallet" to "for now",
        "flera verser" to "several verses",
        "flera vers" to "several verses",
        "mer än en vers" to "more than one verse",
        "mer an en vers" to "more than one verse",
        "versintervall*" to "verse range",
        "ett avsnitt" to "a passage",
        "historik*" to "history",
        "historia" to "history",
        "vad visade vi nyss" to "what did we just show",
        "vad visade vi just" to "what did we just show",
        "vad har vi visat" to "what did we show",
        "senaste verserna" to "recent verses",
        "nyligen visade" to "recently shown",
        "visades tidigare" to "shown before",
        "korshänvisning*" to "cross references",
        "korshanvisning*" to "cross references",
        "korsreferens*" to "cross references",
        "relaterade verser" to "related verses",
        "relaterade vers" to "related verses",
        "liknande verser" to "similar verses",
        "parallellställe*" to "parallel passages",
        "parallella ställen" to "parallel passages",
        "webbsida*" to "web page",
        "internetsida*" to "internet page",
        "webbadress*" to "url",
        "statistik*" to "statistics",
        "hur många gånger" to "how many times",
        "hur manga ganger" to "how many times",
        "hur ofta" to "how often",
        "sånganvändning*" to "song usage",
        "sångrapport*" to "song report",
        "sangrapport*" to "song report",
        "ccli-rapport*" to "ccli report",
        "styr det från" to "control it from",
        "styr det fran" to "control it from",
        "från min telefon" to "from my phone",
        "fran min telefon" to "from my phone",
        "från min mobil*" to "from my phone",
        "från telefonen" to "from the phone",
        "fran telefonen" to "from the phone",
        "från mobilen" to "from the phone",
        "på min telefon" to "on my phone",
        "pa min telefon" to "on my phone",
        "anslut min telefon" to "connect my phone",
        "koppla min telefon" to "connect my phone",
        "fjärrstyrning*" to "remote control",
        "fjarrstyrning*" to "remote control",
        "qr-kod*" to "qr code",
        "qr kod*" to "qr code",
        "minut*" to "minutes",
        "meddela" to "announce",
        "meddela:" to "announce :",
        "annonsera" to "announce",
        "annonsera:" to "announce :",
        "lägg" to "put",
        "lagg" to "put",
        "lägg in" to "put",
        "lagg in" to "put",
        "lägger till" to "add",
        "lägger jag till" to "add",
        "lagger jag till" to "add",
        "lägg till en" to "add a",
        "lägga till en" to "add a",
        "lägger till en" to "add a",
        "lägger jag till en" to "add a",
        "lagger jag till en" to "add a",
        "i programmet" to "in the schedule",
        "till programmet" to "to the schedule",
        "in i programmet" to "into the schedule",
        "på programmet" to "on the schedule",
        "pa programmet" to "on the schedule",
        "i schemat" to "in the schedule",
        "till schemat" to "to the schedule",
        "på schemat" to "on the schedule",
        "punkt" to "item",
        "punkten" to "item",
        "punkter" to "items",
        "programpunkt*" to "item",
        "nästa bild" to "next slide",
        "nasta bild" to "next slide",
        "föregående bild" to "previous slide",
        "foregaende bild" to "previous slide",
        "hur gör jag en" to "how do i make a",
        "hur gör jag ett" to "how do i make a",
        "hur gor jag en" to "how do i make a",
        "ställer in" to "set up",
        "ställer jag in" to "set up",
        "staller jag in" to "set up",
        "vad är live" to "what's live",
        "vad ar live" to "what's live",
        "vad är på skärmen" to "what is on screen",
        "vad visas" to "what's showing",
        "är något live" to "is anything live",
        "vilken version" to "what version",
        "appversion*" to "app version",
        "sök efter uppdateringar" to "check for updates",
        "sok efter uppdateringar" to "check for updates",
        "leta efter uppdateringar" to "check for updates",
        "kolla efter uppdateringar" to "check for updates",
        "finns det en uppdatering" to "is there an update",
        "finns det någon uppdatering" to "is there an update",
        "senaste versionen" to "latest version",
        "uppdaterad" to "up to date",
        "kommando*" to "commands",
        "lista över kommandon" to "list of commands",
        "lista med kommandon" to "list of commands",
        "vad kan jag säga" to "what can i say",
        "vad kan jag skriva" to "what can i type",
        "vad kan jag fråga" to "what can i ask",
        "vad förstår du" to "what do you understand",
        "vad forstar du" to "what do you understand",

        // Look requests.
        "ändrar jag" to "change",
        "andrar jag" to "change",
        "redigerar jag" to "edit",
        "flyttar jag" to "move",
        "flytta*" to "move",
        "stavfel*" to "typo",
        "skrivfel*" to "typo",
        "fet" to "bold",
        "fett" to "bold",
        "fetstil*" to "bold",
        "kursiv*" to "italic",
        "understr*" to "underline",
        "kontur*" to "outline",
        "skugg*" to "shadow",
        "marginal*" to "margins",
        "kanterna" to "edges",
        "högst upp" to "to the top",
        "hogst upp" to "to the top",
        "överst" to "top",
        "overst" to "top",
        "längst ner" to "to the bottom",
        "längst ned" to "to the bottom",
        "langst ner" to "to the bottom",
        "nederst" to "bottom",
        "i mitten" to "in the middle",
        "mitten" to "middle",
        "till vänster" to "to the left",
        "vänster" to "left",
        "vanster" to "left",
        "till höger" to "to the right",
        "höger" to "right",
        "hoger" to "right",
        "centrera*" to "center",
        "justering*" to "alignment",
        "placering*" to "position",
        "vertikal*" to "vertically",
        "sångens slut" to "end of the song",
        "sangens slut" to "end of the song",
        "slutet av sången" to "end of the song",
        "slutet på sången" to "end of the song",
        "slutmarkering*" to "end marker",
        "sångtitel*" to "song title",
        "sangtitel*" to "song title",
        "titel" to "title",
        "titeln" to "title",
        "titlar" to "title",
        "sångnummer*" to "song number",
        "sangnummer*" to "song number",
        "bibelhänvisning*" to "bible reference",
        "bibelhanvisning*" to "bible reference",
        "hänvisning*" to "reference",
        "hanvisning*" to "reference",
        "referens*" to "reference",
        "ser ut" to "look",
        "utseende*" to "appearance",
        "stil" to "style",
        "stilen" to "style",
        "stilar" to "style",
        "formatera*" to "format",
        "formatering*" to "formatting",
        "färg" to "color",
        "färgen" to "color",
        "färger" to "color",
        "farg" to "color",
        "fargen" to "color",

        // The help table's own examples.
        "föräldr*" to "parents",
    ),
)
