package org.churchpresenter.helper.intent.glossary

internal val TAGALOG = Glossary(
    "tl",
    listOf(
        // Asking where, or how.
        "saan" to "where",
        "nasaan" to "where",
        "saan ko makikita" to "where",
        "saan makikita" to "where",
        "paano ko" to "how do i",
        "paano ba" to "how do i",
        "paano mag" to "how do i",
        "paano" to "how do i",
        "pano ko" to "how do i",
        "pano" to "how do i",
        "papaano" to "how do i",
        "paano ko kaya" to "how can i",
        "hindi ko mahanap" to "can't find",
        "di ko mahanap" to "can't find",
        "hindi ko makita" to "can't find",
        "di ko makita" to "can't find",
        "ipakita mo sa akin" to "show me",
        "ipakita sa akin" to "show me",
        "pakita mo sa akin" to "show me",
        "patingin" to "show me",

        // Doing.
        "ipakita" to "show",
        "ipapakita" to "show",
        "pakita" to "show",
        "pakitaan" to "show",
        "i-show" to "show",
        "i-display" to "display",
        "idisplay" to "display",
        "i-project" to "show",
        "ilagay" to "put",
        "buksan" to "open",
        "i-open" to "open",
        "pumunta sa" to "go to",
        "punta sa" to "go to",
        "pumunta ka sa" to "go to",
        "lumipat sa" to "switch to",
        "lipat sa" to "switch to",
        "i-switch sa" to "switch to",
        "hanapin" to "find",
        "maghanap" to "find",
        "hanapan" to "find",
        "basahin" to "read",
        "gawin" to "make",
        "gumawa" to "make",
        "gawan" to "make",
        "lumikha" to "create",
        "idagdag" to "add",
        "magdagdag" to "add",
        "dagdagan" to "add",
        "i-add" to "add",
        "iadd" to "add",
        "i-load" to "load",
        "iload" to "load",
        "i-import" to "import",
        "i-download" to "download",
        "idownload" to "download",
        "i-install" to "install",
        "piliin" to "choose",
        "pumili" to "choose",
        "i-select" to "choose",
        "i-set up" to "set up",
        "i-setup" to "set up",
        "isetup" to "set up",
        "ayusin ang setting" to "set up",
        "ikonekta" to "connect",
        "i-connect" to "connect",
        "ikabit" to "connect",
        "italaga" to "assign",
        "i-assign" to "assign",
        "itago" to "hide",
        "i-hide" to "hide",
        "alisin" to "remove",
        "tanggalin" to "remove",
        "i-remove" to "remove",
        "ihinto" to "stop",
        "itigil" to "stop",
        "tigil" to "stop",
        "i-stop" to "stop",
        "i-pause" to "pause",
        "burahin" to "delete",
        "i-delete" to "delete",
        "i-clear" to "clear",
        "iclear" to "clear",
        "linisin" to "clear",
        "patayin ang screen" to "black out",
        "i-blackout" to "black out",
        "blangkong screen" to "blank",
        "i-undo" to "undo",
        "ibalik" to "undo",
        "ibalik sa dati" to "undo",
        "i-live" to "go live",
        "ilive" to "go live",
        "isalang" to "go live",
        "i-on" to "turn on",
        "buhayin" to "turn on",
        "i-off" to "turn off",
        "patayin" to "turn off",
        "susunod" to "next",
        "kasunod" to "next",
        "sunod" to "next",
        "nakaraan" to "previous",
        "naunang" to "previous",
        "nauna" to "previous",
        "bumalik" to "back",
        "balik" to "back",
        "palakihin" to "enlarge",
        "lakihan" to "enlarge",
        "mas malaki" to "bigger",
        "lakihan pa" to "bigger",
        "dagdagan ang laki" to "increase",
        "paliitin" to "shrink",
        "liitan" to "shrink",
        "mas maliit" to "smaller",
        "bawasan" to "decrease",
        "i-convert" to "convert",
        "iconvert" to "convert",
        "ilipat" to "transfer",
        "i-transfer" to "transfer",
        "i-edit" to "edit",
        "iedit" to "edit",
        "baguhin" to "change",
        "palitan ang pangalan" to "rename",
        "palitan ang name" to "rename",
        "i-rename" to "rename",
        "palitan" to "change",
        "i-change" to "change",
        "ayusin" to "fix",
        "i-fix" to "fix",
        "i-organize" to "organize",
        "isaayos" to "organize",
        "ihambing" to "compare",
        "ikumpara" to "compare",
        "isalin" to "translate",
        "i-translate" to "translate",
        "pagsasalin" to "translation",
        "salin" to "translation",
        "salinwika" to "translation",
        "magplano" to "plan",
        "planuhin" to "plan",
        "i-plano" to "plan",
        "i-automate" to "automate",
        "awtomatiko" to "automatically",
        "kusa" to "automatically",
        "tukuyin" to "identify",
        "lagyan ng numero" to "number the",
        "lagyan ng number" to "number the",

        // Too small, too big, not working.
        "masyadong maliit" to "too small",
        "sobrang liit" to "too small",
        "ang liit" to "too small",
        "maliit masyado" to "too small",
        "hindi mabasa" to "can't read",
        "di mabasa" to "can't read",
        "mahirap basahin" to "hard to read",
        "malabo" to "hard to read",
        "masyadong malaki" to "too big",
        "sobrang laki" to "too big",
        "ang laki" to "too big",
        "hindi kasya" to "doesn't fit",
        "di kasya" to "doesn't fit",
        "hindi magkasya" to "doesn't fit",
        "hindi gumagana" to "not working",
        "di gumagana" to "not working",
        "ayaw gumana" to "not working",
        "hindi nagwo-work" to "not working",
        "sira" to "not working",
        "hindi lumalabas" to "not showing",
        "di lumalabas" to "not showing",
        "ayaw lumabas" to "not showing",
        "walang lumalabas" to "nothing shows",
        "walang lumabas" to "nothing shows",
        "itim ang screen" to "screen is black",
        "itim na screen" to "screen is black",
        "walang signal" to "no signal",
        "walang larawan" to "no picture",
        "walang picture" to "no picture",
        "aling screen" to "which screen",
        "anong screen" to "which screen",
        "alin sa mga screen" to "which screen",
        "aling monitor" to "which monitor",
        "anong monitor" to "which monitor",
        "aling projector" to "which projector",
        "anong projector" to "which projector",

        // What is on screen.
        "likuran" to "background",
        "likod ng" to "background",
        "liriko" to "lyrics",
        "mga liriko" to "lyrics",
        "titik ng kanta" to "lyrics",
        "mga awit" to "mga awit",
        "awit ni solomon" to "awit ni solomon",
        "kanta" to "song",
        "kantahin" to "song",
        "mga kanta" to "songs",
        "awit" to "song",
        "awitin" to "song",
        "mga awitin" to "songs",
        "himno*" to "hymn",
        "papuri" to "worship",
        "pagsamba" to "worship",
        "bibliya" to "bible",
        "biblia" to "bible",
        "kasulatan" to "scripture",
        "salita ng diyos" to "scripture",
        "talata*" to "verse",
        "bersikulo" to "verse",
        "kabanata*" to "chapter",
        "laki ng font" to "font size",
        "laki ng letra" to "font size",
        "laki ng sulat" to "font size",
        "laki" to "size",
        "teksto" to "text",
        "sulat" to "writing",
        "letra" to "letters",
        "mga salita" to "words",
        "larawan*" to "picture",
        "mga larawan" to "pictures",
        "litrato*" to "photo",
        "imahe" to "image",
        "presentasyon*" to "presentation",
        "bidyo" to "video",
        "pelikula" to "movie",
        "tunog" to "audio",
        "pangalan at posisyon" to "name and title",
        "pangalan at titulo" to "name and title",
        "anunsyo*" to "announcement",
        "anunsiyo*" to "announcement",
        "mga anunsyo" to "announcements",
        "patalastas" to "announcement",
        "paalala" to "notice",
        "gumagalaw na teksto" to "ticker",
        "silid ng mga bata" to "kids room",
        "kuwarto ng mga bata" to "kids room",
        "bilang pababa" to "countdown",
        "orasan" to "clock",
        "oras ngayon" to "current time",
        "kasalukuyang oras" to "current time",
        "oras" to "time",
        "tala" to "notes",
        "mga tala" to "notes",
        "kord*" to "chord",
        "wika" to "language",
        "wikang" to "language",
        "lenggwahe" to "language",
        "lengguwahe" to "language",
        "dalawang wika" to "two languages",
        "ibang wika" to "another language",
        "ibang lenggwahe" to "another language",
        "pangalawang wika" to "second language",
        "ikalawang wika" to "second language",

        // Screens and outputs.
        "pangunahing screen" to "main screen",
        "buong screen" to "full screen",
        "pangalawang screen" to "second screen",
        "ikalawang screen" to "second screen",
        "iskrin" to "screen",
        "tabing" to "screen",
        "monitor sa entablado" to "stage monitor",
        "monitor ng entablado" to "stage monitor",
        "screen sa entablado" to "stage monitor",
        "entablado" to "stage",
        "plataporma" to "stage",
        "ayos ng zone" to "layout",
        "pagkakaayos" to "arrangement",
        "mensahe*" to "message",
        "ipadala" to "send",
        "magpadala" to "send",
        "i-send" to "send",
        "isend" to "send",
        "silip" to "preview",
        "ano ang nasa screen" to "what is on screen",
        "anong nasa screen" to "what is on screen",
        "telebisyon" to "tv",

        // Pages, tabs and tools.
        "mga setting" to "settings",
        "mga settings" to "settings",
        "mga opsyon" to "options",
        "opsyon" to "options",
        "gabay sa pagsisimula" to "getting started",
        "magsimula ulit" to "start over",
        "umpisa ulit" to "start over",
        "simula ulit" to "start over",
        "pindutan" to "keyboard",
        "aklatan ng kanta" to "song library",
        "aklatan ng mga awit" to "song library",
        "silid-aklatan" to "library",
        "aklatan" to "library",
        "diksyunaryo" to "dictionary",
        "diksiyonaryo" to "dictionary",
        "kamera" to "camera",
        "malayuan" to "remote",
        "telepono" to "phone",
        "selpon" to "phone",
        "cellphone" to "phone",

        // Services and planning.
        "daloy ng serbisyo" to "order of service",
        "daloy ng pagsamba" to "order of service",
        "pagkakasunod-sunod ng serbisyo" to "order of service",
        "programa" to "order of service",
        "iskedyul" to "schedule",
        "iskejul" to "schedule",
        "serbisyo" to "service",
        "pulong" to "meeting",
        "pagpupulong" to "meeting",
        "araw ng linggo" to "sunday",
        "linggo ng umaga" to "sunday",
        "kalendaryo" to "calendar",
        "tuwing linggo" to "every sunday",
        "bawat linggo" to "every week",
        "kada linggo" to "every week",
        "lingguhan" to "weekly",
        "buwanan" to "monthly",
        "ulitin" to "repeat",
        "paulit-ulit" to "repeat",

        // Many, all, both.
        "lahat" to "all",
        "lahat ng" to "all",
        "pareho" to "both",
        "parehas" to "both",
        "dalawa" to "both",
        "ilang" to "several",
        "marami" to "many",
        "sabay-sabay" to "at once",
        "sabay sabay" to "at once",
        "sabay" to "at once",
        "para sa serbisyong ito" to "this service",
        "ngayong araw" to "for today",
        "para ngayong araw" to "for today",
        "pansamantala" to "temporarily",
        "sa ngayon" to "for now",

        // Languages, by name.
        "ingles" to "english",
        "inggles" to "english",
        "espanyol" to "spanish",
        "kastila" to "spanish",
        "ruso" to "russian",
        "aleman" to "german",
        "pranses" to "french",
        "portuges" to "portuguese",
        "italyano" to "italian",
        "intsik" to "chinese",
        "tsino" to "chinese",
        "hapon" to "japanese",
        "nihongo" to "japanese",
        "koreano" to "korean",
        "arabe" to "arabic",
        "griyego" to "greek",
        "indones" to "indonesian",
        "pilipino" to "filipino",

        // Colors.
        "asul na madilim" to "navy",
        "mapusyaw na asul" to "light blue",
        "asul" to "blue",
        "bughaw" to "blue",
        "itim" to "black",
        "puti" to "white",
        "kulay abo" to "grey",
        "abuhin" to "grey",
        "pilak" to "silver",
        "pula" to "red",
        "kahel" to "orange",
        "dalandan" to "orange",
        "dilaw" to "yellow",
        "ginto" to "gold",
        "ginintuan" to "gold",
        "berde" to "green",
        "luntian" to "green",
        "lila" to "purple",
        "ube" to "purple",
        "lilak" to "violet",
        "rosas" to "pink",
        "kulay rosas" to "pink",
        "kayumanggi" to "brown",
        "tsokolate" to "brown",
        "krema" to "cream",
        "madilim" to "dark",
        "maliwanag" to "light",
        "mapusyaw" to "light",

        // Talking to the helper.
        "kumusta" to "hello",
        "kamusta" to "hello",
        "musta" to "hello",
        "magandang umaga" to "hello",
        "magandang hapon" to "hello",
        "magandang gabi" to "hello",
        "tulong" to "help",
        "tulungan mo ako" to "help",
        "tulungan" to "help",
        "pa-help" to "help",
        "ano ang kaya mong gawin" to "what can you do",
        "anong kaya mong gawin" to "what can you do",
        "anong kaya mo" to "what can you do",
        "ano kaya mo" to "what can you do",
        "ano ang ginagawa mo" to "what do you do",
        "sino ka" to "who are you",
        "sino ka ba" to "who are you",
        "salamat" to "thanks",
        "maraming salamat" to "thank you",
        "salamat po" to "thank you",
        "pakiusap" to "please",
        "paki" to "please",
        "po" to "please",
        "wik" to "wick",
    ),
)
