package org.churchpresenter.helper.intent.glossary

internal val TAMIL = Glossary(
    "ta",
    listOf(
        // Asking where, or how.
        "எங்கே" to "where",
        "எங்கு" to "where",
        "எங்க" to "where",
        "நான் எப்படி" to "how do i",
        "எப்படிச் செய்வது" to "how do i",
        "எப்படி செய்வது" to "how do i",
        "எப்படி செய்ய முடியும்" to "how can i",
        "எப்படி" to "how do i",
        "காணவில்லை" to "can't find",
        "கிடைக்கவில்லை" to "can't find",
        "கண்டுபிடிக்க முடியவில்லை" to "can't find",
        "எனக்குக் காட்டு" to "show me",
        "எனக்கு காட்டு" to "show me",
        "எனக்குக் காட்டுங்கள்" to "show me",
        "enge" to "where",
        "engey" to "where",
        "eppadi" to "how do i",
        "kanavillai" to "can't find",
        "kidaikkavillai" to "can't find",

        // Doing.
        "காட்டு*" to "show",
        "திரையில் காட்டு*" to "show",
        "காண்பி*" to "show",
        "திற" to "open",
        "திறக்க*" to "open",
        "திறங்கள்" to "open",
        "செல்லவும்" to "go to",
        "செல்" to "go to",
        "போ" to "go to",
        "தேடு*" to "find",
        "தேட*" to "find",
        "படிக்க*" to "read",
        "வாசி*" to "read",
        "ஆக்கு*" to "make",
        "உருவாக்கு*" to "create",
        "சேர்க்க*" to "add",
        "சேர்" to "add",
        "ஏற்றவும்" to "load",
        "லோட்" to "load",
        "இறக்குமதி*" to "import",
        "பதிவிறக்க*" to "download",
        "பதிவிறக்கு*" to "download",
        "டவுன்லோட்" to "download",
        "நிறுவு*" to "install",
        "நிறுவ*" to "install",
        "தேர்ந்தெடு*" to "choose",
        "அமைக்க*" to "set up",
        "இணைக்க*" to "connect",
        "இணை" to "connect",
        "ஒதுக்கு*" to "assign",
        "மறைக்க*" to "hide",
        "நிறுத்து*" to "stop",
        "நிறுத்த*" to "stop",
        "நீக்கு*" to "delete",
        "நீக்க*" to "delete",
        "அழி" to "clear",
        "அழிக்க*" to "clear",
        "கருப்புத் திரை" to "black out",
        "கருப்பு திரை" to "black out",
        "வெற்றுத் திரை" to "blank",
        "வெற்று திரை" to "blank",
        "செயல்தவிர்*" to "undo",
        "முன்பு போல" to "undo",
        "நேரலை*" to "go live",
        "இயக்கு*" to "turn on",
        "இயக்க*" to "turn on",
        "ஆன் செய்" to "turn on",
        "அணை*" to "turn off",
        "ஆஃப் செய்" to "turn off",
        "அடுத்த*" to "next",
        "முன்னோக்கி" to "forward",
        "முந்தைய*" to "previous",
        "பின்னோக்கி" to "back",
        "பின்னால்" to "back",
        "பின்செல்" to "back",
        "பெரிதாக்கு*" to "bigger",
        "பெரிதாக்க*" to "bigger",
        "அதிகரி*" to "increase",
        "பெரிய" to "bigger",
        "பெரிதாக" to "bigger",
        "சிறிதாக்கு*" to "smaller",
        "சிறிதாக்க*" to "smaller",
        "குறைக்க*" to "decrease",
        "குறை" to "decrease",
        "சிறிய" to "smaller",
        "சிறிதாக" to "smaller",
        "கன்வர்ட்" to "convert",
        "கன்வர்ட்டர்" to "converter",
        "இடமாற்று*" to "transfer",
        "திருத்து*" to "edit",
        "திருத்த*" to "edit",
        "எடிட்" to "edit",
        "மாற்று*" to "change",
        "மாற்ற*" to "change",
        "பெயர் மாற்று*" to "rename",
        "பெயரை மாற்று*" to "rename",
        "சரிசெய்*" to "fix",
        "சரி செய்*" to "fix",
        "ஒழுங்குபடுத்து*" to "organize",
        "ஒப்பிடு*" to "compare",
        "மொழிபெயர்க்க*" to "translate",
        "திட்டமிடு*" to "plan",
        "திட்டமிட*" to "plan",
        "தானியங்கு*" to "automatically",
        "அடையாளம் காண்*" to "identify",
        "எண்ணிடு*" to "number the",
        "kaattu" to "show",
        "kaatu" to "show",
        "thira" to "open",
        "thedu" to "find",
        "serkka" to "add",
        "maraikka" to "hide",
        "niruthu" to "stop",
        "neekku" to "delete",
        "adutha" to "next",
        "munthaiya" to "previous",
        "periyathu" to "bigger",
        "periya" to "bigger",
        "siriya" to "smaller",
        "maatru" to "change",
        "maathu" to "change",

        // Too small, too big, not working.
        "மிகச் சிறிய*" to "too small",
        "மிகவும் சிறிய*" to "too small",
        "ரொம்ப சின்ன*" to "too small",
        "படிக்கக் கடினம்" to "hard to read",
        "படிக்க கடினம்" to "hard to read",
        "படிக்க முடியவில்லை" to "hard to read",
        "தெளிவாக இல்லை" to "hard to read",
        "மிகப் பெரிய*" to "too big",
        "மிகவும் பெரிய*" to "too big",
        "ரொம்ப பெரிய*" to "too big",
        "பொருந்தவில்லை" to "doesn't fit",
        "வேலை செய்யவில்லை" to "not working",
        "இயங்கவில்லை" to "not working",
        "தெரியவில்லை" to "not showing",
        "காட்டவில்லை" to "not showing",
        "ஒன்றும் தெரியவில்லை" to "nothing shows",
        "எதுவும் தெரியவில்லை" to "nothing shows",
        "திரை கருப்பாக உள்ளது" to "screen is black",
        "திரை கருப்பாக இருக்கிறது" to "screen is black",
        "சிக்னல் இல்லை" to "no signal",
        "படம் இல்லை" to "no picture",
        "எந்தத் திரை" to "which screen",
        "எந்த திரை" to "which screen",
        "எந்த மானிட்டர்" to "which monitor",
        "எந்த புரொஜெக்டர்" to "which projector",
        "romba chinna" to "too small",
        "romba periya" to "too big",
        "velai seyyavillai" to "not working",

        // What is on screen.
        "பின்னணி*" to "background",
        "பேக்கிரவுண்ட்*" to "background",
        "பாடல் வரிகள்" to "lyrics",
        "பாடல்வரி*" to "lyrics",
        "பாடல்கள்" to "songs",
        "பாடல*" to "song",
        "கீர்த்தனை*" to "hymn",
        "ஆராதனை*" to "worship",
        "துதி*" to "worship",
        "வேதாகம*" to "bible",
        "பைபிள்*" to "bible",
        "வேதம்" to "scripture",
        "திருமறை*" to "bible",
        "வசன*" to "verse",
        "அதிகார*" to "chapter",
        "எழுத்துரு*" to "font",
        "ஃபான்ட்*" to "font",
        "எழுத்து*" to "letters",
        "அளவு*" to "size",
        "சைஸ்" to "size",
        "உரை*" to "text",
        "வார்த்தை*" to "words",
        "ஸ்லைடு ஷோ" to "slideshow",
        "ஸ்லைடுஷோ" to "slideshow",
        "ஸ்லைடு*" to "slide",
        "ஸ்லைட்*" to "slide",
        "புகைப்பட*" to "photo",
        "போட்டோ*" to "photo",
        "படங்கள்" to "picture",
        "படம்" to "picture",
        "படத்*" to "picture",
        "ஆல்பம்*" to "album",
        "விளக்கக்காட்சி*" to "presentation",
        "பவர்பாயிண்ட்" to "powerpoint",
        "காணொளி*" to "video",
        "வீடியோ*" to "video",
        "திரைப்பட*" to "movie",
        "கிளிப்*" to "clip",
        "ஊடக*" to "media",
        "மீடியா" to "media",
        "ஆடியோ" to "audio",
        "ஒலி" to "audio",
        "லோயர் தேர்ட்" to "lower third",
        "கீழ் மூன்றில் ஒன்று" to "lower third",
        "பெயர் பட்டை" to "name strap",
        "பெயரும் பதவியும்" to "name and title",
        "அறிவிப்பு*" to "announcement",
        "நகரும் உரை" to "ticker",
        "குழந்தைகள் அறை" to "kids room",
        "கவுண்ட்டவுன்" to "countdown",
        "கவுண்டவுன்" to "countdown",
        "பின்னோக்கு எண்ணிக்கை" to "countdown",
        "டைமர்*" to "timer",
        "நேரங்காட்டி*" to "timer",
        "ஸ்டாப்வாட்ச்" to "stopwatch",
        "கடிகார*" to "clock",
        "தற்போதைய நேரம்" to "current time",
        "இப்போதைய நேரம்" to "current time",
        "நேரம்" to "time",
        "குறிப்பு*" to "notes",
        "கோர்ட்*" to "chord",
        "மொழிபெயர்ப்பு*" to "translation",
        "மொழி*" to "language",
        "இருமொழி*" to "bilingual",
        "வேறு மொழி*" to "another language",
        "மற்றொரு மொழி*" to "another language",
        "இரண்டாவது மொழி*" to "second language",
        "இரண்டு மொழி*" to "two languages",
        "paadal" to "song",
        "padal" to "song",
        "paadalgal" to "songs",
        "padalgal" to "songs",
        "pinnani" to "background",
        "vedhagamam" to "bible",
        "vedagamam" to "bible",
        "vasanam" to "verse",
        "athikaram" to "chapter",
        "aaradhanai" to "worship",
        "arivippu" to "announcement",
        "mozhi" to "language",
        "neram" to "time",

        // Screens and outputs.
        "முதன்மைத் திரை" to "main screen",
        "முதன்மை திரை" to "main screen",
        "முக்கிய திரை" to "main screen",
        "முழுத் திரை" to "full screen",
        "முழு திரை" to "full screen",
        "முழுத்திரை*" to "fullscreen",
        "இரண்டாவது திரை" to "second screen",
        "திரை*" to "screen",
        "ஸ்கிரீன்*" to "screen",
        "புரொஜெக்டர்*" to "projector",
        "ப்ரொஜெக்டர்*" to "projector",
        "மேடை மானிட்டர்" to "stage monitor",
        "மேடைத் திரை" to "stage monitor",
        "மேடை திரை" to "stage monitor",
        "மானிட்டர்*" to "monitor",
        "டிஸ்ப்ளே" to "display",
        "காட்சித்திரை*" to "display",
        "வெளியீட்டு சாளரம்" to "output window",
        "வெளியீடு*" to "output",
        "வெளியீட்*" to "output",
        "அவுட்புட்*" to "output",
        "மேடை*" to "stage",
        "மண்டல*" to "zone",
        "தளவமைப்பு*" to "layout",
        "லேஅவுட்" to "layout",
        "செய்தி*" to "message",
        "அனுப்பு*" to "send",
        "அனுப்ப*" to "send",
        "முன்னோட்ட*" to "preview",
        "முன்னோட்டம்" to "preview",
        "திரையில் என்ன உள்ளது" to "what is on screen",
        "சுயவிவர*" to "profile",
        "ப்ரொஃபைல்*" to "profile",
        "ஒளிபரப்பு*" to "stream",
        "ஸ்ட்ரீம்*" to "stream",
        "தொலைக்காட்சி*" to "tv",
        "டிவி" to "tv",
        "thirai" to "screen",
        "medai" to "stage",

        // Pages, tabs and tools.
        "அமைப்புகள்" to "settings",
        "அமைப்பு*" to "settings",
        "விருப்பங்கள்" to "options",
        "அமைவு வழிகாட்டி" to "setup wizard",
        "மீண்டும் தொடங்கு*" to "start over",
        "குறுக்குவழி*" to "shortcut",
        "ஷார்ட்கட்*" to "shortcut",
        "ஹாட்கீ*" to "hotkeys",
        "விசைப்பலகை*" to "keyboard",
        "கீபோர்டு" to "keyboard",
        "தாவல்*" to "tab",
        "டேப்" to "tab",
        "பாடல் நூலகம்" to "song library",
        "நூலக*" to "library",
        "இணையதள*" to "website",
        "வலைத்தள*" to "website",
        "இணைய*" to "web",
        "உலாவி*" to "browser",
        "அகராதி*" to "dictionary",
        "ஸ்ட்ராங்" to "strong",
        "கேமரா*" to "camera",
        "கேமராவ*" to "camera",
        "கித்தான்" to "canvas",
        "சேவையக*" to "server",
        "சர்வர்*" to "server",
        "தொலை இயக்கி" to "remote",
        "ரிமோட்" to "remote",
        "தொலைபேசி*" to "phone",
        "கைபேசி*" to "phone",
        "போன்" to "phone",
        "மொபைல்" to "phone",
        "டேப்லெட்" to "tablet",
        "ஒருங்கிணைப்பு*" to "integrations",

        // Services and planning.
        "ஆராதனை வரிசை" to "order of service",
        "ஆராதனை ஒழுங்கு" to "order of service",
        "நிகழ்ச்சி நிரல்" to "order of service",
        "சேவை*" to "service",
        "கூட்டம்" to "meeting",
        "கூட்டத்*" to "meeting",
        "சபை கூடுகை" to "meeting",
        "ஞாயிறு*" to "sunday",
        "ஞாயிற்று*" to "sunday",
        "நாட்காட்டி*" to "calendar",
        "காலண்டர்*" to "calendar",
        "அட்டவணை*" to "schedule",
        "பிளேலிஸ்ட்" to "playlist",
        "ஒவ்வொரு ஞாயிறு*" to "every sunday",
        "ஒவ்வொரு ஞாயிற்று*" to "every sunday",
        "ஒவ்வொரு வாரம்*" to "every week",
        "வாராந்திர*" to "weekly",
        "மாதாந்திர*" to "monthly",
        "திரும்பச் செய்" to "repeat",
        "மீண்டும் செய்" to "repeat",
        "வார்ப்புரு*" to "template",
        "டெம்ப்ளேட்*" to "template",
        "gnayiru" to "sunday",
        "nyayiru" to "sunday",

        // Many, all, both.
        "எல்லா" to "all",
        "எல்லாம்" to "all",
        "எல்லாவற்றையும்" to "all",
        "அனைத்து*" to "all",
        "எல்லா இடத்திலும்" to "everything",
        "இரண்டும்" to "both",
        "இரண்டையும்" to "both",
        "இரண்டிலும்" to "both",
        "பல" to "several",
        "சில" to "several",
        "நிறைய" to "many",
        "ஒரே நேரத்தில்" to "at once",
        "இந்த ஆராதனைக்கு" to "this service",
        "இன்றைக்கு" to "for today",
        "இன்று மட்டும்" to "for today",
        "தற்காலிக*" to "temporarily",
        "ellam" to "all",
        "ellaa" to "all",
        "irandum" to "both",

        // Languages, by name.
        "தமிழ்*" to "tamil",
        "தமிழில்" to "tamil",
        "ஆங்கில*" to "english",
        "இந்தி" to "hindi",
        "ஹிந்தி*" to "hindi",
        "நேபாள*" to "nepali",
        "ரஷ்ய*" to "russian",
        "உக்ரைனிய*" to "ukrainian",
        "ஸ்பானிஷ்*" to "spanish",
        "ஜெர்மன்*" to "german",
        "பிரெஞ்சு*" to "french",
        "போர்த்துகீசிய*" to "portuguese",
        "சீன*" to "chinese",
        "ஜப்பானிய*" to "japanese",
        "கொரிய*" to "korean",
        "அரபு*" to "arabic",
        "அரபி*" to "arabic",
        "பாரசீக*" to "persian",
        "எபிரேய*" to "hebrew",
        "கிரேக்க*" to "greek",
        "லத்தீன்*" to "latin",
        "thamizh" to "tamil",
        "tamizh" to "tamil",
        "aangilam" to "english",

        // Colors.
        "அடர் நீல*" to "dark blue",
        "கரு நீல*" to "navy",
        "கருநீல*" to "navy",
        "வெளிர் நீல*" to "light blue",
        "வான நீல*" to "sky",
        "அடர் பச்சை*" to "dark green",
        "வெளிர் பச்சை*" to "light green",
        "அடர் சிவப்பு*" to "dark red",
        "நீல*" to "blue",
        "கருப்பு*" to "black",
        "கறுப்பு*" to "black",
        "வெள்ளை*" to "white",
        "சாம்பல்*" to "grey",
        "வெள்ளி நிற*" to "silver",
        "சிவப்பு*" to "red",
        "மெரூன்" to "maroon",
        "ஆரஞ்சு*" to "orange",
        "செம்மஞ்சள்*" to "orange",
        "மஞ்சள்*" to "yellow",
        "தங்க நிற*" to "gold",
        "தங்கநிற*" to "gold",
        "பச்சை*" to "green",
        "டர்கைஸ்" to "turquoise",
        "ஊதா*" to "purple",
        "இளஞ்சிவப்பு*" to "pink",
        "ரோஸ்" to "pink",
        "பழுப்பு*" to "brown",
        "கிரீம்" to "cream",
        "அடர்*" to "dark",
        "வெளிர்*" to "light",
        "neelam" to "blue",
        "neela" to "blue",
        "karuppu" to "black",
        "vellai" to "white",
        "sivappu" to "red",
        "manjal" to "yellow",
        "pachai" to "green",
        "oodha" to "purple",

        // Talking to the helper.
        "வணக்கம்" to "hello",
        "ஹலோ" to "hello",
        "உதவி*" to "help",
        "நீ என்ன செய்ய முடியும்" to "what can you do",
        "உன்னால் என்ன செய்ய முடியும்" to "what can you do",
        "உங்களால் என்ன செய்ய முடியும்" to "what can you do",
        "நீ யார்" to "who are you",
        "நீங்கள் யார்" to "who are you",
        "நன்றி" to "thanks",
        "மிக்க நன்றி" to "thank you",
        "தயவுசெய்து" to "please",
        "தயவு செய்து" to "please",
        "விக்" to "wick",
        "vanakkam" to "hello",
        "udhavi" to "help",
        "uthavi" to "help",
        "nandri" to "thanks",
        "romba nandri" to "thank you",
        "dhayavu seithu" to "please",

        // Newer requests.
        "தேடுவது" to "search",
        "தேடல்*" to "search",
        "சர்ச்" to "search",
        "வேதாகமத்தில் தேடு*" to "search the bible",
        "பைபிளில் தேடு*" to "search the bible",
        "எப்படி*" to "how do i",
        "பாடலைத் தேடு*" to "find a song",
        "பாடலை தேடு*" to "find a song",
        "வசனத்தைத் தேடு*" to "find a verse",
        "வசனத்தை தேடு*" to "find a verse",
        "பாடல் எண்" to "song number",
        "எண்ணால்" to "by number",
        "எண் மூலம்" to "by number",
        "தலைப்பால்" to "by title",
        "தலைப்பு மூலம்" to "by title",
        "எண்" to "number",
        "பிடித்த*" to "favorite",
        "விருப்பமான*" to "favorite",
        "ஃபேவரிட்*" to "favorite",
        "இந்தப் பாடல*" to "this song",
        "இந்த பாடல*" to "this song",
        "ஒவ்வொரு பாடல*" to "each song",
        "தனிப் பின்னணி*" to "own background",
        "தனி பின்னணி*" to "own background",
        "சொந்தப் பின்னணி*" to "own background",
        "சொந்த பின்னணி*" to "own background",
        "பல வசன*" to "several verses",
        "சில வசன*" to "a few verses",
        "ஒன்றுக்கு மேற்பட்ட வசன*" to "more than one verse",
        "வசன வரம்பு" to "verse range",
        "இப்போது என்ன காட்டினோம்" to "what did we just show",
        "இப்போ என்ன காட்டினோம்" to "what did we just show",
        "என்ன காட்டினோம்" to "what did we show",
        "வரலாறு" to "history",
        "சமீபத்திய வசன*" to "recent verses",
        "தொடர்புடைய வசன*" to "related verses",
        "குறுக்கு குறிப்பு*" to "cross references",
        "இணையான பகுதி*" to "parallel passages",
        "இணை வசன*" to "parallel passages",
        "வலைப்பக்க*" to "web page",
        "இணையப் பக்க*" to "web page",
        "இணைய பக்க*" to "web page",
        "இணைப்பு முகவரி" to "url",
        "பிளானிங் சென்டர்" to "planning center",
        "பிளானிங் செண்டர்" to "planning center",
        "புள்ளிவிவர*" to "statistics",
        "எத்தனை முறை" to "how many times",
        "பாடல் அறிக்கை" to "song report",
        "பாடல் பயன்பாடு" to "song usage",
        "என் தொலைபேசியிலிருந்து" to "from my phone",
        "என் கைபேசியிலிருந்து" to "from my phone",
        "என் போனிலிருந்து" to "from my phone",
        "என் மொபைலிலிருந்து" to "from my phone",
        "தொலைபேசியிலிருந்து" to "from the phone",
        "கைபேசியிலிருந்து" to "from the phone",
        "போனிலிருந்து" to "from the phone",
        "மொபைலிலிருந்து" to "from the phone",
        "என் தொலைபேசியில்" to "on my phone",
        "என் போனில்" to "on my phone",
        "தொலை கட்டுப்பாடு" to "remote control",
        "ரிமோட் கண்ட்ரோல்" to "remote control",
        "qr குறியீடு" to "qr code",
        "க்யூஆர் குறியீடு" to "qr code",
        "க்யூஆர் கோடு" to "qr code",
        "நிமிட*" to "minutes",
        "நிமிஷ*" to "minutes",
        "பின்னோக்கி எண்ண*" to "countdown",
        "அறிவிப்பு:" to "announce",
        "அறிவி" to "announce",
        "அறிவி:" to "announce",
        "அறிவிக்கவும்" to "announce",
        "அறிவிக்கவும்:" to "announce",
        "உருப்படி*" to "item",
        "ஐட்டம்*" to "item",
        "அட்டவணையில்" to "in the schedule",
        "அட்டவணைக்கு" to "to the schedule",
        "இப்போது திரையில் என்ன" to "what's live",
        "இப்போ திரையில் என்ன" to "what's live",
        "திரையில் என்ன" to "what is on screen",
        "நேரலையில் என்ன" to "what's live",
        "இது எந்தப் பதிப்பு" to "what version is this",
        "இது எந்த பதிப்பு" to "what version is this",
        "எந்தப் பதிப்பு" to "which version",
        "எந்த பதிப்பு" to "which version",
        "பதிப்பு*" to "version",
        "சமீபத்திய பதிப்பு" to "latest version",
        "புதுப்பிப்பு* சரிபார்*" to "check for updates",
        "புதுப்பிப்பு உள்ளதா" to "is there an update",
        "புதுப்பிப்புகள் உள்ளதா" to "is there an update",
        "கட்டளை*" to "commands",
        "கட்டளைகளின் பட்டியல்" to "list of commands",
        "கட்டளைப் பட்டியல்" to "list of commands",
        "நான் என்ன சொல்லலாம்" to "what can i say",
        "நான் என்ன தட்டச்சு செய்யலாம்" to "what can i type",
        "உனக்கு என்ன புரியும்" to "what do you understand",
        "உங்களுக்கு என்ன புரியும்" to "what do you understand",
        "மொத்தமாகத் திருத்து*" to "batch edit",
        "மொத்தமாக திருத்து*" to "batch edit",
        "மறை" to "hide",
        "இப்போதைக்கு" to "for now",
        "சிவப்பா*" to "red",
        "எழுத்தை*" to "text",
        "புரொஜெக்டர*" to "projector",
        "அமை" to "set up",
        "அமைப்பது" to "set up",
        "சேர்ப்ப*" to "add",
        "மொழிபெயர்ப்ப*" to "translation",
        "நாண்*" to "chord",
        "ஸ்லைடுஷோ*" to "slideshow",
        "கீழ்ப்பட்டை*" to "lower third",

        // Look requests.
        "பாடல் வரிகளை மாற்று*" to "change song lyrics",
        "பாடல் வரிகளைத் திருத்து*" to "edit song lyrics",
        "பாடல் வரிகளை திருத்து*" to "edit song lyrics",
        "வரிகளை மாற்று*" to "change the lyrics",
        "வரிகளைத் திருத்து*" to "edit the lyrics",
        "வரிகளை திருத்து*" to "edit the lyrics",
        "வரிகளைச் சரிசெய்*" to "fix the lyrics",
        "பாடலைத் திருத்து*" to "edit the song",
        "பாடலை திருத்து*" to "edit the song",
        "எழுத்துப்பிழை*" to "typo",
        "பாடல் வரிக*" to "lyrics",
        "வரிக*" to "lyrics",
        "பாடல் முடிவுக் குறி*" to "end of song marker",
        "பாடல் முடிவு குறி*" to "end of song marker",
        "முடிவுக் குறி*" to "end marker",
        "முடிவு குறி*" to "end marker",
        "பாடல் முடிவ*" to "end of song",
        "பாடல் தலைப்பை*" to "song title",
        "பாடல் தலைப்பின்*" to "song title",
        "தலைப்பு" to "title",
        "தலைப்பை*" to "title",
        "தலைப்பின்*" to "title",
        "வேதாகமக் குறிப்*" to "bible reference",
        "வேதாகம குறிப்*" to "bible reference",
        "வசனக் குறிப்*" to "verse reference",
        "வசன குறிப்*" to "verse reference",
        "தடிம*" to "bold",
        "சாய்வு*" to "italic",
        "சாய்வாக*" to "italic",
        "அடிக்கோடு*" to "underline",
        "அடிக்கோடிட*" to "underline",
        "வெளிக்கோடு*" to "outline",
        "நிழல்*" to "shadow",
        "ஓரம்" to "margins",
        "ஓரங்க*" to "margins",
        "ஓர இடைவெளி*" to "margins",
        "மார்ஜின்*" to "margins",
        "விளிம்பு*" to "edges",
        "மேலே" to "top",
        "மேல்பகுதி*" to "top",
        "கீழே" to "bottom",
        "நடுவில்" to "middle",
        "நடுவே" to "middle",
        "மைய*" to "center",
        "இடது*" to "left",
        "வலது*" to "right",
        "சீரமை*" to "align",
        "இருப்பிட*" to "position",
        "நகர்த்து*" to "move",
        "தட்டச்சுரு*" to "typeface",
        "தோற்ற*" to "look",
        "பாணி*" to "style",
        "வடிவமை*" to "design",
        "நிறம்" to "color",
        "நிறத்*" to "color",

        // The help table's own examples.
        "pdf-ஐ" to "a pdf",
        "பெற்றோர*" to "parents",
        "குழந்தைகள் அறை*" to "nursery",
    ),
)
