package org.churchpresenter.helper.intent.glossary

internal val THAI = Glossary(
    "th",
    listOf(
        // Asking where, or how.
        "ที่ไหน" to "where",
        "อยู่ไหน" to "where",
        "ตรงไหน" to "where",
        "ทำยังไง" to "how do i",
        "ทำอย่างไร" to "how do i",
        "ได้อย่างไร" to "how can i",
        "ได้ยังไง" to "how can i",
        "ยังไง" to "how do i",
        "อย่างไร" to "how do i",
        "วิธี" to "how to",
        "หาไม่เจอ" to "can't find",
        "หาไม่พบ" to "can't find",
        "ไม่เจอ" to "can't find",
        "ไม่พบ" to "can't find",
        "แสดงให้ดู" to "show me",
        "ให้ดู" to "show me",

        // Doing.
        "แสดงบนจอ" to "show",
        "แสดง" to "show",
        "โชว์" to "show",
        "เปิดใช้" to "turn on",
        "เปิด" to "open",
        "ไปที่" to "go to",
        "ไปยัง" to "go to",
        "สลับไป" to "switch to",
        "สลับเป็น" to "switch to",
        "ค้นหา" to "find",
        "อ่าน" to "read",
        "ทำให้จอดำ" to "black out",
        "ทำให้" to "make",
        "สร้าง" to "create",
        "เพิ่มขนาด" to "increase",
        "เพิ่ม" to "add",
        "อัปโหลด" to "upload",
        "ดาวน์โหลด" to "download",
        "โหลด" to "load",
        "นำเข้า" to "import",
        "ติดตั้ง" to "install",
        "เลือก" to "choose",
        "ตั้งค่า" to "set up",
        "เชื่อมต่อ" to "connect",
        "กำหนด" to "assign",
        "ซ่อน" to "hide",
        "เอาออก" to "remove",
        "หยุดชั่วคราว" to "pause",
        "หยุด" to "stop",
        "ลบ" to "delete",
        "ล้างจอ" to "clear screen",
        "ล้าง" to "clear",
        "ปิดจอ" to "black out",
        "จอว่าง" to "blank",
        "เลิกทำ" to "undo",
        "ย้อนกลับ" to "undo",
        "ยกเลิก" to "undo",
        "ขึ้นจอ" to "go live",
        "ออกอากาศ" to "go live",
        "ปิด" to "turn off",
        "สลับ" to "toggle",
        "ถัดไป" to "next",
        "ต่อไป" to "next",
        "ข้างหน้า" to "forward",
        "ก่อนหน้า" to "previous",
        "ย้อน" to "back",
        "กลับ" to "back",
        "ใหญ่ขึ้น" to "bigger",
        "ขยาย" to "bigger",
        "ลดขนาด" to "decrease",
        "เล็กลง" to "smaller",
        "ตัวแปลง" to "converter",
        "แปลงไฟล์" to "convert",
        "แปลง" to "convert",
        "โอนย้าย" to "transfer",
        "ย้าย" to "transfer",
        "แก้ไข" to "edit",
        "เปลี่ยนชื่อ" to "rename",
        "เปลี่ยน" to "change",
        "แก้" to "fix",
        "จัดระเบียบ" to "organize",
        "จัดการ" to "organize",
        "เปรียบเทียบ" to "compare",
        "แปล" to "translate",
        "วางแผน" to "plan",
        "อัตโนมัติ" to "automatically",
        "ระบุ" to "identify",
        "ใส่หมายเลข" to "number the",

        // Too small, too big, not working.
        "เล็กเกินไป" to "too small",
        "เล็กไป" to "too small",
        "อ่านยาก" to "hard to read",
        "อ่านไม่ออก" to "can't read",
        "มองไม่เห็น" to "hard to read",
        "มองไม่ชัด" to "hard to read",
        "ใหญ่เกินไป" to "too big",
        "ใหญ่ไป" to "too big",
        "ไม่พอดี" to "doesn't fit",
        "ล้นจอ" to "doesn't fit",
        "ไม่ทำงาน" to "not working",
        "ใช้ไม่ได้" to "not working",
        "ไม่แสดง" to "not showing",
        "ไม่ขึ้น" to "not showing",
        "ไม่มีอะไร" to "nothing shows",
        "จอดำ" to "screen is black",
        "จอมืด" to "screen is black",
        "ไม่มีสัญญาณ" to "no signal",
        "ไม่มีภาพ" to "no picture",
        "จอไหน" to "which screen",
        "มอนิเตอร์ไหน" to "which monitor",
        "โปรเจคเตอร์ไหน" to "which projector",

        // Songs, by the words around them.
        "เนื้อเพลง" to "lyrics",
        "บทเพลง" to "song",
        "เพลงนมัสการ" to "worship song",
        "เพลงสรรเสริญ" to "hymn",
        "เพลงนี้" to "this song",
        "เพลงถัดไป" to "next song",
        "เพลงต่อไป" to "next song",
        "เพลงก่อนหน้า" to "previous song",
        "เพลงทั้งหมด" to "all songs",
        "เพลงใหม่" to "new song",
        "เพลงภาษา" to "song language",
        "เพลงและ" to "song and",
        "เพลงกับ" to "song and",
        "แท็บเพลง" to "songs tab",
        "คลังเพลง" to "song library",
        "เพิ่มเพลง" to "add song",
        "สร้างเพลง" to "create song",
        "เขียนเพลง" to "write a song",
        "แสดงเพลง" to "show song",
        "เปิดเพลง" to "open song",
        "ค้นหาเพลง" to "find song",
        "หาเพลง" to "find song",
        "แก้ไขเพลง" to "edit song",
        "แปลเพลง" to "translate song",
        "พื้นหลังเพลง" to "song background",
        "ตัวอักษรเพลง" to "song font",
        "ฟอนต์เพลง" to "song font",
        "คอร์ดเพลง" to "song chord",
        "ของเพลง" to "song",
        "ในเพลง" to "in song",
        "หลายเพลง" to "multiple songs",
        "ทุกเพลง" to "every song",

        // What is on screen.
        "พื้นหลัง" to "background",
        "ฉากหลัง" to "backdrop",
        "แบ็คกราวด์" to "background",
        "ข้อพระคัมภีร์" to "verse",
        "พระคัมภีร์" to "bible",
        "ไบเบิล" to "bible",
        "พระวจนะ" to "scripture",
        "นมัสการ" to "worship",
        "ตัวอักษร" to "font",
        "แบบอักษร" to "font",
        "ฟอนต์" to "font",
        "ตัวหนังสือ" to "text",
        "ขนาด" to "size",
        "ข้อความวิ่ง" to "ticker",
        "ข้อความ" to "text",
        "สไลด์โชว์" to "slideshow",
        "สไลด์" to "slide",
        "รูปภาพ" to "picture",
        "รูปถ่าย" to "photo",
        "ภาพถ่าย" to "photo",
        "ภาพยนตร์" to "movie",
        "การฉายภาพ" to "projection",
        "ภาพ" to "picture",
        "อัลบั้ม" to "album",
        "งานนำเสนอ" to "presentation",
        "พาวเวอร์พอยต์" to "powerpoint",
        "วิดีโอ" to "video",
        "วีดีโอ" to "video",
        "วีดิโอ" to "video",
        "หนัง" to "movie",
        "คลิป" to "clip",
        "สื่อ" to "media",
        "เสียง" to "audio",
        "แถบล่าง" to "lower third",
        "ชื่อและตำแหน่ง" to "name and title",
        "ประกาศ" to "announcement",
        "ตัววิ่ง" to "ticker",
        "ห้องเด็ก" to "kids room",
        "นับถอยหลัง" to "countdown",
        "นาฬิกาจับเวลา" to "stopwatch",
        "ตัวจับเวลา" to "timer",
        "จับเวลา" to "timer",
        "นาฬิกา" to "clock",
        "เวลาปัจจุบัน" to "current time",
        "เวลา" to "time",
        "โน้ต" to "notes",
        "คอร์ด" to "chord",
        "คำแปล" to "translation",
        "สองภาษา" to "bilingual",
        "ภาษาอื่น" to "another language",
        "ภาษาที่สอง" to "second language",
        "ภาษา" to "language",

        // Screens and outputs.
        "เต็มจอ" to "full screen",
        "จอหลัก" to "main screen",
        "จอที่สอง" to "second screen",
        "จอสอง" to "second screen",
        "จอบนเวที" to "stage monitor",
        "จอเวที" to "stage monitor",
        "มอนิเตอร์เวที" to "stage monitor",
        "หน้าจอ" to "screen",
        "จอภาพ" to "display",
        "จอ" to "screen",
        "โปรเจคเตอร์" to "projector",
        "โปรเจกเตอร์" to "projector",
        "เครื่องฉาย" to "projector",
        "มอนิเตอร์" to "monitor",
        "ดิสเพลย์" to "display",
        "หน้าต่างเอาต์พุต" to "output window",
        "เอาต์พุต" to "output",
        "เวที" to "stage",
        "โซน" to "zone",
        "เลย์เอาต์" to "layout",
        "การจัดวาง" to "arrangement",
        "ส่งข้อความ" to "send message",
        "ส่ง" to "send",
        "ดูตัวอย่าง" to "preview",
        "ตัวอย่าง" to "preview",
        "พรีวิว" to "preview",
        "อะไรอยู่บนจอ" to "what is on screen",
        "โปรไฟล์" to "profile",
        "ถ่ายทอดสด" to "stream",
        "สตรีม" to "stream",
        "ทีวี" to "tv",

        // Pages, tabs and tools.
        "การตั้งค่า" to "settings",
        "หน้าตั้งค่า" to "settings",
        "ตัวเลือก" to "options",
        "ตัวช่วยตั้งค่า" to "setup wizard",
        "เริ่มต้นใช้งาน" to "setup wizard",
        "เริ่มใหม่" to "start over",
        "แป้นลัด" to "shortcut",
        "คีย์ลัด" to "shortcut",
        "ปุ่มลัด" to "shortcut",
        "คีย์บอร์ด" to "keyboard",
        "แป้นพิมพ์" to "keyboard",
        "แท็บเล็ต" to "tablet",
        "แท็บ" to "tab",
        "คลัง" to "library",
        "เว็บไซต์" to "website",
        "เว็บ" to "web",
        "เบราว์เซอร์" to "browser",
        "พจนานุกรม" to "dictionary",
        "สตรอง" to "strong",
        "กล้อง" to "camera",
        "ผืนผ้าใบ" to "canvas",
        "แคนวาส" to "canvas",
        "เซิร์ฟเวอร์" to "server",
        "รีโมท" to "remote",
        "รีโมต" to "remote",
        "โทรศัพท์" to "phone",
        "มือถือ" to "phone",
        "ไอแพด" to "ipad",
        "คอมแพเนียน" to "companion",

        // Services and planning.
        "ลำดับการนมัสการ" to "order of service",
        "ลำดับนมัสการ" to "order of service",
        "กำหนดการ" to "order of service",
        "การนมัสการนี้" to "this service",
        "การนมัสการ" to "service",
        "รายการ" to "schedule",
        "ประชุม" to "meeting",
        "ทุกวันอาทิตย์" to "every sunday",
        "วันอาทิตย์" to "sunday",
        "ปฏิทิน" to "calendar",
        "เพลย์ลิสต์" to "playlist",
        "ทุกสัปดาห์" to "every week",
        "ทุกอาทิตย์" to "every week",
        "รายสัปดาห์" to "weekly",
        "รายเดือน" to "monthly",
        "ทุกเดือน" to "monthly",
        "ทำซ้ำ" to "repeat",
        "ซ้ำ" to "repeat",
        "แม่แบบ" to "template",
        "เทมเพลต" to "template",

        // Many, all, both.
        "ทั้งหมด" to "all",
        "ทุกอย่าง" to "everything",
        "ทั้งสอง" to "both",
        "ทั้งคู่" to "both",
        "ทุก" to "every",
        "หลาย" to "several",
        "เยอะ" to "many",
        "พร้อมกัน" to "at once",
        "วันนี้" to "for today",
        "ชั่วคราว" to "temporarily",

        // Languages, by name.
        "ภาษาไทย" to "thai",
        "ไทย" to "thai",
        "อังกฤษ" to "english",
        "สเปน" to "spanish",
        "รัสเซีย" to "russian",
        "ยูเครน" to "ukrainian",
        "เบลารุส" to "belarusian",
        "โปแลนด์" to "polish",
        "เยอรมัน" to "german",
        "ฝรั่งเศส" to "french",
        "โปรตุเกส" to "portuguese",
        "อิตาลี" to "italian",
        "ดัตช์" to "dutch",
        "โรมาเนีย" to "romanian",
        "เช็ก" to "czech",
        "สโลวัก" to "slovak",
        "โครเอเชีย" to "croatian",
        "เซอร์เบีย" to "serbian",
        "บัลแกเรีย" to "bulgarian",
        "ฮังการี" to "hungarian",
        "กรีก" to "greek",
        "ตุรกี" to "turkish",
        "อาหรับ" to "arabic",
        "เปอร์เซีย" to "persian",
        "ภาษาฮีบรู" to "hebrew",
        "ฮินดี" to "hindi",
        "เนปาล" to "nepali",
        "ทมิฬ" to "tamil",
        "ลาว" to "lao",
        "จีนกลาง" to "mandarin",
        "กวางตุ้ง" to "cantonese",
        "จีน" to "chinese",
        "ญี่ปุ่น" to "japanese",
        "เกาหลี" to "korean",
        "เวียดนาม" to "vietnamese",
        "อินโดนีเซีย" to "indonesian",
        "มาเลย์" to "malay",
        "ตากาล็อก" to "tagalog",
        "ฟิลิปปินส์" to "filipino",
        "ฟิลิปิโน" to "filipino",
        "สวาฮีลี" to "swahili",
        "คาซัค" to "kazakh",
        "อุซเบก" to "uzbek",
        "เอสโตเนีย" to "estonian",
        "ลัตเวีย" to "latvian",
        "ลิทัวเนีย" to "lithuanian",
        "ฟินแลนด์" to "finnish",
        "สวีเดน" to "swedish",
        "นอร์เวย์" to "norwegian",
        "เดนมาร์ก" to "danish",
        "อาร์เมเนีย" to "armenian",
        "จอร์เจีย" to "georgian",
        "มอลโดวา" to "moldovan",
        "ละติน" to "latin",

        // Colors.
        "สีกรมท่า" to "navy",
        "สีน้ำเงินเข้ม" to "navy",
        "น้ำเงินเข้ม" to "navy",
        "สีฟ้าอ่อน" to "light blue",
        "ฟ้าอ่อน" to "light blue",
        "สีฟ้า" to "sky",
        "สีน้ำเงิน" to "blue",
        "น้ำเงิน" to "blue",
        "สีดำ" to "black",
        "สีขาว" to "white",
        "ขาว" to "white",
        "เทาเข้ม" to "dark grey",
        "เทาอ่อน" to "light grey",
        "สีเทา" to "grey",
        "สีเงิน" to "silver",
        "แดงเข้ม" to "maroon",
        "สีแดง" to "red",
        "แดง" to "red",
        "สีส้ม" to "orange",
        "ส้ม" to "orange",
        "สีเหลือง" to "yellow",
        "เหลือง" to "yellow",
        "สีทอง" to "gold",
        "เขียวเข้ม" to "dark green",
        "เขียวอ่อน" to "light green",
        "สีเขียว" to "green",
        "เขียว" to "green",
        "สีเขียวขี้ม้า" to "olive",
        "สีฟ้าอมเขียว" to "turquoise",
        "สีม่วง" to "purple",
        "ม่วง" to "purple",
        "สีชมพู" to "pink",
        "ชมพู" to "pink",
        "สีน้ำตาล" to "brown",
        "น้ำตาล" to "brown",
        "สีเบจ" to "beige",
        "สีครีม" to "cream",
        "สีเข้ม" to "dark",
        "สีอ่อน" to "light",

        // Talking to the helper.
        "สวัสดี" to "hello",
        "หวัดดี" to "hello",
        "ช่วยด้วย" to "help",
        "ช่วยหน่อย" to "help",
        "ช่วย" to "help",
        "คุณทำอะไรได้บ้าง" to "what can you do",
        "ทำอะไรได้บ้าง" to "what can you do",
        "คุณเป็นใคร" to "who are you",
        "คุณคือใคร" to "who are you",
        "ขอบคุณ" to "thanks",
        "ขอบใจ" to "thanks",
        "กรุณา" to "please",
        "ครับ" to "please",
        "ค่ะ" to "please",
        "คะ" to "please",
        "วิค" to "wick",
    ),
    spaced = false,
)
