package org.churchpresenter.helper.intent.glossary

internal val TURKISH = Glossary(
    "tr",
    listOf(
        // Asking where, or how.
        "nerede" to "where",
        "nerde" to "where",
        "nereye" to "where",
        "nerden" to "where",
        "nereden" to "where",
        "nasıl yapabilirim" to "how can i",
        "nasil yapabilirim" to "how can i",
        "nasıl yaparım" to "how do i",
        "nasil yaparim" to "how do i",
        "nasıl" to "how do i",
        "nasil" to "how do i",
        "bulamıyorum" to "can't find",
        "bulamiyorum" to "can't find",
        "bulamadım" to "can't find",
        "bulamadim" to "can't find",
        "bana göster" to "show me",
        "bana goster" to "show me",
        "bana gösterir misin" to "show me",

        // Doing.
        "göster*" to "show",
        "goster*" to "show",
        "yansıt*" to "show",
        "yansit*" to "show",
        "aç" to "open",
        "açın" to "open",
        "açar mısın" to "open",
        "acar misin" to "open",
        "açmak" to "open",
        "açabilir*" to "open",
        "sekmesine geç" to "switch to",
        "sekmesine gec" to "switch to",
        "geç" to "switch to",
        "geçin" to "switch to",
        "geçiş yap" to "switch to",
        "gecis yap" to "switch to",
        "gidin" to "go to",
        "bul" to "find",
        "bulun" to "find",
        "bulur musun" to "find",
        "ara" to "find",
        "arayın" to "find",
        "arayin" to "find",
        "oku" to "read",
        "okuyun" to "read",
        "yap" to "make",
        "yapın" to "make",
        "yapin" to "make",
        "oluştur*" to "create",
        "olustur*" to "create",
        "ekle*" to "add",
        "yükle*" to "load",
        "yukle*" to "load",
        "içe aktar*" to "import",
        "ice aktar*" to "import",
        "indir*" to "download",
        "kurmak" to "install",
        "kur" to "install",
        "kurun" to "install",
        "seç*" to "choose",
        "secin" to "choose",
        "secmek" to "choose",
        "ayarla*" to "set up",
        "bağla*" to "connect",
        "bagla*" to "connect",
        "atayın" to "assign",
        "atayin" to "assign",
        "atamak" to "assign",
        "gizle*" to "hide",
        "kaldır*" to "remove",
        "kaldir*" to "remove",
        "durdur*" to "stop",
        "duraklat*" to "pause",
        "sil" to "delete",
        "silin" to "delete",
        "silmek" to "delete",
        "temizle*" to "clear",
        "ekranı karart" to "black out",
        "ekrani karart" to "black out",
        "karart*" to "black out",
        "boş ekran" to "blank",
        "bos ekran" to "blank",
        "geri al*" to "undo",
        "eski haline getir" to "undo",
        "yayına al*" to "go live",
        "yayina al*" to "go live",
        "canlıya al*" to "go live",
        "canliya al*" to "go live",
        "aç kapa" to "toggle",
        "kapat*" to "turn off",
        "sonraki" to "next",
        "sonrakine" to "next",
        "ileri" to "forward",
        "önceki*" to "previous",
        "onceki*" to "previous",
        "geri" to "back",
        "geri dön" to "go back",
        "geri don" to "go back",
        "büyüt*" to "enlarge",
        "buyut*" to "enlarge",
        "daha büyük" to "bigger",
        "daha buyuk" to "bigger",
        "artır*" to "increase",
        "artir*" to "increase",
        "arttır*" to "increase",
        "arttir*" to "increase",
        "küçült*" to "shrink",
        "kucult*" to "shrink",
        "daha küçük" to "smaller",
        "daha kucuk" to "smaller",
        "azalt*" to "decrease",
        "dönüştürücü*" to "converter",
        "donusturucu*" to "converter",
        "dönüştür*" to "convert",
        "donustur*" to "convert",
        "aktar*" to "transfer",
        "taşı*" to "migrate",
        "düzenle*" to "edit",
        "duzenle*" to "edit",
        "değiştir*" to "change",
        "degistir*" to "change",
        "yeniden adlandır*" to "rename",
        "yeniden adlandir*" to "rename",
        "adını değiştir" to "rename",
        "adini degistir" to "rename",
        "düzelt*" to "fix",
        "duzelt*" to "fix",
        "organize et" to "organize",
        "karşılaştır*" to "compare",
        "karsilastir*" to "compare",
        "çeviri*" to "translation",
        "ceviri*" to "translation",
        "çevir*" to "translate",
        "cevir*" to "translate",
        "planla*" to "plan",
        "otomatikleştir*" to "automate",
        "otomatiklestir*" to "automate",
        "otomatik*" to "automatically",
        "tanımla*" to "identify",
        "tanimla*" to "identify",
        "numaralandır*" to "number the",
        "numaralandir*" to "number the",

        // Too small, too big, not working.
        "çok küçük" to "too small",
        "cok kucuk" to "too small",
        "fazla küçük" to "too small",
        "okunmuyor" to "hard to read",
        "zor okunuyor" to "hard to read",
        "okunaksız" to "hard to read",
        "okunaksiz" to "hard to read",
        "okuyamıyorum" to "can't read",
        "okuyamiyorum" to "can't read",
        "çok büyük" to "too big",
        "cok buyuk" to "too big",
        "fazla büyük" to "too big",
        "sığmıyor" to "doesn't fit",
        "sigmiyor" to "doesn't fit",
        "çalışmıyor" to "not working",
        "calismiyor" to "not working",
        "görünmüyor" to "not showing",
        "gorunmuyor" to "not showing",
        "gösterilmiyor" to "not showing",
        "hiçbir şey görünmüyor" to "nothing shows",
        "hicbir sey gorunmuyor" to "nothing shows",
        "hiçbir şey yok" to "nothing shows",
        "ekran siyah" to "screen is black",
        "siyah ekran" to "screen is black",
        "sinyal yok" to "no signal",
        "görüntü yok" to "no picture",
        "goruntu yok" to "no picture",
        "hangi ekran" to "which screen",
        "hangi monitör" to "which monitor",
        "hangi monitor" to "which monitor",
        "hangi projeksiyon" to "which projector",
        "hangi projektör" to "which projector",

        // What is on screen.
        "arka plan*" to "background",
        "arkaplan*" to "background",
        "fon" to "background",
        "fonu" to "background",
        "fonunu" to "background",
        "şarkı sözleri" to "lyrics",
        "sarki sozleri" to "lyrics",
        "sözler*" to "lyrics",
        "sozler*" to "lyrics",
        "şarkı*" to "song",
        "şarki*" to "song",
        "sarki*" to "song",
        "ilahi*" to "hymn",
        "övgü*" to "worship",
        "ovgu*" to "worship",
        "tapınma" to "worship",
        "tapinma" to "worship",
        "kutsal kitap*" to "bible",
        "kitabı mukaddes" to "bible",
        "kitabi mukaddes" to "bible",
        "incil*" to "bible",
        "ayet*" to "verse",
        "bölüm*" to "chapter",
        "bolum*" to "chapter",
        "yazı tipi" to "font",
        "yazi tipi" to "font",
        "yazı boyutu" to "font size",
        "yazi boyutu" to "font size",
        "boyut*" to "size",
        "metin*" to "text",
        "yazı*" to "text",
        "yazi*" to "text",
        "harf*" to "letters",
        "kelime*" to "words",
        "slayt gösterisi" to "slideshow",
        "slayt gosterisi" to "slideshow",
        "slayt*" to "slide",
        "fotoğraf*" to "photo",
        "fotograf*" to "photo",
        "resim*" to "picture",
        "görsel*" to "image",
        "gorsel*" to "image",
        "albüm*" to "album",
        "sunum*" to "presentation",
        "klip*" to "clip",
        "medya*" to "media",
        "ses" to "audio",
        "alt bant*" to "lower third",
        "isim bandı" to "name strap",
        "isim bandi" to "name strap",
        "isim ve unvan" to "name and title",
        "duyuru*" to "announcement",
        "kayan yazı" to "ticker",
        "kayan yazi" to "ticker",
        "çocuk odası" to "kids room",
        "cocuk odasi" to "kids room",
        "geri sayım*" to "countdown",
        "geri sayim*" to "countdown",
        "zamanlayıcı*" to "timer",
        "zamanlayici*" to "timer",
        "kronometre*" to "stopwatch",
        "şu anki saat" to "current time",
        "su anki saat" to "current time",
        "şimdiki saat" to "current time",
        "saat*" to "clock",
        "zaman" to "time",
        "notlar*" to "notes",
        "akor*" to "chord",
        "dil" to "language",
        "dili" to "language",
        "dilde" to "language",
        "dilinde" to "language",
        "diller*" to "languages",
        "iki dilli" to "bilingual",
        "başka bir dilde" to "another language",
        "baska bir dilde" to "another language",
        "başka dil*" to "another language",
        "baska dil*" to "another language",
        "ikinci dil*" to "second language",
        "iki dilde" to "two languages",

        // Screens and outputs.
        "ana ekran*" to "main screen",
        "tam ekran" to "full screen",
        "ikinci ekran*" to "second screen",
        "ekran*" to "screen",
        "projeksiyon*" to "projector",
        "projektör*" to "projector",
        "projektor*" to "projector",
        "sahne monitör*" to "stage monitor",
        "sahne monitor*" to "stage monitor",
        "sahne ekran*" to "stage monitor",
        "monitör*" to "monitor",
        "çıktı*" to "output",
        "cikti*" to "output",
        "çıkış penceresi" to "output window",
        "cikis penceresi" to "output window",
        "sahne*" to "stage",
        "bölge*" to "zone",
        "bolge*" to "zone",
        "düzen" to "layout",
        "düzeni" to "layout",
        "yerleşim*" to "layout",
        "yerlesim*" to "layout",
        "mesaj*" to "message",
        "gönder*" to "send",
        "gonder*" to "send",
        "önizleme*" to "preview",
        "onizleme*" to "preview",
        "ekranda ne var" to "what is on screen",
        "profil*" to "profile",
        "canlı yayın*" to "stream",
        "canli yayin*" to "stream",
        "yayın*" to "stream",
        "yayin*" to "stream",
        "televizyon*" to "tv",

        // Pages, tabs and tools.
        "ayarlar*" to "settings",
        "seçenek*" to "options",
        "secenek*" to "options",
        "tercih*" to "preferences",
        "kurulum sihirbazı" to "setup wizard",
        "kurulum sihirbazi" to "setup wizard",
        "başlarken" to "getting started",
        "baslarken" to "getting started",
        "baştan başla" to "start over",
        "bastan basla" to "start over",
        "kısayol*" to "shortcut",
        "kisayol*" to "shortcut",
        "klavye*" to "keyboard",
        "sekme*" to "tab",
        "şarkı kütüphanesi" to "song library",
        "sarki kutuphanesi" to "song library",
        "şarkı kitaplığı" to "song library",
        "kütüphane*" to "library",
        "kutuphane*" to "library",
        "kitaplık*" to "library",
        "kitaplik*" to "library",
        "web sitesi" to "website",
        "tarayıcı*" to "browser",
        "tarayici*" to "browser",
        "sözlük*" to "dictionary",
        "sozluk*" to "dictionary",
        "kamera*" to "camera",
        "tuval*" to "canvas",
        "sunucu*" to "server",
        "uzaktan" to "remote",
        "kumanda*" to "remote",
        "telefon*" to "phone",
        "entegrasyon*" to "integrations",

        // Services and planning.
        "ibadet sırası" to "order of service",
        "ibadet sirasi" to "order of service",
        "ibadet akışı" to "order of service",
        "ibadet akisi" to "order of service",
        "ibadet*" to "service",
        "toplantı*" to "meeting",
        "toplanti*" to "meeting",
        "pazar günü" to "sunday",
        "pazar gunu" to "sunday",
        "pazar" to "sunday",
        "pazarı" to "sunday",
        "pazari" to "sunday",
        "takvim*" to "calendar",
        "programı" to "schedule",
        "programda" to "schedule",
        "akış*" to "schedule",
        "çalma listesi" to "playlist",
        "calma listesi" to "playlist",
        "her pazar" to "every sunday",
        "her hafta" to "every week",
        "haftalık*" to "weekly",
        "haftalik*" to "weekly",
        "aylık*" to "monthly",
        "aylik*" to "monthly",
        "tekrarla*" to "repeat",
        "şablon*" to "template",
        "sablon*" to "template",

        // Many, all, both.
        "hepsi*" to "all",
        "tüm" to "all",
        "tum" to "all",
        "bütün" to "all",
        "butun" to "all",
        "her şey*" to "everything",
        "her sey*" to "everything",
        "her ikisi*" to "both",
        "ikisi de" to "both",
        "ikisini de" to "both",
        "birkaç" to "several",
        "birkac" to "several",
        "çok sayıda" to "many",
        "cok sayida" to "many",
        "aynı anda" to "at once",
        "ayni anda" to "at once",
        "bu ibadet için" to "this service",
        "bu ibadet icin" to "this service",
        "bugün için" to "for today",
        "bugun icin" to "for today",
        "geçici olarak" to "temporarily",
        "gecici olarak" to "temporarily",
        "şimdilik" to "for now",
        "simdilik" to "for now",

        // Languages, by name.
        "türkçe*" to "turkish",
        "turkce*" to "turkish",
        "ingilizce*" to "english",
        "ispanyolca*" to "spanish",
        "rusça*" to "russian",
        "rusca*" to "russian",
        "ukraynaca*" to "ukrainian",
        "almanca*" to "german",
        "fransızca*" to "french",
        "fransizca*" to "french",
        "lehçe*" to "polish",
        "lehce*" to "polish",
        "portekizce*" to "portuguese",
        "italyanca*" to "italian",
        "felemenkçe*" to "dutch",
        "hollandaca*" to "dutch",
        "rumence*" to "romanian",
        "yunanca*" to "greek",
        "arapça*" to "arabic",
        "arapca*" to "arabic",
        "farsça*" to "farsi",
        "farsca*" to "farsi",
        "ibranice*" to "hebrew",
        "çince*" to "chinese",
        "cince*" to "chinese",
        "japonca*" to "japanese",
        "korece*" to "korean",
        "ermenice*" to "armenian",
        "gürcüce*" to "georgian",
        "gurcuce*" to "georgian",
        "kazakça*" to "kazakh",
        "kazakca*" to "kazakh",
        "özbekçe*" to "uzbek",
        "ozbekce*" to "uzbek",

        // Colors.
        "lacivert*" to "navy",
        "açık mavi*" to "light blue",
        "acik mavi*" to "light blue",
        "mavi*" to "blue",
        "siyah*" to "black",
        "beyaz*" to "white",
        "gri" to "grey",
        "griye" to "grey",
        "gümüş*" to "silver",
        "gumus*" to "silver",
        "kırmızı*" to "red",
        "kirmizi*" to "red",
        "bordo*" to "maroon",
        "turuncu*" to "orange",
        "sarı*" to "yellow",
        "sari*" to "yellow",
        "altın*" to "gold",
        "altin*" to "gold",
        "fıstık yeşili" to "lime",
        "fistik yesili" to "lime",
        "yeşil*" to "green",
        "yesil*" to "green",
        "camgöbeği" to "cyan",
        "turkuaz*" to "turquoise",
        "mor" to "purple",
        "mora" to "purple",
        "moru" to "purple",
        "menekşe*" to "violet",
        "menekse*" to "violet",
        "lavanta*" to "lavender",
        "pembe*" to "pink",
        "kahverengi*" to "brown",
        "bej" to "beige",
        "krem*" to "cream",
        "koyu" to "dark",
        "açık" to "light",
        "acik" to "light",

        // Talking to the helper.
        "merhaba" to "hello",
        "selam" to "hello",
        "günaydın" to "hello",
        "gunaydin" to "hello",
        "iyi akşamlar" to "hello",
        "yardım*" to "help",
        "yardim*" to "help",
        "neler yapabilirsin" to "what can you do",
        "ne yapabilirsin" to "what can you do",
        "ne yaparsın" to "what do you do",
        "ne yaparsin" to "what do you do",
        "sen kimsin" to "who are you",
        "kimsin" to "who are you",
        "teşekkürler" to "thanks",
        "tesekkurler" to "thanks",
        "teşekkür ederim" to "thank you",
        "tesekkur ederim" to "thank you",
        "sağ ol" to "thanks",
        "sag ol" to "thanks",
        "sağol" to "thanks",
        "lütfen" to "please",
        "lutfen" to "please",
        "vik" to "wick",
    ),
)
