package org.churchpresenter.helper.intent.glossary

internal val UKRAINIAN = Glossary(
    "uk",
    listOf(
        // Asking where, or how.
        "де" to "where",
        "куди" to "where",
        "як мені" to "how do i",
        "як я можу" to "how can i",
        "як можна" to "how can i",
        "як" to "how do i",
        "не можу знайти" to "can't find",
        "не знаходжу" to "can't find",
        "покажи мені" to "show me",
        "підкажи*" to "how do i",

        // Doing.
        "покажи" to "show",
        "показати" to "show",
        "покажіть" to "show",
        "показувати" to "show",
        "виведи на екран" to "show",
        "виведи" to "show",
        "вивести" to "show",
        "відобрази*" to "display",
        "відкрий*" to "open",
        "відкрити" to "open",
        "перейди на" to "go to",
        "перейди до" to "go to",
        "перейди в" to "go to",
        "перейди у" to "go to",
        "перейди" to "go to",
        "перейти" to "go to",
        "перемкни на" to "switch to",
        "перемкнись на" to "switch to",
        "переключи на" to "switch to",
        "знайди" to "find",
        "знайдіть" to "find",
        "знайти" to "find",
        "прочитай*" to "read",
        "зроби" to "make",
        "зробіть" to "make",
        "зробити" to "make",
        "створи*" to "create",
        "створити" to "create",
        "додай*" to "add",
        "додати" to "add",
        "додава*" to "add",
        "завантаж*" to "get",
        "імпорт*" to "import",
        "скачай*" to "download",
        "скачати" to "download",
        "встанови*" to "install",
        "встановити" to "install",
        "вибери*" to "choose",
        "вибрати" to "choose",
        "обери*" to "choose",
        "обрати" to "choose",
        "налашту*" to "set up",
        "підключ*" to "connect",
        "признач*" to "assign",
        "прибери*" to "hide",
        "прибрати" to "hide",
        "сховай*" to "hide",
        "сховати" to "hide",
        "приховай*" to "hide",
        "приховати" to "hide",
        "зупини*" to "stop",
        "зупинити" to "stop",
        "видали*" to "delete",
        "очисти*" to "clear",
        "очистити" to "clear",
        "затемни*" to "black out",
        "погаси екран" to "black out",
        "порожній екран" to "blank",
        "скасу*" to "undo",
        "відміни" to "undo",
        "відмінити" to "undo",
        "поверни як було" to "undo",
        "поверни назад" to "undo",
        "в ефір" to "go live",
        "у ефір" to "go live",
        "вивести в ефір" to "go live",
        "виведи в ефір" to "go live",
        "увімкни*" to "turn on",
        "увімкнути" to "turn on",
        "вимкни*" to "turn off",
        "вимкнути" to "turn off",
        "перемкни*" to "toggle",
        "наступн*" to "next",
        "далі" to "next",
        "вперед" to "forward",
        "попередн*" to "previous",
        "назад" to "back",
        "збільш*" to "increase",
        "більше" to "bigger",
        "більший" to "bigger",
        "крупніше" to "bigger",
        "зменш*" to "decrease",
        "менше" to "smaller",
        "менший" to "smaller",
        "дрібніше" to "smaller",
        "конвертуй*" to "convert",
        "конвертувати" to "convert",
        "конвертер*" to "converter",
        "перенес*" to "transfer",
        "перенос*" to "transfer",
        "редагу*" to "edit",
        "відредагу*" to "edit",
        "зміни*" to "change",
        "змінити" to "change",
        "поміняй*" to "change",
        "перейменуй*" to "rename",
        "перейменувати" to "rename",
        "виправ*" to "fix",
        "упорядку*" to "organize",
        "організу*" to "organize",
        "навести лад" to "clean up",
        "навести порядок" to "clean up",
        "порівня*" to "compare",
        "переклади пісню" to "translate song",
        "перекласти" to "translate",
        "сплануй*" to "plan",
        "сплануват*" to "plan",
        "плану*" to "plan",
        "заплану*" to "plan",
        "автоматизу*" to "automate",
        "автоматичн*" to "automatically",
        "визнач*" to "identify",
        "пронумеруй*" to "number the",

        // Too small, too big, not working.
        "занадто дрібн*" to "too small",
        "занадто мал*" to "too small",
        "надто дрібн*" to "too small",
        "надто мал*" to "too small",
        "погано видно" to "hard to read",
        "не видно" to "hard to read",
        "не читається" to "hard to read",
        "важко читати" to "hard to read",
        "занадто велик*" to "too big",
        "надто велик*" to "too big",
        "не вміщається" to "doesn't fit",
        "не влазить" to "doesn't fit",
        "не працює" to "not working",
        "не показує" to "not showing",
        "нічого не показує" to "nothing shows",
        "нічого немає" to "nothing shows",
        "чорний екран" to "screen is black",
        "немає сигналу" to "no signal",
        "нема сигналу" to "no signal",
        "немає картинки" to "no picture",
        "немає зображення" to "no picture",
        "який екран" to "which screen",
        "який монітор" to "which monitor",
        "який проектор" to "which projector",
        "який проєктор" to "which projector",

        // What is on screen.
        "фон*" to "background",
        "задній план" to "backdrop",
        "текст пісні" to "lyrics",
        "слова пісні" to "lyrics",
        "пісень" to "songs",
        "пісн*" to "song",
        "гімн*" to "hymn",
        "прославлен*" to "worship",
        "хвал*" to "worship",
        "біблі*" to "bible",
        "писанн*" to "scripture",
        "вірш*" to "verse",
        "розділ*" to "chapter",
        "глава" to "chapter",
        "главу" to "chapter",
        "глави" to "chapter",
        "шрифт*" to "font",
        "розмір*" to "size",
        "текст*" to "text",
        "слова" to "words",
        "літер*" to "letters",
        "букв*" to "letters",
        "слайд-шоу" to "slideshow",
        "слайдшоу" to "slideshow",
        "слайд*" to "slide",
        "фотограф*" to "photo",
        "фото*" to "photo",
        "картин*" to "picture",
        "зображен*" to "image",
        "альбом*" to "album",
        "презентаці*" to "presentation",
        "відео" to "video",
        "фільм*" to "movie",
        "ролик*" to "clip",
        "кліп*" to "clip",
        "медіа" to "media",
        "аудіо" to "audio",
        "нижн* трет*" to "lower third",
        "титр*" to "lower third",
        "плашк*" to "name strap",
        "ім'я та посада" to "name and title",
        "ім'я і посада" to "name and title",
        "оголошен*" to "announcement",
        "анонс*" to "announcement",
        "біжуч* рядок" to "ticker",
        "біжучого рядка" to "ticker",
        "дитяч* кімнат*" to "kids room",
        "зворотн* відлік*" to "countdown",
        "відлік*" to "countdown",
        "таймер*" to "timer",
        "секундомір*" to "stopwatch",
        "годинник*" to "clock",
        "поточний час" to "current time",
        "час" to "time",
        "нотатк*" to "notes",
        "акорд*" to "chord",
        "переклад*" to "translation",
        "мов*" to "language",
        "двомовн*" to "bilingual",
        "іншою мовою" to "another language",
        "інша мова" to "another language",
        "іншу мову" to "another language",
        "другою мовою" to "second language",
        "друга мова" to "second language",
        "другу мову" to "second language",
        "двома мовами" to "two languages",
        "на двох мовах" to "two languages",

        // Screens and outputs.
        "головн* екран*" to "main screen",
        "повний екран" to "full screen",
        "на весь екран" to "full screen",
        "весь екран" to "full screen",
        "повноекранн*" to "fullscreen",
        "другий екран" to "second screen",
        "екран*" to "screen",
        "проектор*" to "projector",
        "проєктор*" to "projector",
        "монітор* сцени" to "stage monitor",
        "монітор* на сцені" to "stage monitor",
        "монітор* для сцени" to "stage monitor",
        "сценічн* монітор*" to "stage monitor",
        "суфлер*" to "confidence monitor",
        "монітор*" to "monitor",
        "дисплей*" to "display",
        "вивід*" to "output",
        "виводу" to "output",
        "вихід*" to "output",
        "вікно виводу" to "output window",
        "сцен*" to "stage",
        "зон*" to "zone",
        "розклад*" to "layout",
        "макет*" to "layout",
        "розташуван*" to "arrangement",
        "повідомлен*" to "message",
        "надішли*" to "send",
        "надіслати" to "send",
        "відправ*" to "send",
        "попередній перегляд" to "preview",
        "перегляд*" to "preview",
        "прев'ю" to "preview",
        "превю" to "preview",
        "що на екрані" to "what is on screen",
        "профіл*" to "profile",
        "трансляці*" to "stream",
        "стрім*" to "stream",
        "телевізор*" to "tv",

        // Pages, tabs and tools.
        "налаштуван*" to "settings",
        "параметр*" to "options",
        "майстер налаштування" to "setup wizard",
        "почати спочатку" to "start over",
        "почати знову" to "start over",
        "сполучен* клавіш" to "shortcut",
        "гаряч* клавіш*" to "hotkeys",
        "клавіатур*" to "keyboard",
        "вкладк*" to "tab",
        "бібліотек* пісень" to "song library",
        "бібліотек*" to "library",
        "веб" to "web",
        "сайт*" to "website",
        "браузер*" to "browser",
        "словник*" to "dictionary",
        "стронг*" to "strong",
        "камер*" to "camera",
        "полотн*" to "canvas",
        "сервер*" to "server",
        "віддален*" to "remote",
        "пульт*" to "remote",
        "телефон*" to "phone",
        "смартфон*" to "phone",
        "планшет*" to "tablet",
        "компаньйон*" to "companion",
        "інтеграці*" to "integrations",

        // Services and planning.
        "порядок служіння" to "order of service",
        "програма служіння" to "order of service",
        "порядку служіння" to "order of service",
        "богослужін*" to "service",
        "служін*" to "service",
        "зібран*" to "meeting",
        "неділ*" to "sunday",
        "календар*" to "calendar",
        "розклад служінь" to "schedule",
        "програм*" to "schedule",
        "плейлист*" to "playlist",
        "щонеділі" to "every sunday",
        "кожної неділі" to "every sunday",
        "кожного тижня" to "every week",
        "щотижн*" to "weekly",
        "щомісяц*" to "monthly",
        "повтор*" to "repeat",
        "шаблон*" to "template",

        // Many, all, both.
        "всі" to "all",
        "усі" to "all",
        "все" to "all",
        "усе" to "all",
        "всюди" to "everything",
        "скрізь" to "everything",
        "обидва" to "both",
        "обидві" to "both",
        "обох" to "both",
        "кілька" to "several",
        "декілька" to "several",
        "багато" to "many",
        "одразу" to "at once",
        "відразу" to "at once",
        "для цього служіння" to "this service",
        "на сьогодні" to "for today",
        "тимчасово" to "temporarily",

        // Languages, by name.
        "російськ*" to "russian",
        "українськ*" to "ukrainian",
        "білорус*" to "belarusian",
        "англійськ*" to "english",
        "іспанськ*" to "spanish",
        "німецьк*" to "german",
        "французьк*" to "french",
        "польськ*" to "polish",
        "казахськ*" to "kazakh",
        "узбецьк*" to "uzbek",
        "румунськ*" to "romanian",
        "молдовськ*" to "moldovan",
        "молдавськ*" to "moldovan",
        "португальськ*" to "portuguese",
        "італійськ*" to "italian",
        "чеськ*" to "czech",
        "словацьк*" to "slovak",
        "грузинськ*" to "georgian",
        "вірменськ*" to "armenian",
        "латин*" to "latin",

        // Colors.
        "темно-син*" to "navy",
        "світло-син*" to "light blue",
        "блакитн*" to "light blue",
        "голуб*" to "light blue",
        "синій" to "blue",
        "синім" to "blue",
        "синього" to "blue",
        "синя" to "blue",
        "синю" to "blue",
        "синє" to "blue",
        "синьою" to "blue",
        "чорн*" to "black",
        "білий" to "white",
        "білим" to "white",
        "білого" to "white",
        "біла" to "white",
        "білу" to "white",
        "біле" to "white",
        "білою" to "white",
        "сірий" to "grey",
        "сірим" to "grey",
        "сірого" to "grey",
        "сіра" to "grey",
        "сіру" to "grey",
        "сіре" to "grey",
        "срібляст*" to "silver",
        "срібн*" to "silver",
        "червон*" to "red",
        "бордов*" to "maroon",
        "помаранчев*" to "orange",
        "оранжев*" to "orange",
        "жовт*" to "yellow",
        "золот*" to "gold",
        "зелен*" to "green",
        "салатов*" to "lime",
        "бірюзов*" to "turquoise",
        "фіолетов*" to "purple",
        "бузков*" to "violet",
        "лілов*" to "violet",
        "рожев*" to "pink",
        "коричнев*" to "brown",
        "бежев*" to "beige",
        "кремов*" to "cream",
        "темн*" to "dark",
        "світл*" to "light",

        // Talking to the helper.
        "привіт" to "hello",
        "вітаю" to "hello",
        "добрий день" to "hello",
        "доброго дня" to "hello",
        "здрастуй*" to "hello",
        "допоможи*" to "help",
        "допомога" to "help",
        "допомогу" to "help",
        "що ти вмієш" to "what can you do",
        "що ти можеш" to "what can you do",
        "хто ти" to "who are you",
        "дякую" to "thanks",
        "спасибі" to "thanks",
        "щиро дякую" to "thank you",
        "будь ласка" to "please",
        "вік" to "wick",
        "уік" to "wick",
    ),
)
