package org.churchpresenter.helper.intent.glossary

internal val UZBEK = Glossary(
    "uz",
    listOf(
        // Asking where, or how.
        "qayerda" to "where",
        "qayerga" to "where",
        "qayerdan" to "where",
        "qayer" to "where",
        "qanday qilib" to "how do i",
        "qanday qilsam" to "how do i",
        "qanday qila olaman" to "how can i",
        "qanday qilsa boʻladi" to "how can i",
        "qanday qilsa bo'ladi" to "how can i",
        "qanday qilsa boladi" to "how can i",
        "qanday" to "how do i",
        "topa olmayapman" to "can't find",
        "topolmayapman" to "can't find",
        "topa olmadim" to "can't find",
        "topolmadim" to "can't find",
        "menga koʻrsat*" to "show me",
        "menga ko'rsat*" to "show me",
        "menga korsat*" to "show me",
        "maslahat ber*" to "how do i",

        // Doing.
        "koʻrsat*" to "show",
        "ko'rsat*" to "show",
        "korsat*" to "show",
        "chiqar*" to "show",
        "ekranga chiqar*" to "go live",
        "efirga chiqar*" to "go live",
        "efirga" to "go live",
        "och" to "open",
        "ochish" to "open",
        "oching" to "open",
        "ochib" to "open",
        "ochgin" to "open",
        "ochsang" to "open",
        "oʻt" to "go to",
        "o't" to "go to",
        "oʻting" to "go to",
        "o'ting" to "go to",
        "oting" to "go to",
        "oʻtish" to "go to",
        "o'tish" to "go to",
        "otish" to "go to",
        "oʻtgin" to "go to",
        "o'tgin" to "go to",
        "otgin" to "go to",
        "oʻtib" to "go to",
        "o'tib" to "go to",
        "otib" to "go to",
        "top" to "find",
        "topish" to "find",
        "toping" to "find",
        "topib" to "find",
        "topgin" to "find",
        "izla*" to "search",
        "qidir*" to "search",
        "oʻqi*" to "read",
        "o'qi*" to "read",
        "qil" to "make",
        "qiling" to "make",
        "qilish" to "make",
        "qilgin" to "make",
        "yasa*" to "make",
        "yarat*" to "create",
        "qoʻsh*" to "add",
        "qo'sh*" to "add",
        "qosh*" to "add",
        "yuklab ol*" to "download",
        "yukla*" to "get",
        "import*" to "import",
        "oʻrnat*" to "install",
        "o'rnat*" to "install",
        "ornat*" to "install",
        "tanla*" to "choose",
        "sozla*" to "set up",
        "ula" to "connect",
        "ulash" to "connect",
        "ulang" to "connect",
        "ulab" to "connect",
        "ulanish*" to "connect",
        "tayinla*" to "assign",
        "biriktir*" to "assign",
        "yashir*" to "hide",
        "olib tashla*" to "hide",
        "toʻxtat*" to "stop",
        "to'xtat*" to "stop",
        "toxtat*" to "stop",
        "oʻchirib tashla*" to "delete",
        "o'chirib tashla*" to "delete",
        "ochirib tashla*" to "delete",
        "yoʻq qil*" to "delete",
        "yo'q qil*" to "delete",
        "tozala*" to "clear",
        "qoraytir*" to "black out",
        "ekranni oʻchir*" to "black out",
        "ekranni o'chir*" to "black out",
        "ekranni ochir*" to "black out",
        "boʻsh ekran" to "blank",
        "bo'sh ekran" to "blank",
        "bosh ekran" to "blank",
        "bekor qil*" to "undo",
        "ortga qaytar*" to "undo",
        "avvalgidek qil*" to "undo",
        "qaytar*" to "undo",
        "yoq" to "turn on",
        "yoqing" to "turn on",
        "yoqish" to "turn on",
        "yoqib" to "turn on",
        "yoqgin" to "turn on",
        "oʻchir*" to "turn off",
        "o'chir*" to "turn off",
        "ochir*" to "turn off",
        "keyingi*" to "next",
        "oldinga" to "forward",
        "oldingi*" to "previous",
        "orqaga" to "back",
        "kattalashtir*" to "increase",
        "kattaroq" to "bigger",
        "yiriroq" to "bigger",
        "kichiklashtir*" to "decrease",
        "kichraytir*" to "decrease",
        "kichikroq" to "smaller",
        "maydaroq" to "smaller",
        "konvertla*" to "convert",
        "konvertatsiya*" to "convert",
        "konverter*" to "converter",
        "aylantir*" to "convert",
        "oʻtkaz*" to "transfer",
        "o'tkaz*" to "transfer",
        "otkaz*" to "transfer",
        "koʻchir*" to "transfer",
        "ko'chir*" to "transfer",
        "kochir*" to "transfer",
        "tahrir*" to "edit",
        "nomini oʻzgartir*" to "rename",
        "nomini o'zgartir*" to "rename",
        "nomini ozgartir*" to "rename",
        "qayta nomla*" to "rename",
        "oʻzgartir*" to "change",
        "o'zgartir*" to "change",
        "ozgartir*" to "change",
        "almashtir*" to "change",
        "tuzat*" to "fix",
        "tartibga sol*" to "organize",
        "tartibla*" to "organize",
        "tartibga keltir*" to "clean up",
        "solishtir*" to "compare",
        "taqqosla*" to "compare",
        "tarjima qil*" to "translate",
        "rejala*" to "plan",
        "avtomatlashtir*" to "automate",
        "avtomatik*" to "automatically",
        "aniqla*" to "identify",
        "raqamla*" to "number the",

        // Too small, too big, not working.
        "juda kichik" to "too small",
        "juda mayda" to "too small",
        "yaxshi koʻrinmaydi" to "hard to read",
        "yaxshi ko'rinmaydi" to "hard to read",
        "yaxshi korinmaydi" to "hard to read",
        "koʻrinmayapti" to "hard to read",
        "ko'rinmayapti" to "hard to read",
        "korinmayapti" to "hard to read",
        "koʻrinmaydi" to "hard to read",
        "ko'rinmaydi" to "hard to read",
        "korinmaydi" to "hard to read",
        "oʻqish qiyin" to "hard to read",
        "o'qish qiyin" to "hard to read",
        "oqish qiyin" to "hard to read",
        "oʻqib boʻlmaydi" to "hard to read",
        "o'qib bo'lmaydi" to "hard to read",
        "oqib bolmaydi" to "hard to read",
        "juda katta" to "too big",
        "juda yirik" to "too big",
        "sigʻmayapti" to "doesn't fit",
        "sig'mayapti" to "doesn't fit",
        "sigmayapti" to "doesn't fit",
        "sigʻmaydi" to "doesn't fit",
        "sig'maydi" to "doesn't fit",
        "sigmaydi" to "doesn't fit",
        "ishlamayapti" to "not working",
        "ishlamaydi" to "not working",
        "koʻrsatmayapti" to "not showing",
        "ko'rsatmayapti" to "not showing",
        "korsatmayapti" to "not showing",
        "koʻrsatmaydi" to "not showing",
        "ko'rsatmaydi" to "not showing",
        "korsatmaydi" to "not showing",
        "hech narsa koʻrsatmayapti" to "nothing shows",
        "hech narsa ko'rsatmayapti" to "nothing shows",
        "hech narsa korsatmayapti" to "nothing shows",
        "hech narsa koʻrinmayapti" to "nothing shows",
        "hech narsa ko'rinmayapti" to "nothing shows",
        "hech narsa korinmayapti" to "nothing shows",
        "hech narsa yoʻq" to "nothing shows",
        "hech narsa yo'q" to "nothing shows",
        "qora ekran" to "screen is black",
        "ekran qora" to "screen is black",
        "signal yoʻq" to "no signal",
        "signal yo'q" to "no signal",
        "rasm yoʻq" to "no picture",
        "rasm yo'q" to "no picture",
        "tasvir yoʻq" to "no picture",
        "tasvir yo'q" to "no picture",
        "qaysi ekran" to "which screen",
        "qaysi monitor" to "which monitor",
        "qaysi proyektor" to "which projector",

        // What is on screen.
        "orqa fon*" to "background",
        "fon*" to "background",
        "qoʻshiq matni" to "lyrics",
        "qo'shiq matni" to "lyrics",
        "qoshiq matni" to "lyrics",
        "qoʻshiq soʻzlari" to "lyrics",
        "qo'shiq so'zlari" to "lyrics",
        "qoshiq sozlari" to "lyrics",
        "qoʻshiqlar*" to "songs",
        "qo'shiqlar*" to "songs",
        "qoshiqlar*" to "songs",
        "qoʻshiq*" to "song",
        "qo'shiq*" to "song",
        "qoshiq*" to "song",
        "madhiya*" to "hymn",
        "gimn*" to "hymn",
        "hamdu sano" to "worship",
        "hamd*" to "worship",
        "muqaddas kitob*" to "bible",
        "bibliya*" to "bible",
        "injil*" to "bible",
        "muqaddas yozuv*" to "scripture",
        "oyat*" to "verse",
        "bob" to "chapter",
        "bobi" to "chapter",
        "bobni" to "chapter",
        "bobga" to "chapter",
        "bobidan" to "chapter",
        "boblar*" to "chapter",
        "shrift*" to "font",
        "oʻlcham*" to "size",
        "o'lcham*" to "size",
        "olcham*" to "size",
        "hajm*" to "size",
        "matn*" to "text",
        "soʻzlar*" to "words",
        "so'zlar*" to "words",
        "sozlar*" to "words",
        "harf*" to "letters",
        "slayd-shou" to "slideshow",
        "slaydshou" to "slideshow",
        "slayd shou" to "slideshow",
        "slayd*" to "slide",
        "foto*" to "photo",
        "surat*" to "photo",
        "rasm*" to "picture",
        "tasvir*" to "image",
        "albom*" to "album",
        "taqdimot*" to "presentation",
        "prezentatsiya*" to "presentation",
        "video*" to "video",
        "film*" to "movie",
        "rolik*" to "clip",
        "klip*" to "clip",
        "media*" to "media",
        "audio*" to "audio",
        "pastki titr*" to "lower third",
        "pastki uchdan bir*" to "lower third",
        "titr*" to "lower third",
        "ism va lavozim" to "name and title",
        "eʼlon*" to "announcement",
        "e'lon*" to "announcement",
        "elon*" to "announcement",
        "yuguruvchi satr*" to "ticker",
        "yuguruvchi qator*" to "ticker",
        "bolalar xonasi*" to "kids room",
        "teskari sanoq*" to "countdown",
        "orqaga sanoq*" to "countdown",
        "sanoq*" to "countdown",
        "taymer*" to "timer",
        "sekundomer*" to "stopwatch",
        "soat*" to "clock",
        "hozirgi vaqt" to "current time",
        "joriy vaqt" to "current time",
        "vaqt*" to "time",
        "izoh*" to "notes",
        "eslatma*" to "notes",
        "akkord*" to "chord",
        "tarjima*" to "translation",
        "til" to "language",
        "tili" to "language",
        "tilda" to "language",
        "tilga" to "language",
        "tilni" to "language",
        "tilida" to "language",
        "tillar*" to "language",
        "ikki tilli" to "bilingual",
        "boshqa tilda" to "another language",
        "boshqa til*" to "another language",
        "ikkinchi til*" to "second language",
        "ikki tilda" to "two languages",

        // Screens and outputs.
        "asosiy ekran*" to "main screen",
        "toʻliq ekran*" to "full screen",
        "to'liq ekran*" to "full screen",
        "toliq ekran*" to "full screen",
        "butun ekran*" to "full screen",
        "ikkinchi ekran*" to "second screen",
        "ekran*" to "screen",
        "proyektor*" to "projector",
        "proektor*" to "projector",
        "sahna monitor*" to "stage monitor",
        "sahnadagi monitor*" to "stage monitor",
        "suflyor*" to "confidence monitor",
        "monitor*" to "monitor",
        "displey*" to "display",
        "chiqish oynasi" to "output window",
        "chiqish*" to "output",
        "sahna*" to "stage",
        "hudud*" to "zone",
        "zona*" to "zone",
        "joylashuv*" to "layout",
        "maket*" to "layout",
        "joylashtir*" to "arrangement",
        "xabar*" to "message",
        "yubor*" to "send",
        "koʻrib chiqish" to "preview",
        "ko'rib chiqish" to "preview",
        "korib chiqish" to "preview",
        "oldindan koʻrish" to "preview",
        "oldindan ko'rish" to "preview",
        "oldindan korish" to "preview",
        "prevyu" to "preview",
        "ekranda nima bor" to "what is on screen",
        "profil*" to "profile",
        "translyatsiya*" to "stream",
        "jonli efir*" to "stream",
        "strim*" to "stream",
        "televizor*" to "tv",

        // Pages, tabs and tools.
        "sozlama*" to "settings",
        "parametr*" to "options",
        "sozlash ustasi" to "setup wizard",
        "oʻrnatish ustasi" to "setup wizard",
        "o'rnatish ustasi" to "setup wizard",
        "ornatish ustasi" to "setup wizard",
        "boshidan boshla*" to "start over",
        "qaytadan boshla*" to "start over",
        "tugmalar birikma*" to "shortcut",
        "tezkor tugma*" to "hotkeys",
        "klaviatura*" to "keyboard",
        "boʻlim*" to "tab",
        "bo'lim*" to "tab",
        "bolim*" to "tab",
        "yorliq*" to "tab",
        "qoʻshiqlar kutubxona*" to "song library",
        "qo'shiqlar kutubxona*" to "song library",
        "qoshiqlar kutubxona*" to "song library",
        "kutubxona*" to "library",
        "veb" to "web",
        "sayt*" to "website",
        "brauzer*" to "browser",
        "lugʻat*" to "dictionary",
        "lug'at*" to "dictionary",
        "lugat*" to "dictionary",
        "kamera*" to "camera",
        "kanvas*" to "canvas",
        "masofaviy*" to "remote",
        "masofadan*" to "remote",
        "pult*" to "remote",
        "telefon*" to "phone",
        "smartfon*" to "phone",
        "planshet*" to "tablet",
        "kompanyon*" to "companion",
        "integratsiya*" to "integrations",

        // Services and planning.
        "xizmat tartibi*" to "order of service",
        "xizmat dasturi*" to "order of service",
        "xizmat*" to "service",
        "ibodat*" to "service",
        "yigʻilish*" to "meeting",
        "yig'ilish*" to "meeting",
        "yigilish*" to "meeting",
        "uchrashuv*" to "meeting",
        "yakshanba*" to "sunday",
        "taqvim*" to "calendar",
        "kalendar*" to "calendar",
        "jadval*" to "schedule",
        "pleylist*" to "playlist",
        "har yakshanba*" to "every sunday",
        "har hafta*" to "every week",
        "haftalik" to "weekly",
        "oylik" to "monthly",
        "har oy*" to "monthly",
        "takrorla*" to "repeat",
        "shablon*" to "template",
        "andoza*" to "template",

        // Many, all, both.
        "hammasi*" to "all",
        "hamma" to "all",
        "barcha*" to "all",
        "hamma joyda" to "everything",
        "har yerda" to "everything",
        "ikkalasi*" to "both",
        "ikkovi*" to "both",
        "bir nechta" to "several",
        "bir necha" to "several",
        "koʻp" to "many",
        "ko'p" to "many",
        "birdaniga" to "at once",
        "bir vaqtda" to "at once",
        "shu xizmat uchun" to "this service",
        "bugun uchun" to "for today",
        "bugunga" to "for today",
        "vaqtincha" to "temporarily",

        // Languages, by name.
        "ruscha" to "russian",
        "rus" to "russian",
        "ukraincha" to "ukrainian",
        "ukrain*" to "ukrainian",
        "belarus*" to "belarusian",
        "inglizcha" to "english",
        "ingliz*" to "english",
        "ispan*" to "spanish",
        "nemis*" to "german",
        "fransuz*" to "french",
        "polyak*" to "polish",
        "qozoq*" to "kazakh",
        "oʻzbek*" to "uzbek",
        "o'zbek*" to "uzbek",
        "ozbek*" to "uzbek",
        "rumin*" to "romanian",
        "moldavan*" to "moldovan",
        "turkcha" to "turkish",
        "turk" to "turkish",
        "koreys*" to "korean",
        "xitoy*" to "chinese",
        "arab*" to "arabic",
        "fors*" to "persian",
        "lotin*" to "latin",

        // Colors.
        "toʻq koʻk" to "navy",
        "to'q ko'k" to "navy",
        "och koʻk" to "light blue",
        "och ko'k" to "light blue",
        "havorang*" to "light blue",
        "zangori*" to "light blue",
        "koʻk*" to "blue",
        "ko'k*" to "blue",
        "qora*" to "black",
        "oq" to "white",
        "oqqa" to "white",
        "oqni" to "white",
        "oq rang*" to "white",
        "kulrang*" to "grey",
        "kumush*" to "silver",
        "toʻq qizil" to "maroon",
        "to'q qizil" to "maroon",
        "qizil*" to "red",
        "toʻq sariq" to "orange",
        "to'q sariq" to "orange",
        "apelsinrang*" to "orange",
        "zargʻaldoq*" to "orange",
        "zarg'aldoq*" to "orange",
        "zargaldoq*" to "orange",
        "sariq*" to "yellow",
        "oltin*" to "gold",
        "tilla*" to "gold",
        "och yashil" to "lime",
        "yashil*" to "green",
        "feruza*" to "turquoise",
        "binafsha*" to "purple",
        "siyohrang*" to "violet",
        "pushti*" to "pink",
        "jigarrang*" to "brown",
        "bej*" to "beige",
        "krem*" to "cream",
        "toʻq" to "dark",
        "to'q" to "dark",
        "qorongʻi*" to "dark",
        "qorong'i*" to "dark",
        "qorongi*" to "dark",
        "ochiq" to "light",
        "yorugʻ" to "light",
        "yorug'" to "light",
        "yorug" to "light",

        // Talking to the helper.
        "assalomu alaykum" to "hello",
        "assalom*" to "hello",
        "salom*" to "hello",
        "xayrli kun" to "hello",
        "yordam*" to "help",
        "nima qila olasan" to "what can you do",
        "nimalar qila olasan" to "what can you do",
        "nima qila olasiz" to "what can you do",
        "sen kimsan" to "who are you",
        "kimsan" to "who are you",
        "siz kimsiz" to "who are you",
        "rahmat" to "thanks",
        "katta rahmat" to "thank you",
        "tashakkur" to "thank you",
        "iltimos" to "please",
        "uik" to "wick",
        "vik" to "wick",

        // Newer requests.
        "qoʻshiq raqami" to "song number",
        "qoshiq raqami" to "song number",
        "raqami boʻyicha" to "by number",
        "raqami boyicha" to "by number",
        "nomi boʻyicha" to "by title",
        "nomi boyicha" to "by title",
        "raqam" to "number",
        "raqami" to "number",
        "deb nomlangan" to "called",
        "sevimli*" to "favorite",
        "bu qoʻshiq*" to "this song",
        "bu qoshiq*" to "this song",
        "shu qoʻshiq*" to "this song",
        "shu qoshiq*" to "this song",
        "har bir qoʻshiq*" to "each song",
        "har bir qoshiq*" to "each song",
        "oʻz fon*" to "own background",
        "oz fon*" to "own background",
        "alohida fon*" to "own background",
        "bir nechta oyat*" to "several verses",
        "bir necha oyat*" to "several verses",
        "koʻp oyat*" to "many verses",
        "kop oyat*" to "many verses",
        "oyatlar oraligʻi" to "verse range",
        "oyatlar oraligi" to "verse range",
        "parcha" to "a passage",
        "parchani" to "a passage",
        "yana bir" to "another",
        "tarix*" to "history",
        "hozirgina nima* koʻrsat*" to "what did we just show",
        "hozirgina nima* korsat*" to "what did we just show",
        "nimani koʻrsatdik" to "what did we show",
        "nimani korsatdik" to "what did we show",
        "oxirgi oyat*" to "recent verses",
        "soʻnggi oyat*" to "recent verses",
        "songgi oyat*" to "recent verses",
        "oʻzaro havola*" to "cross references",
        "ozaro havola*" to "cross references",
        "bogʻliq oyat*" to "related verses",
        "bogliq oyat*" to "related verses",
        "parallel joy*" to "parallel passages",
        "oʻxshash oyat*" to "similar verses",
        "oxshash oyat*" to "similar verses",
        "veb-sayt*" to "website",
        "vebsayt*" to "website",
        "veb-sahifa*" to "web page",
        "veb sahifa*" to "web page",
        "internet sahifa*" to "internet page",
        "planning sentr*" to "planning center",
        "statistika*" to "statistics",
        "necha marta" to "how many times",
        "qanchalik tez-tez" to "how often",
        "qoʻshiq hisobot*" to "song report",
        "qoshiq hisobot*" to "song report",
        "telefonimdan" to "from my phone",
        "telefondan" to "from my phone",
        "planshetdan" to "from my tablet",
        "telefonimda" to "on my phone",
        "telefonda" to "on my phone",
        "telefonni ula*" to "connect my phone",
        "masofadan boshqar*" to "remote control",
        "qr-kod*" to "qr code",
        "qr kod*" to "qr code",
        "daqiqa*" to "minutes",
        "minut*" to "minutes",
        "eʼlon:" to "announce",
        "elon:" to "announce",
        "jadvalga" to "to the schedule",
        "jadvalda" to "in the schedule",
        "jadvaldagi" to "in the schedule",
        "jadvaldan" to "from the schedule",
        "keyingi band*" to "next item",
        "oldingi band*" to "previous item",
        "element*" to "item",
        "punkt*" to "item",
        "hozir ekranda nima bor" to "what's live",
        "hozir efirda nima bor" to "what's live",
        "efirda nima bor" to "what's live",
        "nima koʻrsatilyapti" to "what's showing",
        "nima korsatilyapti" to "what's showing",
        "efirda biror narsa bormi" to "is anything live",
        "bu qaysi versiya" to "what version is this",
        "qaysi versiya*" to "what version",
        "ilova versiyasi" to "app version",
        "dastur versiyasi" to "app version",
        "oxirgi versiya*" to "latest version",
        "yangilanishlarni tekshir*" to "check for updates",
        "yangilanish bormi" to "is there an update",
        "versiya*" to "version",
        "buyruqlar roʻyxati" to "list of commands",
        "buyruqlar royxati" to "list of commands",
        "barcha buyruqlar" to "all commands",
        "buyruqlar" to "commands",
        "buyruqlarni" to "commands",
        "nima deya olaman" to "what can i say",
        "nima yoza olaman" to "what can i type",
        "nimani tushunasan" to "what do you understand",
        "hozircha" to "for now",
        "ommaviy" to "batch",
        "slayd-shou*" to "slideshow",

        // Look requests.
        "qoʻshiq matnini qanday oʻzgartir*" to "how do i change song lyrics",
        "qoshiq matnini qanday ozgartir*" to "how do i change song lyrics",
        "qoʻshiq matnini oʻzgartir*" to "change song lyrics",
        "qoshiq matnini ozgartir*" to "change song lyrics",
        "qoʻshiq matnini tahrir*" to "edit song lyrics",
        "qoshiq matnini tahrir*" to "edit song lyrics",
        "qoʻshiq matnini" to "lyrics",
        "qoshiq matnini" to "lyrics",
        "qoʻshiq matniga" to "lyrics",
        "qoshiq matniga" to "lyrics",
        "matndagi xato*" to "mistake in the lyrics",
        "qoʻshiq oxiri belgi*" to "end of song marker",
        "qoshiq oxiri belgi*" to "end of song marker",
        "qoʻshiq oxiri*" to "end of song",
        "qoshiq oxiri*" to "end of song",
        "oxiri belgi*" to "end marker",
        "qalin*" to "bold",
        "kursiv*" to "italic",
        "tagiga chiz*" to "underline",
        "kontur*" to "outline",
        "soya*" to "shadow",
        "hoshiya*" to "margins",
        "chetlar*" to "edges",
        "tepaga" to "top",
        "tepada" to "top",
        "tepasiga" to "top",
        "yuqori*" to "top",
        "pastga" to "bottom",
        "pastda" to "bottom",
        "pastiga" to "bottom",
        "oʻrtaga" to "center",
        "ortaga" to "center",
        "oʻrtada" to "middle",
        "ortada" to "middle",
        "markaz*" to "center",
        "chapga" to "left",
        "chapda" to "left",
        "oʻngga" to "right",
        "ongga" to "right",
        "oʻngda" to "right",
        "ongda" to "right",
        "tekisla*" to "align",
        "oʻrni" to "position",
        "orni" to "position",
        "oʻrnini" to "position",
        "ornini" to "position",
        "siljit*" to "move",
        "koʻrinish*" to "look",
        "korinish*" to "look",
        "tashqi koʻrinish*" to "appearance",
        "tashqi korinish*" to "appearance",
        "uslub*" to "style",
        "beza*" to "style",
        "rang" to "color",
        "rangi*" to "color",
        "qoʻshiq sarlavha*" to "song title",
        "qoshiq sarlavha*" to "song title",
        "sarlavha*" to "title",
        "havola*" to "reference",

        // The help table's own examples.
        "ni koʻrsat" to "show",
        "ota-ona*" to "parents",
        "qanday qilaman" to "how do i make",
    ),
)
