package org.churchpresenter.lottiegen.ui

import java.text.MessageFormat
import java.util.Locale
import java.util.ResourceBundle

object Strings {
    private var bundle: ResourceBundle = ResourceBundle.getBundle("lottiegen_strings", Locale.getDefault())

    fun setLocale(locale: Locale) {
        bundle = ResourceBundle.getBundle("lottiegen_strings", locale)
    }

    // Main title
    val appTitle: String get() = bundle.getString("app_title")

    // Section headers
    val sectionCanvas: String get() = bundle.getString("section_canvas")
    val sectionStyleLayout: String get() = bundle.getString("section_style_layout")
    val sectionText: String get() = bundle.getString("section_text")
    val sectionTextStyle: String get() = bundle.getString("section_text_style")
    val sectionColors: String get() = bundle.getString("section_colors")
    val sectionShape: String get() = bundle.getString("section_shape")
    val sectionLogo: String get() = bundle.getString("section_logo")
    val sectionTiming: String get() = bundle.getString("section_timing")
    val sectionPosition: String get() = bundle.getString("section_position")
    val sectionLibrary: String get() = bundle.getString("section_library")

    // Canvas labels
    val width: String get() = bundle.getString("width")
    val height: String get() = bundle.getString("height")
    val scale: String get() = bundle.getString("scale")

    // Style & Layout labels
    val style: String get() = bundle.getString("style")
    val alignment: String get() = bundle.getString("alignment")
    val alignLeft: String get() = bundle.getString("align_left")
    val alignCenter: String get() = bundle.getString("align_center")
    val alignRight: String get() = bundle.getString("align_right")

    // Text labels
    val name: String get() = bundle.getString("name")
    val info: String get() = bundle.getString("info")

    // Text Style labels
    val font: String get() = bundle.getString("font")
    val baseSize: String get() = bundle.getString("base_size")
    val nameSize: String get() = bundle.getString("name_size")
    val infoSize: String get() = bundle.getString("info_size")
    val nameWeight: String get() = bundle.getString("name_weight")
    val infoWeight: String get() = bundle.getString("info_weight")
    val nameTransform: String get() = bundle.getString("name_transform")
    val infoTransform: String get() = bundle.getString("info_transform")
    val bold: String get() = bundle.getString("bold")
    val normal: String get() = bundle.getString("normal")
    val uppercase: String get() = bundle.getString("uppercase")
    val none: String get() = bundle.getString("none")

    // Color labels
    val colorNameText: String get() = bundle.getString("color_name_text")
    val colorInfoText: String get() = bundle.getString("color_info_text")
    val colorAccent: String get() = bundle.getString("color_accent")
    val colorBackground: String get() = bundle.getString("color_background")
    val colorBorder: String get() = bundle.getString("color_border")
    val saveColors: String get() = bundle.getString("save_colors")

    // Shape labels
    val corners: String get() = bundle.getString("corners")
    val borderThickness: String get() = bundle.getString("border_thickness")
    val showBackground: String get() = bundle.getString("show_background")
    val shadow: String get() = bundle.getString("shadow")
    val hideName: String get() = bundle.getString("hide_name")
    val hideInfo: String get() = bundle.getString("hide_info")

    // Logo labels
    val showLogo: String get() = bundle.getString("show_logo")
    val logoLabel: String get() = bundle.getString("logo_label")
    val logoNone: String get() = bundle.getString("logo_none")
    val logoImport: String get() = bundle.getString("logo_import")
    val logoSize: String get() = bundle.getString("logo_size")

    // Timing labels
    val animDuration: String get() = bundle.getString("anim_duration")
    val holdDuration: String get() = bundle.getString("hold_duration")

    // Timing preset names
    val timingFast: String get() = bundle.getString("timing_fast")
    val timingMedium: String get() = bundle.getString("timing_medium")
    val timingSlow: String get() = bundle.getString("timing_slow")

    // Position labels
    val marginH: String get() = bundle.getString("margin_h")
    val marginV: String get() = bundle.getString("margin_v")
    val lineSpacing: String get() = bundle.getString("line_spacing")

    // Action buttons
    val saveLowerThird: String get() = bundle.getString("save_lower_third")
    val downloadJson: String get() = bundle.getString("download_json")
    val saveToLibrary: String get() = bundle.getString("save_to_library")

    // Status messages
    val generating: String get() = bundle.getString("generating")
    val previewLabel: String get() = bundle.getString("preview_label")
    val noPresets: String get() = bundle.getString("no_presets")

    // Animation style names
    val style1: String get() = bundle.getString("style_1")
    val style2: String get() = bundle.getString("style_2")
    val style3: String get() = bundle.getString("style_3")
    val style4: String get() = bundle.getString("style_4")
    val style5: String get() = bundle.getString("style_5")
    val style6: String get() = bundle.getString("style_6")
    val style7: String get() = bundle.getString("style_7")
    val style8: String get() = bundle.getString("style_8")
    val style9: String get() = bundle.getString("style_9")
    val style10: String get() = bundle.getString("style_10")
    val style11: String get() = bundle.getString("style_11")
    val style12: String get() = bundle.getString("style_12")

    // Color theme names
    val themeClassicRed: String get() = bundle.getString("theme_classic_red")
    val themeOceanBlue: String get() = bundle.getString("theme_ocean_blue")
    val themeEmerald: String get() = bundle.getString("theme_emerald")
    val themeSunset: String get() = bundle.getString("theme_sunset")
    val themePurpleHaze: String get() = bundle.getString("theme_purple_haze")
    val themeMinimalLight: String get() = bundle.getString("theme_minimal_light")
    val themeGold: String get() = bundle.getString("theme_gold")
    val themeNeonPink: String get() = bundle.getString("theme_neon_pink")

    // Batch import / library actions
    val batchImport: String get() = bundle.getString("batch_import")
    val batchImportTitle: String get() = bundle.getString("batch_import_title")
    val batchImportHint: String get() = bundle.getString("batch_import_hint")
    val batchImportPlaceholder: String get() = bundle.getString("batch_import_placeholder")
    val batchImportBtn: String get() = bundle.getString("batch_import_btn")
    val applyStyleToAll: String get() = bundle.getString("apply_style_to_all")
    val saveAllLowerThirds: String get() = bundle.getString("save_all_lower_thirds")

    fun batchImportedStatus(added: Int, updated: Int): String =
        bundle.getString("batch_imported_status").format(added, updated)

    // Color picker dialog
    val chooseColor: String get() = bundle.getString("choose_color")
    val hex: String get() = bundle.getString("hex")
    val recent: String get() = bundle.getString("recent")
    val ok: String get() = bundle.getString("ok")
    val cancelBtn: String get() = bundle.getString("cancel")

    // Style Editor (developer tool)
    val editorWindowTitle: String get() = bundle.getString("editor_window_title")
    val editorElements: String get() = bundle.getString("editor_elements")
    val editorPlay: String get() = bundle.getString("editor_play")
    val editorPause: String get() = bundle.getString("editor_pause")
    val editorAddElement: String get() = bundle.getString("editor_add_element")
    val editorElementRect: String get() = bundle.getString("editor_element_rect")
    val editorElementEllipse: String get() = bundle.getString("editor_element_ellipse")
    val editorElementPolygon: String get() = bundle.getString("editor_element_polygon")
    val editorElementPath: String get() = bundle.getString("editor_element_path")
    val editorElementNameText: String get() = bundle.getString("editor_element_name_text")
    val editorElementInfoText: String get() = bundle.getString("editor_element_info_text")
    val editorElementLogo: String get() = bundle.getString("editor_element_logo")
    val editorElementBackground: String get() = bundle.getString("editor_element_background")
    val editorMoveUp: String get() = bundle.getString("editor_move_up")
    val editorMoveDown: String get() = bundle.getString("editor_move_down")
    val editorDelete: String get() = bundle.getString("editor_delete")
    val editorSectionGeneral: String get() = bundle.getString("editor_section_general")
    val editorSectionPlacement: String get() = bundle.getString("editor_section_placement")
    val editorSectionSize: String get() = bundle.getString("editor_section_size")
    val editorSectionPaint: String get() = bundle.getString("editor_section_paint")
    val editorSectionText: String get() = bundle.getString("editor_section_text")
    val editorSectionTracks: String get() = bundle.getString("editor_section_tracks")
    val editorSectionLayout: String get() = bundle.getString("editor_section_layout")
    val editorName: String get() = bundle.getString("editor_name")
    val editorVisibleWhen: String get() = bundle.getString("editor_visible_when")
    val editorRuleAlways: String get() = bundle.getString("editor_rule_always")
    val editorRuleBg: String get() = bundle.getString("editor_rule_bg")
    val editorRuleLogo: String get() = bundle.getString("editor_rule_logo")
    val editorRuleName: String get() = bundle.getString("editor_rule_name")
    val editorRuleInfo: String get() = bundle.getString("editor_rule_info")
    val editorRuleBorder: String get() = bundle.getString("editor_rule_border")
    val editorSlot: String get() = bundle.getString("editor_slot")
    val editorAnchor: String get() = bundle.getString("editor_anchor")
    val editorLine: String get() = bundle.getString("editor_line")
    val editorOffsetX: String get() = bundle.getString("editor_offset_x")
    val editorOffsetY: String get() = bundle.getString("editor_offset_y")
    val editorMirror: String get() = bundle.getString("editor_mirror")
    val editorAddOverride: String get() = bundle.getString("editor_add_override")
    val editorRemoveOverride: String get() = bundle.getString("editor_remove_override")
    val editorSizeType: String get() = bundle.getString("editor_size_type")
    val editorSizeEm: String get() = bundle.getString("editor_size_em")
    val editorSizeContent: String get() = bundle.getString("editor_size_content")
    val editorSizeTextWrap: String get() = bundle.getString("editor_size_text_wrap")
    val editorSizeCanvasWidth: String get() = bundle.getString("editor_size_canvas_width")
    val editorWidthEm: String get() = bundle.getString("editor_width_em")
    val editorHeightEm: String get() = bundle.getString("editor_height_em")
    val editorPadX: String get() = bundle.getString("editor_pad_x")
    val editorPadY: String get() = bundle.getString("editor_pad_y")
    val editorTextFieldRef: String get() = bundle.getString("editor_text_field_ref")
    val editorFieldName: String get() = bundle.getString("editor_field_name")
    val editorFieldInfo: String get() = bundle.getString("editor_field_info")
    val editorCorner: String get() = bundle.getString("editor_corner")
    val editorCornerNone: String get() = bundle.getString("editor_corner_none")
    val editorCornerFromConfig: String get() = bundle.getString("editor_corner_from_config")
    val editorCornerEm: String get() = bundle.getString("editor_corner_em")
    val editorCornerFactor: String get() = bundle.getString("editor_corner_factor")
    val editorCornerRadius: String get() = bundle.getString("editor_corner_radius")
    val editorGrowFrom: String get() = bundle.getString("editor_grow_from")
    val editorGrowCenter: String get() = bundle.getString("editor_grow_center")
    val editorGrowEdge: String get() = bundle.getString("editor_grow_edge")
    val editorFill: String get() = bundle.getString("editor_fill")
    val editorStroke: String get() = bundle.getString("editor_stroke")
    val editorColorRole: String get() = bundle.getString("editor_color_role")
    val editorRoleName: String get() = bundle.getString("editor_role_name")
    val editorRoleInfo: String get() = bundle.getString("editor_role_info")
    val editorRoleAccent: String get() = bundle.getString("editor_role_accent")
    val editorRoleBg: String get() = bundle.getString("editor_role_bg")
    val editorRoleBorder: String get() = bundle.getString("editor_role_border")
    val editorGradient: String get() = bundle.getString("editor_gradient")
    val editorStartX: String get() = bundle.getString("editor_start_x")
    val editorStartY: String get() = bundle.getString("editor_start_y")
    val editorEndX: String get() = bundle.getString("editor_end_x")
    val editorEndY: String get() = bundle.getString("editor_end_y")
    val editorStrokeWidthType: String get() = bundle.getString("editor_stroke_width_type")
    val editorStrokeFromConfig: String get() = bundle.getString("editor_stroke_from_config")
    val editorStrokeEm: String get() = bundle.getString("editor_stroke_em")
    val editorBorderFromConfig: String get() = bundle.getString("editor_border_from_config")
    val editorVertices: String get() = bundle.getString("editor_vertices")
    val editorAddVertex: String get() = bundle.getString("editor_add_vertex")
    val editorClosedPath: String get() = bundle.getString("editor_closed_path")
    val editorFitWidth: String get() = bundle.getString("editor_fit_width")
    val editorFitNone: String get() = bundle.getString("editor_fit_none")
    val editorFitName: String get() = bundle.getString("editor_fit_name")
    val editorFitInfo: String get() = bundle.getString("editor_fit_info")
    val editorFitTextBlock: String get() = bundle.getString("editor_fit_text_block")
    val editorMaskReveal: String get() = bundle.getString("editor_mask_reveal")
    val editorMaskPad: String get() = bundle.getString("editor_mask_pad")
    val editorMaskHeight: String get() = bundle.getString("editor_mask_height")
    val editorMaskYOffset: String get() = bundle.getString("editor_mask_y_offset")
    val editorAnimator: String get() = bundle.getString("editor_animator")
    val editorAnimatorKind: String get() = bundle.getString("editor_animator_kind")
    val editorAnimatorSequential: String get() = bundle.getString("editor_animator_sequential")
    val editorAnimatorRandom: String get() = bundle.getString("editor_animator_random")
    val editorStartPct: String get() = bundle.getString("editor_start_pct")
    val editorEndPct: String get() = bundle.getString("editor_end_pct")
    val editorPosOffsetEm: String get() = bundle.getString("editor_pos_offset_em")
    val editorAddTrack: String get() = bundle.getString("editor_add_track")
    val editorRemoveTrack: String get() = bundle.getString("editor_remove_track")
    val editorProperty: String get() = bundle.getString("editor_property")
    val editorPropPosition: String get() = bundle.getString("editor_prop_position")
    val editorPropOpacity: String get() = bundle.getString("editor_prop_opacity")
    val editorPropScale: String get() = bundle.getString("editor_prop_scale")
    val editorPropRotation: String get() = bundle.getString("editor_prop_rotation")
    val editorPropRectSize: String get() = bundle.getString("editor_prop_rect_size")
    val editorPropStrokeWidth: String get() = bundle.getString("editor_prop_stroke_width")
    val editorPropTrim: String get() = bundle.getString("editor_prop_trim")
    val editorEasing: String get() = bundle.getString("editor_easing")
    val editorEasingDefault: String get() = bundle.getString("editor_easing_default")
    val editorEasingLinear: String get() = bundle.getString("editor_easing_linear")
    val editorOffsetUnit: String get() = bundle.getString("editor_offset_unit")
    val editorUnitEm: String get() = bundle.getString("editor_unit_em")
    val editorUnitElementWidth: String get() = bundle.getString("editor_unit_element_width")
    val editorUnitElementHeight: String get() = bundle.getString("editor_unit_element_height")
    val editorKeyframes: String get() = bundle.getString("editor_keyframes")
    val editorAddKeyframe: String get() = bundle.getString("editor_add_keyframe")
    val editorPct: String get() = bundle.getString("editor_pct")
    val editorValue: String get() = bundle.getString("editor_value")
    val editorBlockHeight: String get() = bundle.getString("editor_block_height")
    val editorCenterSingleLine: String get() = bundle.getString("editor_center_single_line")
    val editorSlots: String get() = bundle.getString("editor_slots")
    val editorAddSlot: String get() = bundle.getString("editor_add_slot")
    val editorSlotId: String get() = bundle.getString("editor_slot_id")
    val editorSlotKind: String get() = bundle.getString("editor_slot_kind")
    val editorSlotKindLogo: String get() = bundle.getString("editor_slot_kind_logo")
    val editorSlotKindFixed: String get() = bundle.getString("editor_slot_kind_fixed")
    val editorSlotKindText: String get() = bundle.getString("editor_slot_kind_text")
    val editorGapBefore: String get() = bundle.getString("editor_gap_before")
    val editorGapAfter: String get() = bundle.getString("editor_gap_after")
    val editorAlignLeft: String get() = bundle.getString("editor_align_left")
    val editorAlignCenter: String get() = bundle.getString("editor_align_center")
    val editorAlignRight: String get() = bundle.getString("editor_align_right")
    val editorNoSelection: String get() = bundle.getString("editor_no_selection")
    val editorSlotBlock: String get() = bundle.getString("editor_slot_block")
    val editorNew: String get() = bundle.getString("editor_new")
    val editorOpen: String get() = bundle.getString("editor_open")
    val editorSave: String get() = bundle.getString("editor_save")
    val editorSaveAs: String get() = bundle.getString("editor_save_as")
    val editorExport: String get() = bundle.getString("editor_export")
    val editorTipNew: String get() = bundle.getString("editor_tip_new")
    val editorTipOpen: String get() = bundle.getString("editor_tip_open")
    val editorTipSave: String get() = bundle.getString("editor_tip_save")
    val editorTipSaveAs: String get() = bundle.getString("editor_tip_save_as")
    val editorTipExport: String get() = bundle.getString("editor_tip_export")
    val editorTipModePreview: String get() = bundle.getString("editor_tip_mode_preview")
    val editorTipModeMatrix: String get() = bundle.getString("editor_tip_mode_matrix")
    val editorTipAddElement: String get() = bundle.getString("editor_tip_add_element")
    val editorTipMoveUp: String get() = bundle.getString("editor_tip_move_up")
    val editorTipMoveDown: String get() = bundle.getString("editor_tip_move_down")
    val editorTipDeleteElement: String get() = bundle.getString("editor_tip_delete_element")
    val editorNewTitle: String get() = bundle.getString("editor_new_title")
    val editorNewBlank: String get() = bundle.getString("editor_new_blank")
    val editorProjectName: String get() = bundle.getString("editor_project_name")
    val editorUnsavedTitle: String get() = bundle.getString("editor_unsaved_title")
    val editorUnsavedMessage: String get() = bundle.getString("editor_unsaved_message")
    val editorDiscard: String get() = bundle.getString("editor_discard")
    val editorOpenTitle: String get() = bundle.getString("editor_open_title")
    val editorNoProjects: String get() = bundle.getString("editor_no_projects")
    val editorExportTitle: String get() = bundle.getString("editor_export_title")
    val editorStyleId: String get() = bundle.getString("editor_style_id")
    val editorStyleName: String get() = bundle.getString("editor_style_name")

    /** Localized `style_<id>` label; throws MissingResourceException when none exists. */
    fun styleLabel(id: String): String = bundle.getString("style_$id")

    /** Generic bundle lookup for dynamically-keyed labels (bundled template names). */
    fun byKey(key: String): String = bundle.getString(key)
    val editorExportErrId: String get() = bundle.getString("editor_export_err_id")
    val editorExportErrNoElements: String get() = bundle.getString("editor_export_err_no_elements")
    val editorExportErrKeyframes: String get() = bundle.getString("editor_export_err_keyframes")
    val editorExportChoose: String get() = bundle.getString("editor_export_choose")
    val editorExportRegistered: String get() = bundle.getString("editor_export_registered")
    val editorRegisterBuild: String get() = bundle.getString("editor_register_build")
    val editorRegisterDoneTitle: String get() = bundle.getString("editor_register_done_title")
    val editorTipRegister: String get() = bundle.getString("editor_tip_register")
    val editorExportDoneTitle: String get() = bundle.getString("editor_export_done_title")
    val editorModePreview: String get() = bundle.getString("editor_mode_preview")
    val editorModeMatrix: String get() = bundle.getString("editor_mode_matrix")
    val editorTestConfig: String get() = bundle.getString("editor_test_config")
    val editorTestName: String get() = bundle.getString("editor_test_name")
    val editorTestInfo: String get() = bundle.getString("editor_test_info")
    val editorTestLogo: String get() = bundle.getString("editor_test_logo")
    val editorTestCanvas: String get() = bundle.getString("editor_test_canvas")
    val editorTestBorder: String get() = bundle.getString("editor_test_border")
    val editorTestAnimDuration: String get() = bundle.getString("editor_test_anim_duration")
    val editorTestHoldDuration: String get() = bundle.getString("editor_test_hold_duration")
    val editorTestAlignment: String get() = bundle.getString("editor_test_alignment")
    val editorNone: String get() = bundle.getString("editor_none")
    val editorMatrixTagLogo: String get() = bundle.getString("editor_matrix_tag_logo")
    val editorMatrixTagBg: String get() = bundle.getString("editor_matrix_tag_bg")
    val editorTimeline: String get() = bundle.getString("editor_timeline")
    val editorTimelineNote: String get() = bundle.getString("editor_timeline_note")
    val editorAnchorStart: String get() = bundle.getString("editor_anchor_start")
    val editorAnchorCenter: String get() = bundle.getString("editor_anchor_center")
    val editorAnchorEnd: String get() = bundle.getString("editor_anchor_end")
    val editorLineBlock: String get() = bundle.getString("editor_line_block")
    val editorLineName: String get() = bundle.getString("editor_line_name")
    val editorLineInfo: String get() = bundle.getString("editor_line_info")
    val editorPivotX: String get() = bundle.getString("editor_pivot_x")
    val editorPivotY: String get() = bundle.getString("editor_pivot_y")
    val editorDash: String get() = bundle.getString("editor_dash")
    val editorRepeat: String get() = bundle.getString("editor_repeat")
    val editorRepeatCopies: String get() = bundle.getString("editor_repeat_copies")
    val editorRepeatOffsetX: String get() = bundle.getString("editor_repeat_offset_x")
    val editorRepeatOffsetY: String get() = bundle.getString("editor_repeat_offset_y")
    val editorRepeatRotation: String get() = bundle.getString("editor_repeat_rotation")
    val editorRepeatScale: String get() = bundle.getString("editor_repeat_scale")
    val editorRepeatFade: String get() = bundle.getString("editor_repeat_fade")
    val editorRepeatFitWidth: String get() = bundle.getString("editor_repeat_fit_width")
    val editorElementImage: String get() = bundle.getString("editor_element_image")
    val editorSectionImage: String get() = bundle.getString("editor_section_image")
    val editorImageImport: String get() = bundle.getString("editor_image_import")
    val editorImageNone: String get() = bundle.getString("editor_image_none")
    val editorImageScaleMode: String get() = bundle.getString("editor_image_scale_mode")
    val editorImageFit: String get() = bundle.getString("editor_image_fit")
    val editorImageStretch: String get() = bundle.getString("editor_image_stretch")
    val editorImageCover: String get() = bundle.getString("editor_image_cover")
    val editorImageAlpha: String get() = bundle.getString("editor_image_alpha")
    val editorVertexIn: String get() = bundle.getString("editor_vertex_in")
    val editorVertexOut: String get() = bundle.getString("editor_vertex_out")
    val editorNewFromVine: String get() = bundle.getString("editor_new_from_vine")

    // Bible band generator
    val bandAppTitle: String get() = bundle.getString("band_app_title")
    val bandSectionBand: String get() = bundle.getString("band_section_band")
    val bandSectionLayout: String get() = bundle.getString("band_section_layout")
    val bandSectionAnimation: String get() = bundle.getString("band_section_animation")
    val bandSectionPreviewText: String get() = bundle.getString("band_section_preview_text")
    val bandSectionSave: String get() = bundle.getString("band_section_save")
    val bandStyle: String get() = bundle.getString("band_style")
    val bandEntrance: String get() = bundle.getString("band_entrance")
    val bandTextAnimation: String get() = bundle.getString("band_text_animation")
    val bandLayout: String get() = bundle.getString("band_layout")
    val bandColorBackground: String get() = bundle.getString("band_color_background")
    val bandColorAccent: String get() = bundle.getString("band_color_accent")
    val bandColorGradient: String get() = bundle.getString("band_color_gradient")
    val bandColorThird: String get() = bundle.getString("band_color_third")
    val bandColorTint: String get() = bundle.getString("band_color_tint")
    val bandImage: String get() = bundle.getString("band_image")
    val bandImageNone: String get() = bundle.getString("band_image_none")
    val bandImageChoose: String get() = bundle.getString("band_image_choose")
    val bandImageClear: String get() = bundle.getString("band_image_clear")
    val bandColorBorder: String get() = bundle.getString("band_color_border")
    val bandBorderThickness: String get() = bundle.getString("band_border_thickness")
    val bandCornerRadius: String get() = bundle.getString("band_corner_radius")
    val bandInset: String get() = bundle.getString("band_inset")
    val bandPadding: String get() = bundle.getString("band_padding")
    val bandTimeBandIn: String get() = bundle.getString("band_time_band_in")
    val bandTimeTextIn: String get() = bundle.getString("band_time_text_in")
    val bandTimeHold: String get() = bundle.getString("band_time_hold")
    val bandTimeTextOut: String get() = bundle.getString("band_time_text_out")
    val bandTimeBandOut: String get() = bundle.getString("band_time_band_out")
    val bandTickerSpeed: String get() = bundle.getString("band_ticker_speed")
    val bandPreviewFont: String get() = bundle.getString("band_preview_font")
    val bandPreviewBold: String get() = bundle.getString("band_preview_bold")
    val bandPreviewTextColor: String get() = bundle.getString("band_preview_text_color")
    val bandPreviewReferenceColor: String get() = bundle.getString("band_preview_reference_color")
    val bandFileName: String get() = bundle.getString("band_file_name")
    val bandSave: String get() = bundle.getString("band_save")
    val bandSaveHint: String get() = bundle.getString("band_save_hint")
    val bandUnitSeconds: String get() = bundle.getString("band_unit_seconds")
    val bandUnitPx: String get() = bundle.getString("band_unit_px")
    fun bandStatusSaved(name: String): String = MessageFormat.format(bundle.getString("band_status_saved"), name)
    fun bandStatusError(message: String): String = MessageFormat.format(bundle.getString("band_status_error"), message)
    fun bandStatusPictureUnreadable(name: String): String =
        MessageFormat.format(bundle.getString("band_status_picture_unreadable"), name)

    /** Labels for the band enums, looked up by `band_<prefix>_<constant>`. */
    fun bandEnumLabel(prefix: String, constant: String): String =
        bundle.getString("band_${prefix}_${constant.lowercase()}")

    /**
     * A band label that reads differently for scripture and for a song — "Reference" against
     * "Title", "Verse 1" against "Lyrics 1" — looked up by `band_<key>_<bible|song>`.
     */
    fun bandLabel(key: String, kind: String): String = bundle.getString("band_${key}_$kind")
}

/**
 * The editor's formatted strings.
 *
 * Split out of [Strings] because they are the Style Editor's alone -- a developer tool that does
 * not ship to operators -- and because Strings was carrying eleven formatters over five hundred
 * plain lookups.
 */
object EditorStrings {

    fun styleLabelFormat(id: String, name: String): String =
        Strings.byKey("editor_style_label_format").format(id, name)

    fun exportLabelPreview(label: String): String =
        Strings.byKey("editor_export_label_preview").format(label)

    fun registerDoneBody(specPath: String, registryPath: String, id: String): String =
        Strings.byKey("editor_register_done_body").format(specPath, registryPath, id)

    fun exportReplaces(label: String): String =
        Strings.byKey("editor_export_replaces").format(label)

    fun exportDoneSteps(id: String, fileName: String, styleName: String): String =
        Strings.byKey("editor_export_done_steps").format(id, fileName, styleName)

    fun savedStatus(name: String): String =
        Strings.byKey("editor_saved_status").format(name)

    fun imageInfo(w: Int, h: Int, kb: Int): String =
        Strings.byKey("editor_image_info").format(w, h, kb)
}
