package org.churchpresenter.sharedui.models

enum class Tabs {
    BIBLE, SONGS, PICTURES, PRESENTATION, MEDIA, LOWER_THIRD, ANNOUNCEMENTS, WEB, CANVAS, QA, STT, CROSSWORD,
    DICTIONARY, COMPANION_SURFACE
}
