package org.churchpresenter.crossword.ui

internal object Strings {
    const val navPrev = "←"
    const val navNext = "→"
    const val newLevel = "+ New Level"
    const val jumpTo = "Jump to"
    const val editorPlaceholder = "Enter puzzle plaintext…"
    const val importTxt = "Import .txt…"
    const val loadXwp = "Load .xwp"
    const val exportXwp = "Export .xwp"
    const val fixReorder = "Fix/Reorder"
    const val exportAll = "Export All"
    const val decodeAll = "Decode All"
    const val previewEmpty = "Enter clues to see preview"
    const val cluesAcross = "Across"
    const val cluesDown = "Down"
    const val windowTitle = "ChurchPresenter Cross Editor"
    const val prevLevelTip = "Go to previous level"
    const val nextLevelTip = "Go to next level"
    const val noLevels = "No levels"
    const val newLevelTip = "Create a new empty level and open it for editing"
    const val importTxtTip = "Import a .txt plaintext puzzle file from disk into this level"
    const val loadPlaintextTitle = "Load Plaintext"
    const val loadXwpTip = "Decode and load the saved .xwp file for this level back into the editor"
    const val exportXwpTip = "Encode and save this level as a .xwp file for use in the presenter"
    const val fixReorderTip = "Build the crossword grid and renumber clues in reading order " +
        "(top→bottom, left→right). Also converts simplified formats to " +
        "standard layout."
    const val exportAllTip = "Export all levels to .xwp files in one go, " +
        "skipping any that are invalid or still unedited"
    const val decodeAllTip = "Decode all .xwp files in the encoded/ folder back to plaintext .txt files"
    const val invalidFormat = "Invalid puzzle format."
    const val replacePlaceholders = "Replace the placeholder clues before exporting."
    const val cannotExportInvalid = "Cannot export: clues don't form a valid crossword — run Fix/Reorder first."
    const val cannotReorderInvalid = "Cannot reorder: invalid puzzle format."
    const val cannotReorderNoWords = "Cannot reorder: no words could be placed."
    const val noPlaintextLevels = "No plaintext levels found in puzzles/"
    const val noXwpFiles = "No .xwp files found in encoded/"

    const val levelPosition = "Level %d  (%d / %d)"
    const val templatesWarning = "⚠ Level %s: clues not yet entered"
    const val unexportedWarning = "⚠ Level %s not exported"
    const val imported = "Imported %s"
    const val levelNotFound = "Level %d not found — edit to create it"
    const val newLevelCreated = "New level %d — edit to begin"
    const val exported = "Exported level%d.xwp"
    const val xwpNotFound = "level%d.xwp not found in encoded/"
    const val loadedEncoded = "Loaded encoded level %d"
    const val decodeFailed = "Failed to decode level%d.xwp"
    const val reorderedUnplaced = "Reordered — %d clue(s) not in puzzle"
    const val reorderedAll = "Reordered — all %d clues placed"
    const val exportedCount = "Exported %d level(s)"
    const val skippedCount = ", %d skipped (invalid/unplaceable)"
    const val decodedCount = "Decoded %d level(s)"
    const val failedCount = ", %d failed"
}
