package org.churchpresenter.app.churchpresenter.data

import kotlinx.serialization.json.Json
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/**
 * The packed reference on every interlinear verse.
 *
 * The bundled interlinear data stores a verse's address as one nine-digit string — `"043003016"`
 * is John 3:16 — and the whole dictionary tab depends on unpacking it: the book/chapter filters,
 * the verse cards and their ordering all read these three numbers. The packing is fixed-width, so
 * the leading zeros are load-bearing rather than cosmetic.
 */
class InterlinearVerseTest {

    private fun verse(ref: String) = InterlinearVerse(ref = ref, words = emptyList())

    // ── Unpacking a reference ───────────────────────────────────────────────────

    @Test
    fun `a reference unpacks into book, chapter and verse`() {
        val john316 = verse("043003016")

        assertEquals(43, john316.bookId)
        assertEquals(3, john316.chapter)
        assertEquals(16, john316.verseNumber)
    }

    @Test
    fun `the first verse of the bible unpacks`() {
        val genesis11 = verse("001001001")

        assertEquals(1, genesis11.bookId)
        assertEquals(1, genesis11.chapter)
        assertEquals(1, genesis11.verseNumber)
    }

    @Test
    fun `three-digit chapters and verses unpack`() {
        // Psalm 119 is long in both directions — the widest values the format has to carry.
        val psalm119176 = verse("019119176")

        assertEquals(19, psalm119176.bookId)
        assertEquals(119, psalm119176.chapter)
        assertEquals(176, psalm119176.verseNumber)
    }

    @Test
    fun `the last book unpacks`() {
        assertEquals(66, verse("066022021").bookId)
    }

    @Test
    fun `anything past the ninth digit is ignored`() {
        assertEquals(43, verse("043003016-extra").bookId)
        assertEquals(16, verse("043003016-extra").verseNumber)
    }

    @Test
    fun `a segment that is not a number reads as zero rather than throwing`() {
        val broken = verse("abcdefghi")

        assertEquals(0, broken.bookId)
        assertEquals(0, broken.chapter)
        assertEquals(0, broken.verseNumber)
    }

    /**
     * Documents CURRENT behaviour: the unpacking indexes into the string directly, so a reference
     * shorter than nine characters throws rather than reading as zero — unlike a nine-character
     * reference full of letters, which is tolerated.
     *
     * The data is bundled with the app and generated by the same tooling that reads it, so this
     * needs a truncated or hand-edited data file to reach. Worth knowing because the failure
     * surfaces as an exception out of the dictionary tab rather than as a missing verse.
     */
    @Test
    fun `a truncated reference throws -- known gap`() {
        assertFailsWith<StringIndexOutOfBoundsException> { verse("0430").chapter }
        assertFailsWith<StringIndexOutOfBoundsException> { verse("").bookId }
    }

    // ── The wire format ─────────────────────────────────────────────────────────

    @Test
    fun `a verse is read from the compact json the data files use`() {
        // The bundled files use one-letter keys throughout — the interlinear data is megabytes, so
        // the field names are abbreviated.
        val json = """{"r":"043003016","w":[{"t":"ἀγάπη","s":"G26"},{"t":"θεός","s":"G2316"}]}"""

        val decoded = Json.decodeFromString(InterlinearVerse.serializer(), json)

        assertEquals("043003016", decoded.ref)
        assertEquals(43, decoded.bookId)
        assertEquals(listOf("ἀγάπη", "θεός"), decoded.words.map { it.text })
        assertEquals(listOf("G26", "G2316"), decoded.words.map { it.strongsNumber })
    }

    @Test
    fun `a verse round-trips through the compact json`() {
        val original = InterlinearVerse(
            ref = "043003016",
            words = listOf(InterlinearWord(text = "ἀγάπη", strongsNumber = "G26")),
        )

        val restored = Json.decodeFromString(
            InterlinearVerse.serializer(),
            Json.encodeToString(InterlinearVerse.serializer(), original),
        )

        assertEquals(original, restored)
    }

    @Test
    fun `the abbreviated keys are what gets written`() {
        val encoded = Json.encodeToString(
            InterlinearVerse.serializer(),
            InterlinearVerse(ref = "043003016", words = listOf(InterlinearWord("λόγος", "G3056"))),
        )

        assertTrue(""""r":"043003016"""" in encoded, encoded)
        assertTrue(""""t":"λόγος"""" in encoded, "a rename here would silently break every bundled data file: $encoded")
        assertTrue(""""s":"G3056"""" in encoded, encoded)
    }

    @Test
    fun `a verse with no words is still a verse`() {
        val empty = verse("043003016")

        assertTrue(empty.words.isEmpty())
        assertEquals(43, empty.bookId, "the reference is readable whether or not the words came with it")
    }
}
